### ISSUE TITLE
cannot find protocol declaration error during make

### ISSUE THREAD

**Issue by phirestalker** [theos/theos#103]
I generated a clean xm file with logify.pl using multiple .h files. Here are the errors I am getting:

Tweak.xm:4:9: error: cannot find protocol declaration for 'SAAceCommand'
Tweak.xm:4:8: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:27: error: C++ requires a type specifier for all declarations
Tweak.xm:4:118: error: cannot find protocol declaration for 'SAAceCommand'
Tweak.xm:4:117: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:134: error: C++ requires a type specifier for all declarations
Tweak.xm:4:2181: error: cannot find protocol declaration for 'SVSAceCommandRecordDelegate'
Tweak.xm:4:2180: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:2212: error: C++ requires a type specifier for all declarations
Tweak.xm:4:2313: error: cannot find protocol declaration for 'SVSAceCommandRecordDelegate'
Tweak.xm:4:2312: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:2344: error: C++ requires a type specifier for all declarations
Tweak.xm:4:2355: error: cannot find protocol declaration for 'SVSAceCommandRecordDelegate'
Tweak.xm:4:2354: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:2388: error: C++ requires a type specifier for all declarations
Tweak.xm:4:2477: error: cannot find protocol declaration for 'SVSAceCommandRecordDelegate'
Tweak.xm:4:2476: error: protocol has no object type specified; defaults to qualified 'id' [-Werror]
Tweak.xm:4:2508: error: C++ requires a type specifier for all declarations
Tweak.xm:4:2603: error: redefinition of
      '_logos_orig$_ungrouped$SVSAceCommandRecord$numberOfStartedActions'
Tweak.xm:4:856: note: previous definition is here

and here is a link to the xm file. http://pastebin.com/bnUCLkFJ

I am trying this on OSX 10.9.4

makefile is:
TARGET = iphone:7.1

include theos/makefiles/common.mk

TWEAK_NAME = customsiri
customsiri_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk

after-install::
	install.exec "killall -9 SpringBoard"

**Comment by rpetrich** [comment]
This is a problem with class-dumped headers. It shouldn't be the responsibility of logify, logos or theos to correct this.
