### ISSUE TITLE
Can't compile .m on Ubuntu

### ISSUE THREAD

**Issue by Script36** [theos/theos#107]
Hello! 
when I use 'make' to compile .m file on Ubuntu. I found it always went error:
```
make[2]: *** No rule to make target `obj/main.m.57170fe7.o', needed by `obj/q.app/q.1e401358.unsigned'.  Stop.
make[1]: *** [internal-application-all_] Error 2
make: *** [q.all.application.variables] Error 2
```
but when I change the file type from .M to .MM, it always goes OK.
Can someone tell me why?

Thanks a lot!

**Comment by alucard0134** [comment]
Are you still experiencing this issue @Script36?

**Comment by alucard0134** [comment]
Due to lack of reply by the author I am assuming that this issue is fixed, if it isn't then please comment back and I will reopen this.
