### ISSUE TITLE
failed to exec tar -cf: No such file or directory

### ISSUE THREAD

**Issue by i0sa** [theos/theos#112]
Hello, I'm getting this dpkg error on `make package`

dpkg-deb: ignoring 2 warnings about the control file(s)
dpkg-deb (subprocess): failed to exec tar -cf: No such file or directory
dpkg-deb: subprocess tar -cf returned error exit status 2
make: *** [internal-package] Error 2

I reinstalled theos and everything, `make` works fine, making package gives this tar-related error
Not sure why.

**Comment by i0sa** [comment]
still arguing for a fix..

**Comment by uroboro** [comment]
Is this still happening? Can you share the output of `make clean package messages=yes`?

**Comment by alucard0134** [comment]
It has been over a week since a request to reply. Thus I will be closing this. If you have any other issues please open a new issue
