### ISSUE TITLE
'make install' fails

### ISSUE THREAD

**Issue by cansurmeli** [theos/theos#119]
Hi.

After I successfully compile [wifi from Cykey](https://github.com/Cykey/wifi), `make install` fails with the following error message:

/Users/can/Desktop/wifi/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
install.exec "cat > /tmp/_theos_install.deb; dpkg -i /tmp/_theos_install.deb && rm /tmp/_theos_install.deb" < "./me.cykey.wifi_0.0.1-2_iphoneos-arm.deb"
(Reading database ... 7212 files and directories currently installed.)
Unpacking me.cykey.wifi (from /tmp/_theos_install.deb) ...
dpkg-deb: file `/tmp/_theos_install.deb' contains ununderstood data member data.tar.xz     , giving up
dpkg: error processing /tmp/_theos_install.deb (--install):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1

I've also passed the `-Zgzip` argument to `dpkg`, which appears to solve the problem for other people but not me.

Any ideas what this is related with?

Thanks.

**Comment by awesomebing1** [comment]
Same, it didn't work for me. I saw a patch that had been applied, but it seems as if the patch no longer works.

**Comment by awesomebing1** [comment]
Actually, I just fixed it. Change the 
` $(ECHO_NOTHING)COPYFILE_DISABLE=1 $(FAKEROOT) -r dpkg-deb -b "$(THEOS_STAGING_DIR)" "$(_THEOS_DEB_PACKAGE_FILENAME)" $(STDERR_NULL_REDIRECT)$(ECHO_END)` 

line to 

`$(ECHO_NOTHING)COPYFILE_DISABLE=1 $(FAKEROOT) -r dpkg-deb -Zgzip -b "$(THEOS_STAGING_DIR)" "$(_THEOS_DEB_PACKAGE_FILENAME)" $(STDERR_NULL_REDIRECT)$(ECHO_END)`. Make sure it's `dpkg-deb` you are changing, not `dpkg` itself.

**Comment by uroboro** [comment]
@cansurmeli Is this still happening? Can you post the output of `make clean package debug=yes messages=yes`?

**Comment by cansurmeli** [comment]
`/Users/can/Desktop/wifi/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
rm -rf ./obj/debug
rm -rf "/Users/can/Desktop/wifi/_"
/Applications/Xcode.app/Contents/Developer/usr/bin/make package requires dpkg-deb.
make: *** [internal-package-check] Error 1`

Although I cloned a fresh copy. Somehow my old copy didn't relate to Theos.

**Comment by uroboro** [comment]
`dpkg-deb` isn't packaged within Theos, you have to install it yourself as explained in the [installation wiki](https://github.com/theos/theos/wiki/Installation).

**Comment by cansurmeli** [comment]
Sorry about that.

https://ghostbin.com/paste/tsnmn

**Comment by uroboro** [comment]
Now that's not a Theos issue.

**Comment by uroboro** [comment]
Please reopen if the original issue isn't solved.
