### ISSUE TITLE
make install says no .deb packageto install

### ISSUE THREAD

**Issue by adaptivedev** [theos/theos#120]
How can I fix this? I followed the instructions here and it happens in both tweak and app:

http://iphonedevwiki.net/index.php/Theos/Setup#Creating_a_Project

I don't see any .deb files

RoverMR-2:testapp rover$ find . -name "*deb*"
RoverMR-2:testapp rover$ 

I just see this in packages:

RoverMR-2:testapp rover$ ls -la .theos/packages/
total 8
drwxr-xr-x  3 rover  staff  102 Apr 30 11:12 .
drwxr-xr-x  4 rover  staff  136 Apr 30 11:12 ..
-rw-r--r--  1 rover  staff    1 Apr 30 11:12 com.mysite.testapp-0.0.1

RoverMR-2:testapp rover$ make package
/Users/rover/Documents/Dev/Cydia/Theos/apps/testapp/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Making all for application testapp...
 Copying resource directories into the application wrapper...
 Compiling main.m...
 Compiling testappApplication.mm...
 Compiling RootViewController.mm...
 Linking application testapp...
 Stripping testapp...
 Signing testapp...
Making stage for application testapp...
RoverMR-2:testapp rover$ 
RoverMR-2:testapp rover$ ls
Makefile		RootViewController.h	_			main.m			testappApplication.mm
Resources		RootViewController.mm	control			obj			theos
RoverMR-2:testapp rover$ 
RoverMR-2:testapp rover$ make install
/Users/rover/Documents/Dev/Cydia/Theos/apps/testapp/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Could not find "./com.moveotech.testapp_0.0.1-1_iphoneos-arm.deb" to install. Aborting.
make: *** [internal-install] Error 1

**Comment by BannerBomb1** [comment]
These steps are all wrong add the source on Cydia http://yourepo.bannerbomb.com/ then install the package TheosTutorials and follow all the steps from step 1 to the last step for preparation then you will have to install other stuff but then install the package TheosInstallHelp and goto the link yeah the app isn't finished yet but I gave a link for yall I'll email u the rest of the stuff you need to add to the Theos folder but first u goto email me at BannerBomb55@gmail.com so I can just reply from there because I probably won't come back to this website email me and I will go step by step on fixing all these errors so u will be error free

**Comment by BannerBomb1** [comment]
I and also it's because ur missing files for Theos email me and I'll reply with the files you need

**Comment by DHowett** [comment]
Can you use `make package messages=yes`? It should shed some light on why your package isn't getting built (though Theos thinks it is.)

**Comment by DHowett** [comment]
@BannerBomb1 (please don't advertise or attempt to take users off-site here)

**Comment by BannerBomb1** [comment]
@DHowett I'm not advertising or anything that way I can make sure he has the things installed that he needs because i was getting errors because I was missing certain files that were required he might be missing files and I have all the files that you need for Theos to work saved.

**Comment by BannerBomb1** [comment]
@DHowett o hey I just saw that u made Theos ok I've been looking for someone to help me how can I add text in my Theos application? That's all I need to know is how to add text in the app. Can u help me please

**Comment by BannerBomb** [comment]
@DHowett srry I couldnt find any other place to post this but can u fix Theos to work with iOS 9 please? because I really need it to work with my repo for cydia please update it for iOS 9 plzzzzzzzz.

**Comment by alucard0134** [comment]
Are you still experincing this issue @adaptivedev?

**Comment by alucard0134** [comment]
Due to a lack of response from the author I am assuming that this issue is fixed. If you still have this issue feel free to comment back and I will re-open this
