### ISSUE TITLE
I meet some problem when use theos on linux

### ISSUE THREAD

**Issue by tdh62** [theos/theos#121]
When I use the command make this issue appear

--------------------------------------------------------------------
Your current SYSROOT, "/opt/iphone-sdk-3.0/sysroot", appears to be missing.
/root/deb/test/theos/makefiles/master/rules.mk:20: recipe for target 'before-all' failed
make: *** [before-all] Error 1
---------------------------------------------------------------------
How can I do ? Could you help me ? Thanks a lot.

**Comment by tdh62** [comment]
I tried to find iphone-sdk-3.0 ,but not success.

**Comment by VideahGams** [comment]
I'm having the same issue, not quiet sure what to do.

**Comment by Jake0oo0** [comment]
Did either of you resolve this? @tdh62 @VideahGams

**Comment by VideahGams** [comment]
@Jake0oo0 I managed to get it working using this [pre-configured Theos for Linux](https://mega.co.nz/#!WEQ20RpI!RzdtOJnctxoU463UjmlmvTd-UPoTXwAsXeva1sJgHf8).

I got an error regarding ```libtinfo.so```, but I fixed it by symlinking it to ```libncurses.so```.
If you use Arch, I just used this [AUR Package.](https://aur.archlinux.org/packages/libtinfo/)

**Comment by tdh62** [comment]
I tried various methods, looking for SDK, adjusting the rules.mk to adapt the new sdk, but all of it was not any used.

**Comment by alucard0134** [comment]
You will need to get a toolchain. What I did to fix this issue was grab toolchain/ and /makefiles/targets/Linux/* and moved them to Theos

**Comment by angelXwind** [comment]
@tdh62 I believe I've fixed this issue rather thoroughly by now (I've battle-tested Theos on Windows and Linux by... making it compile literally all my projects ;P) — use coolstar's latest x86_64 toolchain in combination with the new theos repo and try again.

If all is fine, just say so and I'll close this issue (or you can do it yourself, I think)

**Comment by alucard0134** [comment]
@angelXwind I think it is good to close this by now.

@tdh62 if you do need help just hop into #theos and ping Alucard

**Comment by tdh62** [comment]
thanks a lot.I'll close thisissue.
