### ISSUE TITLE
Theos Not Working For iOS 9

### ISSUE THREAD

**Issue by BannerBomb** [theos/theos#122]
@DHowett Theos doent work for iOS 9 it gives a <b>Killed: 9</b> Error when executing the <code>$THEOS/bin/nic.pl</code> command.
I get the <b>Killed: 9</b> error with a lot of MobileTerminal Commands
and a:
<b>/var/theos/makefiles/common.mk:103: *** You did not specify a target, and the "iphone" platform does not define a default target.   Stop.</b> when executing the <code>make package</code> command

and I got another error with a <code>ldid -S ¨command¨</code> error but I dont remember what it is because im not getting it no more now im getting a <b>´<!DOCTYPE html>´</b> error

so can u fix Theos to work with iOS 9 please? because I really need it to work with my repo for cydia please update it for iOS 9 plzzzzzzzz.

btw im running iOS 9.0.2 on iPod Touch 5G

**Comment by halston696** [comment]
Did you ever get theos working?, i have an iPod7,1 and I'm getting all kinds of errors, did you install with the wiki instructions, or another tutorial, really would like to get theos working on ios9.

**Comment by BannerBomb** [comment]
Yes I did and iPod 7 don't exist it's iPod 6 and you have to upgrade Perl on cydia and on MobileTerminal run the command <code>apt-get -f install</code-> and when it says yes or no put <code>yes</code> and make sure "BigBoss Recommended tools" is installed along with all the other dependeincies and theos will work the only thing you cannot do yet is compile packages to deb archives yes

**Comment by BannerBomb** [comment]
Srry at the end I didn't mean to put yes I meant to say Yet

**Comment by halston696** [comment]
i can't get THEOS to work, getting all kinds of errors, and yes, it's the 6th iPod, but it's labeld iPod7,1 :)

**Comment by BannerBomb** [comment]
@halston696 what are the errors you are getting? you might be able to take a screenshot and post them instead of typing them

**Comment by ohyeah521** [comment]
What has changed in iOS 9? (Classes, frameworks, etc.)

Compilation changes
32 bit binaries loaded on 64 bit devices fail to do so since the 32 bit pagesize has been changed from 4096 bytes to 16384 bytes.
Tweaks targeted at 32 bit binaries on iOS 9 must now be compiled with
   -Wl,-segalign,4000
This LDFLAG can be used to compile for older iOS versions as it had to be a multiple of 1000 and this new alignment is compatible.
If using Theos, add it like so to your makefile:
   XXX_LDFLAGS += -Wl,-segalign,4000

**Comment by BannerBomb** [comment]
@oyeah521 but how do I fix these errors that I get when trying to compile a package the errors are below

**Comment by ohyeah521** [comment]
@BannerBomb   edit you makefile   


XXX_LDFLAGS += -Wl,-segalign,4000


xxx is your project name.

**Comment by BannerBomb** [comment]
@ohyeah521 srry for the late response i had to get my computer fixed then my schol tried to say i didnt pay for it well that didnt work i figured it out myself and i forgot how because im not jailbroken anymore im stuck on ios 8.4.1 waiting for the next jailbreak to be released im not upgrading till then

**Comment by angelXwind** [comment]
The `Killed: 9` bug has been fixed with coolstar's latest iOS toolchain, please update from Cydia.

Closing this issue.
