### ISSUE TITLE
Can't compile using toolchain

### ISSUE THREAD

**Issue by ryn-inaba** [theos/theos#125]
I've installed theos and the toolchain using coolstar's PDF, but I cannot compile anything. The error I get is:

$ make package messages=yes
/home/Jennifer/projects/test/theos/makefiles/targets/Cygwin/iphone.mk:38: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Making all for tweak test...
make -f Makefile --no-print-directory --no-keep-going \
        internal-library-compile \
        _THEOS_CURRENT_TYPE=tweak THEOS_CURRENT_INSTANCE=test _THEOS_CURRENT_OPERATION=compile \
        THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
/home/Jennifer/projects/test/theos/bin/logos.pl -c warnings=error    Tweak.xm > ./obj/Tweak.xm.mm
theos/toolchain/windows/iphone/bin/armv7-apple-darwin11-clang++ -x objective-c++ -c -I"/home/Jennifer/projects/test" -DTARGET_IPHONE=1 -O2 -I/home/Jennifer/projects/test/theos/include -include /home/Jennifer/projects/test/theos/Prefix.pch -Wall -Werror  -isysroot "/home/Jennifer/projects/test/theos/sdks/iPhoneOS8.1.sdk" -arch armv7 -miphoneos-version-min=3.0                 -include "logos/logos.h" ./obj/Tweak.xm.mm -o obj/Tweak.xm.25d354ba.o
/home/Jennifer/projects/test/theos/makefiles/instance/rules.mk:144: recipe for target 'obj/Tweak.xm.25d354ba.o' failed
make[2]: *** [obj/Tweak.xm.25d354ba.o] Error 127
/home/Jennifer/projects/test/theos/makefiles/instance/library.mk:19: recipe for target 'internal-library-all_' failed
make[1]: *** [internal-library-all_] Error 2
/home/Jennifer/projects/test/theos/makefiles/master/rules.mk:54: recipe for target 'test.all.tweak.variables' failed
make: *** [test.all.tweak.variables] Error 2

**Comment by angelXwind** [comment]
@ryn-inaba I believe I've fixed this issue rather thoroughly by now — use coolstar's latest x86_64 toolchain in combination with the new theos repo and try again. If all is fine, just say so and I'll close this issue (or you can do it yourself, I think)

**Comment by ryn-inaba** [comment]
It is fixed using the latest toolchain and theos. Thank you.
