### ISSUE TITLE
linux toolchain

### ISSUE THREAD

**Issue by fopina** [theos/theos#131]
Both in iphonedevwiki and this project wiki mention how to get toolchains for windows and on-device but neither specifies how to get it (or build it) for Linux.

I see this has been mentioned in #99 and one of the comments contains this download link
https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip but it would be useful if we had a guide on how to build the linux toolchain somewhere in the wiki..
Or an official source for pre-built toolchains.

I've found some pre-configured theos from coolstar, but that was a zip with theos included, while there should be a clean way to get the toolchain into theos/theos release, not coolstar's..

**Comment by alucard0134** [comment]
Note the 'latest' in the link, just put it in $THEOS/toolchain.

**Comment by fopina** [comment]
What do you mean?
My question was not how to use the link I found. As I mentioned, I used it with success. But the link is not really official (nor is it stable as it has failed a few times).

My question was about the official Theos wiki providing a link to a build or at least a way to build it, as it does for windows and OSX.

I ended up managing to build it like [this](https://github.com/fopina/vagrant-iosjailbreak/blob/master/other/build_toolchain.sh) but it was trial and error to find missing bits (for theos setup) in the default ccports build (like renaming `arm-` to `armv7-`)

**Comment by kirb** [comment]
We're still working on components such as Linux setup, so I apologise that this isn’t clear. At least for now, this is the correct, latest toolchain to use, and what we expect you to be using if you ask for help.

>(nor is it stable as it has failed a few times)

Please explain?

**Comment by fopina** [comment]
I meant the *link* was not stable, not the build :)

One of the days I was trying to use it, it was down most of the day.

Anyway, I opened the ticket because I had to go through the issues to find that link, it wasn't in the wiki.

In [this section of the wiki](https://github.com/theos/theos/wiki/Installation#officially-supported-platforms) there are links to the OSX, iOS and windows toolchains, but not for Linux.

So I was just pointing out, if this is the official toolchain build for linux, it could be added to that section like the other toolchains.

**Comment by CoBrA2168** [comment]
Just wanted to chime in and say I don't think I would have gotten Theos correctly working on my new Linux install if it wasn't for this issue.  I had no idea where to find the toolchain for Linux, and it was only mentioned in this issue.

Even though it's not ready for Linux just yet, we should probably think about adding at least a little something in the wiki about the toolchain in the wiki.  Or at least point people to this issue.

**Comment by alucard0134** [comment]
@fopina https://jbdevs.org/sdks/dl/toolchain.zip heres a mirror. And I personally think that in legal terms this repo may get a DMCA from apple if we put up the toolchain as it is in a "grey area" imo

**Comment by fopina** [comment]
Thanks for the mirror, I'll use it in my script.
You already provide the links for other tool chains in the wiki, why would Linux be different?

**Comment by alucard0134** [comment]
Can you elaborate on 'other toolchains on the wiki' please? As in the link to where it said this

**Comment by uroboro** [comment]
It has been added (https://github.com/theos/theos/wiki/Installation/_compare/d9194926c82843aaa88f77aad77127ad7dcfb7a2...053154175c6a7eb457a85a50e3bf9f458c728fce) but all depend on the same person keeping it up to date.

**Comment by fopina** [comment]
@alucard0134 as mentioned in [this comment](#issuecomment-193206319), [the installation wiki page](https://github.com/theos/theos/wiki/Installation) had links for Coolstar's Windows and iOS toolchains, but nothing for Linux. Not anymore, thanks to @uroboro :+1:
