### ISSUE TITLE
Internal generator throws error while constructing a hook

### ISSUE THREAD

**Issue by kirb** [theos/theos#132]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create Logos file containing:

```logos
%config(generator=internal);

%hook blah
- (void)thing {
    // something...
}
%end
```

2. Feed it through `logos.pl blah.xm`

What happens?
-------------
An internal Logos error occurs.

What were you expecting to happen?
----------------------------------
The syntax is processed successfully.

Any logs, error output, etc?
----------------------------
```
blah.xm: error: generator does not implement Method::initializers
```

Any other comments?
-------------------
N/A

What versions of software are you using?
----------------------------------------
**Operating System:** OS X 10.11.3

**Toolchain Version:** Xcode 7.2

**SDK Version:** iOS 9.2

**Comment by zachatrocity** [comment]
Any fix or work around for this?

**Comment by uroboro** [comment]
If there were, this issue would be fixed and closed. For the time being, use `%config(generator=MobileSubstrate)` which is the default.

**Comment by zachatrocity** [comment]
Sorry, its hard to know what jailbreak projects are active. Should have known by the creation date. Thanks!

**Comment by kirb** [comment]
Fixed this a while ago when pulling in rpetrich’s branch.
