### ISSUE TITLE
Use plistutil instead of plutil on Linux

### ISSUE THREAD

**Issue by fxfactorial** [theos/theos#134]
This is on head and on linux. 

when doing: 

```
FOR_RELEASE=1 make package
```

theos will assume the existence of `plutil` which does not exist on Linux. and hence will crap out on 

```
.theos/_ \( -name \*.plist -or -name \*.strings \) -exec plutil -convert binary1 {} \;
find: `plutil': No such file or directory

```

 There is apparently a linux version called `plistutil` but theos doesn't pick the right one appropriately. I will try to fix this as well and submit upstream when have time. 

The relevant code is line 12 of makefiles/package.mk

**Comment by kirb** [comment]
Good catch. I'll wait for you to send a pull request.
On Thu, 25 Feb 2016 at 08:33, Edgar Aroutiounian <notifications@github.com>
wrote:

> This is on head and on linux.
>
> when doing:
>
> FOR_RELEASE=1 make package
>
> theos will assume the existence of plutil which does not exist on Linux.
> and hence will crap out on
>
> .theos/_ \( -name \*.plist -or -name \*.strings \) -exec plutil -convert binary1 {} \;
> find: `plutil': No such file or directory
>
>
> There is apparently a linux version called plistutil but theos doesn't
> pick the right one appropriately. I will try to fix this as well and submit
> upstream when have time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/134>.
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by uroboro** [comment]
Maybe have a `_THEOS_PLATFORM_PLUTIL` on each makefiles/platform/*.mk?

**Comment by alucard0134** [comment]
This will require another dependency on linux either way, being as plistutils is not installed by default, package name on ubuntu/debian is libplist-utils

**Comment by uroboro** [comment]
`plutil` isn't a builtin tool on iOS either so it requires Erica Utilities.

**Comment by alucard0134** [comment]
(it didnt fix anything :(()

**Comment by kirb** [comment]
Want to get this fixed, but plconvert is really awful to automate as it assumes you know what the input is and that the output you want is the opposite (so binary plist always becomes XML; XML/NeXT always becomes binary). I’ll have to add a script that checks the first few bytes of the file for the binary plist magic bytes `bplist`, and if not present then run plconvert.

**Comment by kirb** [comment]
This is still unresolved, so let’s keep this open.

**Comment by Finermeerkat137** [comment]
I've created a somewhat decent wrapper for `plistutil` on linux (it can only convert) that could be used. It requires (on Arch) `libxml2` and `plistutil`. Its here: https://gist.github.com/Finermeerkat137/e8119a8a8c82ab9c483ff3ccc2a5ea52

**Comment by kirb** [comment]
That looks like a good workaround. Thanks for sharing! I’ll play around with a solution soon.

**Comment by tomasreimers** [comment]
Hi! In case it's still relevant, [Screenplay](https://screenplay.dev/) currently maintains an open-source, cross-platform, drop-in replacement for `plutil`:

https://github.com/screenplaydev/plutil 

It's based on Facebook's xcbuild (a tool developed by them to build xcode projects on Linux), but stripped down to just provide plist-editting functionality.

**Comment by kirb** [comment]
@tomasreimers That’s really useful, thanks! Too bad xcbuild was abandoned, there’s some solid work in there. Good to see people step up to maintaining forks of those tools.

In this case I’m thinking we may still just go ahead with using `plistutil`, with a wrapper script that looks for the bplist magic bytes to decide whether conversion is needed. Just easier for distribution this way, since Theos itself doesn’t actually ship any binaries, and `libplist-utils` should be in every distro.

**Comment by UsrLightmann** [comment]
> @tomasreimers That’s really useful, thanks! Too bad xcbuild was abandoned, there’s some solid work in there. Good to see people step up to maintaining forks of those tools.
> 
> 
> 
> In this case I’m thinking we may still just go ahead with using `plistutil`, with a wrapper script that looks for the bplist magic bytes to decide whether conversion is needed. Just easier for distribution this way, since Theos itself doesn’t actually ship any binaries, and `libplist-utils` should be in every distro.

Since plutil is a macOS exclusive and both plutil and plistutil require an accompanying script to check for the bplist bytes anyway, was the idea to move the conversion over to plistutil for all platforms? 

It looks like it's already available on every platform Theos supports -- jailbroken iOS via Elucubratus/Procursus' respective repos, macOS via brew, and common Linux distros via their accompanying stable/extra repos.

**Comment by UsrLightmann** [comment]
Gotcha. Okay, I might try and implement some or all of that when I get some free time. Will make a pr if I make any progress

**Comment by kirb** [comment]
Fixed with c6da661

**Comment by NoisyFlake** [comment]
I've actually created an alias for plutil, but the conversion script doesn't seem to care. Even though I get the alias when running `command -v plutil` manually, the script keeps telling me that no supported pl tool was found. I might give ply a try though.

**Comment by nyuszika7h** [comment]
aliases don't work in scripts, you need to put a `plutil` wrapper binary somewhere in your PATH.
