### ISSUE TITLE
_prefix/nullabilitycompat.h missing

### ISSUE THREAD

**Issue by ethanf108** [theos/theos#135]
I am using iOS 8.4 iPad mini 2
When I use make I get this error: 
![image](https://cloud.githubusercontent.com/assets/17579380/13442115/8c9e82ae-dfaf-11e5-80d6-d2fa75ef3860.jpg)
What?

**Comment by kirb** [comment]
You did not clone submodules when you cloned Theos. In your project directory, run `make update-theos` and this will be done for you.

**Comment by kirb** [comment]
Added a check to warn of this common mistake in 5a0029f.

**Comment by kirb** [comment]
Closing due to lack of response. If you are still experiencing problems, since this isn’t an issue with Theos itself, please [visit IRC](http://iphonedevwiki.net/index.php/IRC) for further assistance.
