### ISSUE TITLE
More descriptive troubleshoot rule

### ISSUE THREAD

**Issue by uroboro** [theos/theos#136]
`make troubleshoot` should also include the versions of the toolchain tools, git, make, as well as the host machine data (the same data used to determine which makefiles to include via `uname`).

**Comment by uroboro** [comment]
If we dump info to temporal files we can make the ghostbin paste formatted as Markdown with https://ghostbin.com/paste/hdbau having segments for each piece of information. This will render the paste similar to this:

Setup and project
===
___
```
OS:\"$(_THEOS_OS)\"
PLATFORM-ARCH:\"$(_THEOS_PLATFORM_ARCH)\"
TARGET:\"$(TARGET)\"
ARCHS:\"$(ARCHS)\"
```

git version:
===
___
```
'git --version'
```

make version:
===
___
```
'make --version'
```

perl version:
===
___
```
'perl --version'
```

console output
===
___
```
...
```

**Comment by kirb** [comment]
Closing in favor of #171.
