### ISSUE TITLE
Prevent "corrupt" control file.

### ISSUE THREAD

**Issue by uroboro** [theos/theos#139]
Make sure that the control file contains no empty lines and that it contains a newline at the end.

**Comment by kirb** [comment]
But dpkg-deb would throw an error anyway, no?

**Comment by uroboro** [comment]
If this check is done before https://github.com/theos/theos/blob/master/makefiles%2Fpackage%2Fdeb.mk#L31 it should be alright.

**Comment by ahyattdev** [comment]
I think that theos should try to catch as many mistakes as are practical, because when I was starting out as a dev, it was hard to understand what an error from a build system with so many components working together means.

**Comment by kirb** [comment]
May be worth taking advantage of `dpkg-gencontrol`?

It adds some extra features such as being able to define multiple packages in the one file, variables, comments, and having dependencies split over multiple lines, see for example [dpkg’s control file](https://github.com/guillemj/dpkg/blob/master/debian/control).

We would need dpkg-dev/libdpkg-perl ported to iOS and Windows for this (which is mostly Perl scripts).

**Comment by uroboro** [comment]
Fixed with 170de6f.
