### ISSUE TITLE
Use of undeclared identifier 'HBLogError' when trying to build using Xcode

### ISSUE THREAD

**Issue by ilendemli** [theos/theos#141]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a project using Xcode and iOSOpenDev
2. Write a small tweak
3. Try to build it for profiling

What happens?
-------------
Can't compile because HBLogError can't be found

What were you expecting to happen?
----------------------------------
Well, the tweak to get compiled

Any logs, error output, etc?
----------------------------
Use of undeclared identifier 'HBLogError'

Any other comments?
-------------------
nope

What versions of software are you using?
----------------------------------------
OS X 10.11.3

The latest theos version (just downloaded it)

iOS 7.0 SDK

**Comment by kirb** [comment]
My assumption would be that iOSOpenDev (which I know absolutely nothing about) is just directly running logos.pl and then feeding the output straight to clang with the command line configured by Xcode. 

Two potential solutions:

* Go to the build settings, and add to the prefix header field: `$THEOS/Prefix.pch`. (You probably also need to create a new build variable there for `THEOS=/path/to/theos`.)
* Use Theos, either just from the command line or by creating an external build target in Xcode. In the wizard set it to `/usr/bin/make`, arguments `do`. Set $THEOS as above.

**Comment by shadyproject** [comment]
I'm seeing this same issue, but not using iOSOpenDev.
I've just set up theos and I'm trying to build an existing package with minor updates. 

I get the following output

```
==> Preprocessing Tweak.xmi…
==> Compiling Tweak.xmi (armv7)…
Tweak.xmi:122:459: error: use of undeclared identifier 'HBLogError'
```

With about 20 lines of the HBLogError message.  Everything in theos is up-to-date.

**Comment by kirb** [comment]
Hooks are currently broken with .xi/.xmi files, as they rely on a
preprocessor macro, but the preprocessor has already run. What are you
using xi/xmi for? I encourage people to consider if they can avoid xi/xmi
instead. If you absolutely can't without losing something then you'll have
to wait for this to be worked out.

On Tue, 29 Mar 2016 at 04:46, Chris Martin <notifications@github.com> wrote:

> I'm seeing this same issue, but not using iOSOpenDev.
> I've just set up theos and I'm trying to build an existing package with
> minor updates.
>
> I get the following output
>
> ==> Preprocessing Tweak.xmi…
> ==> Compiling Tweak.xmi (armv7)…
> Tweak.xmi:122:459: error: use of undeclared identifier 'HBLogError'
>
> With about 20 lines of the HBLogError message. Everything in theos is
> up-to-date.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/141#issuecomment-202514596>
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by shadyproject** [comment]
At the moment I'm just trying to build an existing code base that makes use of xi/xmi files.  I'm new to Theos and just trying to figure everything out.  I'll see if the same work can be done without using xi/xmi files.

**Comment by rpetrich** [comment]
I'm of the opinion that if iOSOpenDev wants to use the logos compiler, they should pin to a version that works with their setup and ship it inside their installer to their own install path. If there's features that they need from logos upstream to make that work, the iOSOpenDev maintainers should ask for them.

That being said, if xmi/xi doesn't work on HEAD right now when using theos, that's something that should be addressed.

**Comment by kirb** [comment]
At the moment, you may want to jump way back to legacy Theos – `git
checkout legacy`. (You may get strange clang errors – if the build doesn't
fail, ignore them.) It's most likely the case that the codebase you're
looking at was built using legacy Theos, anyway, considering this has been
broken for some time.

On Thu, 31 Mar 2016 at 02:40, Chris Martin <notifications@github.com> wrote:

> At the moment I'm just trying to build an existing code base that makes
> use of xi/xmi files. I'm new to Theos and just trying to figure everything
> out. I'll see if the same work can be done without using xi/xmi files.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/141#issuecomment-203506785>
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by shadyproject** [comment]
Yeah, I'm trying to build Introspy, which  required a specific fork of Theos.  I thought I'd try and update it for the current release, but at the moment I don't know enough about Theos to do it.  If there's any documentation on using xi/xmi files vs not, I'll be happy to take a look at it and see.

**Comment by uroboro** [comment]
Seeing https://github.com/iSECPartners/Introspy-iOS/blob/master/src%2FTweak.xmi popping up again, this is an approach to using a single constructor for multiple group initializations for hooks defined in separate files. I find that including source files is not a good practice and this demonstrates a shortcoming of how Logos works, not allowing forward declaration of groups for initialization since it works with files independently of each other.

To not use .xmi in this case, you'd have to copy the preferences logic in this file and paste it on each .xm file, removing the code not related to the `%group` in that file, or make a file with this logic wrapped in a function that after preprocessing with Logos can successfully initialize each group. This being tedious to maintain and generating more than duplicate code were probably the reasons to use .xmi.

**Comment by hduarte** [comment]
Is there any way that one can rewrite this so it can be compatible with what is the best practice regarding theos ? If so, there is any example that can be used and/or documentation ?

**Comment by uroboro** [comment]
One way would be to replace each `#include "hooks/XXX.xm"` with the contents of _hooks/XXX.xm_.

**Comment by kirb** [comment]
As this thread is a few months old and a workaround has been noted, I’ll be closing this. If you still have issues, please re-open this with your questions.

**Comment by mickymouse1** [comment]
I am confused - what's the workaround? I'm having this same issue.

**Comment by uroboro** [comment]
https://github.com/theos/theos/issues/141#issuecomment-204471775 and https://github.com/theos/theos/issues/141#issuecomment-213743538

**Comment by mickymouse1** [comment]
I'm not understanding what to do - I am having this same problem. I tried to include #import <_Prefix/HBLog.h> in the Prefix.pch folder but the compiler is telling me that it can't find the _Prefix folder. I checked the header search paths in the build settings and it goes to iOSOpenDev/include and the folder is in this file. I am not sure what's going on and would appreciate it if someone could help!

**Comment by hduarte** [comment]
For the ones that wanted a working version of introspy with theos, here it is: https://github.com/integrity-sa/Introspy-iOS. Thks for the help @uroboro :)

**Comment by ThePantsThief** [comment]
> Hooks are currently broken with .xi/.xmi files, as they rely on a preprocessor macro, but the preprocessor has already run.

Is this still the case? I'm having trouble compiling someone's tweak because they're using the xctheos macros by Adam Bell to help develop the tweak in Xcode. Trying to decide if I should ditch them when I submit a pull request.

**Comment by lzyroot** [comment]
.xm  file add code

`#define HBLogError NSLog`

**Comment by kirb** [comment]
This was removed as of 5894628, @lzyroot. If you need that workaround even after `make update-theos`, this is a different bug.

**Comment by lzyroot** [comment]
@kirb how to update theos

**Comment by lzyroot** [comment]
@kirb make: *** No rule to make target `update-theos'.  Stop.   not Theos older version
