### ISSUE TITLE
armv7-apple-darwin11-clang-3.7: command not found

### ISSUE THREAD

**Issue by Starwarsfan2099** [theos/theos#143]
`make package` returns:

`> Making all for application app2…
==> Copying resource directories into the application wrapper…
==> Compiling main.m (armv7)…
/opt/theos/toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++: line 1: armv7-apple-darwin11-clang-3.7: command not found
/opt/theos/makefiles/instance/rules.mk:170: recipe for target '/root/app2/.theos/obj/debug/armv7/main.m.3b9554fa.o' failed
make[3]: *** [/root/app2/.theos/obj/debug/armv7/main.m.3b9554fa.o] Error 127
/opt/theos/makefiles/instance/application.mk:47: recipe for target '/root/app2/.theos/obj/debug/armv7/app2.app/app2' failed
make[2]: *** [/root/app2/.theos/obj/debug/armv7/app2.app/app2] Error 2
/opt/theos/makefiles/instance/application.mk:39: recipe for target 'internal-application-all_' failed
make[1]: *** [internal-application-all_] Error 2
/opt/theos/makefiles/master/rules.mk:85: recipe for target 'app2.all.application.variables' failed
make: *** [app2.all.application.variables] Error 2`

# Main error:

`/opt/theos/toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++: line 1: armv7-apple-darwin11-clang-3.7: command not found`
# Info
I am running theos on Kali Linux.

I have the Linux toolchain installed from  https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip and in `$THEOS/toolchain`

My SDK is from the latest xcode. I do not own a Mac so I downloaded the .dmg and extracted the SDK. It is in `$THEOS/sdks`

**Comment by ahyattdev** [comment]
`linux/iphone/bin/armv7-apple-darwin11-clang++` is a symlink pointing to `armv7-apple-darwin11-clang-3.7`, which appears to be in the same folder as the symlink, so this appears valid to me. 

`line 1: armv7-apple-darwin11-clang-3.7: command not found`

For some reason, the content of the symlink is being treated as a script and it appears as though the first line of it (the destination) is being run as a shell command. 

My machine (Mac OS X 10.11.3 x86_64) recognizes the symlink correctly.

**Comment by supermamon** [comment]
If it helps, I have a working script to install theos on linux. Tested on Linux Mint. 
https://gist.github.com/supermamon/360f53099953c68b66bb

**Comment by kirb** [comment]
Closing as this is an old thread and a solution has been provided.

**Comment by StarSunSunny** [comment]
you could atleast leave a link as to where the old post is
