### ISSUE TITLE
theos assumes that theos is installed to ~/theos/ when running theos-update

### ISSUE THREAD

**Issue by ahyattdev** [theos/theos#144]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run make update-theos
2. Have theos installed to a place other than ~/theos/

What happens?
-------------
> Updating Theos…
Already up-to-date.
> Updating submodules…
Entering 'vendor/include'
fatal: Not a git repository: /Users/username/theos/.git/modules/include
fatal: Not a git repository: /Users/username/theos/.git/modules/include
Stopping at 'vendor/include'; script returned non-zero status.
make: *** [update-theos] Error 1

What were you expecting to happen?
----------------------------------
It should look for theos at $THEOS, which is /opt/theos/ for me, not ~/theos/. 

Any logs, error output, etc?
----------------------------
See What Happens

Any other comments?
-------------------
no

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS X 10.11.3 x86_64

**Toolchain Version:** latest

**SDK Version:** 9.3

**Comment by uroboro** [comment]
Although Theos itself is not broken,

```
Updating Theos…
Already up-to-date.
```

It is the submodules updating part that isn't working here. And it isn't the updating rule that's failing because the error message would be different.

**Comment by kirb** [comment]
It definitely doesn’t make that assumption – [the rule](https://github.com/theos/theos/211ed9680bb58d5b9d3893364dc0b440a60997da/master/makefiles/master/rules.mk#L138-149) uses $(THEOS) in every instance. 

It rather sounds like you cloned Theos in ~, then `sudo mv`’d it to /opt. Git for some stupid reason keeps hardcoded paths to the submodules. Try:

```shellsession
$ find $THEOS -type f -name .git
```

They will all be files containing `gitdir: /path/to/theos/.git/modules/blah`. Open all of them, and fix up the path. (Relative paths are supported.)

**Comment by ahyattdev** [comment]
Could you somehow modify the installation tutorial on the wiki of this repo to avoid this issue? maybe change: 

```
git clone --recursive https://github.com/theos/theos.git
sudo mv theos /opt/theos
```

to

```
sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
chown -R $USER:staff /opt/theos
```

would this work?

**Comment by kirb** [comment]
Just added some info and a (cross-platform) workaround to the wiki.
