### ISSUE TITLE
Failed while updating Theos

### ISSUE THREAD

**Issue by MTShare** [theos/theos#145]
Hi, when i'm trying to update Theos, it gives me this error:

What are the steps to reproduce this issue?
-------------------------------------------
1. make update-theos

What happens?
-------------
> Updating Theos…
Already up-to-date.
> Updating submodules…
Entering 'vendor/include'
Fetching origin
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

Stopping at 'vendor/include'; script returned non-zero status.
make: *** [update-theos] Error 1

Any suggestions?
Thanks in advance

**Comment by ahyattdev** [comment]
#144 is another issue with the whole vender submodule feature. Different cause, however.

**Comment by kirb** [comment]
Hm, I suppose this should rather be a `git fetch` and then a `git checkout` of the parent repo’s reference commit. Or just run `git submodule update` on that individual repo.

**Comment by kirb** [comment]
This was fixed long ago; forgot to close this.
