### ISSUE TITLE
Failed updating theos

### ISSUE THREAD

**Issue by Gh0stByte** [theos/theos#148]
I downloaded theos from this repository a couple weeks ago, and tried to update it today. When I run `make update-theos`, I get this error:

`==> Error: /opt/theos is not a Git repository. For more information, refer to https://github.com/theos/theos/wiki/Installation#updating.
/opt/theos/makefiles/master/rules.mk:138: recipe for target 'update-theos' failed
make: *** [update-theos] Error 1`

I'm using theos on Windows through cygwin.

**Comment by uroboro** [comment]
If you downloaded it as a zip, then that would be the issue. Follow the steps on the [installation page](https://github.com/theos/theos/wiki/Installation) to do a clone of the repository.

**Comment by Gh0stByte** [comment]
Thanks a lot.
