### ISSUE TITLE
Theos with all submodules included, complete self-contained theos desired.

### ISSUE THREAD

**Issue by fxfactorial** [theos/theos#152]
Would it be too much trouble to have another branch that would be the equivalent of 

`--recursive`? 

I want to integrate theos as a sub project for me but the `--recursive` issue is difficult to get to play nicely with a git subtree and simply doing `--recursive` and deleting all the .gitmodules caused me build errors after version controlling the result of 
`git clone --recursive theos/theos` and deleting the .gitmodules.

**Comment by kirb** [comment]
Don’t really think the use case is strong enough for such a thing. It does go against the reason why submodules are used in the first place (so we can separate each unit of Theos, especially as we try to make it less biased towards iOS). Also means you’ll lose the history, or we’ll have to write an awkward script to merge each commit into the one repo (and even then you’ll lose the original SHA). Sorry – it’s just how Git works, and Theos is fairly tightly integrated with Git, but if there’s sufficient demand we can definitely work something out.

**Comment by fxfactorial** [comment]
I see, thanks for the great reply. My use case is that I wanted to integrate theos with https://github.com/NixOS/nixpkgs and having to do a separate nixpkg for each subproject is somewhat tedious.

**Comment by kirb** [comment]
We don’t really have a solution yet for supporting package managers. See #111 for some previous discussion. In general though I don’t think there’s anything that a package manager can provide Theos that a cloned copy of the Git repo doesn’t already.

**Comment by fxfactorial** [comment]
For me it would provide a 1) tighter integration with my projects 2) Provides reproducibility, having to do a --recursive makes me always hope that those submodules will all work together nicely like the last time I did it. Blindly pulling from the network each time I do a new theos --recursive clone is crossing my fingers that everything will work well together. I might just bite the bullet and do the separate nix package for each submodule.

**Comment by kirb** [comment]
I’m a little confused. You can already do this by just not updating Theos, or after a clone simply checking out a known good commit (`git checkout <sha>`). Submodules never automatically update; they use the SHA specified by the parent repo, so the submodules are guaranteed to be the same as they were when you last checked out that commit. You could also make a fork and clone that instead. Is there something I’m missing?

**Comment by fxfactorial** [comment]
Yes, I could do that `git checkout` step, but its an extra step and extra complication. Re submodules, my bad: I forgot that submodules follow the SHA specified by parent repo. I thought about the fork too but then it would be mean a dependency on me having to manually update the fork when upstream theos updates.

**Comment by kirb** [comment]
Closing this as this is old and the request probably won’t be implemented. If you still have questions, you can [ask on IRC](http://iphonedevwiki.net/index.php/IRC).
