### ISSUE TITLE
cant build on windows

### ISSUE THREAD

**Issue by Showian** [theos/theos#154]
I use this tut http://sharedinstance.net/2013/12/build-on-windows/ 
and install all of tools, when i try to make a package on windows i got this error:
The "iphone" target is not supported on the "windows" platform. Stop.

I use windows 7 and latest Theos ios 7 and 8 SDK

**Comment by Gh0stByte** [comment]
Try following this one https://coolstar.org/iOSToolchainOnWindows.html

**Comment by kirb** [comment]
@Gh0stByte, note that uses a very outdated version of Theos.

**Comment by supermamon** [comment]
@Showian try https://gist.github.com/de9cec9cd1ccf0abaa656370e12298de

**Comment by Showian** [comment]
Thank you for reply
@Gh0stByte links broken for download LLVM+Clang 
@supermamon when i run script its give me this error:
```
./install.sh: line 5: $'\r': command not found
./install.sh: line 6: $'\r': command not found

./install.sh: line 7: $'\r': command not found
***** [PRE-SETUP CHECK...] *****
./install.sh: line 9: $'\r': command not found
./install.sh: line 71: syntax error near unexpected token `$'do\r''
'/install.sh: line 71: `for i in ${SDKS[@]}; do
```

**Comment by kirb** [comment]
Don’t use Notepad/WordPad. It uses `\r\n` for newlines (Windows format); you need `\n` (Unix format). Alternatively, you probably have to configure your editor to always use Unix line endings.

**Comment by Showian** [comment]
@kirb thank you so much. I installed it, but i have a problem and this is only for preference bundles,
I can make tweaks but I cant make preference bundles 
this is error that i get:
```
> Making all for bundle preference.
==> Copying resource directories into the bundle wrapper.
==> Compiling XXXRootListController.m (armv7).
==> Linking bundle preference (armv7).
==> Compiling XXXRootListController.m (arm64).
==> Linking bundle preference (arm64).
==> Merging bundle preference.
==> Signing preference.
> Making stage for bundle preference.
==> Error: make package requires you to have a layout/ directory in the project
root, containing the basic package structure, or a control file in the project r
oot describing the package.
/opt/theos/makefiles/package/deb.mk:46: recipe for target 'internal-package' fai
led
make: *** [internal-package] Error 1
```

**Comment by kirb** [comment]
Please be aware that the issue tracker is for discussing actual bugs in Theos, not for requesting troubleshooting help. See our [issue guidelines](https://github.com/theos/theos/blob/master/.github/CONTRIBUTING.md).

---

To answer anyway:

Preference bundle projects are almost always used as a subproject, and you are building it like a master project. If you were to work this way, you would be building a separate package for the tweak and its preference bundle, which almost definitely is not what you want.

The parent project of the preference bundle should already be set up to build the preference bundle as a subproject, if you ran NIC from the same directory as the master project’s makefile. When you build the master project, your subprojects will also be built and included in the same package.

Please also change your class prefix from `XXX` to something else. Your prefix should be unique; if it isn’t then there will be [unexpected surprises](http://nshipster.com/namespacing/).

---

As your original issue seems to be resolved, I will be closing this.
