### ISSUE TITLE
Why linker error would not show on older theos? 

### ISSUE THREAD

**Issue by r-plus** [theos/theos#157]
This is just technical question, not problem.

What are the steps to reproduce this issue?
-------------------------------------------
Build https://github.com/r-plus/theos-link-error-sample used latest theos and older theos.

What happens?
-------------
I recently switched to latest theos from older theos(330c79022bccab58c09f85d907c92e1c0e989200).
I saw below linker error on my project build.

```
Undefined symbols for architecture armv7:
  "_WTFCrash", referenced from:
      StringImpl::characters8() const in OTB.xm.eef8dbff.o
      StringImpl::characters16() const in OTB.xm.eef8dbff.o
  "_WTFReportAssertionFailure", referenced from:
      StringImpl::characters8() const in OTB.xm.eef8dbff.o
      StringImpl::characters16() const in OTB.xm.eef8dbff.o
ld: symbol(s) not found for architecture armv7
```

That symbols contains JavaScriptCore framework, so I add it to makefile then solved error.

```
$ find ${THEOS}/sdks -name "*.tbd" | xargs grep -l WTFCrash
/opt/theos/sdks/iPhoneOS9.2.sdk/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore.tbd
```

Why linking phase is succeed without link to JavaScriptCore framework when using older theos?

What were you expecting to happen?
----------------------------------
Linking code is changed?

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** OS X 10.11.4

**Toolchain Version:** Xcode 7.2.1

**SDK Version:** iPhoneOS 9.2 sdk

**Comment by kirb** [comment]
Support for clang modules was added several months ago. With modules on, `#import <JavaScriptCore/JavaScriptCore.h>` is internally translated to `@import JavaScriptCore;` which imports it as a module. Importing a module also implicitly links against it.

Xcode has had modules enabled for some time, and Swift exclusively only supports importing modules (not headers).

**Comment by kirb** [comment]
Oh – I misread. You could maybe try setting your deployment target to iOS 8.3, which will disable Theos inserting the module flags into the clang command line. If that works, try modifying `$THEOS/makefiles/targets/Darwin/iphone.mk` to remove `-fcxx-modules`. On older versions of clang (3.5, included with Xcode 6.0 – 6.2), support for C++ modules was highly experimental. It was since completed and *should* be ok, but definitely could still be problems.

Let me know how you go. If needed I will add workarounds to Theos.

**Comment by r-plus** [comment]
Oh, I edit first post to write issue template.

And I made repository to reproduce this issue. Could you reproduce this?
https://github.com/r-plus/theos-link-error-sample

deployment target to iOS 8.3(`TARGET = iphone:clang:9.2:8.3`) and remove `-fcxx-modules` are no effect to this issue.

**Comment by kirb** [comment]
Closing this as it’s an old discussion thread. If you still have questions, you can [ask on IRC](http://iphonedevwiki.net/index.php/IRC).
