### ISSUE TITLE
Linking Errors

### ISSUE THREAD

**Issue by Naville** [theos/theos#160]
-------------------------------------------
1. run "make"

What happens?
-------------
==> Linking tweak JXUDARRGD14LZBK (armv7)…
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: arm-apple-darwin15.5.0
Thread model: posix
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk'

.......

ld: library not found for -lobjc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[1]: *** [internal-library-all_] Error 2
make: *** [JXUDARRGD14LZBK.all.tweak.variables] Error 2
Make Exit With Status:  512

What were you expecting to happen?
----------------------------------
build successfully

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/gfjzc

Any other comments?
-------------------
Legacy version of theos works fine
What versions of software are you using?
----------------------------------------
**Operating System:** 10.11.5

**Toolchain Version: Xcode 7.2.1

**SDK Version:**9.2

**Comment by Naville** [comment]
The project is in https://github.com/Naville/WTFJH

**Comment by Naville** [comment]
there was a temporary work around before which adds something like"export TARGET = iphone:clang:7.0:7.0" to the makefile.

While the legacy theos is OK with the toolchain version inconsistency, the latest version results in a build error

**Comment by kirb** [comment]
So is there a bug on our side or no?

**Comment by Naville** [comment]
@kirb yes and no. A while ago there was a widely spreaded tut to compile multiple arches which is what I previously mentioned. Using the legacy version of THEOS, export XXXX7.07.0 thingy works even if I don't have 7.0 SDK installed. The latest theos will throw a error when corresponding SDK doesn't exist

**Comment by kirb** [comment]
Sounds like you’re confused.

The syntax is `target:compiler:sdkversion:deployversion`. The deploy version is the minimum version of iOS that you will allow the code to run on. The SDK version is the version of the SDK to use that is available on your computer. On OS X, SDKs are contained in Xcode and are the latest versions as of when your current version of Xcode was released. On other platforms, you install SDKs to $THEOS/sdks. It’s not possible to use an SDK version that doesn’t exist in the SDKs directory of Xcode or Theos – you would instead be told that the SDK doesn’t exist.

What “multiple archs” are you trying to build for? armv7/arm64? armv6? It sounds like you’re referring to the latter. Be aware that this is supported better by Theos now.

In ~/.theosrc (which you’ll probably need to create), add:

```make
THEOS_PLATFORM_SDK_ROOT_armv6 = /path/to/Xcode-4.4.1.app/Contents/Developer
SDKVERSION_armv6 = 5.1
```

In your tweak makefile:

```make
ARCHS = armv6 armv7 arm64
TARGET_IPHONEOS_DEPLOYMENT_VERSION_armv6 = 5.0
```

Adjust deployment version accordingly.

**Comment by Naville** [comment]
thanks. That's just a old tut around the web though.

I currently simply removed 
#TARGET=XXXXXX 
and it works like a charm
