### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by DylanDuff** [theos/theos#161]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. cd ~/TweakName
2. make package
3. Watch it fail to compile 

What happens?
-------------
When trying to compile with theos under Cygwin on windows 10 I get errors and nothing compiles

What were you expecting to happen?
----------------------------------
It to compile the tweak

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/h5yqk

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10

**Toolchain Version:** Most recent version of coolstar's iOSToolchain4Win

**SDK Version:** iPhoneOS9.0.sdk

Makefile : 

    export THEOS=~/theos
    ARCHS = arm64 armv7
    include $(THEOS)/makefiles/common.mk
 
    TWEAK_NAME = AAAPatch
    AAAPatch_FILES = Tweak.xm
 
    include $(THEOS_MAKE_PATH)/tweak.mk

**Comment by uroboro** [comment]
Can you share the list of directories in `$THEOS/sdks`?

For more context, there's a [previous thread](https://www.reddit.com/r/jailbreakdevelopers/comments/4mffz8/cant_compile_tweak_in_theos/) on reddit.

**Comment by DylanDuff** [comment]
is this okay? https://ghostbin.com/paste/u5p3a

**Comment by DylanDuff** [comment]
Anything new about this?

**Comment by iMokhles** [comment]
You still need help or you solved this problem ?!

**Comment by kirb** [comment]
As this issue is over a month old and the reporter hasn’t responded in some time, I’ll be closing it. If this issue still exists, please re-open it with more details.
