### ISSUE TITLE
Rename THEOS_PACKAGE_DIR_NAME from debs to out(?)

### ISSUE THREAD

**Issue by kirb** [theos/theos#163]
Thanks to some work pulled in from Ryan’s branch, we support deb, rpm, and pkg as packaging formats. Regardless of format used, the packages are still stored in a directory called `debs`. Therefore, wondering whether we should rename `$(THEOS_PACKAGE_DIR_NAME)` to something generic like `packages`, or `out`, or even `$(_THEOS_PACKAGE_FORMAT)s` (ie, `debs`, `rpms`, `pkgs`).

We should probably also move existing `debs` directories to the new name.

**Comment by supermamon** [comment]
I would suggest `bin` that seems to imply that they are executables. I vote for  `packages` -- that is if my vote counts.

**Comment by DHowett** [comment]
`dist` is another option. I'm fairly fond of `packages`.

**Comment by angelXwind** [comment]
I think `packages` works the best here.

`bin` I feel is much more associated with actual binaries as opposed to packages.

**Comment by rpetrich** [comment]
My vote is for packages as well
