### ISSUE TITLE
Back again?

### ISSUE THREAD

**Issue by Packetfahrer** [theos/theos#164]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. make package install
2. …
3. …

What happens?
-------------
sudo: command not found 
make: *** [internal-install] Error 127

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?

when i build with older Version of Xcode (6.4) it  doesn't find CydiaSubstrate

ld: framework not found CydiaSubstrate

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:9.2

**Comment by kirb** [comment]
Install sudo on the device.

You will also need to clone submodules. Use: cd $THEOS; git submodule
update --init
On Sat., 18 Jun. 2016 at 20:28, Packetfahrer <notifications@github.com>
wrote:

> (Thanks for reporting an issue! Please make sure you click the link above
> to view the issue guidelines, then fill out the blanks below.)
> What are the steps to reproduce this issue?
>
>    1. make package install
>    2. …
>    3. …
>
> What happens?
>
> sudo: command not found
> make: *** [internal-install] Error 127
> What were you expecting to happen?
>
> …
> Any logs, error output, etc?
>
> (If it’s long, please paste to https://ghostbin.com/ and insert the link
> here.)
>
> Any other comments?
>
> when i build with older Version of Xcode (6.4) it doesn't find
> CydiaSubstrate
>
> ld: framework not found CydiaSubstrate
> What versions of software are you using?
>
> *Operating System:* …
>
> *Toolchain Version:* …
>
> **SDK Version:9.2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/theos/theos/issues/164>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAvMvZ1sVg5GCG8puvwqCIg5gaKTwY1Eks5qM885gaJpZM4I47GB>
> .
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au
