### ISSUE TITLE
Make Update

### ISSUE THREAD

**Issue by Packetfahrer** [theos/theos#166]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … make update-theos
2. …
3. …

What happens?
-------------
 http://pastebin.com/CEH0bEu9

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by uroboro** [comment]
`What happens?` should probably have a human readable description while `Any logs, error output, etc?` should contain the link to the error output.

Given that Apple ships old versions of tools such as sed, to fix this use brew to install `gnu-sed`

    brew install gnu-sed --with-default-names

and add to your `~/.bash_profile` or equivalent

    export PATH=/usr/local/opt/gnu-sed/bin/:$PATH

so that the brew version of sed is used instead of the one in the Xcode command line tools.

**Comment by kirb** [comment]
It still should support both implementations of sed though, so the bug
still stands.

On Tue., 21 Jun. 2016 at 04:14, Packetfahrer <notifications@github.com>
wrote:

> Closed #166 <https://github.com/theos/theos/issues/166>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/theos/theos/issues/166#event-698059830>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAvMvQ8yNVbCg3IpKOyGi5G-MV3bDzGLks5qNt-QgaJpZM4I5--->
> .
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by kirb** [comment]
Fixed in cd2d4be a few days ago.
