### ISSUE TITLE
No rule to make target `update-theos'.

### ISSUE THREAD

**Issue by markcoker** [theos/theos#170]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Installed Theos
2. Tried to run 'make update-theos'

What happens?
-------------
Update fails saying no rule to make target, even though there is, possibly user error?

What were you expecting to happen?
----------------------------------
Theos updated

Any logs, error output, etc?
----------------------------
make: *** No rule to make target `update-theos'.  Stop.

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS 10.12
**XCode:** 7.3.1

**Comment by kirb** [comment]
You must run this from within a project. Of course, you also must be using a recent version of Theos – the [legacy](https://github.com/theos/theos/tree/legacy) versions (circa 2009 – 2014) did not have this feature.

Refer to [this wiki page](https://github.com/theos/theos/wiki/Upgrading-from-legacy-Theos) if you need more info on updating from legacy Theos.

**Comment by markcoker** [comment]
Yeah, I've tried both from theos git and a project git. Ill refresh my memory and take a look at the wiki page and create a new project and give that a whirl.

**Comment by kirb** [comment]
Feel free to come over to [IRC](http://iphonedevwiki.net/index.php/IRC) if you need help with your setup.
