### ISSUE TITLE
Enabling C++ 11?

### ISSUE THREAD

**Issue by Naville** [theos/theos#173]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. run make

What happens?
-------------
Build Failed

What were you expecting to happen?
----------------------------------
Build Successfully

Any logs, error output, etc?
----------------------------

> In file included from Hooks/Misc/Patch.cpp:8:
> Hooks/Misc/Patch.h:17:1: error: inline namespaces are a C++11 feature
>       [-Werror,-Wc++11-extensions]
> inline namespace liberation {
> ^
> Hooks/Misc/Patch.h:18:15: error: alias declarations are a C++11 extension
>       [-Werror,-Wc++11-extensions]
> using bytes = std::vector<uint8_t>;
>               ^
> Hooks/Misc/Patch.h:20:6: error: scoped enumerations are a C++11 extension
>       [-Werror,-Wc++11-extensions]

Any other comments?
-------------------
Makefile:
```
export CFLAGS=-Wp,"-DWTFJHTWEAKNAME=@\"F1D0ZBKKQS01655\","-DWTFJHHostName=@\"Naville-Zhang-Retina-MacBook-Pro-2\"
include $(THEOS)/makefiles/common.mk
TWEAK_NAME = F1D0ZBKKQS01655
SUBSTRATE ?= yes
F1D0ZBKKQS01655_FILES = Tweak.xm CompileDefines.xm Hooks/Misc/Patch.cpp Hooks/Misc/RemoveASLR.xm Hooks/Misc/SplitMachO.mm Hooks/Misc/WTSubstrate.mm
export ADDITIONAL_CCFLAGS  = -Qunused-arguments
export ADDITIONAL_LDFLAGS  = -Wl,-segalign,4000,-sectcreate,WTFJH,SIGDB,./SignatureDatabase.plist,-sectcreate,WTFJH,classdumpdyld,./classdumpdyld.dylib,-sectcreate,WTFJH,dumpdecrypted,./dumpdecrypted.dylib,-sectcreate,WTFJH,InspectiveC,./InspectiveC.dylib  -lz -L. -v -force_load ./ExtraFWs/libcapstone.a -force_load ./ExtraFWs/libkeystone.a -F./ExtraFWs/ -Wno-unused-function 
export ADDITIONAL_CFLAGS =  -I./Hooks/
export ADDITIONAL_CPPFLAGS +=  -std=c++11
F1D0ZBKKQS01655_LIBRARIES = sqlite3 substrate stdc++ c++ Liberation  
F1D0ZBKKQS01655_FRAMEWORKS = Foundation UIKit Security JavaScriptCore UIKit CoreGraphics CoreFoundation QuartzCore CFNetwork  
F1D0ZBKKQS01655_OBJ_FILES =./ExtraFWs/Reveal.framework/Reveal ./ExtraFWs/Cycript.framework/Cycript  
include $(THEOS_MAKE_PATH)/tweak.mk
after-install::
	install.exec "killall -9 SpringBoard"
```

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by Naville** [comment]
Also tried

>  F1D0ZBKKQS01655_CPPFLAGS +=  -std=c++11

 and 

>  F1D0ZBKKQS01655_CXXFLAGS +=  -std=c++11

still no luck

**Comment by Naville** [comment]
nvm it should be inside CCFLAGS.

Although I'm still wondering why GCC based makefile examples are using CPP/CXXFLAGS

**Comment by kirb** [comment]
Theos is modelled on GNUstep make, which [uses CCFLAGS](https://github.com/gnustep/make/blob/3a998d4d1698661c1cdfafe480be5296f22e8f7a/rules.make#L270-L272) instead of CXXFLAGS as you’d otherwise be used to.

**Comment by swigger** [comment]
Good, CCFLAGS is working!
I just know this after I have made a patch (https://github.com/swigger/theos/commit/16a3655a5188d4ed6a112c6ba5edc3f1c5392848).

**Comment by DHowett-MSFT** [comment]
Theos should possibly set a deployment-specific language standard. The first version of iOS to support C++11 should target that, 14 likewise.
