### ISSUE TITLE
Make Package Install Fails

### ISSUE THREAD

**Issue by nullr1ver** [theos/theos#174]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What happens?
---------------

When running `make package install` I get this error:

> dpkg-deb: error: control directory has bad permissions 777 (must be >=0755 and <=0775)

What were you expecting to happen?
----------------------------------

The tweak to compile (there are no errors)

Any logs, error output, etc?
----------------------------

> → make package install
> > Making all for tweak PopupOnStart…
> make[2]: Nothing to be done for `internal-library-compile'.
> > Making stage for tweak PopupOnStart…
> dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead
> dpkg-deb: error: control directory has bad permissions 777 (must be >=0755 and <=0775)
> make: *** [internal-package] Error 2

(Make troubleshoot [here](https://ghostbin.com/paste/mko7x))

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS X 10.11.3

**Toolchain Version:** N/A

**SDK Version:** Xcode 7.3.1 (latest SDK)

**Comment by kirb** [comment]
Possibly you’ve transferred this from another computer, in a way that ruined the permissions? For instance, flash drives formatted as FAT or SMB network shares. Easiest way to solve this would be to just `make clean` and try again (always try that if something seems strange). You should still take a proper look at your permissions and change them to something more appropriate (e.g. 644 for files, 755 for directories).

Sidenote™: `make do` is an alias for `make package install`.

**Comment by nullr1ver** [comment]
Thanks for the sidenote 👍 

I symlinked that directory to my HDD, so I guess that could be the issue here.
However, chmodding the directories and files didn't change it.

Will try `make clean && make do` now

**Comment by Naville** [comment]
you should be chmod control

**Comment by kirb** [comment]
Sadly external drive manufacturers love to ship their drives as FAT32. You should consider reformatting as HFS+ (aka OS X Extended, which would make it only readable on macOS) or I think exFAT should be ok as well (supported by both macOS and Windows). Alternatively you could create a DMG, formatted as HFS+.

**Comment by Naville** [comment]
tbh HFS+ is supported on Win through commercial software, not expensive though

**Comment by kirb** [comment]
Ah yes forgot about that, so if you can buy/install that driver on every machine it’ll be plugged into you’ll be fine. Partitioning is also an option.

**Comment by kirb** [comment]
Closing this as it’s not a Theos issue. You can still discuss it of course.

**Comment by Naville** [comment]
http://www.paragon-software.com/home/hfs-windows/ $20.

Please notice that I heard it will affect the system in a negative way. I personally use Partitioning

**Comment by nullr1ver** [comment]
Ahh

I know why this is!
I used exFAT so....

**Comment by nullr1ver** [comment]
@kirb So what do you think the best way of fixing this is? Just moving away from my HDD?

**Comment by kirb** [comment]
I don’t really know your setup or intentions so I can’t really tell you which solution is best. You may find partitioning more worthwhile, or you may format the entire drive as HFS+ and use a driver on Windows.

Of course also note that external hard drives tend to be slower than internal drives, especially SSDs. This will directly affect how long a build will take moreso than other factors like CPU/RAM (for most projects).

**Comment by nullr1ver** [comment]
Yeah. Just moved my theos project directory to my SSD

**Comment by Mysteryexe** [comment]
I fixed the same problem by replacing the mount options for the HDD to these below:
`nodev,permissions,windows_names,nosuid,noatime,async,big_writes,timeout=2,uid=1000,gid=1009,fmask=0002,dmask=0002`
