### ISSUE TITLE
Does/will Logos Preprocessor support dynamic values

### ISSUE THREAD

**Issue by Naville** [theos/theos#175]
(Sorry I think the issues template doesn't support my issue so I cleared them)

I'm fully aware of the fact that I can %group YOSWAG and %init(YOSWAG);

Can I %group com.apple.springboard and %init([NSBundle mainBundle].bundleIdentifier); ?

Thanks

EDIT:I'm fully aware that this would require a huge refactor.

**Comment by Naville** [comment]
I.E.:


`
%group com.apple.SpringBoard
%hook AAA
-(void)BlahBlah{
}
%end
%end


%ctor{
%init([NSBundle mainBundle].bundleIdentifier)
}


`

**Comment by MTShare** [comment]
I think that this is the best practice. 

```logos
%group SpringBoardHooks

%hook AAA
-(void)BlahBlah{
}
%end

%end

%ctor {
	@autoreleasepool {
             NSString *bundleID = [[NSBundle mainBundle] bundleIdentifier];
             if([bundleID isEqualToString:@"com.apple.SpringBoard"]){
                     %init(SpringBoardHooks);
             }
	}
}
```

**Comment by kirb** [comment]
Unfortunately, expressions are not supported as group names passed to `%init`. This would require construction of the underlying function and variable names at runtime, which includes classes cached by calls to `%c()`. To call those functions, you would need to use `dlsym()`, which is slower than jumping to it by using the address that’s already known at compile time. It could be implemented, but isn’t really worth it.

**Comment by Naville** [comment]
@MTShare I know that method.
I think that is a little bit messy so I was looking for a better solution.

Thanks for the tip anyway

**Comment by Naville** [comment]
@kirb What about dynamic classes?
i.e. 

```
static Meh=NSClassFromString(@"AAA");
%hook Meh
-(void)AAAA{
}
%end

%ctor{
if(Meh==nil){
Meh=NSClassFromString(@"BBB");

}



}



```

This should be easier to implement and worth the effort? Would be useful.

**Comment by DHowett** [comment]
This one is absolutely supported.

```logos
%group Hello
%hook Meh
- (void)test { }
%end
%end

%init(Hello, Meh=NSClassFromString(@"BBB"));
