### ISSUE TITLE
dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead

### ISSUE THREAD

**Issue by Geforceyu** [theos/theos#180]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …make package
2. …
3. …

What happens?
-------------
…dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
Unfortunately you just have to live with this warning. There’s nothing actually wrong here, just that we have to use a deprecated feature – see the explanation at bb5626b.

**Comment by Geforceyu** [comment]
thanks for your explan,so this warning is not affect for use?

**Comment by kirb** [comment]
Correct.

**Comment by liamcottle** [comment]
This appears to be an error now, rather than a warning.

```
Liams-MacBook-Pro:TweakName liamcottle$ make package
> Making all for tweak TweakName…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak TweakName…
dpkg-deb: error: obsolete compression type 'lzma'; use xz instead

Type dpkg-deb --help for help about manipulating *.deb files;
Type dpkg --help for help about installing and deinstalling packages.
make: *** [internal-package] Error 2
```

I've installed `dpkg` via `brew`, and running `brew list --versions` shows `dpkg 1.18.13`

**Comment by kirb** [comment]
Ugh.

Filed #211 to track this. A workaround is also listed there.
