### ISSUE TITLE
obj/ not correctly linked?

### ISSUE THREAD

**Issue by Naville** [theos/theos#181]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. $THEOS/bin/nic.pl
2. run make

What happens?
-------------
obj/ is empty folder

What were you expecting to happen?
----------------------------------
obj/ should be a symlink to .theos/obj/

Any logs, error output, etc?
----------------------------
NULL

Any other comments?
-------------------
Should be a general issue as I'm not the only one reporting this.
Besides, can we add theos git version to build logs?

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
That directory should actually not be made at all. Been meaning to look into it.

**Comment by Naville** [comment]
.theos/obj works for me.  Got tons of new developers asking me "WHERE IS MY DYLIB??!!" recently so I started this issue

**Comment by uroboro** [comment]
Why do you say `asking me`?

**Comment by Naville** [comment]
We have a local JB developer/RE community, mainly focused in China community.
It's at bbs.iosre.com

**Comment by yu629** [comment]
obj/ is empty folder  me to ,How to solve

**Comment by kirb** [comment]
@yu629, please read the thread. `obj` has been moved to `.theos/obj`, and the `obj` directory in the root of the project is created due to a bug.

**Comment by yu629** [comment]
where is .theos/obj? I can't find it.tell for me thank you

**Comment by yu629** [comment]
@kirb where is .theos/obj? I can't find it .thanks for you tell me.

**Comment by mstg** [comment]
@yu629 It should be in your project root.

**Comment by mstg** [comment]
If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)
