### ISSUE TITLE
How do I import custom files while packing

### ISSUE THREAD

**Issue by Naville** [theos/theos#182]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. run make
2. put required files under .theos/_/
3. make package

What happens?
-------------
all files I've added got wiped

What were you expecting to happen?
----------------------------------
Those files were kept on the disk and also packed in to the package

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
I read through the wiki and didn't find any related info.

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by Naville** [comment]
So basically I created a few preferencesloader files and need theos pack them with the dylib everytime

**Comment by DHowett** [comment]
Use the internal-XXX-stage and internal-stage rules to copy things into
$(THEOS_STAGING_DIR).

-- Dustin L. Howett

**Comment by Naville** [comment]
Thanks. Googled around and found a much simpler method inherited from the original theos:

Create layout/ 

Should be in official wiki though
