### ISSUE TITLE
Can I package my dylib file into a .app?

### ISSUE THREAD

**Issue by Geforceyu** [theos/theos#183]
Now,Can I put my tweak project's dylib file into .app.I try put this dylib file into .app,then package into .ipa to install,but when this app is operation,my dylib not react. If install this app,then install my deb in cycdia,it's usefull

**Comment by uroboro** [comment]
Tweaks' dylibs do not get automatically injected into binaries just by existing. See the [documentation](http://www.cydiasubstrate.com/inject/darwin/) about it.

**Comment by Geforceyu** [comment]
But I saw a developer reverse pokemon go,then i install her ipa,there is a moving direction button in game without install deb form cydia.That i open this ipa.app bundle ,there has a dylib file form her.How dose her realize

**Comment by kirb** [comment]
You are probably looking for [theos-jailed](https://github.com/BishopFox/theos-jailed), a fork of Theos for this purpose. Note that we can’t really help you with it; if you need help then contact them, or ask [#theos](http://iphonedevwiki.net/index.php/IRC) or [/r/jailbreakdevelopers](https://www.reddit.com/r/jailbreakdevelopers).

**Comment by Geforceyu** [comment]
YES So cool ,great thanks!

**Comment by Naville** [comment]
You english is really poor thus I'm having trouble understand you.

Seems like you are looking for a side-load solution. This can be achieved by using instance_USE_SUBSTRATE and https://github.com/iMokhles/TweakApp

The first one is for compiling and the second one is for side loading

**Comment by Geforceyu** [comment]
yea,,my english is so poor, because i‘m not in a english country,but,i'm very thank you for your answer,Now,i'm usering codesign+yololib+xcrun package+resigh ,haha,this TweakApp tool is more quaickly .Thank you!
