### ISSUE TITLE
can't make packages

### ISSUE THREAD

**Issue by Tentacless** [theos/theos#184]
What are the steps to reproduce this issue?
-------------------------------------------
1. … Typing "make package" in console.

What happens?
-------------
… Makefile:19: /bundle.mk: No such file or directory
make: *** No rule to make target '/bundle.mk'.  Stop.

What were you expecting to happen?
----------------------------------
… Compile the example tweak

Any logs, error output, etc?
----------------------------
Makefile:19: /bundle.mk: No such file or directory
make: *** No rule to make target '/bundle.mk'.  Stop.

Any other comments?
-------------------
… I've tried "export THEOS=/opt/theos" and most of what I gathered from googling but haven't been able to figure it out. I'm just trying to get the environment set up first so I don't come across issues when actually building my own tweak. Also, I'm trying to compile the BlurryBadges example

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 7

**Toolchain Version:** … Not sure, although it supports 9.3 from the readme file.

**SDK Version:** … 9.3

**Comment by uroboro** [comment]
See the [Installation](https://github.com/theos/theos/wiki/Installation#installation) wiki. It does look like the environment variable isn't set when you use make.

**Comment by Tentacless** [comment]
I'm guessing I'm not doing the export command correctly. I've tried the 3 different possibilities but the same error comes up. export THEOS=/var/theos should be the one I need.

**Comment by uroboro** [comment]
Try using `export THEOS=/home/user/theos`.

**Comment by Tentacless** [comment]
That worked! Thank you very much.
