### ISSUE TITLE
I am unable to login or make an new account. 

### ISSUE THREAD

**Issue by Xibster** [theos/theos#185]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What happens?
-------------
… Try to login and the login box just goes gray. Refreshing the page just resets it the box as blank.
Waiting 6 seconds will have a message pop up saying I was "successfully logged out". Making a new account and logging in via Email is futile. 
https://i.imgur.com/BY68bdk.jpg

**Comment by kirb** [comment]
Theos is not Ghostbin. https://github.com/DHowett/ghostbin

**Comment by DHowett** [comment]
Why on earth would you report this to the theos repository?
