### ISSUE TITLE
in cygwin ，when make some error

### ISSUE THREAD

**Issue by buzai** [theos/theos#187]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …create a demo
2. …make package
3. …

What happens?
-------------
…$ make package
Makefile:6: /Tweak.mk: No such file or directory
make: *** 没有规则可制作目标“/Tweak.mk”。 停止

What were you expecting to happen?
----------------------------------
…create a deb

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
$ make package
Makefile:6: /Tweak.mk: No such file or directory
make: *** 没有规则可制作目标“/Tweak.mk”。 停止

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …
win7 64
**Toolchain Version:** …
latest
**SDK Version:** …
iPhoneOS8.1.sdk

**Comment by buzai** [comment]
i add theos path ,
now it is :
/home/chenhao/theos/makefiles/common.mk:153: *** The "iphone" target is not supp
orted on the "windows" platform。 停止。

**Comment by Naville** [comment]
需要导出theos路径到bash环境变量

**Comment by uroboro** [comment]
Can you share your `Makefile`, and if you use it, the `~/.theosrc` file?

**Comment by buzai** [comment]
OK，now i chang to mac, i install it ok, i think the problem is THEOS path is not right . but in my life i dont want to use win, it has so many problems. your theos is so great , i am very very like it , but why use perl , i dont known perl.
