### ISSUE TITLE
Dependency installer script

### ISSUE THREAD

**Issue by uroboro** [theos/theos#189]
We could provide a shell script that would install the required tools to use Theos. Something like [Torch](http://torch.ch) has with its [install-deps](https://github.com/torch/distro/blob/master/install-deps).

**Comment by supermamon** [comment]
https://github.com/supermamon/install-theos/blob/master/install-deps
Very crude? Too fancy? Forgive my bash skills. Also, I don't have a mac to test it on mac.

**Comment by kirb** [comment]
Done by #657 :tada:
