### ISSUE TITLE
Compile C++11 projects

### ISSUE THREAD

**Issue by parsifall** [theos/theos#191]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. cd c11proj
2. make

What happens?
-------------
Compiling stops and an error says 'random' file not found.

What were you expecting to happen?
----------------------------------
To compile normally.

Any other comments?
-------------------
If I use a C++11 feature, variadic templates, an error says I'm using a C++11 feature and it stops compiling. A part of that, it seems that C++11 is not supported since I get errors even if trying to include its libraries, like 'array', 'random', and so on. I already tried setting CFLAGS, CCFLAGS or CXXFLAGS to -std=c++11 -stdlib=libc++ but still nothing.

What versions of software are you using?
----------------------------------------
iOS 7.1, Cygwin on Win8.
Latest version of Toolchain from CoolStar's github (for Cygwin).
iOS 9.3 SDK but tried 8.1 too.

**Comment by rpetrich** [comment]
`MyTarget_CCFLAGS = -std=c++11` works for me (where `MyTarget` is the name of the target)

**Comment by parsifall** [comment]
Not for me :/ I noticed that if I use for example CFLAGS or CCFLAGS instead of CXXFLAGS it gives me more errors about not found headers such as cstring and so on. Really weird. Also, I noticed that under iPhoneOS9.3.sdk/usr/include/c++/4.2.1 there are almost all headers like cstrinf, iostream, map, etc except random :/

**Comment by rpetrich** [comment]
Are you using `CCFLAGS = ...` or `MyTarget_CCFLAGS = ...`?

**Comment by parsifall** [comment]
Also, constexpr isn't recognized :(

**Comment by DHowett** [comment]
CoolStar's toolchain may simply not support C++11; this configuration works properly using the Xcode-provided toolchain on OS X.

**Comment by parsifall** [comment]
So far I've solved including the old experimental header placed at 'tr1/random' and setting the CCFLAGS. Those headers are really old, I must find a way to update them
