### ISSUE TITLE
[NIC]PreferencesBundle broken?

### ISSUE THREAD

**Issue by Naville** [theos/theos#193]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. $THEOS/bin/nic.pl
2. select [9.] iphone/preference_bundle_modern
3. make
4. make package

What happens?
-------------
compiles, can't pack due to lacking *control*
The bundle is not loaded after I manually copy the bundle to device at /Library/PreferenceBundles

What were you expecting to happen?
----------------------------------
A new entry appears in Preferences.app

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 9.3.3

**Toolchain Version:** NO IDEA

**SDK Version:** Xcode 7.3.3

**Comment by mstg** [comment]
Temporarily you can do `mkdir layout` in the project root to ignore that error.

**Comment by kirb** [comment]
That’s to be expected. The preference bundle template is intended to be a *subproject* of your main project. Otherwise, you’d need to have a completely separate package for your tweak and its settings.

Run NIC within your main project directory and it will configure it as a submodule for you.

If you do indeed want to have a package that only contains a preference bundle, you need to provide your own `control` file.

**Comment by Naville** [comment]
what about 

"The bundle is not loaded after I manually copy the bundle to device at /Library/PreferenceBundles"

**Comment by mstg** [comment]
@Naville You have to copy the entry.plist to /Library/PreferenceLoader/Preferences/TweakName.plist

**Comment by DHowett** [comment]
@mstg The template should be doing that.

**Comment by mstg** [comment]
@DHowett Yes, I know. He has hinting towards the part where he manually copied the bundle but it still would not work.

>The bundle is not loaded after I manually copy the bundle to device at /Library/PreferenceBundles

Also referenced here: https://github.com/theos/theos/issues/193#issuecomment-240144053

**Comment by DHowett** [comment]
@mstg Oops, good eye. I suppose it pays to read the issue :+1:

**Comment by mstg** [comment]
I believe there is nothing more to discuss. Closing.
