### ISSUE TITLE
Change %property scope to work with 

### ISSUE THREAD

**Issue by caughtinflux** [theos/theos#194]
Currently, %property only works inside %subclass, which is cool in itself. However, since it is using associated objects for the property storage, the same method could be extended to hooks on arbitrary classes.
Adding properties to regular classes by defining setters/getters manually (and using associated objects for storage) is a very common use case, and having %property sugar would eliminate a lot of boilerplate.

**Comment by kirb** [comment]
%property works on %hook. [Example](https://github.com/hbang/FlagPaint-2/blob/ad8a6d37dbedfc006bfe3892d8944947a116b3e8/Banner.xm#L27-L29)

If it’s not working for you, please provide a test case.

**Comment by caughtinflux** [comment]
Oh my goodness. This was just based on a discussion in IRC with uroboro. If
it works with %hook, this can definitely be closed.

On 17-Aug-2016, at 6:05 PM, Adam Demasi <notifications@github.com> wrote:

%property works on %hook. Example
<https://github.com/hbang/FlagPaint-2/blob/ad8a6d37dbedfc006bfe3892d8944947a116b3e8/Banner.xm#L27-L29>

If it’s not working for you, please provide a test case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/theos/theos/issues/194#issuecomment-240397585>, or mute
the thread

**Comment by caughtinflux** [comment]
(The wiki does need updating, though)
