### ISSUE TITLE
How change the owner of daemond?

### ISSUE THREAD

**Issue by onerain88** [theos/theos#195]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
I wanna to make a root daemond with theos, the owner of daemond should be "root:wheel".
In [this blog](http://iosre.com/t/run-a-daemon-as-root-on-ios/212), it recommands the [fauxsu](https://github.com/DHowett/fauxsu).But when I use it on my computer(Mac os 10.11.5), it's unusable.
How can I do it?

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …
Mac OS 10.11.5 
iOS 8.3

**Toolchain Version:** …

**SDK Version:** …

**Comment by mstg** [comment]
Use the xpc-service template as a boilerplate for daemons. Take a look at its Makefile and you will see that it chowns the plist thats placed in `/Library/LaunchDaemons` to `root:wheel` while staging. Be sure that you have fakeroot installed for the process to work.

**Comment by onerain88** [comment]
Thank you for your reply!
I will have a try!
