### ISSUE TITLE
Deb files are too big

### ISSUE THREAD

**Issue by douglas-srs** [theos/theos#197]
Before I updated my theos local repo my tweak files (deb) generated from "make package" were a lot smaller, one of my tweak was 1,84MB and now it's 5,5MB, I dug into it and found out it's not compressing the data archive with gzip anymore.

I believe the issue on this line https://github.com/theos/theos/blob/e2cb518bba9a807b4a2dcaa7ae0e52ac44246a8d/bin/dm.pl#L99

Here is a print of two extracted deb files, left side is from before I updated theos and right is after that.

![difference](https://cloud.githubusercontent.com/assets/1311994/17902855/658524d8-693f-11e6-93ad-99e9c6f039a5.png)
## What are the steps to reproduce this issue?
1. Create a new tweak using the default template
2. Run "make package"
3. Extract the deb file with some extraction tool
4. Check the extracted files.
## What happens?

The data file is not "gzipped" like the control file, making the deb file huger than it needs to be.
## What were you expecting to happen?

I expected it to be gzipped just like the control file in order to my deb file be smaller.
## Any logs, error output, etc?

No.
## Any other comments?

…
## What versions of software are you using?

**Operating System:** Windows 10 x64

**Toolchain Version:** coolstar/iOSToolchain4Win

**SDK Version:** 8.1

**Comment by DHowett** [comment]
dm.pl hasn't changed in ages; are you sure you're using it? it still
defaults to gzip.

**Comment by douglas-srs** [comment]
To be honest, the theos I had was from more than 2 years ago, maybe it wasn't from the official repository and that was why it was using gzip on the data archive. Anyway, I'm sure I'm using it now, to verify I edited line 99 and 102 of dm.pl file:

`my $zFd = IO::Compress::Gzip->new(\$comp, -Level => 9);`

`print_ar_record($ar, $DATAARCHIVENAME, time, 0, 0, 0100644, length($comp));`

After a new "make package", my deb file has the data archive "gziped" and is a lot smaller!

**Comment by mstg** [comment]
If I am not mistaken, theos uses lzma compression (which I don't think is available with cygwin / not implemented in the perl reimplementation of dpkg-deb) and this may have caused your tars to not be compressed at all.

**Comment by DHowett** [comment]
Ah, right. This would be the reason I forgot as to why we should not set a
default that every dpkg-deb implementation does not support.

**Comment by kirb** [comment]
In fact we have `$(_THEOS_PLATFORM_DPKG_DEB_COMPRESSION)`, but windows.mk wasn’t changing it to gzip. Fixed in 345360b.

**Comment by douglas-srs** [comment]
After applying this patch, the deb file has the size I was expecting, the problem now is that it doesn't install on phone, here is the error:

![log](https://cloud.githubusercontent.com/assets/1311994/17930748/27198622-69de-11e6-8294-65397f0a00c6.jpg)

I dug into it again and extracted the deb with "ar -x file.deb" and found out the data archive does not have the correct extension, instead of "data.tar.gz" it's just "data.tar", to workaround this I had to change dm.pl line 36, https://github.com/theos/theos/blob/master/bin/dm.pl#L36, after changing it to "data.tar.gz" and re-running "make package", my deb installed successfully, not sure if that's the right fix but it seems to work.

**Comment by kirb** [comment]
Closing in favor of #211.
