### ISSUE TITLE
can excute make command(not compilin)

### ISSUE THREAD

**Issue by Rafielreca** [theos/theos#199]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
excute  make
what happens?
Makefile:8: theos-jailed/makefiles/tweak.mk: No such file or directory
make: *** No rule to make target 'theos-jailed/makefiles/tweak.mk'.  Stop.

Any logs, error output, etc?
----------------------------
Makefile:8: theos-jailed/makefiles/tweak.mk: No such file or directory
make: *** No rule to make target 'theos-jailed/makefiles/tweak.mk'.  Stop.

What versions of software are you using?
----------------------------------------
**Operating System:** windows 10

**Toolchain Version:** latest

**SDK Version:** 9.3

**Comment by kirb** [comment]
You need to create a `theos-jailed` symlink, pointing to where Theos is located.

**Comment by mstg** [comment]
I think this is posted in the wrong repository. This repo is not for "theos-jailed".
Please go to [BishopFox/theos-jailed](https://github.com/BishopFox/theos-jailed)

But as @kirb noted, you can create a symlink called `theos-jailed` pointing to your theos-jailed installation

---

Feel free to reopen this issue if you believe this is a mistake
