### ISSUE TITLE
Require fakeroot when making package

### ISSUE THREAD

**Issue by kirb** [theos/theos#202]
People are hitting issues related to permissions when they don’t have fakeroot installed. Fakeroot has always been optional, but Optimo is now asking developers to install fakeroot and rebuild the package. Previously he was manually modifying data.tar to change every file’s owner/group to root:wheel.

We might as well just require fakeroot to solve this for everyone. `fakeroot(1)` itself even says:

> fakeroot was specifically written to enable users to create Debian GNU/Linux packages (in the deb(5) format) without giving them root privileges.

We already call fakeroot at the right times; we just need to throw an error in `internal-package-check` if no fakeroot utility exists. As far as I’m aware fakeroot is also available on all platforms we support.

**Comment by kirb** [comment]
I could swear there was fakeroot in Telesphoreo but I can’t find it even with plenty of other developer repos installed. Maybe I’ll have to build and release my own fakeroot package.

**Comment by kirb** [comment]
dm.pl can fix this by specifically setting uid/gid of each file to 0:0. Not using it on iOS yet though, and we also still don’t have fakeroot there. Maybe can use [fauxsu](https://github.com/DHowett/fauxsu)? Support is already built into Theos.

**Comment by uroboro** [comment]
Or do some [nasty root-level work](https://gist.github.com/uroboro/f3c50a25be5c99833dd811a0e2d34cb1) and install the lzma module anyway.

**Comment by kirb** [comment]
(Actually, still not fixed because of iOS, but we’ll switch to using dm.pl across the board as soon as @uroboro’s change to using `/usr/bin/lzma` etc is pushed.)
