### ISSUE TITLE
Where to find SDK and Headers

### ISSUE THREAD

**Issue by nerdtron123** [theos/theos#206]
Where can I find iOS 9.3.3 SDK and Headers so I can I build my PreferenceBundle

**Comment by Packetfahrer** [comment]
http://lmgtfy.com/?q=iOS+10+runtime+header+GitHub

**Comment by xTheMaster3x** [comment]
http://github.com/theos/sdks will have the 9.3 sdk with all of the private frameworks and https://github.com/theos/headers will have all of the headers you will need If you need more, check http://developer.limneos.net/

**Comment by kirb** [comment]
Closing this as it is not a Theos issue. For questions, [please use IRC](http://iphonedevwiki.net/index.php/IRC).
