### ISSUE TITLE
"latest" isn't a supported version number on the macosx platform.

### ISSUE THREAD

**Issue by uroboro** [theos/theos#209]
## What are the steps to reproduce this issue?
1. Make tool project.
2. Set `TARGET` as `native:clang:latest`.
3. Run `make`.
## What happens?

Compilation fails with invalid arguments.
## What were you expecting to happen?

Theos to build with the latest available SDK.
## Any logs, error output, etc?

> clang: error: invalid version number in '-mmacosx-version-min=latest'
## Any other comments?

The iPhone target supports this keyword. Bring that logic to the macosx target.
## What versions of software are you using?

**Operating System:** Travis-CI's Mac OSX

**Toolchain Version:** 7.2

**SDK Version:** Undefined

**Comment by kirb** [comment]
Closing in favor of #242.
