### ISSUE TITLE
ld: framework not found CydiaSubstrate

### ISSUE THREAD

**Issue by Mokled** [theos/theos#210]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?

> Making all for tweak mokle005…
> ==> Preprocessing Tweak.xm…
> ==> Compiling Tweak.xm (armv7)…
> ==> Linking tweak mokle005 (armv7)…
> ld: framework not found CydiaSubstrate
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: **\* [/Volumes/Mokle/mokle005/.theos/obj/debug/armv7/mokle005.dylib] Error 1
> make[2]: **\* [/Volumes/Mokle/mokle005/.theos/obj/debug/armv7/mokle005.dylib] Error 2
> make[1]: **\* [internal-library-all_] Error 2
> make: **\* [mokle005.all.tweak.variables] Error 2
## What happens?

ld: framework not found CydiaSubstrate
## What were you expecting to happen?

Since i install theos , write or non-write . happened this when Compile...
## What versions of software are you using?

**Operating System: OSX 10.10   XCODE6.4

**Toolchain Version:Theos lasted

**SDK Version:iPhoneOS8.4

**Comment by alucard0134** [comment]
i believe #167 is related to this

**Comment by kirb** [comment]
Yes, this is the same issue. Did the workaround listed there solve the problem?

**Comment by Mokled** [comment]
Thank U

Sweet heart!
