### ISSUE TITLE
Add lzma support to dm.pl and use it on macOS/Linux

### ISSUE THREAD

**Issue by kirb** [theos/theos#211]
dpkg 1.18.11 finally [pulled the plug](https://github.com/guillemj/dpkg/commit/ef6187ded62bb3973e4e57779edc87c3e2904af5) on our saving grace; using `-Zbzip2` or `-Zlzma` is now an error.

The most straightforward way to “fix” this would be to just replace it with [dm.pl](https://github.com/theos/theos/blob/master/bin/dm.pl) and add lzma support to it.

(Telesphoreo’s dpkg intentionally does not support xz due to [various flaws](http://www.nongnu.org/lzip/xz_inadequate.html) with xz and LZMA2.)

## Error output
```
dpkg-deb: error: obsolete compression type 'lzma'; use xz instead

Type dpkg-deb --help for help about manipulating *.deb files;
Type dpkg --help for help about installing and deinstalling packages.
make: *** [internal-package] Error 2
```

## Workaround
For the moment, you’ll need to just use 1.18.10.

For Homebrew, you can downgrade like so:

```shellsession
$ brew remove dpkg  # remove latest dpkg
$ brew install --force-bottle https://raw.githubusercontent.com/Homebrew/homebrew-core/7a4dabfc1a2acd9f01a1670fde4f0094c4fb6ffa/Formula/dpkg.rb  # install dpkg as a bottle from the old commit
$ brew pin dpkg  # block homebrew from updating dpkg till you `brew unpin dpkg`
```

(Updated 01/03/17 using @Fr0stDev’s workaround because Debian delete old source releases. 1.18.10 is from July 2016.)

Fortunately, seems Debian/Ubuntu are safe for the moment: https://launchpad.net/dpkg/+packages. But I would expect them to be updating sometime soon.

----

Partly dupes #197.

**Comment by DHowett** [comment]
To facilitate this, I've transferred **DHowett/dm.pl** to **theos/dm.pl**.

**Comment by kirb** [comment]
Cheers :+1:

**Comment by Hax0rDoge** [comment]
Following these instructions let me to an poor where there was an undefined variable "@@HOMEBREW_CELLAR@@". [Here](https://stackoverflow.com/questions/7907055/bash-usr-local-bin-heroku-usr-local-bin-ruby-bad-interpreter-no-such-file) is a solution and it worked for me. Just leaving this here in case anyone else also gets this error.

**Comment by kirb** [comment]
Whoops. Updated to include a sed step.

**Comment by Hax0rDoge** [comment]
Just thought this would also be necessary in the process. To stop home-brew from updating dpkg just run:

```
brew pin dpkg
```

**Comment by kirb** [comment]
Good call, added that too.

**Comment by benjibobs** [comment]
The command `for i in $(brew --cellar)/dpkg/1.18.10/bin/*; do sed -i s/'@@HOMEBREW_CELLAR@@'/$(brew --cellar)/g "$i"; done` gives the following error:
`sed: 1: "/usr/local/Cellar/dpkg/ ...": extra characters at the end of l command`

**Comment by uroboro** [comment]
Install sed from homebrew, Apple's Developer Tools package contains really old versions of such tools.

**Comment by benjibobs** [comment]
Thank you 👍 

If it matters, I got it working with this command using the stock sed:
`for i in $(brew --cellar)/dpkg/1.18.10/bin/*; do sed -i '' s~'@@HOMEBREW_CELLAR@@'~$(brew --cellar)~g "$i"; done`

**Comment by infuse-location** [comment]
Hi kirb,

Thank you very much helping with this issue - I've followed the steps mentioned in **Workaround** and encountered the following error:
```
homebrew-core op$ git checkout 7a4dabf
error: pathspec '7a4dabf' did not match any file(s) known to git.
```

I also tried replacing ```dm.pl``` from the link and adding lzma support - but still get the "use xz instead" error:
```sub compressed_fd {
	my $sref = shift;
	return IO::Compress::Gzip->new($sref, -Level => 9) if $::compression eq "gzip";
	return IO::Compress::Bzip2->new($sref) if $::compression eq "bzip2";
	**return "|lzma -9c" if $::compression eq "lzma";**
	open my $fh, ">", $sref;
	return $fh;
}

sub compressed_filename {
	my $fn = shift;
	my $suffix = "";
	$suffix = ".gz" if $::compression eq "gzip";
	$suffix = ".bz2" if $::compression eq "bzip2";
	**$suffix = ".lzma" if $::compression eq "lzma";**
	return $fn.$suffix;
}```

**Comment by PeterPan507** [comment]
When I checkout old commit and begin install. 
Homebrew will execute 'Updating Homebrew...'
So I always install the newest version.

brew info:
```
Homebrew 1.1.2
Homebrew/homebrew-core (git revision e34b; last commit 2016-12-07)
```

**Comment by kirb** [comment]
Aah I missed the disable updates var. Fixed now. Seems like something Homebrew should detect though (that you manually checked out a commit).

**Comment by andrewwiik** [comment]
also might wanna add "git fetch --unshallow" as some people may not have the dpkg commit referenced

**Comment by Fr0stDev** [comment]
The following works as well, in case you're unable to reference an older commit:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9e6d049c0d22824a4eedddf6f9d471b5ca2c5283/Formula/dpkg.rb

brew pin dpkg
```

This will install dpkg 1.18.9. It seems the formula for 1.18.10 no longer works.

**Comment by andrewwiik** [comment]
good to know

**Comment by abasefive** [comment]
@Fr0stDev thank you,but there is warning:
**```
dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead
dpkg-deb: warning: ignoring 1 warning about the control file(s)
```**
it doesn't matter?

**Comment by mstg** [comment]
@abasefive Yes that is fine.

**Comment by supermamon** [comment]
This allowed me to pull v1.18.10 from the 7a4dabf commit.

```
$ brew remove dpkg  
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7a4dabfc1a2acd9f01a1670fde4f0094c4fb6ffa/Formula/dpkg.rb
$ brew pin dpkg  
```

**Comment by zhahao** [comment]
An error occurred,
```
$ git checkout 7a4dabf
error: pathspec '7a4dabf' did not match any file(s) known to git.
```

**Comment by KTSByJack** [comment]
I already downgrade dpkg，but I still can not make install success, do you guys have  trouble about this

**Comment by uroboro** [comment]
Rather than making a new subprocess in https://github.com/theos/theos/issues/211#issuecomment-264588606 we can add proper support with [Lzma.pm](http://search.cpan.org/~pmqs/IO-Compress-Lzma-2.074/lib/IO/Compress/Lzma.pm).

**Comment by kirb** [comment]
@uroboro, agreed, though a little tricky because macOS doesn't include IO::Compress::Lzma (but does have most other modules of IO::Compress). IO::Compress also seems to be particular about the versions of each script being the same, which might force us to ship the entire module rather than just Lzma or the parts we use, because perl might import older or newer versions if they already exist on the machine. I'd be willing to accept piping to `lzma` for the moment just to get a workable solution out, though.

**Comment by DuIslingr** [comment]
Why not just use gzip?

**Comment by sterling0x1** [comment]
Just install older dpkg and live with the warning. Does the job just fine.

**Comment by kirb** [comment]
@DuIslingr, that's short sighted. If all compression formats except the oldest (gzip) and newest (xz) have been removed, them there's obviously a specific reason gzip is hanging around, and it might not be forever. As far as I'm aware, it's only still available because for some reason dpkg itself is packaged with gzip. Seems strange if its dependencies are using xz, but maybe there's some compatibility detail I don't know. If Debian realises there's no need to do this any more, gzip will be gone, and we loop back to this same situation. 

Also, lzma provides much better compression ratios than gzip/bzip2. You should be conscious of how much data you're asking your users to download. I know we're not packaging 250 MB Facebook here, but you have a duty for your users to save them some download usage by just having your tools set up correctly.

**Comment by michyprima** [comment]
If anyone needs a working link to dpkg 1.18.10 replace url with this [this](https://launchpad.net/debian/+archive/primary/+files/dpkg_1.18.10.tar.xz) in dpkg.rb

**Comment by kirb** [comment]
As of bad135c (release 2.1.0), the deb builder has changed from dpkg-deb to our built-in dm.pl. It has flags compatible with dpkg-deb, so you can also use it directly if needed. Worth noting its default compression format is `gzip` (dpkg-deb’s has been `xz` for a long time; previously was `gzip`). Theos will still manually specify `-Zlzma`, so packages built via Theos will compress with lzma.

There is (unfortunately) a binary dependency which provides bindings for liblzma to Perl. If that’s gibberish to you, don’t worry, it’ll be installed when you run `make update-theos`. The instructions to install it manually while installing Theos from scratch has been [added to the Install page](https://git.io/theosinstall). It’s the best compromise I could come up with and I don’t want any pre-built binaries in Theos. If someone has a smarter solution than mine I’d love to discuss it.

**Comment by rweichler** [comment]
@kirb I feel like it would be easier to just use `-Zgzip`. The only downside is a bigger binary size. And Optimo recompresses everything to LZMA when you submit to BigBoss anyway.
