### ISSUE TITLE
No rule to make target `update-theos'.

### ISSUE THREAD

**Issue by mythkiven** [theos/theos#212]
$  make update-theos
print:No rule to make target `update-theos'.
so,What should I do..

**Comment by mythkiven** [comment]
I know not currently in a project directory，but when  in a project directory:
$  make update-theos
> Updating Theos…
error: cannot open .git/FETCH_HEAD: Permission denied
。。。
How to solve，

**Comment by uroboro** [comment]
Theos isn't yet as magical as to support being used outside of directories with makefiles for it.

Please make sure you followed the [Installation instructions](https://github.com/theos/theos/wiki/Installation#installation), paying close attention to where you can install it and with which permissions. Try applying the `chown` command; if it doesn't work, start over but from the `~` directory so it is installed to `~/theos`.

**Comment by Hax0rDoge** [comment]
There is another way to update theos. It should completely clean any locally committed changes and then download the latest changes from the official repo. You need to use `sudo` as most installations of theos are in root directories.

```
$ cd $THEOS
$ sudo git reset --hard
$ sudo git pull
```

**Comment by kirb** [comment]
Please don’t use sudo. Chown it so it’s owned by you, not root. As @uroboro mentioned please refer to the installation instructions.

Closing as this is not a Theos bug.
