### ISSUE TITLE
fatal error: 'Preferences/Preferences.h' file not found

### ISSUE THREAD

**Issue by zhouhesheng** [theos/theos#213]
What happens?
clone https://github.com/LkeMitchll/StatusTimePlus.git and run make, and it reports:
fatal error: 'Preferences/Preferences.h' file not found
 Prefs/statustimeprefs.mm first line is:
#import <Preferences/Preferences.h>

What were you expecting to happen?
Preferences.h is located in $THEOS/vendor/include, and it should be automatically found.

Any logs, error output, etc?
https://ghostbin.com/paste/c94kg

What versions of software are you using?
----------------------------------------
**Operating System:** … OSX 10.12

**Toolchain Version:** … XCODE 8.1

**SDK Version:** … IOS SDK 10.1

**Comment by supermamon** [comment]
You can either (1) import only the classes you actually need from $THEOS/vendor/include/Preferences or (2) Create Preferences.h which is actually just a bunch of imports of the classes under the same folder.

**Comment by kirb** [comment]
Closing as this is not a Theos issue. If you need further assistance, please try [IRC](http://iphonedevwiki.net/index.php/IRC).
