### ISSUE TITLE
update-theos error 

### ISSUE THREAD

**Issue by thebeastgamer25** [theos/theos#216]
Error 127..
Running as root

**Comment by uroboro** [comment]
This is neither useful nor correct. Never use the root user and follow the given template.

**Comment by mstg** [comment]
Not a theos issue

---

If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)
