### ISSUE TITLE
Keep getting error with Theos compiling on Windows

### ISSUE THREAD

**Issue by JMccormick264** [theos/theos#220]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What happens?
-------------
I get this error  in Cygwin(shown in ghostbin post)

What were you expecting to happen?
----------------------------------
It to compile like it does on my Mac Virtual Machine

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/ozgo5

Any other comments?
-------------------
… None

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10

**Toolchain Version:** Not sure, I am using this one for Windows 
 - https://www.github.com/coolstar/iOSToolchain4Win.git

**SDK Version:** 10.1.1

**Comment by kirb** [comment]
Please run `make troubleshoot` and paste the link here.

**Comment by Legitgamer264** [comment]
@kirb https://ghostbin.com/paste/8j8ux

**Comment by Legitgamer264** [comment]
could it be because I don't have the right tool/add on to compile in armv7? On my Mac VM it compiles and installs fine. its just on windows that it doesn't work

**Comment by kirb** [comment]
127 usually means command not found. Still not printing any error output from bash in that message which is odd. 

How did you set up the toolchain? Any site in particular that you followed? It definitely should work; armv7, armv7s, and arm64 are supported.

**Comment by kirb** [comment]
Closing as it’s been a while without a response, and we haven’t seen this issue occur with anyone else. If you need further assistance, try [asking on IRC](http://iphonedevwiki.net/index.php/How_to_use_IRC).
