### ISSUE TITLE
Unknown option "-Z" while making package

### ISSUE THREAD

**Issue by Teuns** [theos/theos#224]
Hello,

I am trying to build my iOS tweak project as a DEB, but somehow I am getting the following error:
/sw/bin/dpkg-deb: unknown option -Z

**Comment by kirb** [comment]
You have Fink installed, which uses extremely old versions of dpkg and apt. You need to either remove Fink completely and use [Homebrew](http://brew.sh/); or install just dpkg from Homebrew and adjust your `$PATH` so `/usr/local/bin` appears before `/sw/bin`. Use [these directions](https://github.com/theos/theos/issues/211) to install dpkg from Homebrew.

**Comment by Teuns** [comment]
Not working.

**Comment by Teuns** [comment]
Worked. Thanks!
