### ISSUE TITLE
Theos does not work on iOS 10

### ISSUE THREAD

**Issue by thebeastgamer25** [theos/theos#227]
I keep getting "No rules to build /application.mk"

**Comment by uroboro** [comment]
Can you post the contents of your makefile and the value of the environment variable `$THEOS` (and other related Theos env vars)?

**Comment by kirb** [comment]
Closing as there was no response and this seems to most likely just be a makefile typo. If you need further assistance, try [asking on IRC](http://iphonedevwiki.net/index.php/How_to_use_IRC).
