### ISSUE TITLE
Error when trying to Compile tweak in MTerminal using Theos

### ISSUE THREAD

**Issue by Dubstepwolf123** [theos/theos#232]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. su
2. (password)
3. cd /var/mobile/test
4. make package

What happens?
-------------
It says "theos/makefiles/common.mk:153: *** The "iphone" target is not supported on the "macosx" platform.  Stop" 

What were you expecting to happen?
----------------------------------
It should build the tweak.

Any logs, error output, etc?
----------------------------
theos/makefiles/common.mk:153: *** The iphone" target is not supported on the "macosx" platform.  Stop.

Any other comments?
-------------------
Nope

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 10.2

**Toolchain Version:** 6.1-1

**SDK Version:** iPhoneOS9.3

**Comment by kirb** [comment]
You *might* be on an old version of Theos – this issue did exist a few years ago and was fixed. Can you confirm you installed it using the directions at https://git.io/theosinstall?

**Comment by Dubstepwolf123** [comment]
I am using the most updated version of Theos from the http://nix.howett.net/theos/ 
source. It is also installed correctly.

I am using an iPad Air 2 using MTerminal on iOS 10.2 running the Yalu102  Beta 7 jailbreak.

**Comment by Dubstepwolf123** [comment]
I just ran it again and this time the error message was.
theos/make files/common.mk:116: *** The "iphone" target is not supported on the "" platform. Stop.

**Comment by supermamon** [comment]
That latest version is 3 years old. See the [installation](https://github.com/theos/theos/wiki/Installation) wiki to get the latest version.

**Comment by kirb** [comment]
Closing as this is not a Theos issue and a solution was provided. If you need further assistance, try [asking on IRC](http://iphonedevwiki.net/index.php/How_to_use_IRC).
