### ISSUE TITLE
Error when compile in Cygwin64 - window 10

### ISSUE THREAD

**Issue by valuevn** [theos/theos#236]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. make package

What happens?
-------------
$ make package
> Making all for tweak test…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7s)…
==> Linking tweak test (armv7s)…
ld: unexpected token: !tapi-tbd-v2 file '/opt/theos/sdks/iPhoneOS10.1.sdk/usr/lib/libobjc.tbd' for architecture armv7s
arm64-apple-darwin14-clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/theos/makefiles/instance/library.mk:33: /home/ValueVN/project/test/.theos/obj/debug/armv7s/test.dylib] Error 1
make[2]: *** [/opt/theos/makefiles/instance/library.mk:32: /home/ValueVN/project/test/.theos/obj/debug/armv7s/test.dylib] Error 2
make[1]: *** [/opt/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2
make: *** [/opt/theos/makefiles/master/rules.mk:90: test.all.tweak.variables] Error 2

What were you expecting to happen?
----------------------------------

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
https://ghostbin.com/paste/p5823

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System: Window 10

**Toolchain Version: 
1. LLVM + Clang 3.9.1
2. LD64 264.3.102
3. CCTools 877.5

**SDK Version:10.1

**Comment by uroboro** [comment]
Where did you get the iPhoneOS10.1 sdk from?

**Comment by DuIslingr** [comment]
@mstg @coolstar Any comments regarding this issue? I experience it as well with the latest toolchain found on AngelXWinds site for linux. Using 10.1 sdk from theos/sdks which I'm going to assume this guy is as well. However mine is slightly different.

`ld: unexpected token: !tapi-tbd-v2 file '/home/DuIslingr/theos/sdks/iPhoneOS10.1.sdk/System/Library/Frameworks//Foundati
on.framework/Foundation.tbd' for architecture arm64
arm64-apple-darwin14-clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
/home/DuIslingr/theos/makefiles/instance/library.mk:32: recipe for target '/home/DuIslingr//mnt/c/Development/KHUx/.theo
s/obj/debug/arm64/duislingrkhux.dylib' failed
make[3]: *** [/home/DuIslingr//mnt/c/Development/KHUx/.theos/obj/debug/arm64/duislingrkhux.dylib] Error 1
/home/DuIslingr/theos/makefiles/instance/library.mk:32: recipe for target '/home/DuIslingr//mnt/c/Development/KHUx/.theo
s/obj/debug/arm64/duislingrkhux.dylib' failed
make[2]: *** [/home/DuIslingr//mnt/c/Development/KHUx/.theos/obj/debug/arm64/duislingrkhux.dylib] Error 2
/home/DuIslingr/theos/makefiles/instance/library.mk:24: recipe for target 'internal-library-all_' failed
make[1]: *** [internal-library-all_] Error 2
/home/DuIslingr/theos/makefiles/master/rules.mk:90: recipe for target 'duislingrkhux.all.tweak.variables' failed
make: *** [duislingrkhux.all.tweak.variables] Error 2`

**Comment by mstg** [comment]
@DuIslingr That is one of the default tbds, looks like some toolchain error to me as you've suggested.

**Comment by kirb** [comment]
@coolstar, do your toolchains have the latest ld64? ld64 274.2 source is available now.

**Comment by coolstar** [comment]
No, my toolchains use 264.3. However I have validated it on my end and it works fine with iOS 10.2 SDK

**Comment by kirb** [comment]
Yeah, I’m not able to repro either using the same setup.

Closing this due to lack of response. If you need further assistance, try [asking on IRC](http://iphonedevwiki.net/index.php/How_to_use_IRC).

**Comment by bin-y** [comment]
Get same problem as @DuIslingr got.

**Operating System: 
Windows Subsystem for Linux 

**Toolchain Version:
 I downloaded the toolchain from 
` https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip `
and last-modified date of arm64-apple-darwin14-ld in the archive is 2017-03-09

**SDK Version:
10.1 from theos

> Making all for tweak aaiv…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Linking tweak aaiv (arm64)…
ld: unexpected token: !tapi-tbd-v2 file '/root/theos/sdks/iPhoneOS10.0.sdk/usr/lib/libobjc.tbd' for architecture arm64
arm64-apple-darwin14-clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/tmp/aaiv/.theos/obj/debug/arm64/aaiv.dylib] Error 1
make[2]: *** [/tmp/aaiv/.theos/obj/debug/arm64/aaiv.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [aaiv.all.tweak.variables] Error 2

**Comment by qdk0901** [comment]
I got the same problem when building tweak under ubuntu with ios 10.1 sdk。
With 9.3 sdk verything ok except have [this](https://github.com/theos/theos/issues/265 ) issue

Anyone solved the `unexpected token: !tapi-tbd-v2` problem?
I using:
a) ubuntu 14.04
b) latest theos
c) ios 10.1 sdk from theos or from http://resources.airnativeextensions.com/ios
d) latest toolchain from https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip

**Comment by qdk0901** [comment]
finally, I solved this problem by replacing the `theos/toolchaine/linux/iphone/arm64-apple-darwin14-ld` with ld built from https://github.com/tpoechtrager/cctools-port

**Comment by kirb** [comment]
Yep, needs newer cctools + ld64 + libtapi. Clang and most everything else can do with an update too really. @coolstar maybe you could consider an update for ios + linux toolchains?

**Comment by mrkiller2010** [comment]
@qdk0901 Hey, how did you exactly fix it? I'm on windows btw.
What files did you take from the cctools-port?

**Comment by DuIslingr** [comment]
@mrkiller2010 you can literally just install normal clang shipped with your distro and compile the cc-tools port and just point theos to use the port files instead and everything will work fine. well as far as linux is concerned. if ur trying to do this on windows then I have no firsthand experience with cygwin or trying to use the included clang in latest visual studio 2017.

**Comment by kirb** [comment]
Cygwin does have clang, though I'd be unsure whether it can build mach-o's. VS's clang would be unaware of Cygwin paths and I don't think we'll be supporting native Windows anyway (that'd make three different ways of running Theos on Windows).

I reckon if we can be sure the OS's distributed clang can build identical-ish binaries on Linux/Cygwin, and isn't too old on, eg, Ubuntu 16.04 as compared to the cctools and such coolstar distributes, maybe for the next toolchain updates we can make it use system clang. (cc @coolstar)

**Comment by qdk0901** [comment]
@mrkiller2010 ，hi，just ld that built from cctools，but I use it under Windows Bash

[arm64-apple-darwin14-ld.zip](https://github.com/theos/theos/files/1585195/arm64-apple-darwin14-ld.zip)

**Comment by DuIslingr** [comment]
@kirb vs clang wouldnt need to be aware of cygwin paths since cygwin wouldnt be required at that point. but packaging at that stage would become an issue since windows doesnt share the same permissions anyways.

**Comment by kirb** [comment]
@duislingr, oh, you're right. Make does exist for Win32 but again it's a lot of effort when we can specifically target Linux/macOS while API compatibles like Cygwin/WSL fill the gaps for Windows.

**Comment by mrkiller2010** [comment]
@qdk0901 Thanks, but this is for linux I assume, how would I compile the cctools for windows? 
Sorry for asking neewbie questions.
