### ISSUE TITLE
How to run a tweak in the iOS simulator?

### ISSUE THREAD

**Issue by 0xCC0x01** [theos/theos#241]
What are the steps to reproduce this issue?
-------------------------------------------
1. I can make do with iPhone target, and the .deb is there. But I don't know how to run the tweak in the simulator
2.  I tried "export TARGET=simulator" then"make do", error like "requires you set IPHONE_SIMULATOR_ROOT", so I set "export IPHONE_SIMULATOR_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk"
3. Then, make do

What happens?
-------------
Error occurred

What were you expecting to happen?
----------------------------------
...

Any logs, error output, etc?
----------------------------
install.merge "...(the tweak dir)/.theos/_" "(IPHONE_SIMULATOR_ROOT, the dir I just set)"
su: illegal option -- c
usage: su [-] [-flm] [login[args]]
make: *** [internal-install] Error 1

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** OSX 10.11.1

**Toolchain Version:** …

**SDK Version:** 9.1

**Comment by kirb** [comment]
Refer to simject: https://github.com/angelxwind/simject – Theos on its own won’t make tweaks run in the simulator.

This isn’t an issue with Theos, so I’ll be closing this. If you need further assistance you might want to [ask on IRC](http://iphonedevwiki.net/index.php/IRC).

**Comment by 0xCC0x01** [comment]
Got it, thank you.
