### ISSUE TITLE
Clean up/unify the Darwin-based targets

### ISSUE THREAD

**Issue by kirb** [theos/theos#242]
We have 4 different versions of iphone.mk, and holy crap, 7 different Darwin-based targets supported on macOS. There’s a high amount of code duplication and inconsistency, such as in #209.

Almost all of each target makefile is exactly the same, especially on macOS, just with the particular target name changed. And for pretty much every instance of `xcrun -sdk iphoneos` we can just use `xcrun`, because none of these binaries are SDK-specific any more. SDK scanning might need a cleanup. Non-Xcode cross-compile toolchain logic definitely needs a cleanup.

**Comment by sbingner** [comment]
I fixed this by using:
`_IOS_SDKS := $(shell echo $(patsubst $(_XCODE_SDK_DIR)/iPhoneOS%.sdk,%'\n',$(wildcard $(_XCODE_SDK_DIR)/iPhoneOS*.sdk)) $(patsubst $(THEOS_SDKS_PATH)/iPhoneOS%.sdk,%'\n',$(wildcard $(THEOS_SDKS_PATH)/iPhoneOS*.sdk)) | sort -n | paste -s -d" " - )`

in makefiles/targets/Darwin/iphone.mk

**Comment by sbingner** [comment]
I fixed the SDK sort order issue for latest by using:
`_IOS_SDKS := $(shell echo $(patsubst $(_XCODE_SDK_DIR)/iPhoneOS%.sdk,%'\n',$(wildcard $(_XCODE_SDK_DIR)/iPhoneOS*.sdk)) $(patsubst $(THEOS_SDKS_PATH)/iPhoneOS%.sdk,%'\n',$(wildcard $(THEOS_SDKS_PATH)/iPhoneOS*.sdk)) | sort -n | paste -s -d" " - )`

in makefiles/targets/Darwin/iphone.mk

**Comment by kirb** [comment]
Done in [Theos 2.4](https://github.com/theos/theos/releases/tag/2.4).
