### ISSUE TITLE
FINALPACKAGE=1 causing crash in tweak.

### ISSUE THREAD

**Issue by cyanisaac** [theos/theos#244]
Doing "make clean do FINALPACKAGE=1" is causing crashing with my tweak Brightify.

What are the steps to reproduce this issue?
-------------------------------------------
1. Grab the source code for Brightify: https://github.com/cyanisaac/brightify
2. Do "make clean do FINALPACKAGE=1" to ensure a clean build with final package settings.
3. Attempt to run Spotify (Tweak's main functionality).

What happens?
-------------
Spotify crashes, and Brightify is not seen as a suspect.

What were you expecting to happen?
----------------------------------
The tweak would work as it does in debug mode.

Any logs, error output, etc?
----------------------------
https://gist.github.com/cyanisaac/14ab86d7ef11879cf60a92a78aef92d7 crash report

https://gist.github.com/cyanisaac/d10f2bc904e02e4ec244941d8d29112f syslog

Any other comments?
-------------------
My tweak uses ARC, and has an iOS 10.1SDK (from theos/sdks) for Brightify and iOS9.3SDK (from theos/sdks) for the preferences bundle.

This may be an issue with my tweak, but it may also be an issue with Theos, so it would be interesting to see what causes the discrepancy between Debug and Release configurations.

Source code for Brightify is available here: https://github.com/cyanisaac/Brightify and hooks into Spotify.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.12.4

**Toolchain Version:** Latest version of Theos.

**SDK Version:** iOS 10.1 for Brightify target, iOS 9.3 for BrightifyPreferencesBundle target.

**Comment by DHowett** [comment]
The primary difference between debug and release builds is the presence and
level of optimization. Try building in normal (not FINALPACKAGE) mode with
CFLAGS=-O2

If the crash still reproduces, it's not likely to be Theos' fault.
-- 
-- Dustin L. Howett

**Comment by cyanisaac** [comment]
Debug mode with ADDITIONAL_CFLAGS=-O2 doesn't crash.

It seems like it might be some kind of issue with Theos, however.

Setting FINALPACKAGE=1 or DEBUG=0 causes the tweak to crash with the same code. I'm not sure how that _wouldn't_ be an issue with Theos somewhere unless there's some other non-Theos component that handles differences between debug and release builds. It doesn't seem like the tweak should stop working with that flag being changed.

**Comment by kirb** [comment]
Did you ever work this out? I’m still really stumped by this and haven’t seen this issue reported by anyone else.

Going to close this as I don’t think it’s a Theos issue; we can reopen if it is. Wish I had any idea about it, sorry.
