### ISSUE TITLE
No sdk error

### ISSUE THREAD

**Issue by SamHep0803** [theos/theos#245]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. '''cd''' into theos project
2.  run '''make package'''
3. watch the sdk errors

What happens?
-------------
I get sdk errors I goto my sdk folder and its there

What were you expecting to happen?
----------------------------------
run perfectly normal

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/vv64z

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System: MacOS** …

**SDK Version:10.3** …

**Comment by kirb** [comment]
Your developer directory is set to the Command Line Tools and not Xcode. Presumably you have Xcode installed? It automatically switches to itself when installed.

If it’s definitely installed, switch to it with: `sudo xcode-select -switch /Applications/Xcode.app`

Closing as this is not a Theos issue.

**Comment by SamHep0803** [comment]
Thanks i'm pretty sure that helped.
