### ISSUE TITLE
No working toolchain available on Windows Subsystem for Linux.

### ISSUE THREAD

**Issue by bin-y** [theos/theos#248]
What are the steps to reproduce this issue?
-------------------------------------------
follow steps on https://github.com/theos/theos/wiki/Installation to install theos on Windows Subsystem for Linux

What happens?
-------------
theos currently not support [latest toolchain](https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip) ( #240 , #236 ), and there's no other option

What were you expecting to happen?
----------------------------------
I can build/download a working toolchain from some place.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
made a new comment on #236 

What versions of software are you using?
----------------------------------------
**Operating System:** Windows Subsystem for Linux

**Toolchain Version:** https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip ( last-modified date of arm64-apple-darwin14-ld in the archive is 2017-03-09 )

**SDK Version:** https://github.com/theos/sdks 10.1

**Comment by kirb** [comment]
Well, the issue is rather that the iOS 10.1 SDK won’t work due to the newer tbd format. I thought this was working? @coolstar?

(An older SDK will work.)

**Comment by bin-y** [comment]
iOS 9.3 SDK works, not sure if it is compatible with iOS 10 system.

**Comment by kirb** [comment]
Binaries built with old SDKs will always work with the latest iOS. Otherwise, no apps would work until updated with the iOS 10 SDK.

**Comment by bin-y** [comment]
@kirb thanks for the explanation, I'll use iOS 9.3 SDK instead.

**Comment by bin-y** [comment]
There's also some hint if any one using WSL and find this issue:

Default permission of new files on WSL is 777,  that will make some error like  `dpkg: "control directory has bad permissions"` .  
use `umask 022` can change default permission of new files to 755 but that won't work with windows partitions, files mounted from windows partitions always have 777 permission, 
My solution is write a bash script to copy project to /tmp, chmod and build so I can edit the code from windows and build on WSL.

My English is not good, maybe someone can add this to wiki.

**Comment by kirb** [comment]
That's an interesting issue; best thing I can recommend is remounting `/mnt/c` with a better umask:

```bash
sudo mount -o remount,umask=022 /mnt/c
```

...but that doesn't work:

```
umount: /mnt/c: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
```

So I don't really have a good answer to that, and I'm not sure that we'll change how staging works just to work around a WSL limitation that will probably be fixed at some point.

**Comment by DuIslingr** [comment]
@bin-y I have somewhat managed to resolve the issue. You can create and modify projects anywhere you want on windows and it will be able to build. however at this time I have not had time to try and fix the issue when trying to build settings bundles. building simple tweaks however should work fine.

https://github.com/DuIslingr/theos/commit/461e0000ffe36e2eea192e95934c4839485c848f
