### ISSUE TITLE
can u tell me how to build c style program like 7zip?

### ISSUE THREAD

**Issue by rozbo** [theos/theos#250]
I want to build a tool program like 7zip , But I can't find any message in wiki or google. is it doesn't support ?
I use macos 10.12 and newest xcode 8 build for ios10.
thanks for answer!
have a nice day!

**Comment by rozbo** [comment]
I find a `native.mk` ,is that for c style program?

**Comment by kirb** [comment]
You typically shouldn’t use Theos for a project with an existing build system. If you’re making a new project, start from the tool template.

Closing as this is not a Theos issue. If you still need help, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
