### ISSUE TITLE
Xcrun: command not found - ios 10.2

### ISSUE THREAD

**Issue by sterling0x1** [theos/theos#251]
What are the steps to reproduce this issue?
-------------------------------------------
1. Clone Theos 
2. Make necessary changes for arm64
3. Copy files from "vendor"
4. Make a tweak project
5. Compile it with "make"

What happens?
-------------

Theos thinks I'm on OS X, while I'm on iOS 10.2

What were you expecting to happen?
----------------------------------

Compile the test tweak as it was supposed to.

Any logs, error output, etc?
----------------------------

>Sterlings-thing:/var/mobile/projects/test root# make
bash: xcode-select: command not found
bash: xcrun: command not found
bash: xcode-select: command not found
bash: xcode-select: command not found
bash: xcrun: command not found
bash: xcode-select: command not found
bash: xcrun: command not found
-> Making all for tweak test…
bash: xcode-select: command not found
bash: xcrun: command not found
bash: xcode-select: command not found
bash: md5: command not found
bash: xcode-select: command not found
bash: xcode-select: command not found
bash: xcode-select: command not found
bash: xcrun: command not found
bash: xcode-select: command not found
bash: md5: command not found
bash: md5: command not found
bash: xcode-select: command not found
bash: xcode-select: command not found
bash: xcrun: command not found
bash: xcode-select: command not found
bash: md5: command not found
bash: md5: command not found
bash: xcode-select: command not found
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7)…
bash: xcrun: command not found
make[3]: *** [/var/mobile/projects/test/.theos/obj/debug/armv7/Tweak.xm..o] Error 127
make[2]: *** [/var/mobile/projects/test/.theos/obj/debug/armv7/test.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [test.all.tweak.variables] Error 2

Any other comments?
-------------------
Never seen this on iOS 8.4 or Cygwin. Please give me some advice on how I make theos realise I'm compiling on iOS and not OS X 

What versions of software are you using?
----------------------------------------
**Operating System:** ios 10.2

**Toolchain Version:** latest from BB repo

**SDK Version:** 9.2-9.3

**Comment by sterling0x1** [comment]
Here is my makefile:

ARCHS = armv7 arm64
TARGET = iphone:clang:latest:latest
test_CFLAGS = -fobjc-arc
THEOS_PACKAGE_DIR_NAME = debs

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = test
test_FILES = Tweak.xm
test_FRAMEWORKS = UIKit
test_LDFLAGS += -Wl,-segalign,4000
test_CFLAGS = -w

include $(THEOS_MAKE_PATH)/tweak.mk

include $(THEOS_MAKE_PATH)/aggregate.mk

**Comment by kirb** [comment]
>2. Make necessary changes for arm64
>3. Copy files from "vendor"

These steps aren’t necessary. An arm64 platform is internally mapped to arm; and vendor/include/ and vendor/lib/ are always passed to the compiler for you. Revert these changes and see if the issue is solved.

**Comment by sterling0x1** [comment]
@kirb you're right, reverted the changes and it compiled no problem. I didn't realise these were not necessary anymore and it's literally "plug and play".
Thanks
