### ISSUE TITLE
Can't compile with very similar method name

### ISSUE THREAD

**Issue by Akebu** [theos/theos#252]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
Just try to compile

```
%hook SomeClass
- (void)tableView:(UITableView *) willDisplayHeaderView:(UIView *)view forSection:(NSInteger *)index
{
	%orig;
}

- (void)tableView:(UITableView *) willDisplayFooterView:(UIView *)view forSection:(NSInteger *)index
{
	%orig;
}

%end
```

What happens?
-------------
An error of redefinition

What were you expecting to happen?
----------------------------------
Compile 

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/8oa9j

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Debian Jessie

**Toolchain Version:** : 11

**SDK Version:* : 9.0

**Comment by uroboro** [comment]
While this should prompt another error instead, you are missing the argument name for the first arg in both hooks. See if this error still happens after fixing as I said.

**Comment by Akebu** [comment]
Ugh, everything works fine now...
Sorry for inconvenience
