### ISSUE TITLE
OS X - Xcode9(beta2) - make errors

### ISSUE THREAD

**Issue by sterling0x1** [theos/theos#255]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
Have latest Xcode installed.
Have requirements installed (dpkg, ldid)
Follow OS X install guide
Follow OS X setup guide
Create test tweak
make

What happens?
-------------
Tons of error using iOS 9.2 sdk (what I normally used)
1 error using 11.0 sdk from Xcode

What were you expecting to happen?
----------------------------------
Build the project no probs.

Any logs, error output, etc?
----------------------------
iOS 11 sdk
https://ghostbin.com/paste/4o2ne

iOS 9.2 sdk
https://ghostbin.com/paste/xk2oe

Any other comments?
-------------------

I do get sdk not found errors too, even tho I added sdk to both Theos/sdk and to Xcode.app.

What versions of software are you using?
----------------------------------------
**Operating System:** OS X 10.12.5

**Toolchain Version:** Xcode 9.2

**SDK Version:** 9.2/11.0

**Comment by kirb** [comment]
Is your Xcode path set correctly? `xcode-select -print-path`. You're also using a `$THEOS` path that doesn't match the case on the filesystem (`/users` instead of `/Users`). Read your error messages!

Your iOS 9.2 SDK looks like it was possibly from a Cygwin environment, and was copied from outside of Cygwin. Cygwin symlinks are binary files unless you configure `$CYGWIN` to use NTFS symlinks. You should just download a new copy of the SDK.

**Comment by sterling0x1** [comment]
path output is:
`/Library/Developer/CommandLineTools`
 
You're right, capital "U" it is. Compiles ok with iOS 11 sdk now, but still throwing `xcrun: error: SDK "iphoneos" cannot be located` like crazy, even tho it compiles fine.

**Comment by kirb** [comment]
Command line tools package is only intended to build for macOS. Note if you're on (Low) Sierra, these match Xcode 8's tools, not 9. Switch to Xcode 9's tools with `sudo xcode-select -switch /Applications/Xcode-beta.app`.

**Comment by sterling0x1** [comment]
Oh I see. That did the trick, thanks a lot!
