### ISSUE TITLE
My tweak stops working after adding a custom dylib file to it.

### ISSUE THREAD

**Issue by euroboy** [theos/theos#256]
Hello. I've created a simple tweak that adds an yellow UIView to the app window (nothing special), and it works perfectly. Then I made a dylib file (called AlertLib), containing one class (called AlertLib as well), with one method: to show a simple UIAlertView. I copied the AlertLib.dylib to /opt/theos/lib folder, and AlertLib.h to /opt/theos/include folder. 

My Makefile looks this way:

```
export ARCHS = armv7 arm64
export TARGET = iphone:clang:latest:8.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = YellowSquare
YellowSquare_FILES = Tweak.xm
YellowSquare_FRAMEWORKS = UIKit Foundation
YellowSquare_LDFLAGS = -lAlertLib

include $(THEOS_MAKE_PATH)/tweak.mk

after-install::
	install.exec "killall -9 SpringBoard"
```

And Tweak.xm file looks this way:

```
#import "AlertLib.h"

%hook AppDelegate

- (void) applicationDidBecomeActive:(UIApplication *) application
{
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        
        [[AlertLib sharedInstance] showAlert];
        
        UIView *yellowSquareView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
        yellowSquareView.backgroundColor = [UIColor yellowColor];
        
        UILabel *tweakLabel = [[UILabel alloc] initWithFrame:yellowSquareView.bounds];
        tweakLabel.backgroundColor = [UIColor clearColor];
        tweakLabel.text = @"TWEAK";
        tweakLabel.font = [UIFont systemFontOfSize:25];
        tweakLabel.textAlignment = NSTextAlignmentCenter;
        [yellowSquareView addSubview:tweakLabel];
        
        UIWindow *window = [UIApplication sharedApplication].keyWindow;
        yellowSquareView.center = window.center;
        [window addSubview:yellowSquareView];
    });

    %orig;
}

%end
```

After that I compiled the tweak, and installed it to device, with no error. But, now tweak isn't working, i.e no yellow view is added on app's window, and no alert is shown. 
What could be wrong?

**Comment by DHowett** [comment]
You've made sure that AlertLib is installed in the usual/expected location
on the device?
-- 
-- Dustin L. Howett

**Comment by euroboy** [comment]
I only installed the deb file via iFile. I supposed that AlertLib was containing in my final .deb file, isn't it?

**Comment by euroboy** [comment]
How could I embed my custom dylib file (libAlertLib.dylib) to my tweak? Maybe it's very easy, but I'm struggling to find a source how to achieve this.

**Comment by kirb** [comment]
Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
