### ISSUE TITLE
how to add third party frame like svprogresshud in my theos project

### ISSUE THREAD

**Issue by iOS-mamu** [theos/theos#259]
I would like to use SVProgressHUD (no matter .a or .framework) in my theos reverse engineering Project.

I tried to put headers in /opt/theos/inlcude and put .framework file in /op/theos/lib

and add EXTRA_FRAMEWORK += SVProgressHUD in makefile file.

it can compile without issues. but it somehow does not work.

any idea?

**Comment by kirb** [comment]
The framework needs to have an install name (the location on disk where dyld should expect it to be when it tries to load it) and needs to be installed at this place on the device. That said, you shouldn't use a framework here; loading linked frameworks (except for iOS built-in ones) incurs a performance penalty, and SVProgressHUD is a rather small project. You should include it with your main project, and change symbols (class names, constant names, etc) so they are unique (eg, prefix them with your initials) and won't conflict with SVProgressHUD if it's used in any apps you load into or other tweaks. 

Closing as this is not a Theos issue. If you need further assistance, see our [Help](https://github.com/theos/theos/wiki/Help) page.
