### ISSUE TITLE
library not found for -objc   (theos ios)

### ISSUE THREAD

**Issue by BandarHL** [theos/theos#260]
[https://ia601502.us.archive.org/14/items/IMG1512/IMG_1512.PNG](url)

 I need help😢

**Comment by kirb** [comment]
This issue tracker is for issues with Theos itself; this seems to be a configuration issue on your end. Are you missing an SDK or part of the toolchain?

Also, you’re using an old version of Theos that we can’t fully support you with; please [install the latest version](https://git.io/theosinstall) which does also provide more obvious warnings when things like SDKs are missing.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).

**Comment by BandarHL** [comment]
new issues bro
[https://ia601507.us.archive.org/15/items/IMG1513_201709/IMG_1513.PNG](url)

**Comment by kirb** [comment]
Again, this is not the place for general help; please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for advice and places where you can get help.
