### ISSUE TITLE
Add option to specify username for install.exec

### ISSUE THREAD

**Issue by ArtikusHG** [theos/theos#261]
Like, most of the install.exec's are killall -9 SpringBoard, and that can be done from mobile, so do ssh mobile@theos-device-ip and do this. This would save some time for those using theos-device-ip.

**Comment by kirb** [comment]
There is already $THEOS_DEVICE_USER: https://github.com/theos/theos/blob/dd047009ea9737188ff4d8338577569db67a5830/bin/install.exec#L9-L11

**Comment by ArtikusHG** [comment]
Oh thanks, sorry for opening the issue, should've read the wili before :)

**Comment by kirb** [comment]
It’s fine, I can’t blame you. We need better documentation. It’s not really mentioned anywhere.
