### ISSUE TITLE
tweak's contructor function not got called when build under ubuntu

### ISSUE THREAD

**Issue by qdk0901** [theos/theos#265]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1.  git clone https://github.com/nabla-c0d3/ssl-kill-switch2
     make package install  
     under macos
2.  git clone https://github.com/nabla-c0d3/ssl-kill-switch2
    make package install 
     under ubuntu 

What happens?
-------------
1. if tweak make under macos, the constructor function got called, I can see the log printed in the constructor function  by idevicesyslog
2. if tweak make under ubuntu, the constructor function does not got called, I can not see the log printed in the constructor function  by idevicesyslog
3. I pull the SSLKillSwitch2.dylib out of the deb, and push it to the /Library/MobileSubstrate/DynamicLibraries path on the phone. And
  a) the SSLKillSwitch2.dylib build under macos works, the constructor function got called
  b) the SSLKillSwitch2.dylib build under ubuntu not works, he constructor function does not got called
…

What were you expecting to happen?
----------------------------------
tweak build under macos or ubuntu should both work, the constructor function should be called

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
when works as expect, you can find 
"<Notice>: === SSL Kill Switch 2: Preference set to 0" by idevicesyslog

when it does not work, you cannot find anything about ssl kill switch

Any other comments?
I upload the ok and ng dylib here.
[SSLKillSwitch2_ng.zip](https://github.com/theos/theos/files/1335711/SSLKillSwitch2_ng.zip)
[SSLKillSwitch2_ok.zip](https://github.com/theos/theos/files/1335712/SSLKillSwitch2_ok.zip)
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** ubuntu 14.04, macos 10.12

**Toolchain Version:** latest iphone toolchain under ubuntu, xcode toolchain under macos

**SDK Version:** iphone 9.3 under ubuntu, xcode sdk under macos

**Comment by kirb** [comment]
The constructor is working, it's just that logging changed in iOS 10. Previously, logs went to ASL (Apple System Log), now there is both ASL for legacy code and the new Unified Logging System for code linked against iOS 10.0 SDK or newer. The key is that binaries linked against older SDKs still log to ASL. Your best choice is to either use a [newer SDK](https://github.com/theos/sdks), or alternatively view the ASL stream via the `ondeviceconsole` tool from Cydia. 

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
