### ISSUE TITLE
installing & output

### ISSUE THREAD

**Issue by salamsalamhavji** [theos/theos#267]
how to install apps that develop through this way via web? how to get output as ipa?

**Comment by kirb** [comment]
Hi, sorry but the Theos issue tracker isn't for questions, it's for bug reports. Please try one of the places listed on our [Help](https://github.com/theos/theos/wiki/Help) page. Make sure you provide as much detail as possible so someone can better answer your exact problem — are you trying to package an app you've built with Theos into an ipa or a tweak into an existing ipa?

**Comment by salamsalamhavji** [comment]
use "itms-services://?action=download-manifest&url="
