### ISSUE TITLE
dpkg_1.18.10.tar.xz file not found . have another one replace it?

### ISSUE THREAD

**Issue by onezens** [theos/theos#272]
brew install --from-bottle https://raw.githubusercontent.com/Homebrew/homebrew-core/7a4dabfc1a2acd9f01a1670fde4f0094c4fb6ffa/Formula/dpkg.rb
######################################################################## 100.0%
Warning: dpkg 1.18.24 is available and more recent than version 1.18.10.
Warning: dpkg: this formula has no --from-bottle option so it will be ignored!
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/d/dpkg/dpkg_1.18.10.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.1

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "dpkg"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.18.10.tar.xz

**Comment by onezens** [comment]
I have found the directory updated:  https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/d/dpkg/

https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.19.0.4.tar.xz

**Comment by kirb** [comment]
No longer necessary to downgrade dpkg, so closing this.
