### ISSUE TITLE
Can't locate IO/Compress/Lzma.pm in @INC

### ISSUE THREAD

**Issue by haykam821** [theos/theos#273]
What are the steps to reproduce this issue?
-------------------------------------------
1. Follow [a guide](http://iphonedevwiki.net/index.php/Theos/Setup#For_Mac_OS_X)
2. Reinstall stuff
3. Get a SDK
4. `make package`

What happens?
-------------
Some error I don't know about

What were you expecting to happen?
----------------------------------
It to work and not mess up

Any logs, error output, etc?
----------------------------
```
Haykams-MacBook:stringtheory haykam$ make package
> Making all for tweak ExampleName…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak ExampleName…
Can't locate IO/Compress/Lzma.pm in @INC (you may need to install the IO::Compress::Lzma module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /opt/theos/bin/dm.pl line 12.
BEGIN failed--compilation aborted at /opt/theos/bin/dm.pl line 12.
make: *** [internal-package] Error 2
```

Any other comments?
-------------------
Nope

What versions of software are you using?
----------------------------------------
**Operating System:** macOS High Sierra 10.13

**Toolchain Version:** ???

**SDK Version:** iOS 9.3

**Comment by uroboro** [comment]
Please try again with the not-outdated [current set of instructions](https://github.com/theos/theos/wiki/Installation).

**Comment by kirb** [comment]
Install it with `sudo IO::Compress::Lzma`. Sorry, the post-update script was meant to do this but it was broken for a few hours. I guess you updated before I pushed 9d78ab5?

**Comment by haykam821** [comment]
Same error happens. @uroboro

**Comment by haykam821** [comment]
@kirb I ran all four:

    sudo cpan Compress::Raw::Lzma
    cpan Compress::Raw::Lzma
    sudo cpan IO::Compress::Lzma
    cpan IO::Compress::Lzma

**Comment by kirb** [comment]
Is there any error output from cpan? Same not found error if you run the following?

```
perl -MIO::Compress::Lzma -MCompress::Raw::Lzma -e 1
```

(No output will mean success.)

Do you have any environment vars set up for cpan such as  `$PERL_MB_OPT`/`$PERL_MM_OPT`?

**Comment by haykam821** [comment]
@kirb Here's the result:

```
Haykams-MacBook:projectfolderreplacementname haykam$ perl -MIO::Compress::Lzma -MCompress::Raw::Lzma -e 1
Can't locate IO/Compress/Lzma.pm in @INC (you may need to install the IO::Compress::Lzma module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .).
BEGIN failed--compilation aborted.
```

I installed `perl` through Homebrew, and those envvars aren't set up.

**Comment by kirb** [comment]
I've realised the issue — dm.pl was meant to prefer Homebrew perl (via `#!/usr/bin/env perl`) but I didn't commit that so it's always using system perl (`#!/usr/bin/perl`). Till I can get home to fix that, you can modify the first line of `$THEOS/vendor/dm.pl/dm.pl` to use the right hashbang line. The issue being that you're using Homebrew perl's `cpan`, which is installing it to Homebrew's designated path, which system perl isn't aware of.

**Comment by haykam821** [comment]
I changed it to `#!/usr/local/Cellar/perl` and it now works. Thanks for your help!

**Comment by kirb** [comment]
Perfect. Sorry for the inconvenience.

**Comment by kirb** [comment]
Fixed in theos/dm.pl@b77a377.

**Comment by aStudyer** [comment]
I use the latest code,but i still meet the same issue.

**Comment by iEdric** [comment]
I use the latest code,but i still meet the same issue.

**Comment by ondev** [comment]
should both install
sudo cpan IO::Compress::Lzma
and 
cpan Compress::Raw::Lzma

if failed too,  add sudo and install again.

**Comment by onezens** [comment]
@ondev thanks , I fix my issue for

 > Making all for tweak wxprober…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak wxprober…
Can't locate IO/Compress/Lzma.pm in @INC (you may need to install the IO::Compress::Lzma module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /opt/theos/bin/dm.pl line 12.
BEGIN failed--compilation aborted at /opt/theos/bin/dm.pl line 12.
make: *** [internal-package] Error 2

**Comment by covalspace** [comment]
I'm running into an issue with 
`sudo cpan IO::Compress::Lzma`

when I run it I get 

```
Parse errors: No plan found in TAP output
Files=45, Tests=37,  1 wallclock secs ( 0.04 usr  0.03 sys +  0.73 cusr  0.20 csys =  1.00 CPU)
Result: FAIL
Failed 39/45 test programs. 9/37 subtests failed.
make: *** [test_dynamic] Error 255
  PMQS/IO-Compress-Lzma-2.201.tar.gz
one dependency not OK (Compress::Raw::Lzma); additionally test harness failed
  /usr/bin/make test -- NOT OK
```

I'm on MacOS M1 Chip. Installed with macports.

**Comment by qodeninja** [comment]
Anybody have a solution for the `sudo cpan IO::Compress::Lzma` issue?

**Comment by kirb** [comment]
This hasn’t been required in a long time @qodeninja (this issue was closed 6 years ago!), please make sure Theos is up to date. See https://theos.dev/install for help.
