### ISSUE TITLE
"make package" fails with Swift file

### ISSUE THREAD

**Issue by lowip** [theos/theos#275]
What are the steps to reproduce this issue?
-------------------------------------------
1. Generate a tool project with `nic.pl`
2. Create an empty swift file called `main.swift`
3. Replace `main.mm` by `main.swift` in the `makefile`

What happens?
-------------
The compiler fails to use `$THEOS/Prefix.pch` saying it `is not a valid precompiled PCH file`

What were you expecting to happen?
----------------------------------
To compile the `main.swift` without errors

Any logs, error output, etc?
----------------------------
```sh
$ make package
> Making all for tool AutoAppStore…
==> Compiling main.swift (armv7)…
<unknown>:0: error: input is not a PCH file: '/Users/lowip/theos/Prefix.pch'
<unknown>:0: error: file '/Users/lowip/theos/Prefix.pch' is not a valid precompiled PCH file
<unknown>:0: error: clang importer creation failed
make[3]: *** [/project/path/.theos/obj/debug/armv7/main.swift.74b12c38.o] Error 1
make[2]: *** [/project/path/.theos/obj/debug/armv7/AutoAppStore] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [AutoAppStore.all.tool.variables] Error 2
```

Any other comments?
-------------------
In `$THEOS/makefiles/common.mk`, if i disable the `Prefix.pch` import, everything works as expected:
```sh
_THEOS_INTERNAL_IFLAGS_SWIFT = $(_THEOS_INTERNAL_IFLAGS_BASE) # -import-objc-header $(THEOS)/Prefix.pch
```

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.13.2 (17C88)

**Toolchain Version:** Xcode 9.2 (9C40b)

**SDK Version:** iPhoneOS 9.1

**Comment by kirb** [comment]
Fixed this and a few other issues with Swift in [Theos 2.4](https://github.com/theos/theos/releases/tag/2.4). Thanks for reporting!
