### ISSUE TITLE
Cygwin Windows 10 You did not specify a target

### ISSUE THREAD

**Issue by 5H4D0WILA** [theos/theos#276]
Everytime i try "make package" it gives me the "you did not specify a target" error
I did everything that is on the internet to fix this but nothing worked
Please help me
Pls

**Comment by 5H4D0WILA** [comment]
Oh btw
I've 9.3 sdks and the latest toolchains

**Comment by kirb** [comment]
I don’t think we were able to repro this issue but it may have been fixed in [Theos 2.4](https://github.com/theos/theos/releases/tag/2.4). If you’re still having this issue after updating Theos, reopen this issue and include the output of `uname -a`.
