### ISSUE TITLE
ld: malformed file

### ISSUE THREAD

**Issue by Packetfahrer** [theos/theos#277]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. make package

What happens?

==> Linking tweak Test10 (armv7)…
ld: malformed file
/usr/local/opt/theos/vendor/lib/libapplist.tbd:4:26: error: unknown key 'flags'
flags:                 [ not_app_extension_safe ]

Any logs, error output, etc?
----------------------------

https://ghostbin.com/paste/br73t

What versions of software are you using?
----------------------------------------
**Operating System: macOS 10.13.2 (17C88)

**Toolchain Version:Xcode 9.2 (9C40b)

**SDK Version:iPhoneOS10.1.sdk

**Comment by kirb** [comment]
Fixed in theos/lib@aca2019. Thanks.
