### ISSUE TITLE
Package fails if makefile or control have CRCRLF return encoding

### ISSUE THREAD

**Issue by zEstLabs** [theos/theos#280]
What are the steps to reproduce this issue?
-------------------------------------------
1. Hex edit makefile, replace all 0x0A with 0x0D, 0x0A
2. Hex edit control, replace all 0x0A with 0x0D, 0x0A
3. run 'make package'

What happens?
-------------
packaging fails with error “package name has characters that aren’t lowercase alphanums or ‘-+’.”

What were you expecting to happen?
----------------------------------
successful packaging

Any logs, error output, etc?
----------------------------
...

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** OSX 10.13.2

**Toolchain Version:** Latest

**SDK Version:** All

**Comment by kirb** [comment]
Both are definitely not right; you’re dealing with a POSIX-like system and shouldn’t expect CRLF to work anywhere. We can add an `s/\r\n/\n/g` workaround for control but we can’t fix Make behavior (I don’t think GNU would consider it a bug anyway). There’s also places we can’t check that might choke on CRLF, such as shell scripts, and us somewhat providing affordances to allow CRLF would make the issue less obvious.

I think this’ll most likely be wontfix, but an error for CRLF use in control would be a good idea.

**Comment by kirb** [comment]
Throwing an error when `\r` is present in control was implemented in dm.pl a while ago.
