### ISSUE TITLE
Can't locate object method "chown" via package "NIC::Archive::Tar::File" at /opt/theos/bin/dm.pl line 148.

### ISSUE THREAD

**Issue by snakeninny** [theos/theos#284]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. `make package`

What happens?
-------------
`Can't locate object method "chown" via package "NIC::Archive::Tar::File" at /opt/theos/bin/dm.pl line 148.`

What were you expecting to happen?
----------------------------------
`make package` produces a deb file

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
`Can't locate object method "chown" via package "NIC::Archive::Tar::File" at /opt/theos/bin/dm.pl line 148.`

Any other comments?
-------------------
Simply running `sudo cpan IO::Compress::Lzma` returned error that some tests failed to pass, so the install failed too. Then I run `sudo cpan -f IO::Compress::Lzma` instead and the installment succeeded. Don't know if this matters.

What versions of software are you using?
----------------------------------------
**Operating System:** …
macOS 10.13.3

**Toolchain Version:** …
`This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level`

**SDK Version:** …
Xcode 9.2

**Comment by kirb** [comment]
Not sure how you have Perl 5.12.4 on macOS 10.13.3. On a test VM with 10.13.1 I have 5.18.2 from the system and 5.26.1 from Homebrew. Try a `brew update; brew upgrade` (or whatever)? Still raises a good point that this function possibly(?) is rather recent and won’t exist on macOS <10.13’s perl.

**Comment by snakeninny** [comment]
I run `brew install perl` and got perl 5.26.1 installed. But with `perl -v` I still got `This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level` and the same error as above when `make package`. Any ideas? @kirb

**Comment by kirb** [comment]
Try `which perl`, maybe something is overriding Homebrew’s? Also `brew info perl` and make sure you haven’t got an older Perl linked. `brew switch perl 5.26.1` if that’s the case.

**Comment by snakeninny** [comment]
`which perl` returns `/opt/local/bin/perl`, which I believe is the stock perl; and HomeBrew installs perl at `/usr/local/Cellar/perl/5.26.1/bin/perl`:

```
/usr/local/Cellar/perl/5.26.1/bin/perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for darwin-thread-multi-2level
```

How do I make perl 5.26.1 as the default perl? Thanks!

**Comment by kirb** [comment]
/opt/local would be MacPorts. You should clean that up; use one or the other not both.

**Comment by snakeninny** [comment]
Uninstalled MacPorts by following the [official guide](https://guide.macports.org/chunked/installing.macports.uninstalling.html), reboot macOS and rerun `cpan -f IO::Compress::Lzma`, then every thing worked as expected. Thanks @kirb !
