### ISSUE TITLE
Theos Preference Bundle Crashing

### ISSUE THREAD

**Issue by jacc** [theos/theos#285]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … create a preference bundle inside the project folder
2. … make package
3. … error

What happens?
-------------
returns an error

What were you expecting to happen?
----------------------------------
the package to be bundled

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/PrivateFrameworks'
ld: framework not found Preferences
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** MacOS Sierra

**Toolchain Version:** Not sure?

**SDK Version:** Also not sure. Followed instructions.

**Comment by kirb** [comment]
You need a patched SDK. Xcode no longer includes private frameworks, so you can’t link private frameworks like Preferences.framework.

Download a ZIP of https://github.com/theos/sdks and extract them into $THEOS/sdks/.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
