### ISSUE TITLE
Cygwin - Can't locate IO/Compress/Lzma.pm in @INC

### ISSUE THREAD

**Issue by castix** [theos/theos#287]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Install Cygwin
2. Install Theos & Dependencies
3. Compile any project

What happens?
-------------
Compiling cancels due to the error when trying to make the preference bundle

What were you expecting to happen?
----------------------------------
Get a full working package

Any logs, error output, etc?
----------------------------
Can't locate IO/Compress/Lzma.pm in @INC (you may need to install the IO::Compress::Lzma module) (@INC contains: /usr/local/lib/perl5/site_perl/5.26/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.26 /usr/lib/perl5/vendor_perl/5.26/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.26 /usr/lib/perl5/5.26/x86_64-cygwin-threads /usr/share/perl5/5.26) at /home/castix/theos/bin/dm.pl line 12.
BEGIN failed--compilation aborted at /home/castix/theos/bin/dm.pl line 12.

Any other comments?
-------------------
I've seen previous commits with this error but none of the solutions were working for Cygwin or not that I'm aware of.

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 64-bit

**Toolchain Version:** iOSToolchain4Win

**SDK Version:** 9.3

**Comment by kirb** [comment]
Cygwin kinda makes this a lot more complicated… I only just tested this a few days ago (and fortunately this won’t be necessary soon).

IIRC I had to install:

* gcc-core
* gcc-g++
* liblzma-devel
* libcrypt-devel

Then do `cpan IO::Compress::Lzma` and it should succeed. If not, post here anything that looks like an error message.

**Comment by castix** [comment]
Yes that fixed my issue, thank you very much. I hope you can implement a long term solutions soon

**Comment by Arodos** [comment]
I still get the mistake. In which folder do I have to install this?
