### ISSUE TITLE
Compiling error - openurl is deprecated

### ISSUE THREAD

**Issue by GodlyOne123** [theos/theos#289]
What are the steps to reproduce this issue?
-------------------------------------------
1. Compile

What happens?
-------------
Get an error

What were you expecting to happen?
----------------------------------
Deb file created

Any logs, error output, etc?
----------------------------
PvZ2.mm:17:40: error: 'openURL:' is deprecated: first deprecated in iOS 10.0 -
      Please use openURL:options:completionHandler: instead
      [-Werror,-Wdeprecated-declarations]
    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"ht...
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:127:1: note: 
      'openURL:' has been explicitly marked deprecated here
- (BOOL)openURL:(NSURL*)url NS_DEPRECATED_IOS(2_0, 10_0, "Please use ope...
^

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …
iMac 

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
I’m sorry but this isn’t a Theos issue. Please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places you can get help with general programming issues.

**Comment by codyd51** [comment]
To put it another way: @GodlyOne123 did you try reading your error message? It is a compiler warning that you're using a deprecated API, and has nothing to do with theos. The error your pasted even tells you exactly what to change your call to to fix the error.
