### ISSUE TITLE
make update-theos fails due to missing update-git-repo script.

### ISSUE THREAD

**Issue by leftyfl1p** [theos/theos#290]
What are the steps to reproduce this issue?
-------------------------------------------
1. run `make update-theos` inside a project.

What happens?
-------------
The update fails in an unfinished state due a script that no longer exists. Projects cannot be built as a result.

What were you expecting to happen?
----------------------------------
The update to succeed.

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/4qz2b

Any other comments?
-------------------
...

What versions of software are you using?
----------------------------------------
**Operating System:** OSX 10.12.6

**Toolchain Version:** Xcode 9.2

**SDK Version:** 9.3

**Comment by kirb** [comment]
Erp. Dammit.

I'll have to bring back `update-git-repo` as a script that calls `update-theos`, somehow. (I should have just implemented the updater entirely as a shell script in the first place…)

**Comment by kirb** [comment]
Fixed in 5b65888, although it’ll cause submodules to not be updated, which kinda sucks, but I don’t really think there’s any good options to prevent that.
