### ISSUE TITLE
git issue: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1

### ISSUE THREAD

**Issue by iOSGods** [theos/theos#293]
I understand this isn't a theos specific issue, rather a GitHub one but it's affecting a lot of new users that are trying to setup theos on their iDevices. From what I know, Saurik did update **APT 0.7 Strict (lib)** to fix this issue, but it's still present. I tried on 2 devices & a few others have tested also.

What are the steps to reproduce this issue?
-------------------------------------------
1. Run the **git clone --recursive https://github.com/theos/theos.git $THEOS** command on any iOS terminal.

What happens?
-------------
Theos fails to clone and we're are presented with this error instead:
 git clone --recursive https://github.com/theos/theos.git /var/theostest
Cloning into '/var/theostest'...
fatal: unable to access 'https://github.com/theos/theos.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Apologies if this shouldn't be here. Remove/Mark as solved if so. 

Thank you! :)

**Comment by kirb** [comment]
The fix for APT only fixes APT. Git isn’t APT.

This… sucks. Looks like an OpenSSL update is needed now.

**Comment by iOSGods** [comment]
My bad. I just based it off reading your Tweet and thought it was related. https://twitter.com/hbkirb/status/968597962103300096

Yeah... it does.

**Comment by iOSGods** [comment]
Is there a suggested way of installing it manually while we wait for this to be fixed?

**Comment by kirb** [comment]
Best/easiest thing I can think of is to clone it somewhere else (Mac, Cygwin, etc.) and use `rsync` to copy everything to your phone. Make sure file permissions and symlinks are retained; `scp` won’t do that.

**Comment by iOSGods** [comment]
Thank you, kirb! I cloned it to a Mac and then used rsync to copy it over to my iDevice and now it works fine.

**Comment by kirb** [comment]
Update on this: @uroboro spoke to saurik and he’s working on it.

**Comment by iOSGods** [comment]
@kirb Any other updates on this? :)

**Comment by ipadkid358** [comment]
@sbingner has updated git for iOS on http://repo.bingner.com/

**Comment by sbingner** [comment]
If you load that you may need my curl also.  I think coolstar released a curl with a newer version so you may need to “downgrade” to load it.

**Comment by XxDdosingDosaxX** [comment]
@sbingner I installed your git and curl and when I try git clone --recursive https://github.com/theos/theos.git it says dyld: lazy symbol binding failed:Symbol not found: _clock_gettime
Refrenced from: /usr/libexec/git-core/git
Expected in: dyld shared cache

**Comment by sbingner** [comment]
Which iOS version are you on, and are you sure it is my curl and git?  I thought I had the iOS version requirements proper on both but I may need to go back and check again.  I was trying to make everything work to iOS2 for armv6 but I may not have tested every iOS for arm64

**Comment by XxDdosingDosaxX** [comment]
Hi, thanks for responding. I'm on ios 9.0.2 and I installed both from your repo. Thanks.

**Comment by isupport3r** [comment]
sh: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]

**Comment by lyqflnh** [comment]
@sbingner I have the same problem @XxDdosingDosaxX had. 

My device is iOS 9.1

@XxDdosingDosaxX Did you find the solution for git?

**Comment by XxDdosingDosaxX** [comment]
Nope. I have still been waiting for a fix. Would really appreciate it @sbingner if you could double check the requirements.

**Comment by sbingner** [comment]
I just updated that git with one that forced no clock_gettime - tested it working on iOS 9.0.1

**Comment by kirb** [comment]
I’ll close this as interest in the Telesphoreo platform is significantly reduced now - Git works fine on Elucubratus and Electra/Chimera. Anyone who encounters this should still find this thread via Google.
