### ISSUE TITLE
IO::Compress::Lzma can't found

### ISSUE THREAD

**Issue by tahadarendeli** [theos/theos#301]
What are the steps to reproduce this issue?
-------------------------------------------
1. $THEOS/bin/update-theos
2. or $ make update-theos

What happens?
-------------
$THEOS/bin/update-theos
Fetching origin
Already up-to-date.

===============================================================================

The Perl module IO::Compress::Lzma needs to be installed. For more information, refer to https://github.com/theos/theos/wiki/Installation#prerequisites.

What were you expecting to happen?
----------------------------------
Already up-to-date.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
due to this missing dependency "make: *** No rule to make target `update-theos'.  Stop." shown on the terminal. I install lzma and other stuff directly to the guide. Also checked the other issue but didn't find the solution. Have can i make theos see the lzma?

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS High Sierra

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
`make update-theos` only works from within the same directory as a Theos project makefile. (That's why I changed it to a script you can call from anywhere.)

You did install the module using cpan, right? You can test whether it works by running `$THEOS/bin/dm.pl`. It should give you a help message, and shouldn't complain about not finding the module.

**Comment by tahadarendeli** [comment]
this is the output:

Can't locate Compress/Raw/Lzma.pm in @INC (you may need to install the Compress::Raw::Lzma module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Library/Perl/5.18/IO/Compress/Adapter/Lzma.pm line 9.
BEGIN failed--compilation aborted at /Library/Perl/5.18/IO/Compress/Adapter/Lzma.pm line 9.
Compilation failed in require at /Library/Perl/5.18/IO/Compress/Lzma.pm line 11.
BEGIN failed--compilation aborted at /Library/Perl/5.18/IO/Compress/Lzma.pm line 11.
Compilation failed in require at /Users/tahadarendeli/theos/bin/dm.pl line 12.
BEGIN failed--compilation aborted at /Users/tahadarendeli/theos/bin/dm.pl line 12.

**Comment by tahadarendeli** [comment]
I solve this issue by myself. As i figured out IO::Compress::Lzma cannot be installed because of dependency  of Compress::Raw::Lzma . Compress::Raw::Lzma not be installed because it gives lzma.h not found error. To provide lzma.h file i deleted xz brew package and installed again. Then it works now.
