### ISSUE TITLE
theos make package error

### ISSUE THREAD

**Issue by 1DI4R** [theos/theos#304]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1.cd /opt/projects/test
2.export THEOS=/opt/theos
3. make package

What happens?
-------------
getting lots of errors

What were you expecting to happen?
----------------------------------
compiling test tweak

Any logs, error output, etc?
----------------------------
i get these errors
https://ghostbin.com/paste/35jna

Any other comments?
-------------------
Pls Help How I can Fix it :(

What versions of software are you using?
----------------------------------------
**Operating System:** windows 10 

**Toolchain Version:** lastest version from CoolStar

**SDK Version:** 11.2 SDKS

**Comment by Gh0stByte** [comment]
Try using this [sdk](https://twitter.com/coolstarorg/status/695014029601865728?lang=en)

**Comment by mstg** [comment]
If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)
