### ISSUE TITLE
Error building prefix & os | Windows 10 Linux Subsystem

### ISSUE THREAD

**Issue by Gh0stByte** [theos/theos#305]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos on Windows Linux Subsystem with this [tutorial](https://gist.github.com/JohnCoates/ea7b8002b77ab7c1c758384e55538603)
2. Create a test tweak
3. run `make package`

What happens?
-------------
The tweak does not compile, and errors are thrown

What were you expecting to happen?
----------------------------------
The tweak to compile without 

Any logs, error output, etc?
----------------------------
~~~~While building module 'os' imported from /opt/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:8:
/opt/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/log.h:17:2: error: using os/log.h requires Xcode 8 or later
#error using os/log.h requires Xcode 8 or later
 ^
In file included from <built-in>:1:
In file included from /opt/theos/Prefix.pch:32:
/opt/theos/vendor/include/_Prefix/HBLog.h:2:10: fatal error: could not build module 'os'
        #import <os/log.h>
         ~~~~~~~^
2 errors generated.
~~~~

Any other comments?
-------------------
A bypass it to comment out lines 
https://github.com/theos/theos/blob/ad06e90efb7927a80267483f2294d89addd586d6/makefiles/common.mk#L200-L201

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 Pro (1709)

**Toolchain Version:** unsure

**SDK Version:** iPhoneOS10.3.sdk

**Comment by kirb** [comment]
iOS 10 and newer SDKs aren’t supported with this toolchain. Use 9.3 or older.

**Comment by DuIslingr** [comment]
or just use cctools and forget coolstars toolchain 👌

**Comment by shane1027** [comment]
@DuIslingr can you elaborate on this?  I am on Arch Linux and would love to use the newer SDKs.

**Comment by kirb** [comment]
Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
