### ISSUE TITLE
ldid error with linux subsystem

### ISSUE THREAD

**Issue by Gh0stByte** [theos/theos#306]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos on Windows Linux Subsystem with this [tutorial](https://gist.github.com/JohnCoates/ea7b8002b77ab7c1c758384e55538603)
2. Create a test tweak
3. run `make package`

What happens?
-------------
The tweak does not compile, and errors are thrown while attempting to sign

What were you expecting to happen?
----------------------------------
The tweak to compile without 

Any logs, error output, etc?
----------------------------
~~~~
ldid.cpp(1286): _assert(false); errno=5
~~~~

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 Pro (1709)

**Toolchain Version:** ios-toolchain_clang+llvm+ld64_latest_linux_x86_64.zip 

**SDK Version:** iPhoneOS9.2.sdk

**Comment by DuIslingr** [comment]
You need to use the wsl branch

**Comment by mstg** [comment]
There has been no follow up, so I assume it's resolved

---

If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)
