### ISSUE TITLE
Unable to find PrivateFrameworks

### ISSUE THREAD

**Issue by ZaneH** [theos/theos#311]
What are the steps to reproduce this issue?
-------------------------------------------
1. Include *_PRIVATE_FRAMEWORKS = PhotoLibrary
2. Ensure PhotoLibrary directory exists within $THEOS/include and / or the SDK PrivateFrameworks folder
3. make package install

What happens?
-------------
```
$ make package install
> Making all for tweak Unsplash2…
==> Linking tweak Unsplash2 (armv7)…
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/PrivateFrameworks'
ld: framework not found PhotoLibrary
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/zane/repos/unsplash2/.theos/obj/debug/armv7/Unsplash2.dylib] Error 1
make[2]: *** [/Users/zane/repos/unsplash2/.theos/obj/debug/armv7/Unsplash2.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [Unsplash2.all.tweak.variables] Error 2
```

What were you expecting to happen?
----------------------------------
$THEOS should've seen the PhotoLibrary directory inside $THEOS/include/PrivateFrameworks.

Any logs, error output, etc?
----------------------------
(posted above)

What versions of software are you using?
----------------------------------------
**Operating System:** macOS

**Toolchain Version:** Latest

**SDK Version:** iOS 11.1.2

**Comment by kirb** [comment]
include is only for headers, used by the compiler. Binaries or `.tbd`s you want to link against go in lib.

You need to install a patched SDK, which you can get by downloading from https://github.com/theos/sdks and installing to $THEOS/sdks/. As you’re using Xcode 9.3 which includes the iOS 11.3 SDK but the latest patched SDK is 11.2, you’ll need to add to the top of your makefile:

```make
```
