### ISSUE TITLE
make package Error 

### ISSUE THREAD

**Issue by Packetfahrer** [theos/theos#314]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. make package 

What happens?

/usr/local/opt/theos/makefiles/instance/library.mk:32: *** missing separator.  Stop.
make[3]: *** [/Users/renekahle/Tweaks2/dimme/.theos/obj/armv7/DimMe9.dylib] Error 2

What versions of software are you using?
----------------------------------------
macOS High Sierra
theos 2.4
Xcode9.3

**Comment by kirb** [comment]
Are you sure you’re on the latest commit? This should have been fixed in 54dcd44.

**Comment by Packetfahrer** [comment]
I didn't see this thanks.
