### ISSUE TITLE
how to set cflag and cxx flag

### ISSUE THREAD

**Issue by mwpcheung** [theos/theos#315]
when I set name_CFLAGS += -std=gnu99. the complier says "'-std=gnu99' not allowed with 'Objective-C++'"

when I set name_CFLAGS += std=c++14.  there are many errors. my project has

*.xm files
*.mm files
*.m  files

I want compile the *.m file with "gnu99" and 
*.mm file with c++14. 

is there anyway to solve it?

**Comment by mwpcheung** [comment]
I've tried to set 
name_CCFLAGS += -std=c++14
name_CFLAGS += gnu99
it does not work.  

CFLAGS works very well. And  I've drag the *.m files to xcode lib project and compiled to a static library and then link to my tweak successfully.

**Comment by kirb** [comment]
The CFLAGS value should be `-std=gnu99`. What error output do you get?

**Comment by mwpcheung** [comment]
many other errors. 
![image](https://user-images.githubusercontent.com/5516920/39092754-5188d08c-45da-11e8-9817-bc24661c87d4.png)
 these files are compiled in xcode with gnu99  well.

the project is from https://github.com/zwopple/PocketSocket

the original setting in the xcode project is :
![image](https://user-images.githubusercontent.com/5516920/39092776-9879dd9c-45da-11e8-88b3-78bea0b45952.png)

**Comment by mwpcheung** [comment]
It's very easy to build the project  to a static library with xcode.
I've tried many ways to build with theos makefile. 
Failed.

**Comment by mwpcheung** [comment]
Changing the C dialect solved

**Comment by LittleLydia** [comment]
> Changing the C dialect solved

how to change the C dialect in Makefile, what's the right code, tried suggestions above but failed.~~

**Comment by EchoSkill** [comment]
> CXXFLAGS is called CCFLAGS in Theos (the name is carried over from GNUstep Make). CFLAGS applies to both (Obj)C and (Obj)C++. If you want to set `-std=c++14`, use CCFLAGS. This will override Theos’s default of `c99`. I’m not certain but setting your CFLAGS to include `-std=gnu99` and CCFLAGS to include `-std=c++14` should work.

this helps me a lot, with latest theos update!!, thank you so much!
