### ISSUE TITLE
How to get the version of deb?

### ISSUE THREAD

**Issue by onezens** [theos/theos#316]
How to get the version of deb?

Example my control file, in the code get the  `Name: pluginVersion: 1.0.31`
```
Package: cc.onezen.plugin
Name: pluginVersion: 1.0.31
Architecture: iphoneos-arm
Description:plugin
Maintainer:plugin
Author: wz
Section:  stage
```

**Comment by kirb** [comment]
I’m not very clear on what you’re asking… it sounds like an [XY problem](http://xyproblem.info/). What are you actually trying to achieve?

Theos provides the package version in `$(PACKAGE_VERSION)` in Make, and `$(THEOS_PACKAGE_BASE_VERSION)` for the original version as seen in your control file without the build number, `+debug`, etc. included. There is also the `.theos/last_package` file containing the filename of the latest package built.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
