### ISSUE TITLE
iphone/tool application cannot work in iOS 11.

### ISSUE THREAD

**Issue by wuqingtao** [theos/theos#317]
I installed the latest-version theos.
I made a iphone/tool application named "dddd". When i installed it to my jailbroken iphone6 (iOS 11), and ran it through the command line, it quickly gave me "Killed".
Actually it work well in iphone6 (iOS 10.2).

qingtaoteki-iPhone:~ mobile$ dddd
Killed
qingtaoteki-iPhone:~ mobile$ 

Here is Makefile:
ARCHS = arm64
TARGET = iphone:latest:11.0

include $(THEOS)/makefiles/common.mk

TOOL_NAME = dddd
dddd_FILES = main.mm

include $(THEOS_MAKE_PATH)/tool.mk

control:
Package: com.yourcompany.dddd
Name: dddd
Depends: 
Version: 0.0.1
Architecture: iphoneos-arm
Description: An awesome tool of some sort!!
Maintainer: qingtao wu
Author: qingtao wu
Section: System
Tag: role::hacker

main.mm
int main(int argc, char **argv, char **envp) {
	return 0;
}

// vim:ft=objc

thanks
qingtao

**Comment by uroboro** [comment]
This is an issue about the jailbreak you're using. I'm not well versed with this season of jailbreaks but you need to add extra entitlements for your binaries to work.

**Comment by wuqingtao** [comment]
thanks to @ueoboro, i will try to verify my jailbreak tool, and tanks ag.

**Comment by wuqingtao** [comment]
Thanks to @uroboro 
i solved the issue by doing this:
make
ldid -Sent.xml .theos/obj/debug/dddd
make package install

and ent.xml is:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>platform-application</key>
        <true/>
    </dict>
</plist>

**Comment by ipadkid358** [comment]
@wuqingtao Theos provides the following variable: `CODESIGN_FLAGS`

See this example `Makefile`: https://github.com/ipadkid358/FlexToTheos/blob/ab3ecae2428ffc97c541f2959423d78ee6bebbbb/Makefile#L8
(The `-I` argument is not needed)

**Comment by wuqingtao** [comment]
@ipadkid358 That's GREAT!
Thanks!
