### ISSUE TITLE
Flag -FINALPACKAGE=1 breaks my preference bundle

### ISSUE THREAD

**Issue by rudikelly** [theos/theos#318]
What are the steps to reproduce this issue?
-------------------------------------------
I have a preference bundle with multiple PSSwitchCells and PSSliderCells, and a libcolorpicker cell. Works without finalpackage flag but not with

What happens?
-------------
Settings app crashes and no preference bundles are visible until I respring

What were you expecting to happen?
----------------------------------
The reference bundle to open

Any logs, error output, etc?
----------------------------
Settings app crash log (submitted by user) https://pastebin.com/Sv3tX6Nn

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
iOS 11, tested on 11.0, 11.1 and 11.2, all have same issue

11.3 sdk

**Comment by kirb** [comment]
This looks a lot like a bug in libcolorpicker and not at all related to Theos? Does this consistently happen for everyone?

Electra’s TweakInjector disables all tweaks on next launch after a crash. Quitting and relaunching the app will enable tweaks again.

**Comment by rudikelly** [comment]
No I’m just saying whatever theos does behind he scenes when using finalpackage breaks support for libcolorpicker

**Comment by kirb** [comment]
Does this consistently happen for everyone?

**Comment by rudikelly** [comment]
honestly, no idea. i’m not aware of anyone else using libcolorpicker on ios 11

**Comment by jontelang** [comment]
If you upload a deb or the source maybe someone (maybe even me) could test it out. I've got a 11.0.3 jb device for example to try on. Deb is preferred.

**Comment by DHowett** [comment]
FINALPACKAGE, I believe, disables DEBUG and disabling DEBUG enables optimizations. This just sounds like a classic “my code has some undefined behavior and the optimizer has a heyday with it” issue.

Can you try with `make FINALPACKAGE=1 OPTFLAG=-O0`?

**Comment by rudikelly** [comment]
Sorry for the late reply. Still breaks with`OPTFLAG=-O0`

**Comment by uroboro** [comment]
For people still bumping onto this "issue", the root of problem is that Foundation loads plists into memory as mutable or immutable dictionaries depending on the storage format. Apparently XML property lists are loaded into mutable dictionaries while binary ones are loaded into immutable ones.

Theos will optimize xml plists into binary ones when building a release package. 

Still, it is not a problem of Theos but of libcolorpicker.

https://github.com/atomikpanda/libcolorpicker/blob/193df0a1f566aaeb9f1d238b921ee7a098684043/PFSimpleLiteColorCell.mm#L29-L31

It incorrectly treats an NSDictionary (the one returned by `[self.specifier properties][@"libcolorpicker"]`) as NSMutableDictionary and later attempts to set a key-value pair:

https://github.com/atomikpanda/libcolorpicker/blob/193df0a1f566aaeb9f1d238b921ee7a098684043/PFSimpleLiteColorCell.mm#L36

So while a tweak uses an xml format in debug mode libcolorpicker will incorrectly not break but will as soon as a release package is made.

**Comment by rudikelly** [comment]
Agreed, this is a non-issue. An easy fix was available at the time of me opening this issue that i overlooked, but thanks for the explanation. :D

**Comment by uroboro** [comment]
If anything, file an issue on their repository, otherwise people will be releasing debug versions of their tweaks and incorrectly blame Theos like it happened here.
