### ISSUE TITLE
Compiler Exiting

### ISSUE THREAD

**Issue by tarekbahie** [theos/theos#319]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
after installing theos and all dependencies, i run the $THEOS/bin/nic.pl and choosing 11 to make a tweak
i then use cygwin to access the new tweak folder. Then use the "make package" command.

What happens?
> Making all for tweak youtube…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7)…
bash: /opt/theos/toolchain/windows/iphone/bin/armv7-apple-darwin11-clang++: No such file or directory
make[3]: *** [/opt/theos/makefiles/instance/rules.mk:250: /opt/projects/youtube/.theos/obj/debug/armv7/Tweak.xm.7fd0fb61.o] Error 127
rm /opt/projects/youtube/.theos/obj/debug/armv7/Tweak.xm.mm
make[2]: *** [/opt/theos/makefiles/instance/library.mk:33: /opt/projects/youtube/.theos/obj/debug/armv7/youtube.dylib] Error 2
make[1]: *** [/opt/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2
make: *** [/opt/theos/makefiles/master/rules.mk:123: youtube.all.tweak.variables] Error 2

What were you expecting to happen?
create the .deb file

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 7 32 bit

**Toolchain Version:** iOSToolchain4Win

**SDK Version:** 9.3

**Comment by kabiroberai** [comment]
This might be related to 857495d. Please run `make troubleshoot` in your project and paste the ghostbin link here.

**Comment by kirb** [comment]
Have you installed the toolchain to `$THEOS/toolchain/windows/iphone/`? Like this:

```
git clone -b master https://github.com/coolstar/iOSToolchain4Win.git $THEOS/toolchain/windows/iphone/
```

If you downloaded the repo as a ZIP, you most likely lost the symlinks. `armv7-apple-darwin11-clang++.exe` is a symlink to `armv7-apple-darwin11-clang.exe`. Windows-based tools like Explorer and WinRAR won’t preserve symlinks; you need to use Git from within Cygwin.

Also be aware that the toolchain for 32-bit Windows is very old. You’d be limited to using the iOS 8.4 or older SDK, and might have trouble building newer code. You may want to consider using Theos on your iPhone/iPad instead.

**Comment by tarekbahie** [comment]
Is it stable to use Theos on a jailbroken Iphone 7 iOS 11.0.1 ?

**Comment by kirb** [comment]
Yes. See [our instructions](https://git.io/theosinstall), and download Make + Perl from http://repo.bingner.com/.

Closing as this is probably not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
