### ISSUE TITLE
SYSROOT issue

### ISSUE THREAD

**Issue by Lucaiii** [theos/theos#321]
I'm trying to compile Apex 2 for ios 10.3.1, and i continuously get this

sh-3.2# make
==> Error: Your current SYSROOT, “/Users/owenwatts/Downloads/Apex-dev/sdks/iPhoneOS10.3.sdk”, appears to be missing.
make: *** [before-all] Error 1

my SDK is in the right place, i'm pretty sure I've declated the $(THEOS) variable correctly and have read write perms to it
export PATH
export THEOS=/opt/theos
export PATH=$THEOS/bin:$PATH
export THEOS_DEVICE_IP=[REDACTED] THEOS_DEVICE_PORT=[REDACTED]
export THEOS_MAKE_PATH=/opt/theos/makefiles 

heres the declaration of sysroot ive got

export SDKVERSION = 10.3
export SYSROOT = $(THEOS)/sdks/iPhoneOS10.3.sdk
export TARGET = iphone:clang:10.3:10.3

help appreciated, thanks

**Comment by ipadkid358** [comment]
where are these exports? in the shell? if not, where in the Makefile are they?

I would recommend exporting the following variables externally (in your shell or in `~/.theosrc`):
`THEOS` (this needs to be in your shell, not `~/.theosrc`)
`THEOS_DEVICE_IP`
`THEOS_DEVICE_PORT`

The following variables can be exported in either of the locations above, or in the `Makefile`:
`TARGET`

I don't recommend exporting any of the other variables that you mentioned that I did not

**Comment by Lucaiii** [comment]
the exports are in my .bash_profile file

**Comment by ipadkid358** [comment]
Be sure to `source ~/.bash_profile` if you've made changes without restarting the shell

**Comment by kirb** [comment]
Closing as this is an old thread and probably not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
