### ISSUE TITLE
Theos gives this error when I try to make package: xcrun: error: SDK “iphoneos” cannot be located

### ISSUE THREAD

**Issue by Patrickk17** [theos/theos#322]
What are the steps to reproduce this issue?
-------------------------------------------
1. Pick template with theos
2. Cd into tweak folder
3. Make package

What happens?
It spams like 60 error messages that say the same thing: xcrun: error: SDK “iphoneos” cannot be located

What were you expecting to happen?
I expected that it would make my package into a .deb file or whatever else it usually does.

Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** macOS High Sierra version 10.13.3

**Toolchain Version:** Latest version

**SDK Version:** 9.3, 10.3, 11.2

**Comment by kirb** [comment]
Seems this happens with Xcode 9 or macOS 10.13 if you previously had the standalone Command Line Tools package installed. Open Xcode and go to Preferences, then Locations, and make sure the command line tools is set to the version of Xcode you’re using.

**Comment by pranavjandial123** [comment]
Thanks a lot @kirb 
This worked for me.

**Comment by kirb** [comment]
Closing due to lack of response from the original poster.

**Comment by arunkarka** [comment]
This worked for me.  In Preferences->Locations, Command Line tools wasn't pointing to any thing.  
I clicked on the dropdown, selected the only option I had "Xcode 10.1 (/Applications/Xcode.app).  And the above error vanished.

**Comment by otaviopace** [comment]
It worked out great! ❤️

**Comment by linvix-sistemas** [comment]
@kirb , Work for me!
Thank you!!

**Comment by SmoshySmosh** [comment]
`sudo xcode-select --reset` works to resolve this issue.

**Comment by ProdigyView** [comment]
> sudo xcode-select --reset

Actually, this solved my issue. I installed command line tools without XCode, stuff broke. So when I installed XCode, the reset worked.

**Comment by LoneDespair** [comment]
> `sudo xcode-select --reset` also works to resolve this issue.

Thank you, worked flawlessly on me
