### ISSUE TITLE
syntax error in expression (error token is "(,1,)")

### ISSUE THREAD

**Issue by klmitchell2** [theos/theos#323]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create new theos project
2. `make package install`
3. …

What happens?
-------------
`/var/root/theos/bin/install.exec: line 2: [[: if (,1,): syntax error in expression (error token is "(,1,)")`

What were you expecting to happen?
----------------------------------
Preferably not get this error and that the tweak (simple alert view shown) will work. 

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
```
dpkg-deb: building package 'com.yourcompany.helloworld' in './packages/com.yourcompany.helloworld_0.0.1-11+debug_iphoneos-arm.deb'.
==> Installing…
/var/root/theos/bin/install.exec: line 2: [[: if (,1,): syntax error in expression (error token is "(,1,)")
(Reading database ... 9308 files and directories currently installed.)
Preparing to unpack .../com.yourcompany.helloworld_0.0.1-11+debug_iphoneos-arm.deb ...
Unpacking com.yourcompany.helloworld (0.0.1-11+debug) over (0.0.1-9+debug) ...
Setting up com.yourcompany.helloworld (0.0.1-11+debug) ...
install.exec "killall -9 SpringBoard"
/var/root/theos/bin/install.exec: line 2: [[: if (,1,): syntax error in expression (error token is "(,1,)")
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 11.0.3

**Toolchain Version:** Latest version

**SDK Version:** 11.0

**Comment by uroboro** [comment]
Can you share your Makefile? (I would recommend installing Theos in /var/mobile while logged as mobile instead of /var/root while logged as any user)

**Comment by klmitchell2** [comment]
Heres my Makefile

```
ARCHS = armv7 armv7s arm64
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = HelloWorld
HelloWorld_FILES = Tweak.xm
HelloWorld_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk

after-install::
	install.exec "killall -9 SpringBoard"
```

**Comment by uroboro** [comment]
Do you have a `~/.theosrc` file or a `~/.bach_profile` (or equivalent) with exported Theos variables?

**Comment by klmitchell2** [comment]
I have a ~/.profile which looks like this: 

```
export THEOS=/var/mobile/theos
alias theos='$THEOS/bin/nic.pl'
```

**Comment by uroboro** [comment]
That's ok (not sure about aliasing nic as "theos"). Notice that the error you posted in the OP references `/var/root/theos` while your `~/.profile` has `/var/mobile/theos`. Please make sure that you have only one installation and it is located at `/var/mobile/theos`.

**Comment by klmitchell2** [comment]
I was in the middle of moving theos over, thats why the paths did not patch up. They do now (and did before).

**Comment by uroboro** [comment]
Do you have `sudo` installed?

**Comment by klmitchell2** [comment]
Just downloaded it

**Comment by uroboro** [comment]
No, just try installing again, does it fail with the same error?

**Comment by klmitchell2** [comment]
yeah same error

**Comment by uroboro** [comment]
I'm running out of ideas. Can you do `make clean do messages=yes`?

**Comment by klmitchell2** [comment]
Still getting this: 

```
/var/mobile/theos/bin/install.exec: line 2: [[: if (,1,): syntax error in expression (error token is "(,1,)")
(Reading database ... 9409 files and directories currently installed.)
Preparing to unpack .../com.yourcompany.test_0.0.1-5+debug_iphoneos-arm.deb ...
Unpacking com.yourcompany.test (0.0.1-5+debug) over (0.0.1-4+debug) ...
Setting up com.yourcompany.test (0.0.1-5+debug) ...
install.exec "killall -9 SpringBoard"
/var/mobile/theos/bin/install.exec: line 2: [[: if (,1,): syntax error in expression (error token is "(,1,)")
```

**Comment by kirb** [comment]
This should have been fixed a while ago.
