### ISSUE TITLE
Can not compile tweak project with .x file when using MSHookIvar inside

### ISSUE THREAD

**Issue by ienthach** [theos/theos#324]
What are the steps to reproduce this issue?
-------------------------------------------
1. create tweak project with NIC.pl
2. write some code with MSHookIvar used
3. rename tweak.xm to tweak.x
4. edit Makefile to compile tweak.x

What happens?
-------------
 i use MSHookIvar in tweak. If the file is tweak.xm, the project is compiled, but if i change to tweak.x compile with error 

tweak.xm:

%hook ClassName

-(void) viewDidLoad{
	id ButtonPresenter = MSHookIvar<id>(self, "presenter");
	NSLog(@"get instance %@", ButtonPresenter);
	return %orig;
}
%end

What were you expecting to happen?
----------------------------------
it can be compiled when the file name is tweak.x

Any logs, error output, etc?
----------------------------
> Making all for tweak HelloWorld…
==> Preprocessing HelloWorld.x…
==> Compiling HelloWorld.x (arm64)…
HelloWorld.x:3533:43: error: unexpected type name 'id': expected expression
    id ButtonPresenter = MSHookIvar<id>(self, "presenter");
                                          ^
HelloWorld.x:3533:32: error: use of undeclared identifier 'MSHookIvar'
    id ButtonPresenter = MSHookIvar<id>(self, "presenter");
                               ^
HelloWorld.x:3533:47: error: expression result unused [-Werror,-Wunused-value]
    id ButtonPresenter = MSHookIvar<id>(self, "presenter");

Any other comments?
-------------------
I noticed about File Extensions for Logos at http://iphonedevwiki.net/index.php/Logos, i dont know how to fix

What versions of software are you using?
----------------------------------------
**Operating System:** macos 10.3.3

**Toolchain Version:** lastest theos

**SDK Version:** 10.1

**Comment by uroboro** [comment]
There's at least two issues here. First, `MSHookIvar` is defined as either a C++ template or a macro (which expands to said template). As such, you have to use a C++ file extension for Theos to handle it as a C++ file. So, you have to use .xm instead of .x.

The second issue is your usage of `MSHookIvar`:

>     MSHookIvar(self, "presenter");

It is defined like this:

    template <typename Type_>
    static inline Type_ &MSHookIvar(id self, const char *name) {
    ...

and

    #define MSIvarHook(type, name) \
        type &name(MSHookIvar<type>(self, #name))

So you didn't use either properly.

**Comment by ienthach** [comment]
Thank you, the second is my mistake. 

Is there any chance for me to use MSHookIvar in .x file extension?

**Comment by uroboro** [comment]
From its definition, no. Is there an impediment in your project to using .xm?

**Comment by ienthach** [comment]
Yes, i have. 

I hook to 
> CFStringRef CTRegistrationCopyServiceProviderName(CFAllocatorRef allocator);
and
> CFStringRef CTRegistrationCopyLocalizedOperatorName(CFAllocatorRef allocator);

and get compile error with 

```
Undefined symbols for architecture arm64:
  "CTRegistrationCopyServiceProviderName(__CFAllocator const*)", referenced from:
      _logosLocalCtor_4f5a97cf(int, char**, char**) in Tweak.xm.9c81295e.o
  "CTRegistrationCopyLocalizedOperatorName(__CFAllocator const*)", referenced from:
      _logosLocalCtor_4f5a97cf(int, char**, char**) in Tweak.xm.9c81295e.o
ld: symbol(s) not found for architecture arm64
```

although i have xxx_FRAMEWORKS = CoreTelephony in Makefile. that only compiled and work fine with .x file extension.

**Comment by ienthach** [comment]
here my helloworld codes 
https://ghostbin.com/paste/ywcbu

**Comment by ienthach** [comment]
@kirb @uroboro thank you so much, you guyz save my day.
