### ISSUE TITLE
Makefile:11 compile error

### ISSUE THREAD

**Issue by th0ex** [theos/theos#326]
when i compile ipa "make package" it give this error:

_**Makefile:11: theos/makefiles/application.mk: No such file or directory
make: ***  no rules to generate the goal"theos/makefiles/application.mk".  stop.**_

(I translate the text from italian to english)

my Makefile:

**_include $/theos/makefiles/common.mk
ARCHS = arm64
APPLICATION_NAME = aurora
aurora_FILES = main.m AuroraAppDelegate.m AuroraRootViewController.m
aurora_FRAMEWORKS = UIKit CoreGraphics
include $/theos/makefiles/application.mk_**

I try with this makefile:

**_include $(THEOS)/makefiles/common.mk
ARCHS = arm64
APPLICATION_NAME = aurora
aurora_FILES = main.m AuroraAppDelegate.m AuroraRootViewController.m
aurora_FRAMEWORKS = UIKit CoreGraphics
include $(THEOS_MAKE_PATH)/application.mk_**

and this makefile:

**_include $theos/makefiles/common.mk
ARCHS = arm64
APPLICATION_NAME = aurora
aurora_FILES = main.m AuroraAppDelegate.m AuroraRootViewController.m
aurora_FRAMEWORKS = UIKit CoreGraphics
include $theos/makefiles/application.mk_**

**Comment by uroboro** [comment]
`ARCHS` has to be both above the `common.mk` include and exported (`export ARCHS = ...`).

The second makefile is the one using the Theos variable correctly. It's `$(THEOS)`. It should be exported in the environment like the installation instructions say.

**Comment by kirb** [comment]
`$theos` isn’t valid syntax in Make, and `$/theos` isn’t valid anywhere. Bash and similar shells use `$THEOS` while Make uses `$(THEOS)`. You shouldn’t ever need to change the `include` lines after you generate a project with NIC.

Please double check the [installation instructions](https://github.com/theos/theos/wiki/Installation#installation) — you might have missed the first part about setting the $THEOS variable in `.bash_profile`.

Closing as I don’t think this is a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
