### ISSUE TITLE
gcc-g++ command not found

### ISSUE THREAD

**Issue by iBootDev** [theos/theos#327]
this happens when i type make package to make one tweak on arch linux
help me please

$make package
> Making all for tool testando…
==> Compiling main.mm…
bash: gcc-g++: command not found 
make[2]: *** [/home/iboot/theos/makefiles/instance/rules.mk:181: /home/iboot/developing/projetos/testando/.theos/obj/linux/debug/main.mm.4f517ab1.o] Error 127
make[1]: *** [/home/iboot/theos/makefiles/instance/tool.mk:11: internal-tool-all_] Error 2
make: *** [/home/iboot/theos/makefiles/master/rules.mk:123: testando.all.tool.variables] Error 2
========================================================================
MakeFile: 
export THEOS_DEVICE_IP = 192.168.0.100
export THEOS_DEVICE_PORT = 22
export TARGET = linux:gcc:8.0:8.0
ARCHS = armv7 arm64
TARGET_IPHONEOS_DEPLOYMENT_VERSION = 8.0

include /home/iboot/theos/makefiles/common.mk

TOOL_NAME = testando
testando_FILES = main.mm

include /home/iboot/theos/makefiles/tool.mk
========================================================================
Operating System:Arch Linux
SDK Version:8.0

**Comment by kirb** [comment]
Closing due to lack of response.
