### ISSUE TITLE
Issue When Compiling

### ISSUE THREAD

**Issue by Ezb2661** [theos/theos#328]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create new Theos project (App/Tweak etc.)
2. Run "make package"

What happens?
-------------

Is unable to find Foundation/Foundation.h file.

What were you expecting to happen?
----------------------------------

The project to be compiled

Any logs, error output, etc?
----------------------------

```> Making all for tweak TestTweak…
==> Compiling Tweak.xm (armv7)…
In file included from <built-in>:1:
/home/ezb2661/theos/Prefix.pch:11:25: fatal error: 'Foundation/Foundation.h' file not found
                #import <Foundation/Foundation.h>
                        ^
1 error generated.
/home/ezb2661/theos/makefiles/instance/rules.mk:249: recipe for target '/home/ezb2661/projects/testtweak/.theos/obj/debug/armv7/Tweak.xm.e0320735.o' failed
make[3]: *** [/home/ezb2661/projects/testtweak/.theos/obj/debug/armv7/Tweak.xm.e0320735.o] Error 1
/home/ezb2661/theos/makefiles/instance/library.mk:32: recipe for target '/home/ezb2661/projects/testtweak/.theos/obj/debug/armv7/TestTweak.dylib' failed
make[2]: *** [/home/ezb2661/projects/testtweak/.theos/obj/debug/armv7/TestTweak.dylib] Error 2
make[2]: *** Waiting for unfinished jobs....
==> Compiling Tweak.xm (arm64)…
In file included from <built-in>:1:
/home/ezb2661/theos/Prefix.pch:11:25: fatal error: 'Foundation/Foundation.h' file not found
                #import <Foundation/Foundation.h>
                        ^
1 error generated.
/home/ezb2661/theos/makefiles/instance/rules.mk:249: recipe for target '/home/ezb2661/projects/testtweak/.theos/obj/debug/arm64/Tweak.xm.5d6af2e0.o' failed
make[3]: *** [/home/ezb2661/projects/testtweak/.theos/obj/debug/arm64/Tweak.xm.5d6af2e0.o] Error 1
/home/ezb2661/theos/makefiles/instance/library.mk:32: recipe for target '/home/ezb2661/projects/testtweak/.theos/obj/debug/arm64/TestTweak.dylib' failed
make[2]: *** [/home/ezb2661/projects/testtweak/.theos/obj/debug/arm64/TestTweak.dylib] Error 2
/home/ezb2661/theos/makefiles/instance/library.mk:24: recipe for target 'internal-library-all_' failed
make[1]: *** [internal-library-all_] Error 2
/home/ezb2661/theos/makefiles/master/rules.mk:123: recipe for target 'TestTweak.all.tweak.variables' failed
make: *** [TestTweak.all.tweak.variables] Error 2
```
Any other comments?
-------------------
I am using debian subsystem

What versions of software are you using?
----------------------------------------
**Operating System:** Windows Debian Subsystem

**Toolchain Version:** ios-toolchain_clang+llvm+ld64_latest_linux_x86_64.zip

**SDK Version:** iPhoneOS11.2.sdk

**Comment by uroboro** [comment]
Did you unzip the sdk using Window's unzipping tools?

**Comment by Ezb2661** [comment]
I used WinRAR

**Comment by uroboro** [comment]
Yeah, don't. Unzip from within WSL and use the 9.2 SDK given that the current toolchain doesn't support SDK versions like 10 and 11.

**Comment by kirb** [comment]
Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
