### ISSUE TITLE
got killed: 9 when compile with FINALPACKAGE=1 (specially on iPhone SE)

### ISSUE THREAD

**Issue by cjsworld** [theos/theos#329]
What are the steps to reproduce this issue?
-------------------------------------------
1. create a tool project, make the binary's size large enough, like 478 KB in my case
2. connect a iPhoneSE, iOS10, make do FINALPACKAGE=1
3. run the tool over SSH, it may start properly
4. kill the process, run it again. Got Killed: 9 with no crash report
5. copy the binary with a new name, it can run again, but same as step 4
6. just make clean, make do. It is all fine!
7. other smaller binarys are working properly
8. the large binary has no problem on iPhone5S, iPhone6 (we have about 50 iPhoneSE, which all encounter this problem)
9. then i move the code to a lib, and the tool just a main() to invoke the lib, problem solved.

What happens?
-------------
the binary tool can not run twice, and produce a Killed: 9, when:
1. binary size large enough
2. iPhoneSE, iOS10
3. FINALPACKAGE=1

What were you expecting to happen?
----------------------------------
the binary tool can run properly

Any logs, error output, etc?
----------------------------
there is no log when Killed: 9, may be rejected by kernel?

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** iPhoneSE, iOS 10.0.2 - 10.2

**Toolchain Version:** latest 2118f8a

**SDK Version:** iPhoneOS11.2.sdk

**Comment by XMB5** [comment]
in the makefile, set application_CODESIGN_FLAGS = -Sent.xml and create the ent.xml file with entitlements

**Comment by uroboro** [comment]
Closing due to lack of response. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
