### ISSUE TITLE
Suggestion: Strip DOS return characters from control file

### ISSUE THREAD

**Issue by clubby789** [theos/theos#331]
I did most of a tweak I made in Notepad through cyberduck, and I later wasted around 2 hours trying to work out why compilation was failing. It would be nice to automatically strip the DOS characters from files.

**Comment by kirb** [comment]
We won’t be automatically fixing line endings because it could be a symptom of other issues. You’re building for a Unix(-alike) platform so you should be using Unix line endings. That said, there should be communication about this, so I’ve done that in theos/dm.pl@60af184.

**Comment by kirb** [comment]
Notepad doesn’t have any support for converting line endings (in fact it [only just](https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/) got support for displaying files with Unix endings correctly!). You need to use pretty much any proper code editor (Notepad++, Sublime, VSCode, etc) which usually has it somewhere in the menus or the bottom status bar. Cyberduck might have an option somewhere to change line endings to Unix while uploading and Windows when downloading.

You might also want to consider using [rmate](https://github.com/aurora/rmate). This lets you run `rmate myfile.m` in SSH to have the file seamlessly copied to your PC for you to edit, then copied back every time you save. There’s [rsub](https://github.com/henrikpersson/rsub) for Sublime, [Remote VSCode](https://marketplace.visualstudio.com/items?itemName=rafaelmaiolla.remote-vscode) for VSCode, etc. for your PC, and rmate is installed on the device. See [this tutorial](https://blog.cs.wmich.edu/sublime-text-putty-and-you/) if you use PuTTY.

**Comment by clubby789** [comment]
Thanks!
