### ISSUE TITLE
Error while trying to use make package install

### ISSUE THREAD

**Issue by chashmeetsingh** [theos/theos#332]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create a new tweak
2. run `make package install`
3. Asks for password enter and error

What happens?
-------------
root@192.168.1.100's password:
make: *** No rule to make target 'install'.  Stop.
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 750 package 'libmoorecon':
 missing maintainer
dpkg-deb: error: '/tmp/_theos_install.deb' is not a debian format archive
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1

What were you expecting to happen?
----------------------------------
package to install

Any logs, error output, etc?
----------------------------
root@192.168.1.100's password:
make: *** No rule to make target 'install'.  Stop.
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 750 package 'libmoorecon':
 missing maintainer
dpkg-deb: error: '/tmp/_theos_install.deb' is not a debian format archive
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Mac 10.13.5

**Toolchain Version:** 6.1-1

**SDK Version:** 11.2

**Comment by uroboro** [comment]
Can you share your `control` file?

**Comment by chashmeetsingh** [comment]
Sure:

```
Package: singh.chashmeet.notimelabel
Name: NoTimeLabel
Depends: mobilesubstrate
Version: 0.0.1
Architecture: iphoneos-arm
Description: An awesome MobileSubstrate tweak!
Maintainer: Chashmeet Singh
Author: Chashmeet Singh
Section: Tweaks
```
