### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by cydiaksg** [theos/theos#334]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. installed theos
2. set targets
3. make package install

What happens?
-------------
error shows up

What were you expecting to happen?
----------------------------------
compile succesfully

Any logs, error output, etc?
----------------------------
make: execvp: /var/theos/bin/vercmp.pl: Operation not permitted
make: execvp: /var/theos/bin/vercmp.pl: Operation not permitted
make: execvp: /var/theos/bin/vercmp.pl: Operation not permitted
make: execvp: /var/theos/bin/vercmp.pl: Operation not permitted
/var/theos/makefiles/targets/Darwin-arm64/iphone.mk:77: *** invalid syntax in conditional. Stop.

Any other comments?
-------------------
I really want to fix it fast.

What versions of software are you using?
----------------------------------------
**Operating System: iOS 11.3.1 with Electra 1.0.3 multi_path** 

**Toolchain Version:6.1-1** 

**SDK Version:iPhoneOS9.3.sdk**

**Comment by xelahot** [comment]
Same problem here, I follow Billy Hellis tutorial for iOS but I get the same errors. I can create the project but when time comes to build it does’nt work. When I created the project, I only had 5 options to choose from even if I installed the Perl version, Theos, and everything in the youtube tutorial he made.

**Comment by kirb** [comment]
@cydiaksg and @xelahot, you're not using the latest version of Theos. We fixed this some time ago when the iOS 11 jailbreak was new. As far as I remember Billy Ellis's tutorial recommends you install an extremely old version of Theos. Please see https://git.io/theosinstall for our official installation instructions.

**Comment by xelahot** [comment]
Thanks alot @kirb, it works now! I always wanted to experiment iOS mods, let’s gooooo!

**Comment by xelahot** [comment]
@kirb, do you know a way to dump header files from an app store app binary file directly from my device on iOS 11.3.1? There seem to be alot of stuff but none of them seem to be working... ex: class-dump, classdump-dyld, uncrypt11, ...

I’m looking to find methods names just like Flex 3 does.
