### ISSUE TITLE
(Undefined symbols for architecture arm64: "_memcpy", referenced from: _logosLocalInit()) - when you use Logos %new to declare a new method that takes an NSString* as a parameter

### ISSUE THREAD

**Issue by metalpython** [theos/theos#335]
Hi. If i use the Logos %new command before a new method that takes an NSString* as a parameter then I get the linker error:
 Undefined symbols for architecture arm64:
  "_memcpy", referenced from:
      _logosLocalInit() in Tweak.xm.1d3abc5e.o
ld: symbol(s) not found for architecture arm64

It seems to be a bug with memory management from %new as NSString* is a pointer not a value but I am not sure.

I am compiling on device iOS 10.0.2 iPhone 6 Plus.
Thanks

**Comment by kirb** [comment]
That logic is definitely correct. It’s constructing a type encoding for the method (a string of the method’s return and argument types). See https://github.com/theos/logos/blob/886885b273d38092687616c83ec5f452c3b2e965/bin/lib/Logos/Generator/MobileSubstrate/Method.pm#L88-L104.

This sounds more like an SDK issue? Double check that you have $THEOS/sdks/iPhoneOSX.Y.sdk/usr/lib/libSystem.B.tbd (or .dylib), and libSystem.tbd is a symlink to libSystem.B.tbd. If you extracted the SDK on Windows and copied it over, the symlinks were probably corrupted. It’s always best to extract on the device.

**Comment by kirb** [comment]
Closing as this is an old thread and hasn’t been reported otherwise.

**Comment by frakman1** [comment]
I am getting the same error. You can reproduce it using [this](https://github.com/CPDigitalDarkroom/SimplePasscodeButtons) project. I change target in Makefile to:
`TARGET := iphone:10.3:10.0`
to match my iOS. I checked my sdk folder and the libSystem* files look like this:

```
root@7f2cefb0be8a:~/projects/SimplePasscodeButtons# ls -lasth /opt/theos/sdks/iPhoneOS10.3.sdk/usr/lib/libSystem.*
4.0K -rw-r--r-- 1 root root 2.2K Nov  8 05:47 /opt/theos/sdks/iPhoneOS10.3.sdk/usr/lib/libSystem.B.tbd
   0 lrwxrwxrwx 1 root root   15 Nov  8 05:47 /opt/theos/sdks/iPhoneOS10.3.sdk/usr/lib/libSystem.tbd -> libSystem.B.tbd
```

The full compile and error log is this:
```
root@7f2cefb0be8a:~/projects/SimplePasscodeButtons# make package
> Making all for tweak SimplePasscodeButtons…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Linking tweak SimplePasscodeButtons (arm64)…
Undefined symbols for architecture arm64:
  "_memcpy", referenced from:
      __ZL15_logosLocalInitv in Tweak.xm.c86c9353.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/opt/theos/makefiles/instance/library.mk:32: recipe for target '/root/projects/SimplePasscodeButtons/.theos/obj/debug/arm64/SimplePasscodeButtons.dylib' failed
make[3]: *** [/root/projects/SimplePasscodeButtons/.theos/obj/debug/arm64/SimplePasscodeButtons.dylib] Error 1
rm /root/projects/SimplePasscodeButtons/.theos/obj/debug/arm64/Tweak.xm.mm
/opt/theos/makefiles/instance/library.mk:32: recipe for target '/root/projects/SimplePasscodeButtons/.theos/obj/debug/arm64/SimplePasscodeButtons.dylib' failed
make[2]: *** [/root/projects/SimplePasscodeButtons/.theos/obj/debug/arm64/SimplePasscodeButtons.dylib] Error 2
/opt/theos/makefiles/instance/library.mk:24: recipe for target 'internal-library-all_' failed
make[1]: *** [internal-library-all_] Error 2
/opt/theos/makefiles/master/rules.mk:111: recipe for target 'SimplePasscodeButtons.all.tweak.variables' failed
make: *** [SimplePasscodeButtons.all.tweak.variables] Error 2
```
