### ISSUE TITLE
Use of uninitialized value in addition (+)

### ISSUE THREAD

**Issue by Relisiuol** [theos/theos#337]
Hi,

I have a problem, something is constantly write into Apache log. Can you help me please?

What are the steps to reproduce this issue?
-------------------------------------------
1. I only installed THEOS on my server
2. And used it to compile some packages
3. But my hosting provider suspended my account due to too much writing in Apache logs

What happens?
-------------
"Use of uninitialized value in addition (+) at /home/yourepo/theos/bin/dm.pl line 122."

What were you expecting to happen?
----------------------------------
An option to mute warnings? Not sure it's a warning.

Regards,

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by rpetrich** [comment]
Your Apache logs are unrelated to Theos.
