### ISSUE TITLE
Error 139: rules.mk:123

### ISSUE THREAD

**Issue by J0113** [theos/theos#338]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install latest theos on iOS with the tuturial
2. Make a new tweak
3. Run `make package install`

What happens?
-------------
Error 139: 
/bar/theos/makefiles/master/rules.mk:123

It does not install my tweak

What were you expecting to happen?
----------------------------------
Install tweak

Any logs, error output, etc?
----------------------------
              
```
iPhone-van-Jolle:~ mobile$ cd settingsxi/               
iPhone-van-Jolle:~/settingsxi mobile$ make package install                                                       
> Making all for bundle SettingsXI…                     
bash: line 25: 21506 Segmentation fault: 11  make -f Makefile --no-keep-going COLOR=1 --no-print-directory internal-bundle-all _THEOS_CURRENT_TYPE="bundle" THEOS_CURRENT_INSTANCE="SettingsXI" _THEOS_CURRENT_OPERATION="all" THEOS_BUILD_DIR="."                                          
make: *** [/var/theos/makefiles/master/rules.mk:123: SettingsXI.all.bundle.variables] Error 139 

```
Any other comments?
-------------------
If have tried a lot of things: reinstalling from scratch, suggestions of older issues here.

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 11.3.1

**Toolchain Version:** currently latest

**SDK Version:** 10.3, 10.2 and 9.3...

**Comment by Eelson126** [comment]
Install latest theos on iOS with the tuturial
Make a new tweak
Run make package install
result：dm.pl: building package `com.allen.test:iphoneos-arm' in `./packages/com.allen.test_0.0.1-5+debug_iphoneos-arm.deb'
open2: exec of lzma -c0 failed at /Users/AllenG/theos/bin/dm.pl line 113.

**Comment by kirb** [comment]
@Eelson126, please don’t hijack existing issue threads, especially unrelated ones. You likely missed installing xz. Please review https://git.io/theosinstall. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).

Closing this due to lack of response.
