### ISSUE TITLE
Llvm+Clang not installable

### ISSUE THREAD

**Issue by 5H4D0WILA** [theos/theos#339]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. open cydia
2. search for llvm+Clang

What happens?
-------------
Cydia says that i can't install llvm+clang (i would need 64 bit and firmware below ios 9) which is a must have to install ios toolchain or theos dependencies.

What were you expecting to happen?
----------------------------------
installing dependencies

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
i have a iphone 4s with ios 9.3.5
I had theos installed once but i needed to reset my iphone so i wanted to install it again and yeah

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** No version because i can't install ios toolchain

**SDK Version:** …

**Comment by kirb** [comment]
Closing as this is an old thread and doesn’t seem to have been reported otherwise.

**Comment by bogardon** [comment]
Is theos just not supported on 32bit devices anymore?

**Comment by oasis-eos** [comment]
i find an answer in iosgods: Coolstar removed 32 bit support completely. Now all of the dependencies seem to just have 64 bit support only.

**Comment by bogardon** [comment]
I found you can still download the 32 bit version if you navigate to his list of packages and find it there.
