### ISSUE TITLE
Can Theos, in conjunction with codesign, create Ipa files that run on non jailbroken devices? 

### ISSUE THREAD

**Issue by vedantroy** [theos/theos#342]
Is it possible to use Theos to generate an ipa file which can be run on a non-jailbroken device? Possibly by first generating the ipa file with Theos and then using the codesign utility for Mac (or isign: https://github.com/saucelabs/isign)

**Comment by kirb** [comment]
For app tweaking there's [theos-jailed](https://github.com/kabiroberai/theos-jailed). I don't know if there's any solution to build regular iOS apps to an ipa at the moment. This ties into #286 which we've been intending to start work on at some point.

**Comment by DHowett** [comment]
Somewhere in the annals of history (and on one of my various nearly-lost machines) I have an `ipa` package format module. Perhaps it'll help if I can dig it up.

It _it_ possible (and fairly civilized, as well!)

**Comment by kabiroberai** [comment]
Closing in favour of #286, since this is essentially a duplicate of that issue.
