### ISSUE TITLE
[Feature-Request]print time when make install / do

### ISSUE THREAD

**Issue by Kunderscore** [theos/theos#343]
This is a feature request for theos, when doing development, after `make do`, I would do some more edits to my source files, therefore, sometimes making it hard to know whether these edits were already part of the latest `make do`, or were the edits I just made after the latest `make do`

Of course, I could do all my edits, then `make do` or `make do && date`, but would be a convenient to have it part of theos.

**Comment by kirb** [comment]
You could do something such as:

```make
after-install::
    @echo "Finished at $(shell date)"
```

To have this globally you can put it in `~/.theosrc`, which itself is a makefile. Create it if it doesn't exist. You could also set up a shell prompt with the time — Google how to do this for your shell. If you use zsh it's built into many of the [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) themes. I personally use a shell prompt with the date/time for this reason. 

Not sure that we'll make this a feature. Sorry.
