### ISSUE TITLE
Fix Building with Xcode 10

### ISSUE THREAD

**Issue by Naville** [theos/theos#346]
What are the steps to reproduce this issue?
-------------------------------------------
1. Just run make

What happens?
-------------
A bunch of issues regarding failed to build Darwin module and failed to include stdlibc++

What were you expecting to happen?
----------------------------------
Build successfully

Any logs, error output, etc?
----------------------------
```
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7)…
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
While building module 'Foundation' imported from /Users/XXX/theos/Prefix.pch:11:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: fatal error: could not build module
      'Darwin'
#include <sys/types.h>
 ~~~~~~~~^
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
```

Any other comments?
-------------------
I noticed that modifying the Makefile to the following can fix the issue:
```
TWEAK_NAME = FOOOOOO
FOOOOOO_FILES = Tweak.xm
FOOOOOO_CFLAGS = -std=c++11 -stdlib=libc++
FOOOOOO_LDFLAGS = -stdlib=libc++
```

What versions of software are you using?
----------------------------------------
**Operating System:** ``macOS10.13.6``

**Toolchain Version:** ``Apple LLVM version 10.0.0 (clang-1000.11.45.2)``

**SDK Version:** ``Xcode 10.0``

**Comment by sbingner** [comment]
What is your target set to?  I think setting target to ios8+ already changes the stdlib

**Comment by jerukim** [comment]
I'm having the same issue... sorry for noob question but i cant figure out how to set to target with any of the documentation from github/iphonedevwiki

**Comment by yangshebing** [comment]
great

**Comment by Naville** [comment]
@jerukim 
```
however now i'm getting the error: no such sysroot directory: '' [-Werror,-Wmissing-sysroot]
```
Your target should match you local SDK's version/path.

```
just kidding
```
I failed to see how this is actually funny


@sbingner 

I didn't manually override the target setting

**Comment by Naville** [comment]
@kabiroberai Hi:
When can we expect to see your patch merged into the upstream?

**Comment by kabiroberai** [comment]
@Naville as soon as I get to test it with an SDK version lower than 12.0

**Comment by Ethavn** [comment]
when mac updated to 10.14, the newest THEOS had the same error

**Comment by Naville** [comment]
Can confirm

**Comment by Naville** [comment]
From my understanding here your patch only updated LDFLAGS,while C/CPPFLAGS are required as well. Can you take a further look into this?

@kabiroberai

**Comment by kabiroberai** [comment]
That’s strange – it works fine on my Mac (which is on High Sierra though). I’ll look into it

**Comment by Naville** [comment]
I've attempted to look at it unfortunately I have no idea which file I should modify to pass new CFLAGS : (

**Comment by wuqingshengge** [comment]
很好

**Comment by SoundBlaster** [comment]
For iOS 14 working options:
```
ECGEnabler14_CFLAGS = -std=c++11 -stdlib=libc++ -miphoneos-version-min=14.0
ECGEnabler14_LDFLAGS = -stdlib=libc++ -miphoneos-version-min=14.0
```
