### ISSUE TITLE
make package fail

### ISSUE THREAD

**Issue by dongxiexidu** [theos/theos#354]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1.nic.pl
2.13
3.make
4.make package
What happens?
-------------
dm.pl: building package `com.li.firstproject:iphoneos-arm' in `./packages/com.li.firstproject_0.0.1-1+debug_iphoneos-arm.deb'
open2: exec of lzma -c6 failed at /Users/lidongxi/theos/bin/dm.pl line 113.
make: *** [internal-package] Error 2

What versions of software are you using?
----------------------------------------
**Operating System:** …
mac 10.13.6

**Comment by kirb** [comment]
Strange. What is the output of `which lzma`? If you run `lzma`, what do you see? If it works, it should be “`lzma: Compressed data cannot be written to a terminal`”.

**Comment by MangoSeries** [comment]
vim /Users/xxx/theos/makefiles/package/deb.mk
then change _THEOS_PLATFORM_DPKG_DEB_COMPRESSION ?= lzma to _THEOS_PLATFORM_DPKG_DEB_COMPRESSION ?= gzip at line 6.

**Comment by uroboro** [comment]
We'd rather you didn't edit or suggest editing Theos' files.

**Comment by kirb** [comment]
Closing due to lack of response.

**Comment by kevinpiac** [comment]
I had the same issue and running `brew install xz` worked for me.
