### ISSUE TITLE
Failed to codesign when targeting simulator

### ISSUE THREAD

**Issue by wstyres** [theos/theos#356]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create project (in this case, an application)
2. Target iPhone simulator (TARGET=simulator::latest:latest)

What happens?
-------------
Building fails during the signing stage with `codesign: invalid option -- S`

What were you expecting to happen?
----------------------------------
Project builds and is signed

Any logs, error output, etc?
----------------------------
```
==> Signing AUPM…
codesign: invalid option -- S
Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
       codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
       codesign -d [options] path ... # display contents
       codesign -h pid ... # display hosting paths
make[2]: *** [~/AUPM/.theos/obj/iphone_simulator/debug/AUPM.app/AUPM] Error 2
rm ~/AUPM/.theos/obj/iphone_simulator/debug/AUPM.app/AUPM.4c5c5016.unsigned
make[1]: *** [internal-application-all_] Error 2
make: *** [AUPM.all.application.variables] Error 2
```

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.14.1

**Toolchain Version:** Xcode 10.1 (happens with 10 as well)

**SDK Version:** 10.3 from theos/sdks

**Comment by the-casle** [comment]
https://github.com/angelXwind/simject/issues/43#issuecomment-441659203

https://github.com/angelXwind/simject/issues/42#issuecomment-440920466

From simject setup page.
