### ISSUE TITLE
Failed to compile, missing libtinfo.so.5 on Arch Linux

### ISSUE THREAD

**Issue by midnightchip** [theos/theos#357]
What are the steps to reproduce this issue?
-------------------------------------------
1. Attempt to compile any tweak using Arch

What happens?
-------------
You will receive the error: `arm64-apple-darwin14-ld: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

What were you expecting to happen?
---------------------------------
The tweak to compile.

Any other comments?
-------------------
I have attempted the normal fixes, Arch has libtinfo.so.6 and libtinfo.so available from ncurses. When creating a symlink to libtinfo.so.5, theos reports `arm64-apple-darwin14-ld: error while loading shared libraries: /usr/lib/libtinfo.so.5: file too short`

What versions of software are you using?
----------------------------------------
**Operating System:** Arch Linux

**Toolchain Version:** Latest
**SDK Version:** 11.2, 9.2

**Comment by midnightchip** [comment]
Ok, I figured out how to get past this error, you need to symlink `/usr/lib/libtinfo.so.6` to `/usr/libtinfo.so.5`

**Comment by midnightchip** [comment]
Another solution is installing ncurses5-compat-libs from AUR

**Comment by mstg** [comment]
Closing since it's resolved.

---

If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)

**Comment by Kunderscore** [comment]
manjaro installing 

> ncurses5-compat-libs 6.1.1
encountered error
`   ncurses-6.1.tar.gz ... FAILED (unknown public key 702353E0F7E48EDB)
==> ERROR: One or more PGP signatures could not be verified!
==> ERROR: Makepkg was unable to build ncurses5-compat-libs.`

So is there another way 
And also  symbol link from /usr/lib/libtinfo.so.6 to /usr/lib/libtinfo.so.5
would give this error:
```
/opt/theos/toolchain/linux/iphone/bin/arm64-apple-darwin14-ld: /usr/lib/libtinfo.so.5: no version information available
```

**Comment by aimorris** [comment]
@Inc0ns1st3nt That's a common error when installing from the AUR. Run `gpg --recv-keys 702353E0F7E48EDB` and try installing again.

**Comment by cloudlyhima** [comment]
its realy work, thx
