### ISSUE TITLE
%log can't output information

### ISSUE THREAD

**Issue by MangoSeries** [theos/theos#361]
What are the steps to reproduce this issue?
-------------------------------------------
1. add %log into hook method.
2. make package and make install.
3. open Xcode->Window->Devices and Simulators->Open Console
4. open the target app.

What happens?
-------------
I can't find any information %log output.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.13.5

**Xcode Version:** 9.3.1

**Comment by RMKitty** [comment]
I have the same issuse.  The Console also can't find any information. i add `NSLog(@">>>>%s",__func__);`then i can see what it does.

**Comment by Patrickk17** [comment]
I’m not familiar with %log but why not use NSLog?

**Comment by kirb** [comment]
%log expands to an NSLog() call containing the signature of the current method and parameter values/descriptions.

**Comment by kirb** [comment]
Closing due to lack of response. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
