### ISSUE TITLE
Issues makefile

### ISSUE THREAD

**Issue by Haizanjs** [theos/theos#362]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

![img_6809](https://user-images.githubusercontent.com/27821536/49970436-3866ce80-ff23-11e8-9063-17cbbd2803e4.PNG)
![screenshaat_2](https://user-images.githubusercontent.com/27821536/49970488-60563200-ff23-11e8-815a-0c6e27adc309.png)

**Comment by uroboro** [comment]
What’s the ownership of `/var/mobile/test`?

**Comment by Haizanjs** [comment]
![img_6818](https://user-images.githubusercontent.com/27821536/50003801-d8147300-ff9c-11e8-98eb-b009b2f5ab7c.PNG)

I've managed to get to this part now if this helps?

**Comment by uroboro** [comment]
It doesn't. Show the output of `ls -ld /var/mobile/test`.

**Comment by Haizanjs** [comment]
**Output**
![image](https://user-images.githubusercontent.com/27821536/50012644-1cad0800-ffb7-11e8-802a-ada3b9f33c31.png)

**Comment by uroboro** [comment]
It's exactly what I thought. Change the ownership to mobile with `chown -R mobile:mobile /var/mobile/test` and don't use root to create, build, or package Theos projects.

**Comment by Haizanjs** [comment]
![image](https://user-images.githubusercontent.com/27821536/50046132-0fb31600-0096-11e9-99e2-a34659707ea6.png)

![sad](https://user-images.githubusercontent.com/27821536/50046130-02962700-0096-11e9-9fac-90eac3f4e327.jpg)

**Comment by Wh0ba** [comment]
Run `make clean` to clean these temp files  then `make` to recompile

**Comment by kirb** [comment]
This seems to be an issue of bad permissions and this thread has been quiet for a while so closing this.

If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
