### ISSUE TITLE
Compiler hanging on chmod -R 0755 '/tmp/theos_for_wsl/[tweakname]/_'

### ISSUE THREAD

**Issue by M4cs** [theos/theos#365]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run `make package` or `make package install`

What happens?
-------------
Hangs on this:
![image](https://user-images.githubusercontent.com/34947910/50428017-2f5df180-0881-11e9-8d9d-ffb6e0d468cf.png)

What were you expecting to happen?
----------------------------------
To compile the tweak

Any logs, error output, etc?
--------------------------
![image](https://user-images.githubusercontent.com/34947910/50428020-38e75980-0881-11e9-9c86-152e2a979564.png)

What versions of software are you using?
----------------------------------------
**Operating System:** WSL

**Toolchain Version:** Whatever one is in the WSL install guide

**SDK Version:** 11.2

**Comment by L1ghtmann** [comment]
Closing as wsl workaround logic has since [been removed](https://github.com/theos/theos/commit/fdc473a8e0139acd838ad7d8d96ea8cfb4838ff5). Feel free to reopen if the issue persists with the latest Theos.
