### ISSUE TITLE
Theos doesn't work on iSH app

### ISSUE THREAD

**Issue by uroboro** [theos/theos#373]
What are the steps to reproduce this issue?
-------------------------------------------
1. Get into iSH TestFlight and install app.
2. Follow installation instructions for Linux but using `apk add bash clang coreutils curl fakeroot git grep make openssh-client perl rsync sed` for installing dependencies.
3. Run nic to make a (tool) project and `make`.

What happens?
-------------
    /root/theos/makefiles/common.mk:154: *** You did not specify a target, and the "linux" platform does not define a default target.  Stop.

What were you expecting to happen?
----------------------------------
To build.

Any logs, error output, etc?
----------------------------
Nope.

Any other comments?
-------------------
When Theos determined the platform it uses `uname`.

On iSH,

    echo $(uname -s)-$(uname -p)::$(uname -o 2>/dev/null)

returns:

    Linux-unknown::GNU/Linux

Which appears to be the same as Debian on WSL.

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 12.1.2

**iSH Version:** 1.0 (48)

**Comment by uroboro** [comment]
I've given this a more in-depth look, turns out that while the step that runs `target.pl` in [makefiles/common.mk#L144](https://github.com/theos/theos/blob/badb4240cbde4a0788e0961d6c6d1d2cfbbd4562/makefiles/common.mk#L144) returns a temporary file path, it doesn't actually write any content. To complicate things even more, running the command manually works fine.

**Comment by L1ghtmann** [comment]
A little update on theos in iSH:

Missing a default target is no longer an issue as of [this commit](https://github.com/theos/theos/commit/195c4a375d72fceb78e31d163a24aa9762c8f203). 

After 1) checking for iSH (in a similar manner to how WSL is checked) and 2) adjusting the bin paths (sdk and swift) to point to /usr/bin, theos appears to works entirely as intended. 

The only two issues I encountered were: 1) the binutils package has to be installed along with the others mentioned above (contains ld, among other things) and 2) the builds of clang and ld currently available in alpine do not support arm64e as a target arch.

**Comment by L1ghtmann** [comment]
Took a look at this a while back and concluded that the limiting factor, as with most platforms, was an iOS toolchain (musl; x86). A musl llvm toolchain is particularly difficult to piece together, so going to close for the time being. May reopen in the future if we decide this is worth giving a proper go.
