### ISSUE TITLE
cannot find symbol of SBApplication when compile a category file to 

### ISSUE THREAD

**Issue by liuxuan30** [theos/theos#376]
Hi @kirb sorry bother again. I tried to google or search the wiki, but cannot find any clues. So I have to post here as new issue. Sorry about that

I'm trying to add a category to SBApplication in SpringBoard like below.
`PrivateHeaders.h` contains all the SpringBoard class definitions such as SBApplication:
```objective-c
@interface SBApplication : NSObject
-(id)bundleIdentifier;
@end
```

in `SBApplication+MyCategory.h`:
```objective-c
#import <Foundation/Foundation.h>
#import "PrivateHeaders.h"

@class SBApplication;

@interface SBApplication (MyCategory)
-(NSString *)doSomething;
@end
```

in `SBApplication+MyCategory.m`:
```objective-c
#import "SBApplication+DPI.h"

@implementation SBApplication (MyCategory)

-(NSString *)doSomething {
    return @"Hello World";
}
@end
```
I have added SBApplication+MyCategory.m in Makefile.

while compiling, it always gives
```
==> Compiling SBApplication+DPI.m (arm64)…                                                                                                         
==> Linking tweak MyTweak (arm64)…                                                                                                     
Undefined symbols for architecture arm64:                                                                                                          
  "_OBJC_CLASS_$_SBApplication", referenced from:                                                                                                  
      l_OBJC_$_CATEGORY_SBApplication_$_MyCategory in SBApplication+MyCategory.m.80c1058e.o                                                                      
ld: symbol(s) not found for architecture arm64                                                                                                     
clang: error: linker command failed with exit code 1 (use -v to see invocation)   
```

I suppose it should be able to find the class symbols, but it didn't. Does theos/logos allow such usage or where am I wrong? Thanks in advance!

**Comment by Kunderscore** [comment]
if you are hooking then
```
%hook
-(NSString *)doSomething {
    return @"Hello World";
}
```
if` -(NSString *)doSomething;` is a new method to the class sbapplication then
```
%new
-(NSString *)doSomething {
    return @"Hello World";
}
```

if for example class sbapplication is a class you have created, there shouldn't be error for such usage
but we are "hacking" here, so `%new` syntax is required.

Essentially %New would translate to objc_addClass something like that

This is as much as i know and can explain to.

**Comment by kirb** [comment]
This is correct behavior; a category can only be made on a linkable symbol or the binary could fail to load at runtime. `%new` is the way to go as it lets it fail silently if not found.
