### ISSUE TITLE
changing the ssh client for theos

### ISSUE THREAD

**Issue by Kunderscore** [theos/theos#377]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. make install
2. enter password for ssh
3. hangs

What happens?
-------------
my ssh client is broken sometimes, so i use putty (plink and pscp) most of the times,
and it hangs for all consecutive sessions after a unsuccesfull scp transfer 

So is there a way to change scp to pscp for theos

**Comment by Kunderscore** [comment]
changed from (ssh, scp) to (plink, pscp) by editing the following files:
bin/install.exec 
bin/install.copyFile

**Comment by uroboro** [comment]
Please do *not* edit Theos files, fix your ssh client instead.
