### ISSUE TITLE
Ghostbin Script Download Blocked by Cloudflare

### ISSUE THREAD

**Issue by JeffResc** [theos/theos#378]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Installing Theos for iOS

What happens?
-------------
When downloading the ghostbin script automatically as shown [in step 6 of the installation](https://github.com/theos/theos/wiki/Installation-iOS), the download was blocked by Cloudflare and not noticed until I manually opened the file.

What were you expecting to happen?
----------------------------------
For the download not to be blocked.

Any logs, error output, etc?
----------------------------
[Ghostbin Link](https://ghostbin.com/paste/zcv3f)

What versions of software are you using?
----------------------------------------
**Operating System:** N/A

**Toolchain Version:** N/A

**SDK Version:** N/A

**Comment by kirb** [comment]
We don’t control Ghostbin so we can’t do anything about that. It’s an optional step anyway.

**Comment by JeffResc** [comment]
Should the file perhaps be moved to a site where Cloudflare won't block the request, such as GitHub?
