### ISSUE TITLE
theos & c++ & linux compilation either cannot find ___isOSVersionAtLeast or standar c++ library

### ISSUE THREAD

**Issue by Kunderscore** [theos/theos#380]
Steps to reproduce this issue
-------------------------------------------
0. linux operating system with theos setup
1. have a project with c++ & some objc code about view controllers
2. make

What happens?
-------------
situation 1 => when makefile is configured with minimum flags (-fobjc-arc -w etc), 
symbol `___isOSVersionAtLeast` cannot be find

situation 2 => when makefile is configured with `TARGET = iphone:clang:latest`
standard c++ library such as `#include <set>` or `#include <fstream>` cannot be find

logs, error output, etc?
----------------------------
situation 1 
```
Undefined symbols for architecture arm64:
  "___isOSVersionAtLeast", referenced from:
      -[FLEXExplorerViewController viewSafeArea] in FLEXExplorerViewController.m.91212ede.o
      -[FLEXExplorerViewController viewSafeAreaInsetsDidChange] in FLEXExplorerViewController.m.91212ede.o
      -[FLEXExplorerToolbar safeArea] in FLEXExplorerToolbar.m.91212ede.o
```

situtaion 2 
```
jsdebugger-src/JDLog.mm:9:9: fatal error: 'fstream' file not found
#import <fstream>
...
==> Compiling jsdebugger-src/JDChoose.mm (arm64)…
jsdebugger-src/JDChoose.mm:16:10: fatal error: 'iostream' file not found
#include <iostream>
```

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Oher comments
-------------------
However compilation will be successful regardless of makefile if project is a cmd tool application

Versions of software
----------------------------------------
**Operating System:** 4.19.20-1-MANJARO

**Toolchain Version:** 

**SDK Version:** 11.2

**Comment by nguyenthienhoan** [comment]
with situation 1: How can you fix this problem ?

**Comment by nguyenthienhoan** [comment]
with situation 1: How can you fix this problem ?

**Comment by eclair4151** [comment]
i fixed this by adding this to the top of the file where needed

int __isOSVersionAtLeast(int major, int minor, int patch) { NSOperatingSystemVersion version; version.majorVersion = major; version.minorVersion = minor; version.patchVersion = patch; return [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:version]; }
