### ISSUE TITLE
WSL Fakeroot doesn't work with Theos

### ISSUE THREAD

**Issue by Cryptiiiic** [theos/theos#388]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos on WSL
2. create a package using a NIC template
3. make package

What happens?
-------------
WSL fakeroot doesn't work with theos.

What were you expecting to happen?
----------------------------------
`fakeroot` when run won't work.

On WSL you need to set it up as tcp.
Here is the fix
`sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp`
This fix should be noted in the linux install wiki.

Any logs, error output, etc?
----------------------------
```fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
```

What versions of software are you using?
----------------------------------------
**Operating System:** Windows WSL(Linux)

**Toolchain Version:** Any

**SDK Version:** Any

**Comment by chrisderwahre** [comment]
i just ran into the same issue, the fix you provided worked fine, thank you.

**Comment by uroboro** [comment]
Fixed in https://github.com/theos/theos/wiki/Installation-Linux/c31e47f4bec9a30ffdf364acf0d1eda029d0c3c5.
