### ISSUE TITLE
Freezes when building package

### ISSUE THREAD

**Issue by the-casle** [theos/theos#389]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Only randomly started occurring
2. Updated to most recent version of theos
3. Ran make-clean or make clean-packages
4. make package no longer worked

What happens?
-------------
Compiles fine, but when trying to make the package it freezes and gets stuck on
dm.pl: building package ... 

What were you expecting to happen?
----------------------------------
It would finish making the package and install onto my device

Any logs, error output, etc?
----------------------------
The -d logs freeze at the exact same point when making the package

Any other comments?
-------------------
Not really

What versions of software are you using?
----------------------------------------
**Operating System:** mac 10.13.6

**Toolchain Version:** Updated from xcode

**SDK Version:** 11.2

**Comment by iKilledAppl3** [comment]
Similar issue some not all packages do this to me

**Comment by kirb** [comment]
Any open source examples of projects that cause this so I can take a look?

**Comment by the-casle** [comment]
https://github.com/midnightchip/Asteroid

**Comment by the-casle** [comment]
@kirb This seemed to only affect Asteroid’s preferences subproject, removing built fine. In addition it could build if I changed the bundle name of the preferences (But that obviously broke a lot of other stuff).

**Comment by M4cs** [comment]
Run umask. Is it 0022?

**Comment by the-casle** [comment]
Yea 0022 @M4cs

**Comment by M4cs** [comment]
Try running `make do` instead. It does the same thing but fixed this issue for me sometimes.

**Comment by the-casle** [comment]
@m4cs it has the same issue, however I think it may have worked once randomly a while ago.

**Comment by the-casle** [comment]
It was just a really big video. Thanks for the help
