### ISSUE TITLE
Updated to Xcode10.2: unable to find utility "llvm-dsymutil“

### ISSUE THREAD

**Issue by Nosskirneh** [theos/theos#391]
What are the steps to reproduce this issue?
-------------------------------------------
1. Update Xcode to 10.2.
2. Compile any theos project.

What happens?
-------------
Build not successful.

What were you expecting to happen?
----------------------------------
Successful build, as a result of no missing executable.

Any logs, error output, etc?
----------------------------
`xcrun: error: unable to find utility "llvm-dsymutil", not a developer tool or in PATH`

Any other comments?
-------------------
Created a thread about it [here](https://www.reddit.com/r/jailbreakdevelopers/comments/b725qg/updated_to_xcode_102_unable_to_find_utility/).

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.14

**SDK Version:** 9.2

**Comment by juanillo62gm** [comment]
Same here, after updated yesterday y have same problem. I posted on Reddit today and nothing 😥

**Comment by kentkrantz** [comment]
[Solution](https://www.reddit.com/r/jailbreakdevelopers/comments/b725qg/updated_to_xcode_102_unable_to_find_utility/ejp6zgx?utm_source=share&utm_medium=web2x)

**Comment by kirb** [comment]
Fixed in 3e36066.
