### ISSUE TITLE
Theos enviornment variable not taking effect

### ISSUE THREAD

**Issue by Patrickk17** [theos/theos#394]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Set up theos; including the environment variable 
2. Try to use the environment variable in any way 

What happens?
The environment variable does not take effect.

What were you expecting to happen?
I was expecting $THEOS to equate to my theos directory, but this is not happening.

Any logs, error output, etc?
When testing the environment variable by running `echo $THEOS`, there is no output.
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
I have checked the shell/bash profile, and it looks as you would expect.

`export THEOS=~/theos`
is at the bottom of the file.

What versions of software are you using?
----------------------------------------
**Operating System:** Debian Stretch Linux (Raspbian)

**Toolchain Version:** Latest

**SDK Version:** 11.2

**Comment by uroboro** [comment]
What's the complete path of the profile file you edited? Try adding an `echo hello` to it to verify that it is not being executed or the environment variables aren't being set properly.

**Comment by Patrickk17** [comment]
the complete path is /home/pi/.profile
Nothing indifferent happened after adding `echo hello` to the end

**Comment by Patrickk17** [comment]
### **Fixed:**

**In case someone reading this has the same issue:**

The ~ symbol which equates to you home directory seems to only be relevant in the terminal emulator, not to the machine (at least for my distro). You have to put the full path of theos in your profile.

For example at the bottom of the file
`export THEOS=/home/pi/theos`
Instead of:
`export THEOS=~/theos`

**Comment by kirb** [comment]
Are you running a sh, ash, or dash shell by any chance? Try `echo $SHELL`. What distro are you using? Is it possibly using Busybox (which we don’t recommend or test Theos with)?
