### ISSUE TITLE
PFSimpleLiteColorCell not showing (FINALPACKAGE=1 and colorpicker)

### ISSUE THREAD

**Issue by JunesiPhone** [theos/theos#397]
When FINALPACKAGE=1 is used the project will build fine, but PFSimpleLiteColorCells do not populate the color pickers in Preferences.app.

Filter plist.
{ Filter = { Bundles = ( "com.apple.mobilesafari" ); }; }

What's odd is if you install another package that uses the colorpicker and uses UIKit they will populate in the package that used FINALPACKAGE=1. 

You can also add com.apple.UIKit to the filters and the pickers will populate with FINALPACKAGE=1, but is pointless if you are only hooking an app.
e.g. { Filter = { Bundles = ( "com.apple.mobilesafari", "com.apple.UIKit" ); }; }

Library is added in the make file
$(TWEAK_NAME)_LIBRARIES = colorpicker

Dependency is installed
Dependency: org.thebigboss.libcolorpicker

Header is included in the tweak.
#import <libcolorpicker.h>

Cell is defined in the settings plist.
<key>cellClass</key>
<string>PFSimpleLiteColorCell</string>

Just putting this here incase someone else pulls their hair out trying to figure out why the  PFSimpleLiteColorCell isn't showing. Remove FINALPACKAGE=1 and everything will work as it should.

**Comment by JunesiPhone** [comment]
Update: Replacing SDKs seemed to resolve the issue.

**Comment by uroboro** [comment]
Please do **NOT** use `$(TWEAK_NAME)_LIBRARIES`, use the actual name.

**Comment by JunesiPhone** [comment]
I do. https://github.com/JunesiPhone/SafariButtons/blob/master/Makefile

Used $(TWEAK_NAME) to state its a name.

**Comment by uroboro** [comment]
Ok, just know we usually either use the actual variable (`SafariButtons_LIBRARIES` in this case) or `XXX_LIBRARIES` if you want to keep the name private.

I'm trying to prevent people from using `$(TWEAK_NAME)_LIBRARIES` literally which would cause issues if `TWEAK_NAME` contains a list of tweaks.
