### ISSUE TITLE
Make Package Fails

### ISSUE THREAD

**Issue by Witherking25** [theos/theos#398]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. use theos to make a modern application template
2. use make package on the template without changing anything

What happens?
-------------
make fails

What were you expecting to happen?
----------------------------------
not break

Any logs, error output, etc?
----------------------------
$ make package
> Making all for application HelloWorld…
==> Copying resource directories into the application wrapper…
==> Compiling main.m (arm64)…
==> Compiling WTAppDelegate.m (armv7)…
==> Compiling WTAppDelegate.m (arm64)…
==> Compiling main.m (armv7)…
==> Compiling WTRootViewController.m (arm64)…
==> Compiling WTRootViewController.m (armv7)…
==> Linking application HelloWorld (arm64)…
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/arm64/main.m.82a3dbcb.o'
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/arm64/WTAppDelegate.m.82a3dbcb.o'
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/arm64/WTRootViewController.m.82a3dbcb.o'
make[3]: *** [/opt/theos/makefiles/instance/application.mk:50: /opt/projects/helloworld/.theos/obj/debug/arm64/HelloWorld.app/HelloWorld] Error 1
make[2]: *** [/opt/theos/makefiles/instance/application.mk:50: /opt/projects/helloworld/.theos/obj/debug/arm64/HelloWorld.app/HelloWorld] Error 2
make[2]: *** Waiting for unfinished jobs....
==> Linking application HelloWorld (armv7)…
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/armv7/main.m.7a2c8ab6.o'
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/armv7/WTAppDelegate.m.7a2c8ab6.o'
arm64-apple-darwin14-clang-3.9: error: no such file or directory: '/opt/projects/helloworld/.theos/obj/debug/armv7/WTRootViewController.m.7a2c8ab6.o'
make[3]: *** [/opt/theos/makefiles/instance/application.mk:50: /opt/projects/helloworld/.theos/obj/debug/armv7/HelloWorld.app/HelloWorld] Error 1
make[2]: *** [/opt/theos/makefiles/instance/application.mk:50: /opt/projects/helloworld/.theos/obj/debug/armv7/HelloWorld.app/HelloWorld] Error 2
make[1]: *** [/opt/theos/makefiles/instance/application.mk:41: internal-application-all_] Error 2
make: *** [/opt/theos/makefiles/master/rules.mk:123: HelloWorld.all.application.variables] Error 2

Any other comments?
-------------------
SDK: https://github.com/DavidSkrundz/sdks
Toolchain: https://github.com/coolstar/iOSToolchain4Win/tree/x86_64

What versions of software are you using?
----------------------------------------
**Operating System:** Windows

**Toolchain Version:** 10.2

**SDK Version:** 12.0

**Comment by uroboro** [comment]
Which installation tutorial for Windows did you follow?

**Comment by kirb** [comment]
Closing due to lack of response.
