### ISSUE TITLE
main.xm:4:9: fatal error: 'ChatKit/CKComposition.h' file not found

### ISSUE THREAD

**Issue by mac-user669** [theos/theos#399]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Download [TextSender for Pebble](https://github.com/runnersaw/pebble-text)
2. cd to pebblesmstweak
3. `make package`

What happens?
-------------
`> Making all for tweak pebblesmstweak…
==> Preprocessing main.xm…
==> Compiling main.xm (armv7)…
main.xm:4:9: fatal error: 'ChatKit/CKComposition.h' file not found
#import <ChatKit/CKComposition.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [/Users/cooperhull/Downloads/pebble-text-master/pebblesmstweak/.theos/obj/debug/armv7/main.xm.72fe1e4b.o] Error 1
rm /Users/cooperhull/Downloads/pebble-text-master/pebblesmstweak/.theos/obj/debug/armv7/main.xm.mm
make[2]: *** [/Users/cooperhull/Downloads/pebble-text-master/pebblesmstweak/.theos/obj/debug/armv7/pebblesmstweak.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [pebblesmstweak.all.tweak.variables] Error 2`

What were you expecting to happen?
----------------------------------
I was expecting it to not have any errors, and make me a .deb

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** MacOS 10.14.4 beta (18E220a)

**Toolchain Version:** How can I see this?

**SDK Version:** 11.2

**Comment by wstyres** [comment]
Looks like you just don't have the right headers needed to build the tweak. If the GitHub repo you downloaded the source didn't provide you with them, you'll have to find the ChatKit headers from somewhere else.

**Comment by mac-user669** [comment]
Thanks! I'm talking to the dev of this tweak, and this is what he's recommending me. I'll let you know what happens...

**Comment by uroboro** [comment]
It is not a Theos knowledge issue, it is a lack of knowledge about compiled languages in general. Use google to search for the headers you need.
