### ISSUE TITLE
Entitlement support request

### ISSUE THREAD

**Issue by szcoder** [theos/theos#40]
Sorry, I didn't find a way to submit feature request so open an issue instead.
The current version of theos doesn't support using entitlement with ldid. I modified it to work around.

Open file <theos>/makefiles/targets/Darwin/iphone.mk and change line
"TARGET_CODESIGN_FLAGS ?= -S" to "TARGET_CODESIGN_FLAGS ?= -S$(CODESIGN_ENTITLEMENT)" and then define CODESIGN_ENTITLEMENT in my Makefile when needed.

Hope this is helpful for people who need it.

Regards and thanks for the great project.

**Comment by jiro9611** [comment]
Hello, I face the same issue, can anyone help me? 

I got this error log:
`Process Myproject (pid 7949) is required to have an entitlement named "com.apple.private.mobileinstall.allowedSPI" with an array containing "UninstallForLaunchServices" to call the MobileInstallation SPI.`
Here is my makefile:
```
include $(THEOS)/makefiles/common.mk
ARCHS = armv7 arm64
TARGET = iphone:latest:8.1
THEOS_DEVICE_IP=127.0.0.1
THEOS_DEVICE_PORT=2222

APPLICATION_NAME = MyProject
MyProject_FILES = main.m ZRAppDelegate.m ZRRootViewController.m AppsCleaner.m
MyProject_FRAMEWORKS = UIKit CoreGraphics
MyProject_PRIVATE_FRAMEWORKS = MobileInstallation
MyProject_LIBRARIES = applist
MyProject_LDFLAGS = -lsqlite3
MyProject_CODESIGN_FLAGS = -Sentitlements.xml

include $(THEOS_MAKE_PATH)/application.mk

after-stage::
	$(ECHO_NOTHING)chmod +s $(THEOS_STAGING_DIR)/Applications/MyProject.app/MyProject$(ECHO_END)

after-install::
	install.exec "killall -9 SpringBoard"

```
Here is my entitlements.xml, and I put this file at my project root, which is at the same level of obj, packages, Resources folder etc.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.private.mobileinstall.allowedSPI</key>
        <array>
            <string>Install</string>
            <string>Browse</string>
            <string>Uninstall</string>
            <string>Archive</string>
            <string>RemoveArchive</string>
            <string>UninstallForLaunchServices</string>
        </array>
        <key>com.apple.springboard.launchapplications</key>
        <true/>
        <key>com.apple.springboard.openapplications</key>
        <true/>
    </dict>
</plist>
```
I make package install and there is no error log, but when I run my theos app (.deb) still has the same error. How can I correctly code sign the entitlement to the theos app (.deb)?

**Comment by phamvansy** [comment]
> Hello, I face the same issue, can anyone help me?
> 
> I got this error log: `Process Myproject (pid 7949) is required to have an entitlement named "com.apple.private.mobileinstall.allowedSPI" with an array containing "UninstallForLaunchServices" to call the MobileInstallation SPI.` Here is my makefile:
> 
> ```
> include $(THEOS)/makefiles/common.mk
> ARCHS = armv7 arm64
> TARGET = iphone:latest:8.1
> THEOS_DEVICE_IP=127.0.0.1
> THEOS_DEVICE_PORT=2222
> 
> APPLICATION_NAME = MyProject
> MyProject_FILES = main.m ZRAppDelegate.m ZRRootViewController.m AppsCleaner.m
> MyProject_FRAMEWORKS = UIKit CoreGraphics
> MyProject_PRIVATE_FRAMEWORKS = MobileInstallation
> MyProject_LIBRARIES = applist
> MyProject_LDFLAGS = -lsqlite3
> MyProject_CODESIGN_FLAGS = -Sentitlements.xml
> 
> include $(THEOS_MAKE_PATH)/application.mk
> 
> after-stage::
> 	$(ECHO_NOTHING)chmod +s $(THEOS_STAGING_DIR)/Applications/MyProject.app/MyProject$(ECHO_END)
> 
> after-install::
> 	install.exec "killall -9 SpringBoard"
> ```
> 
> Here is my entitlements.xml, and I put this file at my project root, which is at the same level of obj, packages, Resources folder etc.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
>     <dict>
>         <key>com.apple.private.mobileinstall.allowedSPI</key>
>         <array>
>             <string>Install</string>
>             <string>Browse</string>
>             <string>Uninstall</string>
>             <string>Archive</string>
>             <string>RemoveArchive</string>
>             <string>UninstallForLaunchServices</string>
>         </array>
>         <key>com.apple.springboard.launchapplications</key>
>         <true/>
>         <key>com.apple.springboard.openapplications</key>
>         <true/>
>     </dict>
> </plist>
> ```
> 
> I make package install and there is no error log, but when I run my theos app (.deb) still has the same error. How can I correctly code sign the entitlement to the theos app (.deb)?

Fix it:
CODESIGN_ENTITLEMENT = entitlements.xml
MyProject_CODESIGN_FLAGS = -S$(CODESIGN_ENTITLEMENT)
