### ISSUE TITLE
Make Install Package error: No such file or directory found

### ISSUE THREAD

**Issue by TrentKnight** [theos/theos#401]
What are the steps to reproduce this issue?
-------------------------------------------
1. use command make package install

What happens?
-------------
I get an error

What were you expecting to happen?
----------------------------------
it to make my package

Any logs, error output, etc?
----------------------------
https://ghostbin.com/paste/nba87

What versions of software are you using?
----------------------------------------
Operating System: Windows Subsystem for Linux

Toolchain Version: not sure how to check this but i just installed it

SDK Version: 11.2

**Comment by TrentKnight** [comment]
also my theos/toolchain folder only has a folder named swift and the .keep file

**Comment by wstyres** [comment]
Looks like you've missed some steps when setting up theos for your device. I assume you're using some distribution of Linux. Try following https://github.com/theos/theos/wiki/Installation-Linux (specifically step 4 to get a toolchain) and also checking you have all the dependencies installed.

**Comment by TrentKnight** [comment]
okay, i found out what it was, originally i missed the part that said to reopen the console after setting up the theos environment variable so it didnt add the toolchain correctly when i tried to add it so i reinstalled it and its good now
