### ISSUE TITLE
-bash: /opt/theos/bin/nic.pl: No such file or directory

### ISSUE THREAD

**Issue by xhzth7091** [theos/theos#403]
![屏幕快照 2019-04-26 下午4 37 46](https://user-images.githubusercontent.com/13980546/56795194-7dd8c800-6842-11e9-9910-65734be6fbab.png)
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. macOS 10.13.6,Xcode10.1, I installed the theos

Theos  version is the latest
![16_39_40__04_26_2019](https://user-images.githubusercontent.com/13980546/56795112-51bd4700-6842-11e9-8176-0ef4c6ae0805.jpg)
![屏幕快照 2019-04-26 下午4 37 46](https://user-images.githubusercontent.com/13980546/56795226-90eb9800-6842-11e9-8c2d-99735625dd04.png)

**Comment by kirb** [comment]
Did you forget to use `--recursive` when initially cloning Theos? You can run `$THEOS/bin/update-theos` which will clone the submodules.

**Comment by uroboro** [comment]
Closing due to lack of response. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
