### ISSUE TITLE
update-theos: Handle cases where $THEOS isn't writable

### ISSUE THREAD

**Issue by Naville** [theos/theos#406]
Background:
On macOS theos is usually installed to ``/opt/theos``, which is fine as long as you have sudo.

However, most naive users are calling tools from the non-sudoers user, this is entirely fine.

UNTIL:
The user decides to call ``sudo $THEOS/bin/update-theos``, since sudo doesn't pass environment variables by default as least on BSD/macOS, the user would be really lost at the cryptic message ``$THEOS must be set to the location of Theos to use ``. I suggest warning the user with a message like "If you are calling with sudo, remember to pass -E" to that error message.

I'm sure this has been asked a million times, this is just my 5 cents.

Zhang

**Comment by Naville** [comment]
Also ghostbin is shutting down so related components might need an update too

**Comment by kirb** [comment]
I think a lot of people have installed Theos somewhere they own, since this hasn't been brought up before. The install instructions suggest installing to `~/theos`, or if you want to put it somewhere like `/opt/theos`, to change the ownership of that dir to yourself. But it's a good point that we should add some handling for this.

We're looking at our options for replacing Ghostbin. `make troubleshoot` hasn't worked in a while anyway since the Cloudflare DDOS protection makes it impossible for `ghost.sh` to make API calls.

**Comment by Naville** [comment]
I'm aware. However iPhoneDevWiki suggests using that path in the first place: https://iphonedevwiki.net/index.php/Theos/Setup And many other projects like MonkeyDev still depends on it too

**Comment by Naville** [comment]
And talking about ghostbin, you can actualy just use github with parameters: https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters which is imho the most appropriate one

**Comment by kirb** [comment]
Using issues in that way is neat but I don't think it's the right thing to do, slightly abusing what issues are for. Some Ghostbin hosts have appeared in the past few weeks but we're also looking at Gist. The downside is we need to ask for your GitHub login or API key, so it's not anonymous like Ghostbin, but I suspect way less likely to be abused considering you need to make an account and pass the captcha and email verification first, so it should be reliable.

**Comment by Naville** [comment]
Homebrew does similar things of asking for API key so I guess it should be fine on that side

**Comment by EthanArbuckle** [comment]
An API key would be pretty inconvenient and may have the side effect of causing people to not report their issues / bugs.

**Comment by uroboro** [comment]
https://iphonedevwiki.net/index.php/Theos/Setup contains a warning message at the top asking people to follow the GitHub wiki’s instructions.

**Comment by Naville** [comment]
Yeah but that page's content got translated and mirrored a dozen times which still uses /opt/theos , actually i reported this issue because a friend ran into it using /opt/theos read from a mirrored article

**Comment by Naville** [comment]
When you think about it, is there any reason ``update-theos`` doesn't just extract $THEOS from current script's path as the fallback plan?

**Comment by kirb** [comment]
Fixed with #656
