### ISSUE TITLE
Now that Swift 5 is released, can we start writing tweaks completely in Swift?

### ISSUE THREAD

**Issue by SwiftWinds** [theos/theos#410]
I'm really new to tweak development, so sorry if this is a silly question, but does ABI stability with the new Swift 5 allow us to add support for Swift (i.e. hooking and logos support)? Someone posted [a similar question on r/jailbreakdevelopers](https://www.reddit.com/r/jailbreakdevelopers/comments/bdbhr1/question_what_does_swift_5_mean_for_tweak/) a while back, but it didn't get much attention and I'd love to hear what the Theos maintainers think about this idea.

**Comment by kabiroberai** [comment]
You can't make Swift tweaks yet, but it should be possible some time in the future. Check <https://github.com/theos/theos/wiki/Swift> for more information on Swift support in Theos.
