### ISSUE TITLE
Language dialect cannot be set

### ISSUE THREAD

**Issue by leptos-null** [theos/theos#416]
What are the steps to reproduce this issue?
-------------------------------------------
1. Set Target_CFLAGS = -std=11
2. `make`

What happens?
-------------
The target is compiled with `c99`

What were you expecting to happen?
----------------------------------
The target is compiled with `c11`

Any logs, error output, etc?
----------------------------
Relevant extract from `make messages=1`:

```txt
clang++ -x objective-c ... -std=c11 ... -std=c99 Tweak.m
```

Any other comments?
-------------------
Theos sets `-std=c99`, and that's the dialect that's used, because it's being placed later in the flags than the "user supplied" flags.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.14.5

**Toolchain Version:** clang-1001.0.46.4, GNU Make 3.81

**SDK Version:** iOS 10.2

**Comment by kirb** [comment]
I’m going to solve this by removing `-std=c99` entirely. Xcode doesn’t specify the `-std=` flag if you haven’t overridden it in the project settings, and the current default is `gnu17`, so we should be able to rely on this behavior. In this case, if a new C standard comes about, you can specify `-std=c20` yourself. If a C standard becomes default, we adopt it automatically.

**Comment by kirb** [comment]
Fixed in 53ca676.
