### ISSUE TITLE
Apps made with theos are crashing on launch 

### ISSUE THREAD

**Issue by Wh0ba** [theos/theos#426]
What are the steps to reproduce this issue?
-------------------------------------------
1. create an app with theos
2. compile and package 
3. convert it to an .ipa and install it 

What happens?
------------
The app crashes on launch 

What were you expecting to happen?
----------------------------------
Duh... the app should run 

Any logs, error output, etc?
----------------------------
Nope for some reason the crash is not producing and kind of logs 

Any other comments?
-------------------
When installing the same ipa using Cydia Impactor
The app works flawlessly 

Note that my method of converting apps from .deb to .ipa to install them as user apps and running them used to work flawlessly on iOS 10 
So I used to compile ,convert and run with no problems 

What versions of software are you using?
----------------------------------------
**Operating System:** 12.2

**Toolchain Version:** latest

**SDK Version:** latest

**Comment by L1ghtmann** [comment]
Closing as the employed methods are now outdated and the issue likely spawned from insufficient entitlements introduced between iOS 10 and 12.2. If the issue persists with the latest Theos, paired with `make package PACKAGE_FORMAT=ipa`, please feel free to reopen.
