### ISSUE TITLE
I need help finishing the Theos installation, it is really getting in my way as I can not install nor delete anything without finishing it.

### ISSUE THREAD

**Issue by doxmg** [theos/theos#427]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Install Theos SDK Version 10.3
2. …Run “apt-get install ﻿-y --force-yes org.theos.dependenci﻿e﻿s”
3. …”Depends: rsync”

What happens?
-------------
…Run “apt —fix-broken install” but I get the problem attached in the screenshot.

What were you expecting to happen?
----------------------------------
…rsync to install

Any logs, error output, etc?
---------------------------- I posted all of my errors shown in the screenshots
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
------------------- I cannot install/remove anything in Cydia/Sileo due to this error please help my device is depending on this.
![D1142035-C9B0-41D5-98AD-7D3AE15593BE](https://user-images.githubusercontent.com/39409557/61830786-0fec6e80-ae3a-11e9-9e93-0cb573fdeaa5.png)
![A73F4662-35B4-492A-AA9D-52F6CD383208](https://user-images.githubusercontent.com/39409557/61830789-10850500-ae3a-11e9-9bfa-756b8e5481b3.png)
![04044DA8-DD82-4CA8-AC69-F45BAEA1047D](https://user-images.githubusercontent.com/39409557/61830790-10850500-ae3a-11e9-9180-c5989a5d7478.png)

…

What versions of software are you using?
----------------------------------------
**Operating System:** …iOS 11.4 (Jailbroken)

**Toolchain Version:** …iOS Toolchain (Version: 6.1-1)

**SDK Version:** …10.3

**Comment by doxmg** [comment]
The first 2 screenshots are my errors trying to fix the Theos installation and the 3rd one is an example of how I cannot manage my packages.

**Comment by DHowett** [comment]
Uninstall net.howett.theos and org.theos.dependencies using dpkg -r. It's
apt that's complaining about the dependencies, so remove the packages with
dpkg so it stops complaining.

**Comment by doxmg** [comment]
@DHowett yea I found that out earlier today and removed the packages thanks
