### ISSUE TITLE
Remove "Set up ghostbin script" from installation instructions

### ISSUE THREAD

**Issue by andermoran** [theos/theos#428]
Since ghostbin.com is no longer, this step to set up the ghostbin script should be removed.

**Comment by kirb** [comment]
I think this was removed from the initial setup steps a year ago. However ghostbin.com is still mentioned on the Help page, so I’ve [changed it](https://github.com/theos/theos/wiki/Help/_compare/1237c5f4a7820b3ad5a5f866692ea90d7c56cf49...effd969c9ad6f4c223a4a545c62b6479a47098f5) to ghostbin.co.
