### ISSUE TITLE
Unable to make package on arch linux. ldid cant execute

### ISSUE THREAD

**Issue by 00p513-dev** [theos/theos#438]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
`make package` on arch linux

What happens?
-------------
`make package` moans about being unable to execute ldid when trying to compile the tweak

What were you expecting to happen?
---------------------------------
The tweak to compile or something. This is my first tweak

Any logs, error output, etc?
----------------------------
[root@iusearchbtw firsttweak]# make package
> Making all for tweak FirstTweak…
==> Merging tweak FirstTweak…
==> Signing FirstTweak…
bash: /usr/bin/ldid: cannot execute binary file: Exec format error
make[2]: *** [/root/theos/makefiles/instance/library.mk:32: /root/firsttweak/.theos/obj/debug/FirstTweak.dylib] Error 126
rm /root/firsttweak/.theos/obj/debug/FirstTweak.dylib.9666f125.unsigned
make[1]: *** [/root/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2
make: *** [/root/theos/makefiles/master/rules.mk:112: FirstTweak.all.tweak.variables] Error 2

What versions of software are you using?
----------------------------------------
**Operating System:** Arch Linux (latest updates installed)

**Toolchain Version:**  One in wiki page on setup for Linux

**SDK Version:** 11.2

**Comment by kirb** [comment]
What is /usr/bin/ldid? The toolchain zip is meant to be placed in a specific directory inside Theos and includes ldid, no need to copy it to /usr/bin. 

Post the output of: `file /usr/bin/ldid`

**Comment by 00p513-dev** [comment]
I have the toolchain placed in the toolchain folder in $THEOS. So it is $THEOS/toolchain/linux/iphone then /bin etc. However thereis this file in /usr/bin that i dont rememember placing. Here is the output of `file`.

```
[alex@iusearchbtw ~]$ file /usr/bin/ldid
/usr/bin/ldid: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>

```

**Comment by 00p513-dev** [comment]
Right sorry for wasting your time. It turns out $THEOS wasn't defined properly. I did that and reinstalled theos and now it works. Sorry.

**Comment by kirb** [comment]
That copy of ldid is a Mach-O binary (macOS/iOS) not an ELF binary (Linux) so you’re aware. Glad you got it working.

**Comment by 00p513-dev** [comment]
Oh right i wasnt aware there was a difference. Thanks for helping.
