### ISSUE TITLE
Fatal error: 'xpc/xpc.h' file not found

### ISSUE THREAD

**Issue by krisanovdev** [theos/theos#439]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a basic xpc service with the use of nic.pl
2. Compile basic example with no changes

What happens?
---------------
Basic example not compileable via missing xpc.h header

What were you expecting to happen?
----------------------------------
There are instructions for xpc service compilation

Any logs, error output, etc?
----------------------------
main.m:1:10: fatal error: 'xpc/xpc.h' file not found
#include <xpc/xpc.h>
         ^~~~~~~~~~~
1 error generated.
make[3]: *** [/var/theos/makefiles/instance/rules.mk:192: /krisanov/httphookxpc/.theos/obj/debug/arm64/main.m.1a7e9175.o] Error 1
make[2]: *** [/var/theos/makefiles/instance/tool.mk:20: /krisanov/httphookxpc/.theos/obj/debug/arm64/httphookxpc] Error 2
make[1]: *** [/var/theos/makefiles/instance/tool.mk:11: internal-tool-all_] Error 2
make: *** [/var/theos/makefiles/master/rules.mk:112: httphookxpc.all.tool.variables] Error 2

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 12.1

**Toolchain Version:** theos 2.5.0

**SDK Version:** 10.3

**Comment by kirb** [comment]
Indeed I doubt you’ll find XPC headers in the iOS 10.3 SDK. Try 11.2 or newer?

**Comment by MrKris99** [comment]
Same issue @kirb

**Comment by MrKris99** [comment]
I should notice - I compiling on iPhone, no Mac.

**Comment by ConorTheDev** [comment]
I also received this issue before. Just added the XPC header to my project and changed the import to the project level header.

**Comment by uroboro** [comment]
Fixed in https://github.com/theos/templates/commit/7d98646871281e5b71e280e8f80d3fc27b69aeef
