### ISSUE TITLE
theos throwing about 35 errors for no reason

### ISSUE THREAD

**Issue by nn9dev** [theos/theos#440]
Oopsie

What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos
2. make

What happens?
-------------
stupid error at https://pastebin.com/Fw2ccKH5

What were you expecting to happen?
----------------------------------
well i guess i was expecting it to compile because i could get it to work on my iPhone SE just fine

Any logs, error output, etc?
----------------------------
https://pastebin.com/Fw2ccKH5

What versions of software are you using?
----------------------------------------
**Operating System:** MacOS 

**Toolchain Version:** XCode 10.2.1

**SDK Version:** 11.2

**Comment by uroboro** [comment]
Can you share your makefile?

**Comment by uroboro** [comment]
I'd think the main issue is your TARGET, `iphone:11.2:10.0` vs `iphone::11.2:10.0`. Here's a corrected version of your makefile:

```makefile
export TARGET = iphone::11.2:10.0
export ARCHS = arm64

INSTALL_TARGET_PROCESSES = backboardd

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = screendump
screendump_FILES = Tweak.xm
screendump_FRAMEWORKS = IOSurface IOKit
screendump_PRIVATE_FRAMEWORKS = IOMobileFramebuffer
screendump_CFLAGS = -w -Ivncbuild/include -Iinclude
screendump_LDFLAGS = -Lvncbuild/lib
screendump_LIBRARIES = vncserver png jpeg lzo2 ssl crypto z
 
include $(THEOS_MAKE_PATH)/tweak.mk
 
# SUBPROJECTS += screendumpprefs
# include $(THEOS_MAKE_PATH)/aggregate.mk

internal-stage::
	#PreferenceLoader plist
	$(ECHO_NOTHING)if [ -f Preferences.plist ]; then mkdir -p $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/screendump; cp Preferences.plist $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/screendump/; fi$(ECHO_END)
```

**Comment by nn9dev** [comment]
alright, that somehow fixed a lot of them but i get this now
```
kanye-tab:screendump owenwatts$ make
> Making all for tweak screendump…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Linking tweak screendump (arm64)…
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk/System/Library/PrivateFrameworks'
ld: framework not found IOMobileFramebuffer
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/owenwatts/gits/screendump/.theos/obj/debug/arm64/screendump.dylib] Error 1
rm /Users/owenwatts/gits/screendump/.theos/obj/debug/arm64/Tweak.xm.mm
make[2]: *** [/Users/owenwatts/gits/screendump/.theos/obj/debug/arm64/screendump.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [screendump.all.tweak.variables] Error 2
kanye-tab:screendump owenwatts$ 
```

which i'm going to GUESS would be fixed by adding the IOMobileFramebuffer framework from the MacOS SDK to the iPhoneOS sdk, yes?

**Comment by uroboro** [comment]
Try making use of [theos/sdks](https://github.com/theos/sdks), which are patched and contain said framework.

**Comment by nn9dev** [comment]
i don't exactly know how i would make it use the sdks in $THEOS/sdks rather than the XCode sdks :/

**Comment by uroboro** [comment]
You can set after TARGET and ARCHS

```makefile
export SYSROOT = $(THEOS)/sdks/iPhoneOS12.4.sdk
```

**Comment by uroboro** [comment]
Closing due to lack of response.
