### ISSUE TITLE
pincrush not found

### ISSUE THREAD

**Issue by MatRanc** [theos/theos#445]
![Screen Shot 2019-10-14 at 4 26 50 PM](https://user-images.githubusercontent.com/40959576/66780685-74e6bc00-ee9f-11e9-9978-9b24e37e27ab.png)
![Screen Shot 2019-10-14 at 4 27 18 PM](https://user-images.githubusercontent.com/40959576/66780703-8334d800-ee9f-11e9-940d-24f62d150fc6.png)
done!

What are the steps to reproduce this issue?
-------------------------------------------
1. Make a tweak
2. Compile with FINALPACKAGE
(FINALPACKAGE=1 make package)

What happens?
-------------
find: pincrush: No such file or directory

although it still compiles, tweaks with cephei (and possibly others) will give the infamous developer error

What were you expecting to happen?
----------------------------------
My tweak to compile with a clean name (no debug) and not have any errors relating to pngs

Any logs, error output, etc?
----------------------------
find /Users/[user]/[tweak]/.theos/_ -name \*.png -a ! -type l -exec pincrush -i {} \;
find: pincrush: No such file or directory
find: pincrush: No such file or directory
find: pincrush: No such file or directory
find /Users/[user]/[tweak]/.theos/_ \( -name \*.plist -or -name \*.strings \) -exec plutil -convert binary1 {} \;

Any other comments?
-------------------
if you forget why im doing this: https://discordapp.com/channels/349243932447604736/349251798621749261/625421549742063636

What versions of software are you using?
----------------------------------------
**Operating System:** 10.14.5

**Toolchain Version:** 10.2.1

**SDK Version:** 12.2

**Comment by menushka** [comment]
1) Install pincrush from here: https://www.howett.net/pincrush/
2) Add to path
3) Profit  🎉🎉

**Comment by kirb** [comment]
Removed the usage of pincrush in 579a494 (not yet merged to master) as I don’t believe it’s useful any more. iPhones are extremely fast now; optimising PNGs to use Apple’s special format isn’t exactly speeding anything up.
