### ISSUE TITLE
Theos clean install error

### ISSUE THREAD

**Issue by Faen668** [theos/theos#447]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … install theos as per tutorial on this page
2. … run make package on any template
3. …

What happens?
-------------
…theos kicks out the error when the command “make package” is run but compiles fine when run a second time

What were you expecting to happen?
----------------------------------
…Compile fine on first run

Any logs, error output, etc?
----------------------------
> Making all for tweak test…                       
==> Preprocessing Tweak.x…                         
==> Preprocessing Tweak.x…                         
==> Compiling Tweak.x (armv7)…                     
bash: line 1: 34343 Killed: 9               ( clang++ -x objective-c -c -I"/var/mobile/test" -I/var/theos/include -I/var/theos/vendor/include -I/var/theos/include/_fallback -include /var/theos/Prefix.pch -MT
/var/mobile/test/.theos/obj/debug/armv7/Tweak.x.cb4e7d83.o -MMD -MP -MF "/var/mobile/test/.theos/obj/debug/armv7/Tweak.x.cb4e7d83.Td" -fcolor-diagnostics -DTARGET_IPHONE=1 -O0 -Wall -ggdb -Werror -isysroot "/var/theos/sdks/iPhoneOS10.3.sdk" -miphoneos-version-min=6.0 -fmodules -fcxx-modules -fmodule-name=test -fbuild-session-file=/var/mobile/test/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session -fobjc-arc -DDEBUG -O0 -DTHEOS_INSTANCE_NAME="\"test\"" -fmodules -fcxx-modules -fmodule-name=test -fbuild-session-file=/var/mobile/test/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session -arch armv7 -std=c99 /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.m -o /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.cb4e7d83.o )                 
make[3]: *** [/var/theos/makefiles/instance/rules.mk:261: /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.cb4e7d83.o] Error 137                            
rm /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.m                                                   
make[2]: *** [/var/theos/makefiles/instance/library.mk:33: /var/mobile/test/.theos/obj/debug/armv7/test.dylib] Error 2                                     
make[2]: *** Waiting for unfinished jobs....       
==> Compiling Tweak.x (arm64)…                     
==> Linking tweak test (arm64)…                    
==> Generating debug symbols for test…             
warning: no debug symbols in executable (-arch arm64)                                                  
rm /var/mobile/test/.theos/obj/debug/arm64/Tweak.x.m                                                   
make[1]: *** [/var/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2              
make: *** [/var/theos/makefiles/master/rules.mk:111: test.all.tweak.variables] Error 2                 
Christians-iPhone:/var/mobile/test root#            

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …iOS 12.4

**Toolchain Version:** …Theos Dependencies 0.0.4

**SDK Version:** …10.3/12.2/9.2 - error happens on any SDK

**Comment by badger200** [comment]
```==> Compiling Tweak.x (armv7)…  
bash: line 1: 34343 Killed: 9 ( clang++```

This Killed: 9 seems like the most obvious culprit. I use unc0ver and I’ve battled this error for a long time and can never solve it. dmesg will complain code completely unsigned, needs to be at least adhoc signed, even though sometimes the executable IS signed. I strongly suspect it’s a time-delayed bug in MobileSubstrate because it only happens are I’ve been uptime several hours, and a reboot always fixes it.

When I switched to Substitute I almost never have this problem again.

But yea run your compile and immediately check dmesg. Mine is always 99-100% full of these bullshit Library validation overridden errors, even with Substitute, I even tweeted Pwn20wnd and he replied “None of my devices do that.” (Gee thanks for nothing.) Well ALL 3 of my devices have ALWAYS done it on ALL versions of unc0ver from 3.3 to 6.1.1 on both iOS 12.4 and 13.3.

**Comment by L1ghtmann** [comment]
This is due to Theos being installed to /var and run with root. Theos should never be installed to /var or run with root. Please reinstall Theos following the [official docs](https://theos.dev/docs/installation) if the issue persists.
