### ISSUE TITLE
Make install is broken on the last commit

### ISSUE THREAD

**Issue by AeonLucid** [theos/theos#449]
What are the steps to reproduce this issue?
-------------------------------------------
1. Update theos to last commit
2. Create fresh project
3. Run `make package install`

What happens?
-------------
```
bash: -c: line 1: syntax error: unexpected end of file
make: *** [internal-install-check] Error 2
```

Any other comments?
-------------------
Happens since commit https://github.com/theos/theos/commit/d04a1529452d59bac838ccf385cce2455c53e0d3, the one before it works.

**Comment by uroboro** [comment]
I did these changes in good faith but I'll be fixing it in the following days, thanks for reporting.

**Comment by BlueCordedRanger** [comment]
How would I go about downgrading theos to avoid this error in the meantime?

**Comment by AeonLucid** [comment]
@BlueCordedRanger if you want to use the last working commit, open the theos directory in a terminal and enter `git checkout 40857d53fe7bb4a9e299d3dab86e09f134107795`.

**Comment by BlueCordedRanger** [comment]
@AeonLucid Thank you so much!
