### ISSUE TITLE
Can't run Make Package

### ISSUE THREAD

**Issue by keepitup86** [theos/theos#450]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…It says "No such file or directory

What were you expecting to happen?
----------------------------------
…It was supposed to run it and install the package

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target '/tweak.mk'.  Stop.
Any other comments?
-------------------
…Thank you!

What versions of software are you using?
----------------------------------------
**Operating System:** …Iphone 8 plus ios 12.4

**Toolchain Version:** …6.1-1

**SDK Version:** …9.2

**Comment by kirb** [comment]
You forgot to set `$THEOS`. Please check the [install instructions](https://git.io/theosinstall) again for anything you may have missed. 

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
