### ISSUE TITLE
Theos not accepting my sdk

### ISSUE THREAD

**Issue by Witherking25** [theos/theos#451]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos on iOS 12.4
2. Try to build a project
3. Realize that theos doesn’t like the sdk I dumped from xcode

What happens?
-------------
Theos says that the tbd files in my sdk were build for a different platform and doesn’t load them

What were you expecting to happen?
----------------------------------
No errors

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
https://pastebin.com/FWhXvTEs

Any other comments?
-------------------
The sdk works on macOS Catalina

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 12.4

**Toolchain Version:** Theos Dependencies

**SDK Version:** 12.2

**Comment by uroboro** [comment]
The only toolchain that supports the iOS 12 SDK is the one in Xcode. Until they release the updated source we can't support building with that SDK outside the macOS platform.

**Comment by Witherking25** [comment]
My Mac is a vm. VMs are slow

**Comment by Witherking25** [comment]
Macs are already potatos, but mine is on another level.

**Comment by Witherking25** [comment]
What sdk should I use that works with the tool chain on the iPhone?

**Comment by uroboro** [comment]
Up to 11, if I remember correctly.

**Comment by Witherking25** [comment]
Can I use that for 12?

**Comment by uroboro** [comment]
With limitations, you can use iOS 7 SDK even.

**Comment by Witherking25** [comment]
Got it working.
