### ISSUE TITLE
Issues in makefile result in the confusing output "@printf: command not found"

### ISSUE THREAD

**Issue by KritantaDev** [theos/theos#454]
What are the steps to reproduce this issue?
-------------------------------------------
1. Use NIC.pl to create a new project
2. Rename Tweak.x to Tweak.xm but do not update makefile
3. $ make package install

What happens?
-------------
Theos outputs the confusing and somewhat useless error message "bash: @printf: command not found"

What were you expecting to happen?
----------------------------------
I think a message of some sort indicating an error in the makefile would be much more helpful as to fixing the issue and not making first time users think that there's a syntax error in their own code

Any logs, error output, etc?
----------------------------
> $ make package install
\> Making all for tweak HomePlus…
bash: @printf: command not found
make[1]: *** [before-HomePlus-all] Error 1
make: *** [HomePlus.all.tweak.variables] Error 2
$ 

Any other comments?
-------------------
Doesn't have to be a verbose error output or anything, but the first time I had this error I figured i'd erroneously included '@printf' somewhere in my tweak.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS Catalina Beta 10.15.1

**Toolchain Version:** Latest at time of submission, I set up THEOS/the entire OS last week

**SDK Version:** 9.2/11.1, issue persists across all installed SDKs and is irrelevant to the one used.

**Comment by uroboro** [comment]
Can you do `make update-theos`? There we’re a series of commits I made recently that caused this issue if you cloned somewhere in the middle of them

**Comment by kirb** [comment]
>an incorrectly capitalized file name results in a completely different but equally useless/confusing error.

What error? What should it be doing instead?

Case sensitivity is a filesystem-level thing; we aren’t going to add complex error handling to determine if you probably meant a file with the same name but differing case. In general - don’t expect Unix-alike OSes to know what you mean if you feed them a file path with incorrect case.

**Comment by KritantaDev** [comment]
> we aren’t going to add complex error handling 

Its not so much a need for complex error handling as it is any error handling whatsoever; getting "bash: @printf: command not found" makes it sound like I left a "printf" somewhere in my project

**Comment by kirb** [comment]
It’d be great if it gave that kind of debugging info, but what you’re asking for is something that needs to happen at the level of the [GNU Make](https://www.gnu.org/software/make/) project, not Theos. Sorry, Theos is only a client of Make so we’re subject to all the downsides of how it’s designed (including other annoying things like not supporting spaces in filenames).

Since this seems to be solved anyway, I’m going to close this.

**Comment by 865102930** [comment]
I have the same issue, Rename Tweak.x to Tweak.xm and modify Makefile "test_FILES=Tweak.xm".

**Comment by bensh** [comment]
still getting this error 

`make install
bash: @printf: command not found
make: *** [internal-install-check] Error 1`

**Comment by uroboro** [comment]
Can you run the following:

    pushd $THEOS
    git rev-parse HEAD
    popd

And share the output?

**Comment by bensh** [comment]
> Can you run the following:
> 
> ```
> pushd $THEOS
> git rev-parse HEAD
> popd
> ```
> 
> And share the output?

Appreciate your help

```
git rev-parse HEAD
59a75b25105041c43b016c5538d4f58d72746ea4
```

**Comment by bensh** [comment]
Made a new project called 'sportroot' and added some stuff to the Tweak.x file, and got this printf error again.

Went back to a previous project, added my Tweak code into this Tweak.x file, and it built and installed fine.
Seems very hit and miss when this error happens depending on the files Theos creates or the name of the Tweak, frustrating.

**Comment by BlakeBoxberger** [comment]
Same error here when running `make install`, on the latest version of theos, trying to install a package that was created in May of 2019.
