### ISSUE TITLE
THEOS ld: warning

### ISSUE THREAD

**Issue by Faen668** [theos/theos#456]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install Theos on Mac OS 10.15 Catalina
2. … Install latest command line tools (11.0.0.0.1.1567737322)
3. … Run Make on any template

What happens?
-------------
…
make successful with errors

What were you expecting to happen?
----------------------------------
…
no errors

Any logs, error output, etc?
----------------------------
ld: warning: building for iOS, but linking in .tbd file (/Users/USER/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for iOS Simulator

Any other comments?
-------------------
…this happened after updating from Mojave > Catalina

What versions of software are you using?
----------------------------------------
**Operating System:** … Mac OS 10.15 Catalina

**Toolchain Version:** … Xcode 11 (CLTools 11.0.0.0.1.1567737322)

**SDK Version:** … 11.2

**Comment by kirb** [comment]
Seems like a weird specific (breaking, may I add…) change made in Xcode 11. Possibly due to the new concepts of xcframeworks, which is a workaround to the unfortunate design flaw where an x86_64 binary could equally be intended for either the iOS simulator, or macOS Catalyst.

I think the best near-term solution is to just remove `i386, x86_64` from all the tbds, and later on we’ll have to split up the [lib](https://github.com/theos/lib) repository with subdirectories specific to each target platform. (The upcoming tbdv4 format would let us solve this problem in a clean way as that is also designed to work around the design flaw Catalyst poses, but aside from not existing yet, we’re sticking to tbdv1 for the widest compatibility.)

**Comment by Ic0nic0de** [comment]
> Seems like a weird specific (breaking, may I add…) change made in Xcode 11. Possibly due to the new concept of xcframeworks, which is a workaround to the unfortunate design flaw where an x86_64 binary could equally be intended for either the iOS simulator, or macOS Catalyst.
> 
> I think the best near-term solution is to just remove `i386, x86_64` from all the tbds, and later on we’ll have to split up the [lib](https://github.com/theos/lib) repository with subdirectories specific to each target platform. (The upcoming tbdv4 format would let us solve this problem in a clean way as v4 was designed to work around the design flaw Catalyst poses, but aside from it not being released yet, we’re sticking to tbdv1 for the widest compatibility.)

Thanks for the reply, so for continued usage you'd suggest rolling back to Xcode 10 or Mojave if possible?

**Comment by ConorTheDev** [comment]
Also experiencing weird issues when using Xcode 11, downgrading to Xcode 10 later and hopefully they will be resolved c:

**Comment by iosdec** [comment]
Any future fix for this? Don't have the option of rolling back OSX

**Comment by mtshare** [comment]
Same for me

**Comment by iosdec** [comment]
Installed the previous major version major version of Xcode and switched command line tools - works perfect

**Comment by anthonyvallone** [comment]
Does this stop the actual linking of the symbol & functions?
ie: the tweak wont work unless i install xcode 10.3 toolchain?

**Comment by lockdownderp** [comment]
Does this stop the actual linking of the symbol & functions?
ie: the tweak wont work unless i install xcode 10.3 toolchain?

**Comment by kabiroberai** [comment]
This is partially resolved by https://github.com/theos/lib/commit/29edf8e3f5a6f048d8121f5c83fc80b8f348b115. A more long-term solution (which would add support for platforms other than iphoneos) is to add different platforms to the TBDs as @kirb suggested.

**Comment by kabiroberai** [comment]
I've merged the fix into theos/lib's master branch so this PR can be closed whenever that submodule is updated
