### ISSUE TITLE
Projects should not require/expect a control file

### ISSUE THREAD

**Issue by leptos-null** [theos/theos#458]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a `tool` (currently `iphone/tool`)
2. `cd PROJECT`
3. `rm control`
4. `make TARGET=macosx` 

What happens?
-------------
```text
grep: PROJECT/control: No such file or directory
grep: PROJECT/control: No such file or directory
```

What were you expecting to happen?
----------------------------------
No `grep` errors

Any logs, error output, etc?
----------------------------
```shell
$ ls -a
.        ..       Makefile main.c
$ cat Makefile 
include $(THEOS)/makefiles/common.mk

TOOL_NAME = demo
demo_FILES = main.c

include $(THEOS_MAKE_PATH)/tool.mk
$ cat main.c 
int main() {
	return 0;
}
$ make TARGET=macosx:clang::10.10
grep: PROJECT/control: No such file or directory
grep: PROJECT/control: No such file or directory
> Making all for tool demo…
==> Compiling main.c (x86_64)…
==> Linking tool demo (x86_64)…
==> Generating debug symbols for demo…
==> Merging tool demo…
==> Signing demo…
$ 
```

Any other comments?
-------------------
Everything works fine, just the `grep` errors show up on every `make`. 
This error does not occur when targeting `iphoneos`.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.15.1

**Toolchain Version:** theos/theos @ badb424, Xcode 11.1

**SDK Version:** macosx:10.15

**Comment by kirb** [comment]
We do use control to set some variables internal to Theos, especially the `Version`. Not sure if we’ll ever stop using control format altogether, as it’s fairly easy to parse out things like the version from it. It’s not a hardcoded assumption that you’re deploying to deb format as such, just a design decision to specify these things in a file called control with this format.

There are still issues here though:

1. Theos’s need for control isn’t documented, so the user assumption is control is unused on non-deb targets.
2. The assumption that the file exists / bad error reporting.
