### ISSUE TITLE
Installation to checkra1n device fails

### ISSUE THREAD

**Issue by opa334** [theos/theos#459]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try to install a package to a device running the checkra1n jailbreak via "make do"

What happens?
-------------
```
dm.pl: building package `com.opa334.ccsupport:iphoneos-arm' in `./packages/com.opa334.ccsupport_1.2.1-6+debug_iphoneos-arm.deb'
==> Installing…
tar: unrecognized option `--warning=no-timestamp'
Try `tar --help' or `tar --usage' for more information.
dpkg-deb: error: tar subprocess returned error exit status 64
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1
```

What were you expecting to happen?
----------------------------------
I expected the package to install

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------
Installation of the same package works fine to a device on 12.4 running the unc0ver jailbreak

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.13.6 High Sierra

**Toolchain Version:** Xcode 10.3 / Latest commit of theos

**SDK Version:** 12.1.2

**Comment by NoisyFlake** [comment]
Did you figure it out yet? Seems like we two are the only ones with this problem. Other devs in the r/jailbreak discord said that it works for them on iOS 13.

**Comment by opa334** [comment]
Nope! Just resorted to manually transfering over the deb and installing via Filza for now.

**Comment by opa334** [comment]
Fixed by changing iproxy to the device port 22 instead of 44. It seems like there's two ssh servers running and the one on 44 has an outdated tar binary? not sure, it works now tho.

**Comment by dibas** [comment]
Thanks for the fix! Had the same problem, working now. Weird how there are two ssh servers running.

**Comment by shinvou** [comment]
For me @opa334's fix is not working, I still have the problem.

**Comment by ConorTheDev** [comment]
I installed it to /opt/theos and it worked fine

**Comment by shinvou** [comment]
When theos tries to install a package, this is $PATH:

`/binpack/usr/bin:/binpack/usr/sbin:/binpack/bin:/binpack/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin`

dpkg then uses /binpack/usr/bin/tar, which is outdated. I can't explain why not everyone has this problem. I also can't explain why $PATH is different when I ssh into the device via terminal.

**Comment by kirb** [comment]
That is the PATH for dropbear, which listens on port 44 and is set up for the binpack environment. OpenSSH is on port 22 and uses a standard PATH and the Elucubratus environment. You need to be connecting to OpenSSH.

**Comment by ConorTheDev** [comment]
```

**Comment by ConorTheDev** [comment]
```
Conors-iMac:~ conor$ iproxy 2222 22
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: [REDACTED]), port 22
Error connecting to device!```

Anyone else experiencing this when running: ``ssh root@localhost -p 2222``?

**Comment by mac-user669** [comment]
I've tried using ports 22 and 44, and it's still not working. iPhone 6s 13.3

**Comment by shinvou** [comment]
@mac-user669 read the last comment by @kirb.

**Comment by mac-user669** [comment]
>That is the PATH for dropbear, which listens on port 44 and is set up for the binpack environment. OpenSSH is on port 22 and uses a standard PATH and the Elucubratus environment. You need to be connecting to OpenSSH.

@shinvou This one? Like I said in my first comment, I've tried both 22 and 44

**Comment by jacc** [comment]
```
λ  ~ iproxy 4200 22
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 4 (serial: serial), port 22
Error connecting to device!
```
anyone else get this?

**Comment by sbingner** [comment]
> When theos tries to install a package, this is $PATH:
> 
> `/binpack/usr/bin:/binpack/usr/sbin:/binpack/bin:/binpack/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin`
> 
> dpkg then uses /binpack/usr/bin/tar, which is outdated. I can't explain why not everyone has this problem. I also can't explain why $PATH is different when I ssh into the device via terminal.

That is the default path for the dropbear binary because it needs it before you bootstrap.  When you ssh in it executes the profile and updates the path, apparently theos is connecting in a way that leaves the compiled-in path and doesn't get it updated... if you use this maybe theos would need to source /etc/profile or something.  You could easily fix it that way but I'm not sure if it should be doing that or if dropbear should be updated somehow to not have the binpack be default path if it's bootstrapped

**Comment by ckcfcc** [comment]
> I've tried using ports 22 and 44, and it's still not working. iPhone 6s 13.3

not working. TOO.  iphone 6 plus 12.4.9

**Comment by lhj217** [comment]
modify iosod by adding **source /etc/profile;**
ssh -p$hostPort root@$hostAddress "source /etc/profile;$cmdBin" $cmdArg "$packageFileOrName" || \
		panic $? "Failed."

**Comment by Squ1dd13** [comment]
I'm not using Theos, but I had this exact same issue.
The problem only seems to appear when giving a command as part of the `ssh` command:
```sh
> ssh root@blah "dpkg -i /path/to/sth.deb"
tar: unrecognized option `--warning=no-timestamp'
...
```
vs.
```sh
> ssh root@blah
iPhone > dpkg -i /path/to/sth.deb
...
```
And the second one works.

If I run `which tar` by each method:
* Inline: `/binpack/usr/bin/tar`
* Remote shell: `/usr/bin/tar`

Since `/binpack/usr/bin/tar` is the out-of-date one, you can just add `/usr/bin` to the start of the `PATH` for inline commands:
```sh
> ssh root@blah "PATH=/usr/bin:$PATH && dpkg -i /path/to/sth.deb"
```
And that works.

I don't know what important differences there are for some of the tools in `/binpack/usr/bin`, so I think it only makes sense to do this for the install command (so I wouldn't do it for all the commands, just broken ones).

**Comment by kabiroberai** [comment]
The underlying issue appears to be that `ssh <command>` uses a remote shell instead of a login shell. Rather than modifying `PATH` directly, a more robust workaround could be to do something like `ssh <ip> -t 'exec $SHELL -l -c "<command>"'` ensuring that a login shell is used.

**Comment by kirb** [comment]
If you are using checkra1n 0.12.1, upgrade. There was [a bug](https://checkra.in/releases/0.12.2-beta) where the included dropbear launch daemon would steal port 22 away from OpenSSH.

**Comment by sbingner** [comment]
Just pushed an update to checkra1n that switches it to gnu tar in the binpack and changes the default search list to find system binaries first so this should no longer be an issue *after* the next checkra1n release, whenever that is.
