### ISSUE TITLE
iOS 13 support?

### ISSUE THREAD

**Issue by qnzboi0102** [theos/theos#460]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …installed theos
2. …
3. …

What happens?
-------------
…nothing killed 9

What were you expecting to happen?
----------------------------------
…Theos nic.pl to open

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…Checkra1n Jailbreak on both iOS 12.4.3 and ios13.2.2 
What versions of software are you using?
----------------------------------------
**Operating System:** …
13.2.2 and 12.4.3
**Toolchain Version:** …
Latest
**SDK Version:** …
All none work

**Comment by kirb** [comment]
Please install Theos somewhere other than /var - exec operations are blocked by the iOS sandbox in /var for security. You could do:

```bash
# mkdir /opt
# git clone --recursive https://github.com/theos/theos.git /opt/theos
```

**Comment by qnzboi0102** [comment]
Can I make this in var?

**Comment by kirb** [comment]
I don’t understand your question. You just need to place Theos anywhere other than /var and it will work.

Closing as this is not a Theos issue, and a workaround has been provided. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
