### ISSUE TITLE
Make package error

### ISSUE THREAD

**Issue by DanteCY** [theos/theos#465]
at first the error is private framework not found .Then I download the sdk and put into theos/sdks/
and add command export SYSROOT = $(THEOS)/sdks/iPhoneOS9.3.sdk to my makefile
and make.
> Making all for bundle hcylocationbundle…
==> Copying resource directories into the bundle wrapper…
==> Linking bundle hcylocationbundle (armv7)…
ld: warning: OS version (6.0.0) too small, changing to 7.0.0
ld: warning: ignoring file /Users/hcy/Documents/tw/theos/sdks/iPhoneOS9.3.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences.tbd, building for iOS-armv7 but attempting to link with file built for unknown-unsupported file format ( 0x2D 0x2D 0x2D 0x0A 0x23 0x20 0x47 0x65 0x6E 0x65 0x72 0x61 0x74 0x65 0x64 0x20 )
ld: warning: Could not find or use auto-linked framework 'FileProvider'
ld: warning: Could not find or use auto-linked framework 'IOSurface'
ld: warning: Could not find or use auto-linked framework 'UserNotifications'
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_PSListController", referenced from:
      _OBJC_CLASS_$_XXXRootListController in XXXRootListController.m.2a8bcf47.o
  "_OBJC_IVAR_$_PSListController._specifiers", referenced from:
      -[XXXRootListController specifiers] in XXXRootListController.m.2a8bcf47.o
  "_OBJC_METACLASS_$_PSListController", referenced from:
      _OBJC_METACLASS_$_XXXRootListController in XXXRootListController.m.2a8bcf47.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/hcy/Documents/tw/hcylocationbundle/.theos/obj/debug/armv7/hcylocationbundle.bundle/hcylocationbundle] Error 1
make[2]: *** [/Users/hcy/Documents/tw/hcylocationbundle/.theos/obj/debug/armv7/hcylocationbundle.bundle/hcylocationbundle] Error 2
make[1]: *** [internal-bundle-all_] Error 2
make: *** [hcylocationbundle.all.bundle.variables] Error 2

then i cat the Preferences.tbd
hcydeMacBook-Pro-3:Preferences.framework hcy$ cat Preferences.tbd 
---
# Generated with machotbd by mstg
# https://github.com/mstg/machotbd
archs:           [ armv7, armv7s, arm64 ]
platform:        ios
install-name:    /System/Library/PrivateFrameworks/Preferences.framework/Preferences
current-version: 1.0.0
compatibility-version: 1.0.0
exports:
  - archs:            [ armv7, armv7s, arm64 ]
.So I'dont know how to fix this error.
My makefile is 
include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = hcylocationbundle
export SYSROOT = $(THEOS)/sdks/iPhoneOS9.3.sdk

hcylocationbundle_FILES = XXXRootListController.m
hcylocationbundle_INSTALL_PATH = /Library/PreferenceBundles
hcylocationbundle_FRAMEWORKS = UIKit,CoreLoaction,MapKit
hcylocationbundle_PRIVATE_FRAMEWORKS = Preferences
hcylocationbundle_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk

internal-stage::
	$(ECHO_NOTHING)mkdir -p $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences$(ECHO_END)
	$(ECHO_NOTHING)cp entry.plist $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/hcylocationbundle.plist$(ECHO_END)

**Comment by uroboro** [comment]
One issue you have is that `_FRAMEWORKS = UIKit,CoreLoaction,MapKit` should be space separated, not comma separated.

**Comment by DanteCY** [comment]
> One issue you have is that `_FRAMEWORKS = UIKit,CoreLoaction,MapKit` should be space separated, not comma separated.

thanks.

**Comment by L1ghtmann** [comment]
Just tested on Linux (WSL) with the latest non-swift Linux toolchain and iPhoneOS9.3,10.3,11.4 sdks from theos/sdks and was unable to replicate. Issue likely spawned from a malformed tbd. Feel free to reopen if the issue persists.
