### ISSUE TITLE
tar: unrecognized option `--warning=no-timestamp'

### ISSUE THREAD

**Issue by ConorTheDev** [theos/theos#466]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run ``make clean package install`` on a project

What happens?
-------------
At the installing stage it prints the following:
```
==> Installing…
tar: unrecognized option `--warning=no-timestamp'
Try `tar --help' or `tar --usage' for more information.
dpkg-deb: error: tar subprocess returned error exit status 64
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1
Conors-iMac:Lyricify conor$ 
```

What were you expecting to happen?
----------------------------------
It to install properly and restart springboard

Any logs, error output, etc?
----------------------------
```
==> Installing…
tar: unrecognized option `--warning=no-timestamp'
Try `tar --help' or `tar --usage' for more information.
dpkg-deb: error: tar subprocess returned error exit status 64
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1
Conors-iMac:Lyricify conor$ 
```

Any other comments?
-------------------
iPhone 6s, iOS 13.2.3 - checkra1n

What versions of software are you using?
----------------------------------------
**Operating System:** macOS High Sierra (10.13.6)

**Toolchain Version:** Xcode version 10.1

**SDK Version:** 13.0

**Comment by kirb** [comment]
Already answered in #459. This is currently the first pinned item - please search before filing an issue in future.

**Comment by ckcfcc** [comment]
> Already answered in #459. This is currently the first pinned item - please search before filing an issue in future.

not working!
