### ISSUE TITLE
which directory put the third frameworks? 

### ISSUE THREAD

**Issue by hnsxcxwpf2** [theos/theos#471]
I put my MySupport.framework in $THEOS/lib/

makefile is:
```
$(TOOL_NAME)_FRAMEWORKS += MySupport
```
case an error of 
```
ld: framework not found MySupport
```

**Comment by kirb** [comment]
Frameworks from $THEOS/lib/ $THEOS/vendor/lib/ need to go in `mything_EXTRA_FRAMEWORKS` rather than `mything_FRAMEWORKS`.
