### ISSUE TITLE
how to add an append header includ path . i

### ISSUE THREAD

**Issue by hnsxcxwpf2** [theos/theos#472]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
Please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places where your questions can be answered. The Theos issue tracker is only for Theos issues, not general questions.

**Comment by hnsxcxwpf2** [comment]
how to add an append header include path. 
i want add $THOES/vendor/include to header search path

**Comment by hnsxcxwpf2** [comment]
ok  thanks
