### ISSUE TITLE
where can i get the detail docs about theos config。 like variables myprogram_EXTRA_FRAMEWORKS. 

### ISSUE THREAD

**Issue by hnsxcxwpf2** [theos/theos#475]
i have read [https://github.com/theos/theos/wiki/Help](https://github.com/theos/theos/wiki/Help) and [https://github.com/theiostream/theos-ref](https://github.com/theiostream/theos-ref). but can not get the full docs about theos config.

**Comment by kirb** [comment]
Unfortunately Theos documentation is lacking. What you’re seeing is pretty much all the documentation available. There are bits and pieces scattered around the internet if you google the right keywords. See also #308.

**Comment by hnsxcxwpf2** [comment]
Thanks
