### ISSUE TITLE
Theos tweak compilation errors

### ISSUE THREAD

**Issue by localacct** [theos/theos#477]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a new tweak from Theos
2. Attempt to run "make package install"

What happens?
-------------
Error messages were seen even when compiling the templated tweak file (with all the code examples commented out) from Theos and the tweak does not get installed.

What were you expecting to happen?
----------------------------------
The tweak will compile and install onto the jailbroken iPhone

Any logs, error output, etc?
----------------------------
````
bash: line 1:  4665 Done                    swift --version
      4667 Broken pipe: 13         | head -1
      4669 Killed: 9               | cut -d'v' -f2
      4670 Killed: 9               | cut -d' ' -f2
      4672 Killed: 9               | cut -d'-' -f1

....

bash: -c: line 3: syntax error: unexpected end of file
make: *** [/var/root/theos/makefiles/package.mk:80: internal-install-check] Error 1
````

What versions of software are you using?
----------------------------------------
**Operating System:**
iOS 12.2

**Toolchain Version:**
Theos Dependencies 0.0.4

**Comment by bubrakshahik** [comment]
i need help
https://github.com/bubrakshahik/bubrakshahik.github.io/issues/1#issue-598856870

**Comment by kabiroberai** [comment]
Could you please confirm whether this is still an issue? Also, which platform are you using Theos on?

**Comment by L1ghtmann** [comment]
This is due to Theos being installed to /var/root and run with root. Theos should never be installed as or run with root. Please reinstall Theos following the [official docs](https://theos.dev/docs/installation) if the issue persists.
