### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Smikkel20** [theos/theos#480]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. run make package

What happens?
-------------
error while compiling package

What were you expecting to happen?
----------------------------------
succesfully compiling to deb file

Any logs, error output, etc?
----------------------------
<built-in>:1:10: error: non-portable path to file
      '"/Users/Gijs/theos/Prefix.pch"'; specified path differs in case from file
      name on disk [-Werror,-Wnonportable-include-path]
#include "/Users/gijs/theos/Prefix.pch"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "/Users/Gijs/theos/Prefix.pch"
2 errors generated.
make[3]: *** [/Users/gijs/test/.theos/obj/debug/arm64/Tweak.xm.6902f7f2.o] Error 1
rm /Users/gijs/test/.theos/obj/debug/arm64/Tweak.xm.mm
make[2]: *** [/Users/gijs/test/.theos/obj/debug/arm64/test.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [test.all.tweak.variables] Error 2

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** 
imac 10.13.6 (13-inch, Late 2011)

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
It seems like your Mac user folder is `Gijs`, but perhaps you’ve set `THEOS` to `gijs`. If you followed the [instructions](https://git.io/theosinstall) and you’ve set it to `~/theos`, there’s something a bit wonky about your macOS install. What do you get when you type `echo $USER, $HOME`?

**Comment by Smikkel20** [comment]
when i type `echo $USER, $HOME` I get `gijs, /Users/gijs`

**Comment by Smikkel20** [comment]
If you have this issue your probably on the second account of you mac, you can get this error away by (so far I know) installing theos on the other account and move your file to that home and running `make package`.

**Comment by kirb** [comment]
I don’t think that’s the case. I think there’s just something odd about your setup for some reason, I don’t know why. You sidestepped the issue by simply moving it somewhere else.

**Comment by Smikkel20** [comment]
Could it be that my account is just weirdly setup? If so that could be the cause.
