### ISSUE TITLE
[Logos] Redefinition Problem / Incremental Method Names

### ISSUE THREAD

**Issue by eswick** [theos/theos#484]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try to hook a method multiple times in one group

What happens?
-------------
Logos creates two hooks with the same method name, causing a redefinition error

e.g.

```
Tweak.xm:775:28: error: redefinition of '_logos_method$_ungrouped$SBDockIconListView$initWithModel$layoutProvider$iconLocation$orientation$iconViewProvider$'
static SBDockIconListView* _logos_method$_ungrouped$SBDockIconListView$initWithModel$layoutProvider$iconLocation$orientation$iconViewProvider$(_LOGOS_SELF_TYPE_INIT SBDockIconListView* __unused self, SEL __unused _cmd, id arg1, id arg2, id arg3, long long arg4, id arg5...
Tweak.xm:391:28: note: previous definition is here
static SBDockIconListView* _logos_method$_ungrouped$SBDockIconListView$initWithModel$layoutProvider$iconLocation$orientation$iconViewProvider$(_LOGOS_SELF_TYPE_INIT SBDockIconListView* __unused self, SEL __unused _cmd, id arg1, id arg2, id arg3, long long arg4, id arg5...
```

What were you expecting to happen?
----------------------------------
Expected Logos to output 

```
_logos_orig$_ungrouped$SBDockIconListView$initWithModel$layoutProvider$iconLocation$orientation$iconViewProvider$1
_logos_orig$_ungrouped$SBDockIconListView$initWithModel$layoutProvider$iconLocation$orientation$iconViewProvider$2
```

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------
I like to organize my tweaks in the following layout:

```
#pragma mark Feature 1

%hook SBFloatingDockView
- (id)init {
// Initialize some variable
}
%end

#pragma mark Feature 2

%hook SBFloatingDockView
- (id)init {
// Initialize another variable
}
%end
```

This is where the issue arises for me. I cannot hook an init method twice, to initialize variables related to different features. I have to initialize variables related to Feature 2 in the init method of the section dedicated to Feature 1, or have a dedicated init function outside of these sections. Not a big deal, just a pet peeve.

It seems to me like it shouldn't be a problem to have logos output incremental method names, as different tweaks hook the same method all the time, and MobileSubstrate manages the order. Curious on your thoughts on this.

Thanks

**Comment by DHowett** [comment]
I think the classic solution to this is to use `%group`s, and then initialize them in the order you'd like them applied in. Is that unacceptable here?

**Comment by eswick** [comment]
That's true, I suppose I could organize them that way. I prefer to use `#pragma` because of IDE integration, but using `%group`s and having an extra `#pragma` above them is still nicer than what I currently have. However, I will have to add extra code to initialize them manually. No biggie!
