### ISSUE TITLE
No such file or Directory

### ISSUE THREAD

**Issue by NOSLWB** [theos/theos#487]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Make package

What happens?
I get an error that say " ~/test
$ make package
> Making all for tweak Test…
make[2]: Nothing to be done for 'internal-library-compile'.
> Making stage for tweak Test…
bash: /home/Lionel/test/.theos/_ /DEBIAN/control: No such file or directory
make: *** [/home/Lionel/theos/makefiles/package/deb.mk:32: /home/Lionel/test/.theos/_ /DEBIAN/control] Error 1
"
What were you expecting to happen?
Make my package

Any other comments?
I am completely new to this, And i am using Cygwin64 Terminal

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10

**Toolchain Version:** Newest

**SDK Version:** Newest

![image](https://user-images.githubusercontent.com/62527647/77270981-aba0d980-6c6a-11ea-9385-601c570663c2.png)

**Comment by uroboro** [comment]
Two things:

First: can you share your makefile contents?

Second: you should be using WSL instead of Cygwin on Windows 10

**Comment by NOSLWB** [comment]
![image](https://user-images.githubusercontent.com/62527647/77369899-e5321d00-6d1c-11ea-9e69-01e83d92261c.png)

that is what I was told to type in a saw in a video I watched, I can't find any other videos on these types of things.

**Comment by Dadoum** [comment]
This error also occurs on Manjaro Linux (Arch-based distro) with latest Theos.

**Comment by kirb** [comment]
This was a breaking change in Make 4.3 which has been fixed on the `next` branch. For now, please switch to that branch. Example:

```bash
cd $THEOS
git pull origin --all
git checkout next
```

Should be merged to master soon.

**Comment by CRKatri** [comment]
Using the `next` branch breaks even more things, I can't even compile with it.

**Comment by kirb** [comment]
Can you please run `make clean all messages=yes` and copy the output to https://ghostbin.co?

**Comment by CRKatri** [comment]
This is using Arch Linux, theos next branch, and sbingner's toolchain
https://ghostbin.co/paste/ohcum

**Comment by CRKatri** [comment]
running `git cherry-pick 56ec6496b8ecc4e12797f997981548c61668f51d` while in `master` will fix `make package`

**Comment by iEmptyModz** [comment]
Help me

**Comment by kirb** [comment]
@iEmptyModz Please create a new [discussion](https://github.com/theos/theos/discussions/categories/questions) or ask on Discord at https://theos.dev/discord.
