### ISSUE TITLE
Can't compile tweak

### ISSUE THREAD

**Issue by JezWal** [theos/theos#491]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Compile the tweak

What happens?
-------------
Makefile:15: /tweak.mk: No such file or directory
make: *** No rule to make target '/tweak.mk'. Stop.

What were you expecting to happen?
----------------------------------
Make the tweak compile

Any logs, error output, etc?
----------------------------
Makefile:15: /tweak.mk: No such file or directory
make: *** No rule to make target '/tweak.mk'. Stop.

Any other comments?
-------------------
I've tried `export THEOS=/home/Jez/theos` but it doesn't work

What versions of software are you using?
----------------------------------------
**Operating System:** … Pop os (Linux)

**Toolchain Version:** … Not sure

**SDK Version:** … 13.3

**Comment by alexPNG** [comment]
Post your makefile here.

**Comment by uroboro** [comment]
It might be an issue with your shell.

If you do `export THEOS=/home/Jez/theos` followed by `echo $THEOS` does it show `/home/Jez/theos`?

**Comment by uroboro** [comment]
Closing due to lack of response. If this is still happening, please reopen the issue.
