### ISSUE TITLE
Undefined symbols for arm64 and arm64e - ___isOSVersionAtLeast symbol

### ISSUE THREAD

**Issue by alexPNG** [theos/theos#493]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create tweak.
2. Compile it with Theos in iOS.

What happens?
-------------
Theos throws an undefined symbol error:
`iPhone-de-Alexandre:/var/mobile/Downloads/TestMode2 root# make package                             
> Making all for tweak TestMode…                 
==> Preprocessing Tweak.xm…                      
==> Preprocessing Tweak.xm…                      
==> Compiling Tweak.xm (arm64)…                  
==> Compiling Tweak.xm (arm64e)…                 
==> Linking tweak TestMode (arm64e)…             
Undefined symbols for architecture arm64e:       
  "___isOSVersionAtLeast", referenced from:      
      __ZL56_logos_method$_ungrouped$UIWindow$motionEnded$withEvent$P8UIWindowP13objc_selector14UIEventSubtypeP7UIEvent in Tweak.xm.1e3e8ec6.o       
ld: symbol(s) not found for architecture arm64e  
Not signing file                                 
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)                 
make[3]: *** [/var/theos/makefiles/instance/library.mk:33: /var/mobile/Downloads/TestMode2/.theos/obj/debug/arm64e/TestMode.dylib] Error 1           
==> Linking tweak TestMode (arm64)…              
Undefined symbols for architecture arm64:        
  "___isOSVersionAtLeast", referenced from:      
      __ZL56_logos_method$_ungrouped$UIWindow$motionEnded$withEvent$P8UIWindowP13objc_selector14UIEventSubtypeP7UIEvent in Tweak.xm.174c607a.o       
ld: symbol(s) not found for architecture arm64   
Not signing file                                 
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)`

What were you expecting to happen?
----------------------------------

The tweak should be successfully compiled since I’m using the patched SDKs with all private symbols.

Any logs, error output, etc?
----------------------------
(Pasted above.)

Any other comments?
-------------------
Running my device on iOS 13.3, using the latest version of TheosInstaller for checkra1n.

I’m using checkra1n 0.9.8.1 for Linux CLI.

Latest Toolchain version available for TheosInstaller.

Using the patched SDKs provided in the repository, and iOS 12 and 13 SDKs from another source.

**Comment by alexPNG** [comment]
**Update:** compiling the tweak with a Mac solved the issue.

I’m leaving this issue open for further inspection. My guess is that the __isOSVersionAtLeast symbol is not present in the patched SDKs, and it can only be compiled by having the necessary symbols from xCode, making it impossible to use the symbol in TheosInstaller.

**Comment by uroboro** [comment]
Thanks for the heads up on the sdk issue, that would be more suitable as an issue on its own in https://github.com/theos/sdks/issues/.

Additionally, please do not compile as root and follow the official guides to setting up Theos. If you are able, try installing Theos with https://github.com/theos/theos/wiki/Installation-iOS

**Comment by eclair4151** [comment]
i fixed this by adding this to the top of the file where needed

int __isOSVersionAtLeast(int major, int minor, int patch) { NSOperatingSystemVersion version; version.majorVersion = major; version.minorVersion = minor; version.patchVersion = patch; return [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:version]; }

**Comment by alexPNG** [comment]
Thank you for the solution, it will come in handy for sure.
