### ISSUE TITLE
Compile swift?

### ISSUE THREAD

**Issue by ca13ra1** [theos/theos#495]
Attempting to compile a swift project available on GitHub. Classes are exposed to objective-c. Compiling tweak with swift file with Xcode 11 results in many errors. 

> ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
> ld: warning: Could not find or use auto-linked library 'swiftDarwin'
> ld: warning: Could not find or use auto-linked library 'swiftUIKit'
> ld: warning: Could not find or use auto-linked library 'swiftFoundation'
> ld: warning: Could not find or use auto-linked library 'swiftMetal'
> ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
> ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
> ld: warning: Could not find or use auto-linked library 'swiftDispatch'
> ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
> ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
> ld: warning: Could not find or use auto-linked library 'swiftCore'
> ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
> 

Compiling with Xcode 10.2.1 works, no errors but the tweak immediately crashes when testing the tweak using libswift. Unknown culprit when checking the crash logs. Any help would be greatly appreciated. Is it not possible to compile a tweak wth swift successfully?

**Comment by kabiroberai** [comment]
This bug should have been resolved by 83e019b3fc4cb1c98c562e847334ff47aa1b1a74 (currently in `next`). Please switch to the `next` branch and check whether the issue persists.

**Comment by ca13ra1** [comment]
Will try that, thank you @kabiroberai

**Comment by ca13ra1** [comment]
Segmentation fault: 11 Xcode Version 11.4 (11E146) [log](https://ghostbin.co/paste/475zh) @kabiroberai

**Comment by kabiroberai** [comment]
Could you please share your Makefile? Also, please provide the entire output of `make clean all messages=yes`

**Comment by ca13ra1** [comment]
@kabiroberai here's the [makefile](https://ghostbin.co/paste/psrco) and [output](https://ghostbin.co/paste/tme94)

**Comment by kabiroberai** [comment]
Thanks; I believe kirb was experiencing a similar bridging-header related crash a while ago. @kirb could you take a look and check whether this is the same issue?

**Comment by ca13ra1** [comment]
@kabiroberai I have previously contacted him but I wasn’t given a definitive answer or a reply about what could be the issue. He said it was either an issue with my code but it works just fine in Xcode when importing the swift file manually.

**Comment by kabiroberai** [comment]
Can you check whether a basic swift project without a bridging header compiles? If it does, at least we’ll have isolated the issue a little more.

**Comment by ca13ra1** [comment]
Yes, I can try that and see what happens.
