### ISSUE TITLE
Not able to hook into Objective C Method

### ISSUE THREAD

**Issue by chetansrm** [theos/theos#496]
I am trying to make to tweak to hook into the application other than SpringBoard. I picked up [DVIA](https://github.com/prateek147/DVIA). I want to hook into the following objective-C method "_-(BOOL)isLoginValidated"_ [defined here](https://github.com/prateek147/DVIA/blob/master/DVIA/DamnVulnerableIOSApp/DamnVulnerableIOSApp/RuntimeManipulationDetailsVC.m)

Below, I have mentioned my tweak inputs:
**Tweak Setup**
------------------------------
  [1.] iphone/activator_event
  [2.] iphone/application_modern
  [3.] iphone/application_swift
  [4.] iphone/flipswitch_switch
  [5.] iphone/framework
  [6.] iphone/library
  [7.] iphone/preference_bundle_modern
  [8.] iphone/tool
  [9.] iphone/tool_swift
  [10.] iphone/tweak
  [11.] iphone/xpc_service
Choose a Template (required): 10
Project Name (required): dviaHook
Package Name [com.yourcompany.dviahook]: 
Author/Maintainer Name [System Administrator]: 
[iphone/tweak] MobileSubstrate Bundle filter [com.apple.springboard]: com.highaltitudehacks.dvia
[iphone/tweak] List of applications to terminate upon installation (space-separated, '-' for none) [SpringBoard]: 
Instantiating iphone/tweak in dviahook/...
Done.

**Make File Setup**
 export THEOS = /var/theos
ARCH = armv7 arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = dviaHook

dviaHook_FILES = Tweak.x
dviaHook_CFLAGS = -fobjc-arc
dviaHook_FRAMEWORK = UIKit
include $(THEOS_MAKE_PATH)/tweak.mk

**Setup Tweak.x**
%hook RuntimeManipulationDetailsVC

-(_Bool)isLoginValidated{

NSLog(@"Login method called");

return YES;

 }
...................................................................................
I moved the relevant headers inside 

> /var/theos/include

 directory and installed my tweaks on using the above files. But whenever I call the respective application/method (DVIA), I don't see any Log in the console. 

I am able to hook into the iOS system-level method but not able to hook into any installed application.

Can you please help me out?

**Comment by uroboro** [comment]
You left this step empty "List of applications to terminate upon installation (space-separated, '-' for none) [SpringBoard]:" meaning it will kill SpringBoard instead of this DVIA app. That'll save you from unnecessary resprings.

Other than that, the only issue I see is using `_Bool` instead of `BOOL`.

Logging is dependent on which SDK you used to build with and which version of iOS you are using.

**Comment by chetansrm** [comment]
@uroboro Thank you for the suggestion I tried all these however still not able to hook into any of the method. Below mentioned are platform details:

iPhone Model: **iPhone7,2**
iOS Version: **ProductVersion: 12.1.2**
SDK: **iPhoneOS11.2sdk**

**Comment by lucian-ma** [comment]
> @uroboro Thank you for the suggestion I tried all these however still not able to hook into any of the method. Below mentioned are platform details:
> 
> iPhone Model: **iPhone7,2**
> iOS Version: **ProductVersion: 12.1.2**
> SDK: **iPhoneOS11.2sdk**
> Jailbreak: **Unc0ver**


I get same problem , did you sovled it？

**Comment by chetanlucid** [comment]
> > @uroboro Thank you for the suggestion I tried all these however still not able to hook into any of the method. Below mentioned are platform details:
> > iPhone Model: **iPhone7,2**
> > iOS Version: **ProductVersion: 12.1.2**
> > SDK: **iPhoneOS11.2sdk**
> > Jailbreak: **Unc0ver**
> 
> I get same problem , did you sovled it？

Nope. I tried with the different SDK and other solutions as well. I contacted other tweak developers as well they asked me to follow the same approach that we are doing already but no luck

**Comment by chetansrm** [comment]
> > @uroboro Thank you for the suggestion I tried all these however still not able to hook into any of the method. Below mentioned are platform details:
> > iPhone Model: **iPhone7,2**
> > iOS Version: **ProductVersion: 12.1.2**
> > SDK: **iPhoneOS11.2sdk**
> > Jailbreak: **Unc0ver**
> 
> I get same problem , did you sovled it？

Nope. I tried with the different SDK and other solutions as well. I contacted other tweak developers as well they asked me to follow the same approach that we are doing already but no luck

**Comment by L1ghtmann** [comment]
Can confirm the hook is functional with the latest Theos. This is almost certainly due to Theos being installed to /var and presumably run with root. Theos should never be installed to /var or run with root. Please reinstall Theos following the [official docs](https://theos.dev/docs/installation) if the issue persists.
