### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by bubrakshahik** [theos/theos#497]
I made a repo on github with my user name including that is bubrakshahik; so i made it like this bubrakshahik.github.io and put the index.html, Release, Packages and Packages.bz2.
and .deb file of my package and data folder also in it.
Repo added successfully loaded the tweaks also.
But when i try to install it always comes with these two errors in cydia

Method https has died unexpectedly!
Sub-process https received signal5.

And i install .deb via filza tweak is working perfectly o.k. Please Help

![aaaa](https://user-images.githubusercontent.com/51922221/79122979-83f8e900-7db2-11ea-8dc4-c821fc677eba.jpg)
![bbbbb](https://user-images.githubusercontent.com/51922221/79122984-852a1600-7db2-11ea-90ad-971e28b087dc.jpg)
![WhatsApp Image 2020-04-13 at 4 43 33 PM](https://user-images.githubusercontent.com/51922221/79122986-85c2ac80-7db2-11ea-9b87-3974f6e9c666.jpeg)

**Comment by uroboro** [comment]
This is not an issue regarding Theos. You'll have better luck asking in the jailbreak developer Discord or subreddit.

**Comment by bubrakshahik** [comment]
i am not so nobe bro it is regarding to theos and github i know cydia and jailbreak well
