### ISSUE TITLE
Hello, I install theos using pdf link 

### ISSUE THREAD

**Issue by bubrakshahik** [theos/theos#498]
Hello, I install theos using coolstar pdf link which is;

https://www.youtube.com/redirect?q=https%3A%2F%2Fcoolstar.org%2Ftheos.pdf&redir_token=-8ZsLly8hPVc66QPdfNyjGFhjk18MTU4NjgwNzEzN0AxNTg2NzIwNzM3&event=video_description&v=OwEL64vCKaU

But these two commands are not going through  
error
-bash: wget: command not found
commands;
wget http://iphone.howett.net/sdks/dl/iPhoneOS8.1.sdk.tbz2  
 tar xvf iPhoneOS8.1.sdk.tbz2 

so i download master-sdk 'and also tied sdk 13 too' and put it to sdk folder properly in theos
And when i put this command image attached please check,
~/theos/bin/nic.pl  
 
cygwin toolchain sdk installed
windows 10
if i am wrong please guide me how to install it properly

![theos](https://user-images.githubusercontent.com/51922221/79124269-624d3100-7db5-11ea-89a6-bdade425b116.jpg)

**Comment by kirb** [comment]
Those instructions are outdated but I think you definitely missed something. Please try again with the [official instructions](https://git.io/theosinstall).

**Comment by bubrakshahik** [comment]
i go with this too but these commands did not works for me idk,

curl -LO https://github.com/theos/sdks/archive/master.zip
 TMP=$(mktemp -d)
 unzip master.zip -d $TMP
 mv $TMP/sdks-master/*.sdk $THEOS/sdks
 rm -r master.zip $TMP

**Comment by demhademha** [comment]
Make sure you’ve installed THEOS dependencies first

**Comment by kabiroberai** [comment]
Closing since afaict there isn't an actual issue with Theos here. For support installing Theos, consider asking elsewhere such as [r/jailbreakdevelopers](https://reddit.com/r/jailbreakdevelopers) or the #development channel in the [r/jailbreak Discord server](https://discord.gg/jb).
