### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by mateeuslinno** [theos/theos#501]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a simple project
2 make package

What happens?
-------------
I created a simple projetc when i used 'make packeges' i see error.

What were you expecting to happen?
----------------------------------
XPC error

Any logs, error output, etc?
----------------------------
```
make package
> Making all for tool faceidbypass…
==> Compiling main.m (armv7)…
main.m:1:10: fatal error: 'xpc/xpc.h' file not found
#include <xpc/xpc.h>
         ^~~~~~~~~~~
1 error generated.
```

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS - Catalina 10.15.3

**Toolchain Version:**  2.5.0

**SDK Version:** 11.2

**Comment by ScenicJaguar101** [comment]
Same problem on macOS Catalina 10.15.1

**Comment by uroboro** [comment]
Please confirm if this issue happens when using the xpc_service template. If so, this issue will be fixed in for the next release of Theos

**Comment by uroboro** [comment]
Fixed in https://github.com/theos/templates/commit/7d98646871281e5b71e280e8f80d3fc27b69aeef
