### ISSUE TITLE
Strange theos warning/erros, eg: rules.mk:37: warning: overriding commands for target

### ISSUE THREAD

**Issue by joeyjurjens** [theos/theos#502]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
I bought a new macbook which has been restored completely.
I downloaded & installed xCode & then followed the instructions on the theos installation page.
I tried to compile a simple project, with no changes to tweak.xm or anything yet. 

What happens?
-------------
It's first giving me some warnings about what the rules.mk file does
It's also generating a empty file called "Theos" two directories back from the actual project I'm trying to compile (which seems very odd to me)

What were you expecting to happen?
----------------------------------
A clean compile without errors.

Any logs, error output, etc?
----------------------------
make package output: https://pastebin.com/nNBFZabv
make package messages=yes output: https://pastebin.com/dkS0z1SD

Any other comments?
-------------------
I didn't download xCode from AppStore due the fact I run on High Sierra. I downloaded it from the apple developers website, but this should come with all requirements aswell I think.

When I do the installation progress on my old 2012 macbook, I'm not getting these errors so I follow the instructions correctly.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS High Sierra v10.13.6

**Toolchain Version:** Unsure how to check?

**SDK Version:** 12.1 (xCode one)

**Comment by kirb** [comment]
Your pathname has spaces. Spaces are the enemy of Make - it uses them as the list delimiter, as you may have seen yourself in `mything_FILES`, `mything_FRAMEWORKS`, etc, so having spaces in a pathname just isn’t a supported thing. Theos actually smartly works around it by making a symlink to your project at `/tmp/theos`, and pretending from then on that `/tmp/theos` is your project path. Or, it’s meant to be doing that, at least.

The easiest solution here is to just rename your Theos Projects folder to not have spaces. However, we should look into this.

Does the path on your old machine have spaces? If so, perhaps you’re using an older version of Theos where this was working. It’d be useful to know what commit that is so I have a starting point to find out (`git bisect`) where this may have broken. Could you run `git rev-parse HEAD` inside the Theos directory and paste the output here?

**Comment by joeyjurjens** [comment]
> Your pathname has spaces. Spaces are the enemy of Make - it uses them as the list delimiter, as you may have seen yourself in `mything_FILES`, `mything_FRAMEWORKS`, etc, so having spaces in a pathname just isn’t a supported thing. Theos actually smartly works around it by making a symlink to your project at `/tmp/theos`, and pretending from then on that `/tmp/theos` is your project path. Or, it’s meant to be doing that, at least.
> 
> The easiest solution here is to just rename your Theos Projects folder to not have spaces. However, we should look into this.
> 
> Does the path on your old machine have spaces? If so, perhaps you’re using an older version of Theos where this was working. It’d be useful to know what commit that is so I have a starting point to find out (`git bisect`) where this may have broken. Could you run `git rev-parse HEAD` inside the Theos directory and paste the output here?

Oh wow, this is it indeed. I couldn't find any answer like this online, might have searched the wrong terms. On my old machine my folder had no spaces, so unfortunately I can't give you a starting point.

Thanks allot!

**Comment by kirb** [comment]
No worries, thanks for reporting 🙂

I’m mistaken, the `/tmp/theos` workaround is for Theos itself being installed somewhere with spaces. Project paths with spaces aren’t supported at the moment. Added a check in b9e0f65 so we can display a useful error message instead of blowing up.
