### ISSUE TITLE
ld: unrecognised emulation mode: ultiply_defined

### ISSUE THREAD

**Issue by tmded** [theos/theos#505]
What are the steps to reproduce this issue?
-------------------------------------------
I am unsure how to reproduce this issue this is what i did at the time
1. checkout next 
2. pull 
3. checkout master

What happens?
-------------
linking fails with the error 
`ld: unrecognised emulation mode: ultiply_defined`
this is because ld is being passed the -multiply_defined flag for some reason

What were you expecting to happen?
----------------------------------
for it to finish linking with no errors

Any other comments?
-------------------
To fix this run git pull --force after checking out master

What versions of software are you using?
----------------------------------------
**Operating System:** bedrock linux (manjaro + debian)  

**SDK Version:** 11.2 but this occured with any sdk i used

**Comment by uroboro** [comment]
Which version of `ld` do you have?

**Comment by JesseB0rn** [comment]
Same issue here, I have ld 2.34

**Comment by tmded** [comment]
I no longer have this issue however talking to people about it, it appears to consistently affect ubuntu 20.04 wsl enviroments. 18 does not have this issue.

**Comment by JesseB0rn** [comment]
I also have the wsl on ubuntu 20.04

**Comment by tmded** [comment]
Use Ubuntu 18 on wsl I haven’t met anyone with the issue there.

**Comment by JesseB0rn** [comment]
I tried with ubuntu 18 on wsl, issue persists

**Comment by kabiroberai** [comment]
Closing in favor of #528
