### ISSUE TITLE
Fatal error: 'theos/BackwardsCompat.h' file not found w/o `-DTHEOS_LEAN_AND_MEAN`

### ISSUE THREAD

**Issue by jacobcxdev** [theos/theos#513]
Compiling without `ADDITIONAL_CFLAGS = -DTHEOS_LEAN_AND_MEAN` results in the following issue.

It's annoying.

What are the steps to reproduce this issue?
-------------------------------------------
1. Make a new project
2. Add some code 
3. Run `make`

What happens?
-------------
```
In file included from <built-in>:1:
/Users/jacob/.theos/Prefix.pch:22:11: fatal error: 'theos/BackwardsCompat.h' file not found
                #import <theos/BackwardsCompat.h>
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
```

What were you expecting to happen?
----------------------------------
Successful compilation.

Any logs, error output, etc?
----------------------------
```
In file included from <built-in>:1:
/Users/jacob/.theos/Prefix.pch:22:11: fatal error: 'theos/BackwardsCompat.h' file not found
                #import <theos/BackwardsCompat.h>
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Any other comments?
-------------------
Nope.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.15.4

**Toolchain Version:** …

**SDK Version:** 13.5

**Comment by kirb** [comment]
I think you force updated the vendor/include/ submodule to the HEAD commit, rather than the one the Theos repo is pointed to. If you do `git status`, is vendor/include listed as modified?

**Comment by KritantaDev** [comment]
I say that if there's an issue here, it probably shouldn't get patched 😛

**Comment by jacobcxdev** [comment]
> I think you force updated the vendor/include/ submodule to the HEAD commit, rather than the one the Theos repo is pointed to. If you do `git status`, is vendor/include listed as modified?
> 
> Edit: I think it’s actually the opposite - you updated Theos but not submodules. Try `git submodule update --init --recursive`.

You're right, it does show up as modified:
```
❯ git status
On branch kabiroberai/swift-driver
Your branch is up to date with 'origin/kabiroberai/swift-driver'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   vendor/include (new commits, modified content, untracked content)
	modified:   vendor/lib (new commits, modified content, untracked content)
```

It doesn't let me update submodules either:
```
❯ git submodule update --init --recursive
error: Your local changes to the following files would be overwritten by checkout:
	Celestial/AVSystemController.h
	SpringBoard/VolumeControl.h
	UIKit/UIFunctions.h
	UIKit/UIPanGestureRecognizer+Private.h
	UIKit/UIStatusBarItem.h
	UIKit/UIWindow+Private.h
Please commit your changes or stash them before you switch branches.
error: The following untracked working tree files would be overwritten by checkout:
	BaseBoard/BSAuditToken.h
	BaseBoard/BSProcessHandle.h
	BatteryCenter/BCBatteryDevice.h
	BatteryCenter/BCBatteryDeviceController.h
	BluetoothManager/BluetoothDevice.h
	BluetoothManager/BluetoothManager.h
	BluetoothManager/RemoteDeviceManager.h
	BulletinBoard/BBSettingsGateway.h
	FrontBoard/FBSMutableSceneSettings.h
	FrontBoard/FBSSceneSettings.h
	FrontBoard/FBSSceneSettingsDiff.h
	FrontBoardServices/FBSOpenApplicationOptions.h
	FrontBoardServices/FBSProcessHandle.h
	GeoServices/GEOCelestialBody.h
	GeoServices/GEOCelestialEphemeris.h
	GeoServices/GEOEquatorialCelestialBodyData.h
	GeoServices/GEOHorizontalCelestialBodyData.h
	GeoServices/GEOSolarEclipticCelestialBodyData.h
	MediaPlayer/MPAVRoutingController.h
	MediaPlayer/MPAVRoutingSheet.h
	PersonaKit/PRLikeness.h
	PersonaUI/PRLikenessView.h
	PersonaUI/PRMonogram.h
	PersonaUI/PRMonogramView.h
	launch.h
Please move or remove them before you switch branches.
Aborting
error: Your local changes to the following files would be overwritten by checkout:
	CydiaSubstrate.framework/CydiaSubstrate.tbd
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '159a952c71bba3e7e3ae68b16d29c7fc549f5cdc' in submodule path 'vendor/include'
Unable to checkout '8df1bccbc66922d7b5d7b7c86d18dadc1d87ef91' in submodule path 'vendor/lib'
```

**Comment by ifisq** [comment]
Hey I just ran across the same issue, running `make update-theos` in one of my projects fixed the issue. I think it's like kirb said, the submodules you have come from the wrong commit, so running that should restore your THEOS to the main repo's version.

**Comment by uroboro** [comment]
Closing due to lack of response. If this is still happening, please fill out the issue template as you can find [here](https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE.md).
