### ISSUE TITLE
Wiki Pages for iOS and Linux Contain Outdated Toolchain

### ISSUE THREAD

**Issue by CRKatri** [theos/theos#517]
The wiki pages for both Linux and iOS recommend outdated toolchains incapable of compiling for arm64e.

For iOS, the ideal solution is to create a meta-package containing these depends: 
`clang, ld64, odcctools, make, ldid, git`
This will take the place of theos dependencies package and download an arm64e compatible toolchain from elucubratus, however, this will not work with the chimera bootstrap and am unsure if that is possible to achieve. 

For Linux the code snippet for downloading the toolchain should be replaced by
```sh
curl https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64e-clang-toolchain.tar.lzma -Lo toolchain.tar.lzma
mkdir -p $THEOS/toolchain/linux/iphone/
tar xf toolchain.tar.lzma -C $THEOS/toolchain/linux/iphone
rm toolchain.tar.lzma
```

**Comment by tylerwolf35** [comment]
If you use the tar command that you have created, the archive directory will remain. This means that the proper command would be `sudo tar --strip-components=1 xf toolchain.tar.gz -C $THEOS/toolchain/linux/iphone`.

**Comment by CRKatri** [comment]
The `-C` argument makes the iphone directory the output, so that is not a problem. I have tested it and verified that it works.

**Comment by nzaar9** [comment]
[https://gist.github.com/cbyrne/ffb790ff70311c17d23552b25fc54ac3#file-arm64e-linux-sh](url)

**Comment by CRKatri** [comment]
That includes unnecessary steps, the need for them was removed with a recent commit

**Comment by uroboro** [comment]
For iOS the Theos Dependencies package _is_ a meta-package.

**Comment by CRKatri** [comment]
However it is a meta package with the wrong depends. It installs coolstar’s toolchain which isn’t compatible with arm64e and hasn’t been updated in about 4 years

**Comment by CRKatri** [comment]
Oh, uroboro, I just realized you put up the theos dependencies package, perhaps it’s could be updated to prefer bingner’s toolchain but install coolstar’s if bingner’s is not available. That way there won’t be two different packages.

**Comment by kabiroberai** [comment]
Merging into #551.
