### ISSUE TITLE
Error Compiling preference bundle - Ubuntu WSL1

### ISSUE THREAD

**Issue by respiredev** [theos/theos#518]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create Project
2. Create Preference Bundle for Project
3. Try to "make package"

What happens?
-------------
Error when trying to make the preference bundle. 

What were you expecting to happen?
----------------------------------
Compile the project

Any logs, error output, etc?
----------------------------
Error output: https://ghostbin.co/paste/b7xyd

Project makefile: https://ghostbin.co/paste/t6x4u

Preference Bundle makefile: https://ghostbin.co/paste/eunh8

Any other comments?
-------------------
If I "make package" **WITHOUT** a preference bundle for my project, the project successfully compiles

What versions of software are you using?
----------------------------------------
**Operating System:** Using Ubuntu 18.04 WSL(Microsoft Store version) on Windows 10 1909

**Toolchain Version:** Using Toolchain downloaded from the Theos installation guide

**SDK Version:** Using Theos patched 11.2 SDK

**Comment by uroboro** [comment]
Is this issue fixed? If so, how?
