### ISSUE TITLE
Using #include inside .s files causes hang

### ISSUE THREAD

**Issue by qwertyuiop1379** [theos/theos#520]
I understand if these issues are not a high priority, I just wanted to throw them out there.

I'm using Theos to assemble a tool I'm writing in arm64 assembly and deploy it to my device. However, using the `#include` directive in .s files causes Theos to hang. Gets stuck here:

    $ make all
    > Making all for tool chip64…

Another thing is that when assembling .s files, Theos will add a bunch of unused compiler flags, even while using `THEOS_LEAN_AND_MEAN`: https://paste.bingner.com/paste/5dj8o

Using sbingner's arm64e toolchain

**Comment by sbingner** [comment]
please use `make all messages=yes` so you can see what it was doing when it hung

**Comment by qwertyuiop1379** [comment]
I figured it out, I had to change the file extension to `.S` instead of `.s`. Apparently lowercase file extension isn't supposed to have preprocessor info.
