### ISSUE TITLE
Deb error 60

### ISSUE THREAD

**Issue by demhademha** [theos/theos#522]
Hi, whilst compiling a tweak, I get the following error 
Making all for tweak dockify…
==> Preprocessing Tweak.x…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Compiling Tweak.x (armv7)…
==> Linking tweak dockify (armv7)…
==> Linking tweak dockify (arm64)…
rm /theosapps/dockify/.theos/obj/debug/arm64/Tweak.x.m
rm /theosapps/dockify/.theos/obj/debug/armv7/Tweak.x.m
==> Merging tweak dockify…
==> Signing dockify…
> Making stage for tweak dockify…
/var/root/theos/bin/fakeroot.sh: line 46:  3946 Killed: 9               $fakeroot $cmd
make: *** [/var/root/theos/makefiles/package/deb.mk:60: internal-package] Error 137

Any help would be appreciated

**Comment by kirb** [comment]
Please fill out the [issue template](https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by demhademha** [comment]
Would you like me to resubmit my issue, or to eddit this one?

**Comment by kirb** [comment]
Whichever is easiest for you.
