### ISSUE TITLE
Theos trying to link phantom object files

### ISSUE THREAD

**Issue by jacobcxdev** [theos/theos#524]
What are the steps to reproduce this issue?
-------------------------------------------
1. [Download this sample project](https://github.com/theos/theos/files/4805235/Test.zip)
2. Run `make` in the root project dir

What happens?
-------------
Theos tries to link a phantom object file.

What were you expecting to happen?
----------------------------------
Either Theos to link an existing object file, or to generate the phantom object file.

Any logs, error output, etc?
----------------------------
https://paste.mod.gg/ibukeyoyaf.coffeescript

Any other comments?
-------------------
This is a really hacky 'solution' to trying to share a Swift class between a project and subprojects.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.15.5

**Toolchain Version:** …

**SDK Version:** iOS 13.5

**Comment by kirb** [comment]
Fix PR was merged ages ago, so this can be closed.

**Comment by kirb** [comment]
Oops, this is only merged into the orion branch, so will reopen. GitHub will close it when merged to master.

**Comment by jacobcxdev** [comment]
Adam moment
