### ISSUE TITLE
Invocation of su with procursus

### ISSUE THREAD

**Issue by demhademha** [theos/theos#526]
The procursus bootstrap is not compatible with theos's su invocation as it uses  BSD su

**Comment by uroboro** [comment]
Would this be fixed with https://github.com/theos/theos/pull/527?

**Comment by demhademha** [comment]
> Would this be fixed with https://github.com/theos/theos/pull/527?

yes it would

**Comment by uroboro** [comment]
Fixed in https://github.com/theos/theos/pull/618
