### ISSUE TITLE
Wiki Pages for Linux Contains Wrong Prerequisites For Linux Mint 20

### ISSUE THREAD

**Issue by SarahH12099** [theos/theos#532]
The wiki pages for Linux don't contain new the prerequisite needed by Linux Mint 20 for compiling.

For Linux Mint 20 a new prerequisite is libtinfo5 which is needed for building now.

sudo apt install -y libtinfo5

**Comment by kabiroberai** [comment]
Closing in favor of #551; that issue covers this as well as a bunch of other changes
