### ISSUE TITLE
PACKAGE_VERSION trick to build debs with clear version number no longer works

### ISSUE THREAD

**Issue by Naville** [theos/theos#542]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
```
TARGET := iphone:clang:latest:7.0
PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION) #STFU Theos
include $(THEOS)/makefiles/common.mk
```

What happens?
-------------
Created deb no longer has the ``.deb`` suffix

What were you expecting to happen?
----------------------------------

Deb got created successfully with proper extension

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------

I was trying to prevent Theos from adding a suffix like ``-18.deb`` to my packages. However after following [@DHowett 's guide on Reddit](https://www.reddit.com/r/jailbreakdevelopers/comments/2mmc98/how_to_stop_theos_from_adding_a_build_number_to/) I got a deb which filename is ``PackageID-VERSION`` without the ``.deb`` suffix.

I'm current using Theos at ``d9b6b86c7f902dfaab9b69b415629103d1ff0ebd``

What versions of software are you using?
----------------------------------------
**Operating System:**  macOS

**Toolchain Version:**  N/A

**SDK Version:** N/A

**Comment by sbingner** [comment]
You can make it not add suffixes via make FINALPACKAGE=1 package which is probably better than that hack.  OTOH it not adding a deb suffix when you set the version does also seem like a bug.

**Comment by kirb** [comment]
Remove the comment.

If you run with `messages=yes`, you’ll notice:

```
set -o pipefail; (COPYFILE_DISABLE=1 /Users/kirb/theos/bin/fakeroot.sh -p "/tmp/test/.theos/fakeroot" -r dm.pl -Zlzma -z0 -b "/tmp/test/.theos/_" "./packages/com.example.test_0.0.1 _iphoneos-arm.deb")
dm.pl: building package `com.example:iphoneos-arm' in `./packages/com.example_0.0.1'
```

There’s a space at the end of the version! Unfortunately, Make just isn’t smart about things like this. It’s possible this was caused by recent breaking behavior changes from Make 4.3 (which also caused some trouble for Theos’s staging rules). This issue though reveals a bug in fakeroot.sh. The spaces in the script’s quoted arguments are being lost. Need to look into that.

**Comment by Naville** [comment]
Thanks!
