### ISSUE TITLE
Tweak.x:6:16: error: use of undeclared identifier 'MSHookIvar'

### ISSUE THREAD

**Issue by liuxingIphone** [theos/theos#544]
**What are the steps to reproduce this issue?**
-------------------------------------------
1. install theos，Configure environment variables
2. #include <substrate.h>

%hook ALUAccuratePWDView
-(void)onNext
{
	UIView * v1 = MSHookIvar <UIView *>(self,"_loginBox");
	UIView * v2 = MSHookIvar <UIView *>(v1,"_passwordInputBox");
	UITextField * pwd = MSHookIvar <UITextField *>(v2,"_textField");
    [[[UIAlertView alloc] 
    	initWithTitle:@"密码" 
    	message:pwd.text 
    	delegate:nil 
    	cancelButtonTitle:@"cancle" 
    	otherButtonTitles:nil, nil] show];

}

%end
3.make

**What happens?**

 make

==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://github.com/theos/theos/wiki/Parallel-Building
> Making all for tweak AlipayPwdDemo…
==> Compiling Tweak.x (armv7)…
Tweak.x:6:28: error: unexpected interface name 'UIView': expected expression
        UIView * v1 = MSHookIvar <UIView *>(self,"_loginBox");
                                  ^
Tweak.x:6:16: error: use of undeclared identifier 'MSHookIvar'
        UIView * v1 = MSHookIvar <UIView *>(self,"_loginBox");
                      ^
Tweak.x:6:36: error: expected expression
        UIView * v1 = MSHookIvar <UIView *>(self,"_loginBox");

**Comment by kirb** [comment]
MSHookIvar uses C++ features and can’t be used from an ObjC (.m or Logos .x) file. To use it, you need to rename the file to .mm or .xm respectively, and update the Makefile to point to the new filename. You may also want to consider using `[self _valueForKey:@"_loginBox"]`, which is almost the same as MSHookIvar. 

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
