### ISSUE TITLE
Unknown bit value when compiling on Linux

### ISSUE THREAD

**Issue by EphraimBane** [theos/theos#546]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Install all dependencies for Linux as specified in the installation guide.
2. Attempt to compile a blank tweak template.

What happens?
-------------
There is an error referring to an "unknown bit value" in reference to $ARCHS, from what I can tell.

What were you expecting to happen?
----------------------------------
I expect the project to compile successfully.

Any logs, error output, etc?
----------------------------
```
> Making all for tweak test…
==> Linking tweak test (arm64)…
ld: malformed file
/home/user/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:2:42: error: unknown bit value
archs:           [ armv7, armv7s, arm64, arm64e, i386, x86_64 ]
                                         ^~~~~~
 file '/home/user/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/user/theos/makefiles/instance/library.mk:52: /home/user/IOSTweaks/test/.theos/obj/debug/arm64/test.dylib] Error 1
==> Linking tweak test (armv7)…
ld: malformed file
/home/user/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:2:42: error: unknown bit value
archs:           [ armv7, armv7s, arm64, arm64e, i386, x86_64 ]
                                         ^~~~~~
 file '/home/user/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/user/theos/makefiles/instance/library.mk:52: /home/user/IOSTweaks/test/.theos/obj/debug/armv7/test.dylib] Error 1
make[2]: *** [/home/user/theos/makefiles/instance/library.mk:52: /home/user/IOSTweaks/test/.theos/obj/debug/arm64/test.dylib] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/home/user/theos/makefiles/instance/library.mk:52: /home/user/IOSTweaks/test/.theos/obj/debug/armv7/test.dylib] Error 2
make[1]: *** [/home/user/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/user/theos/makefiles/master/rules.mk:116: test.all.tweak.variables] Error 2

```

What versions of software are you using?
----------------------------------------
**Operating System:** Debian 10
**Toolchain Version:** Latest as of October 12, 2020
**SDK Version:** iOS 9.3, iOS 10.3, iOS 11.2 (Unsure of which is being used)

**Comment by UsrLightmann** [comment]
This is due to a lack of arm64e support on the toolchain mentioned in the Wiki. I have also posted an issue about this to hopefully get it updated.

To fix:

sudo rm -rf $THEOS/toolchain/*

sudo curl -LO https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64e-clang-toolchain.tar.lzma

TMP=$(mktemp -d)

tar --lzma -xvf linux-ios-arm64e-clang-toolchain.tar.lzma -C $TMP

mkdir -p $THEOS/toolchain/linux/iphone

mv $TMP/ios-arm64e-clang-toolchain/* $THEOS/toolchain/linux/iphone/

rm -r $TMP linux-ios-arm64e-clang-toolchain.tar.lzma

**Comment by kabiroberai** [comment]
Closing in favor of #551
