### ISSUE TITLE
![image](https://user-images.githubusercontent.com/64208426/97065997-60370c80-1566-11eb-9f91-fa5243f2fa05.png)I am also getting errors pls help

### ISSUE THREAD

**Issue by medoosh** [theos/theos#549]
![image](https://user-images.githubusercontent.com/64208426/97065997-60370c80-1566-11eb-9f91-fa5243f2fa05.png)I am also getting errors pls help

_Originally posted by @iplovings in https://github.com/theos/theos/issues/467#issuecomment-715659442_

**Comment by kirb** [comment]
What happened here?

Already answered in #548.
