### ISSUE TITLE
Help bro pls

### ISSUE THREAD

**Issue by iplovings** [theos/theos#550]
![image](https://user-images.githubusercontent.com/64208426/97095583-23c2e980-1616-11eb-94ac-96bc6a46047a.png)

**Comment by kirb** [comment]
Hi, I’m sorry but this isn’t a Theos issue, and this isn’t the place to get support. Please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places where you can get support.

**Comment by iplovings** [comment]
> Hi, I’m sorry but this isn’t a Theos issue, and this isn’t the place to get support. Please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places where you can get support.

Pls help

**Comment by iplovings** [comment]
> Hi, I’m sorry but this isn’t a Theos issue, and this isn’t the place to get support. Please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places where you can get support.

Where is GitHub page for help
