### ISSUE TITLE
The latest Prefix.pch breaks projects

### ISSUE THREAD

**Issue by heromantf** [theos/theos#552]
What are the steps to reproduce this issue?
-------------------------------------------
1. Build a tweak project using latest Theos

What happens?
-------------
Report some errors about missing headers

What were you expecting to happen?
----------------------------------
Successfully build the project

Any logs, error output, etc?
----------------------------
None

Any other comments?
-------------------
After digging in for some while, I found that the new Prefix.pch uses the macro TARGET_OS_IPHONE instead of TARGET_IPHONE and on my machine it is not defined. I also found that the common.mk and iphone.mk defines -DTARGET_IPHONE=1, so I added -DTARGET_OS_IPHONE=1 in cflags and it works. Is it a problem only for my environment or it is a common problem?

What versions of software are you using?
----------------------------------------
**Operating System:** MacOS 10.15

**Toolchain Version:** From Xcode 11.7

**SDK Version:** iPhone 11.2

**Comment by opa334** [comment]
Same issue here, Xcode 11.7 / 12.2, macOS 11.0.1, iOS 13.0 SDK
