### ISSUE TITLE
How to use socket in iphone/application?

### ISSUE THREAD

**Issue by Tiepbm** [theos/theos#554]
Hi,
I want to make an application to connect to server socket and run commandline on iPhone jailbroken. I use THEOS and choose iphone / application_modern to create the app. I used posix_spawnp to run the command line in that application and it worked.
How can I install socket library for use in this application?

Thanks!

**Comment by kabiroberai** [comment]
If you're using C a good choice for sockets is libc's socket API – check out the socket(2) man page for more info. If you have control over both the client and server though, consider using XPC as it can be more secure and ergonomic to use in Darwin-based environments.

I'm closing this as this is not an issue related to Theos itself, but if you still need help please use the [Discussions](https://github.com/theos/theos/discussions) feature instead.
