### ISSUE TITLE
Cannot build tweaks anymore (missing frameworks?)

### ISSUE THREAD

**Issue by woodfairy** [theos/theos#555]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Follow the installation guide
2. Try to compile any tweak

What happens?
-------------
I always get error messages saying that there are no declarations for stuff like UIView, or even NSObject
When I import Foundation and other frameworks manually, I still get errors, like:
1. fatal error: 'Foundation/Foundation.h' file not found
2. unknown selected sharedApplication

What were you expecting to happen?
----------------------------------
Tweaks compiling as used,

Any logs, error output, etc?
----------------------------
error: cannot find interface declaration for 'NSObject', superclass of 'WDFReachabilityController
...
cantreachme/CantReachMe/WDFReachabilityController.h:5:30: error: expected a type
-(void)runStrategyForAction:(NSString *)action;
...
fatal error: 'Foundation/Foundation.h' file not found

Any other comments?
-------------------
Project I tried to compile: https://github.com/woodfairy

What versions of software are you using?
----------------------------------------
**Operating System:** OS X 10.15.5

**Toolchain Version:** 11.7 (11E801a)

**SDK Version:** 13.3, 13.5 (both not working)

I really don't know if this issue is theos related but I followed the instructions precisely, and on all my other Macs it is working.

**Comment by badger200** [comment]
I’m new to iOS development so I don’t really know what I’m doing but I had to tinker with it an insane amount to even get a simple `stdio.h void main{ printf(“hello world”);}` to compile and run. I read somewhere in the theos /docs that you will typically need to add `#import <UIKit/UIKit.h> ` and there was 1 other alternative I’m forgetting.
For stuff with Objective C (like NSObject) it seems you also need to add `#import <objc/runtime.h>`

But the MOST IMPORTANT thing is it seems clang MUST be called with parameter `-isysroot/var/theos/sdks/iPhoneOS12.4.sdk` or whatever. (No spaces) That solved 99% of my linking failures. Idk why but some projects even if your makefile defines CFLAGS or CXXFLAGS or CPPFLAGS and you add the above isysroot parameter, it still doesn’t get called. In those cases I run `make -d` to find the final link command and then I try to recreate it to include isysroot.

Another thing that sometimes helps is setting environment variables export CFLAGS, CPPFLAGS, CXXFLAGS, LDFLAGS (I might be forgetting a pair) all to that isysroot parameter, 

I don’t know why this is such a fuckshow but maybe I’m doing something wrong or maybe I screwed up when I first tried using BigBoss clang/gcc and the unbeknownst-to-me 10 year old iphoneos-sys package containing outdated headers. Then I tried getting the SDK from Apple and extracting the iOS headers from the cpio, only to later discover they’re specific to building on Mac OS X and cause many build failures. (Fortunately I was wise enough to backup my /usr/include before I did this, the include/sys/ headers being most important as they seem to define the machine’s capabilities.)

I have been able to build simple tweak .dylibs and I’m running 2 of them right now with no problems, but I have not been able to get any Preference bundles to build no matter how hard I try adding PSListViewController.h, PSSpecifier.h, etc etc.

**Comment by kirb** [comment]
@badger200 You definitely want to start fresh by restoring the original root filesystem (there will be a button or switch for this in your jailbreak’s app) and follow the official instructions at https://git.io/theosinstall.

You don’t need to specify `-isysroot` yourself. Theos does this for you. Have you possibly used instructions that refer to a super old version of Theos?

If you still have issues, please take a look at our [help page](https://github.com/theos/theos/wiki/Help) for places where you can get help, as it’s best to not hijack an existing thread about likely a different issue.

**Comment by badger200** [comment]
@kirb thanks I will try this. It’s encouraging that you seem to be suggesting it shouldn’t be so difficult. Are you certain that one can take a freshly jailbroken device, use “tai” by Randy420 package to install theos, and then one can write a printf hello world .c program which should successfully compile and produce a.out by running gcc hello.c? Because my experience was there were about 50 obscure steps I had to take before I got that far. 

That’s great about isysroot, I hope to never have to deal with it ever again.

Btw I don’t see why you think I’m hijacking this thread? I literally have the exact same issue as the OP and I posted my solutions that actually worked for me. This poor fella has been waiting 4 months without a single reply. Surely he will appreciate my comments.

**Comment by badger200** [comment]
@kirb BTW now that I visit your official install link, I see where it all went wrong. Step 5 says `Get an iOS SDK:`

`You can get patched SDKs from our SDKs repo.`

I don’t recall why I didn’t get your patched SDK but I read your instruction “Get an iOS SDK” so I went to Apple and did exactly that. Nowhere was I warned it MUST be a PATCHED SDK, and that using Apple’s SDK will be disastrous. 

I would definitely consider changing the text to say “Get a patched iOS SDK from our SDKs repo. (An Apple SDK will fail to compile on an iOS device.)”

**Comment by L1ghtmann** [comment]
The issue(s) here appear to have been from a potentially misconfigured Theos install. If you're still having issues, please reinstall following the instructions available on https://theos.dev/docs/installation and reopen this issue. Thanks!
