### ISSUE TITLE
Theos undefined symbol help

### ISSUE THREAD

**Issue by amirhacks** [theos/theos#559]
![7D73F6B7-A50C-4089-A726-1A94A9FA852A](https://user-images.githubusercontent.com/74278079/102045939-2b805c80-3e15-11eb-853e-e9274619ff97.jpeg)
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …IOS

**Toolchain Version:** … LATEST

**SDK Version:** …13.0

**Comment by kirb** [comment]
Our install instructions for iOS need a little bit of updating (see #551), sorry about that.

Uninstall the “iOS Toolchain” package (this will also uninstall Theos Dependencies), then install the following from Elucubratus repo:

* clang
* ld64
* odcctools (aka Darwin CC Tools)
* make
* git

Note - if installing through a GUI package manager, check the author of each package and ensure the developer is Sam Bingner.

**Comment by PoomSmart** [comment]
@amirhacks Is your issue resolved?

**Comment by L1ghtmann** [comment]
Closing as the insufficient iOS dependencies package has been superseded on newer versions (>= 12) with the newer packages listed by Kirb above.
