### ISSUE TITLE
m1 make install error

### ISSUE THREAD

**Issue by wangchuanlai** [theos/theos#561]
Using Make Install on M1 causes the following error
➜  nima make install messages=yes
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 6 "Installing"); set -o pipefail; (install.exec " dpkg -i \"./packages/com.yourcompany.nima_0.0.1-9+debug_iphoneos-arm.deb\"")
==> Installing…

su: illegal option -- c
usage: su [-] [-flm] [login [args]]
make: *** [internal-install] Error 1

It's more like a local installation

**Comment by quiprr** [comment]
Theos and this command specifically work fine for me on m1, so I would check your setup.

**Comment by kirb** [comment]
Please try:

```
cd $THEOS
git checkout kirb/unify-darwin-platform
```

Then `make clean` and try building again. 

Theos previously assumed ARM means iOS, so it’s trying to do things that make sense for jailbroken iOS. The unified Darwin platform branch no longer makes that assumption. Will be merged soon when I have a moment to test it on all platforms.

**Comment by wangchuanlai** [comment]
Thank you for solving my problem
