### ISSUE TITLE
I can’t use NSLog method in .xm file cause the “make” failed

### ISSUE THREAD

**Issue by wxzhh** [theos/theos#572]

**Comment by wxzhh** [comment]
**when I use “make”,it shows as below,which says NSLog method is undeclared:**

Making all for tweak readingcrack…
==> Preprocessing src/PFLListenBookVC_test.xm…
==> Compiling src/PFLListenBookVC_test.xm (arm64)…
src/PFLListenBookVC_test.xm:3:181: error: use of undeclared identifier 'NSLog'
  ...__unused self, SEL __unused _cmd, _Bool  hasReport) { NSLog(@"-[<PFLList...
                                                           ^
**The .xm file is as below:**
…
- (_Bool )hasReport { %log; _Bool  r = %orig; NSLog(@" = %d", r); return r; }
…

**and the make file is :**
TARGET := iphone:latest:7.0
INSTALL_TARGET_PROCESSES = SpringBoard
ARCHS = arm64
THEOS_DEVICE_IP = localhost -p 10010
include $(THEOS)/makefiles/common.mk
TWEAK_NAME = readingcrack
readingcrack_FILES = $(wildcard src/*.xm)
readingcrack_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/tweak.mk

**Who can tell me why and how to solve it?**

**Comment by demhademha** [comment]
Does your tweak file **explisitly** include  Foundation 
```objc
#import <Foundation/Foundation.h>
```

**Comment by PoomSmart** [comment]
The solution is as @demhademha replied, closing the issue.
