### ISSUE TITLE
xcode 10 'theos/BackwardsCompat.h' file not found

### ISSUE THREAD

**Issue by Jason-an** [theos/theos#577]
sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
MonkeyDev build Error   'theos/BackwardsCompat.h' file not found

**Comment by kirb** [comment]
Hard to provide any assistance with your issue as you’ve deleted the issue template. If this is still happening, please fill out the issue template as you can find [here](https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by kirb** [comment]
Closing due to lack of response. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
