### ISSUE TITLE
master.zip decompression failed

### ISSUE THREAD

**Issue by Gordon0918** [theos/theos#579]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------

master.zip decompression failed. What's the reason

Archive:  master.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of master.zip or
        master.zip.zip, and cannot find master.zip.ZIP, period.

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
Hard to answer this without further information, as you haven’t filled out the issue template. You may not have copied the command correctly, or you accidentally added extra characters to the url, or curl can’t access the internet for some reason?
