### ISSUE TITLE
Wrong mv command?

### ISSUE THREAD

**Issue by AndnixSH** [theos/theos#580]
When I do mv
`mv $TMP/sdks-master/*.sdk $THEOS/sdks`
It just print out this 
```
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
```

But if i do:
`mv $TMP/sdks-master/*.sdk THEOS/sdks`

It works and folder moved successfully

Is the command wrong on Wiki or it just me?

I'm using macOS Catalina 10.15.7

**Comment by SomeNowTakenUsername** [comment]
Is your `$THEOS` set correctly? What does `echo $THEOS` output?

**Comment by AndnixSH** [comment]
`$THEOS` works but i wondered why this works `mv $TMP/sdks-master/*.sdk THEOS/sdks` when the one explained in Wiki didn't. My system was clean installed though

**Comment by RPwnage** [comment]
Please run `echo $THEOS && echo $TMP` and comment the output.

**Comment by AndnixSH** [comment]
```
/Users/maccer/theos
/var/folders/y5/85d60b612vj1drjmkrv1z0q80000gn/T/tmp.z8xi4Mzv
```

Idk what I did wrong. The move command is working now
