### ISSUE TITLE
invalid argument '-std=c++14' not allowed with 'Objective-C'

### ISSUE THREAD

**Issue by AndnixSH** [theos/theos#581]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Add `-std=c++14` to your CFLAGS in Makefile
2. `make package`

What happens?
-------------
`-std=c++14` flag is no longer allowed on latest version of theos, but my code requiring the flag

What were you expecting to happen?
----------------------------------
To compile without problem like it used to. I have an older version of Theos folder which works perfectly

Any logs, error output, etc?
----------------------------
```
> Making all for tweak test2…
==> Compiling Tweak.xm (arm64)…
==> Compiling ESP/CGView.m (arm64)…
error: invalid argument '-std=c++14' not allowed with 'Objective-C'
make[3]: *** [/Users/maccer/Desktop/test2/.theos/obj/arm64/ESP/CGView.m.fd8baef2.o] Error 1
make[2]: *** [/Users/maccer/Desktop/test2/.theos/obj/arm64/test2.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [test2.all.tweak.variables] Error 2
maccer@Mac-tilhrende-maccer test2 % 
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** macOS Catalina 10.15.7

**Toolchain Version:** xcode-select version 2373.

**SDK Version:** 11.4

**Comment by AndnixSH** [comment]
Welp it turns out the latest theos is totally broken, I got a lot more errors than that. My old theos from June 2020 works perfectly

**Comment by DHowett** [comment]
Consider that you are telling the compiler that all **C** files are C++14. There's no reason that that should work even with a sane toolchain. The specific error you're getting is, of course, that you've told Clang your file is both "Objective-C" and "C++14," which is a combination only possible if you're compiling as _"Objective-C++"_ (.mm files).

**Comment by AndnixSH** [comment]
Oh ok, I removed it and fixed a lot of declaration errors
Works now with latest theos
