### ISSUE TITLE
error: %ctor does not make sense inside a block

### ISSUE THREAD

**Issue by Toshiba1127** [theos/theos#583]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Add this code in tweak.xm

```
%ctor {
  CFNotificationCenterAddObserver(CFNotificationCenterGetLocalCenter(), NULL, &didFinishLaunching, (CFStringRef)UIApplicationDidFinishLaunchingNotification, NULL, CFNotificationSuspensionBehaviorDeliverImmediately);
}
```

What happens?
-------------
`Tweak.xm:101: error: %ctor does not make sense inside a block`

What were you expecting to happen?
----------------------------------
To compile fine just like older theos

Any logs, error output, etc?
----------------------------
```
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://github.com/theos/theos/wiki/Parallel-Building
> Making all for tweak BanGDream…
==> Preprocessing Tweak.xm…
Tweak.xm:101: error: %ctor does not make sense inside a block
make[3]: *** [/Users/maccer/Projects/bangdream/.theos/obj/arm64/Tweak.xm.mm] Error 22
rm /Users/maccer/Projects/bangdream/.theos/obj/arm64/Tweak.xm.mm
make[2]: *** [/Users/maccer/Projects/bangdream/.theos/obj/arm64/BanGDream.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [BanGDream.all.tweak.variables] Error 2
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** macOS Catanlina 10.15.7

**Toolchain Version:** ?

**SDK Version:** Tried 11.4, 12.2 and 14.4

**Comment by kirb** [comment]
You have a syntax error somewhere earlier in your file. Please review all `{ … }` braces carefully, you’ve missed at least one closing `}` brace. You might consider installing an extension such as [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) (there should be similar extensions for other editors) to help. Mismatched braces will show in red.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).

**Comment by Toshiba1127** [comment]
Ok thanks, I was using Notepad++ so i couldn't figure out why
