### ISSUE TITLE
Can't compile package on linux

### ISSUE THREAD

**Issue by Keneshin** [theos/theos#598]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Update toolchain for arm64e from Bingner's repo
2. Try to compile the package with make package

What happens?
-------------
Gives the error and stops.

What were you expecting to happen?
----------------------------------
Package being compiled.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
/home/keneshin/theos/makefiles/common.mk:144: *** You did not specify a target, and the "linux" platform does not define a default target.

Any other comments?
-------------------
...
What versions of software are you using?
----------------------------------------
**Operating System:** Arch Linux

**Toolchain Version:** Latest from Bingner's repo

**SDK Version:** I'm not sure

**Comment by UsrLightmann** [comment]
Sounds like you're missing a -target flag. 

In your Makefile, add the following line: `TARGET = iphone:clang:latest:13.0`

This will set the target SDK to the latest in `$THEOS/sdks` and the minimum target iOS version to 13.0. 

For more information see [here](https://iphonedev.wiki/index.php/Theos#Theos_variables).

**Comment by Keneshin** [comment]
Still the same

**Comment by Keneshin** [comment]
Here's my Makefile
```mk
TARGET = iphone:clang:latest:13.0
INSTALL_TARGET_PROCESSES = SpringBoard


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = PrikolTweak

PrikolTweak_FILES = Tweak.x
PrikolTweak_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
```
It doesn't work even after i create a new tweak through NIC

**Comment by Keneshin** [comment]
Nevermind, the issue fixed after reboot.
