### ISSUE TITLE
Error installing libtinfo5

### ISSUE THREAD

**Issue by Babyyoda777** [theos/theos#620]
What are the steps to reproduce this issue?
-------------------------------------------
1. install ubuntu 20.04 LTS
2. run sudo apt-get install fakeroot git perl build-essential libtinfo5

What happens?
-------------
says it cant be found
What were you expecting to happen?
----------------------------------
install without errors
…
Any logs, error output, etc?
----------------------------

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libtinfo5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libtinfo5' has no installation candidate

Any other comments?
-------------------
install normally
What versions of software are you using?
----------------------------------------
**Operating System:** Windows 11
**Toolchain Version:**n/a

**SDK Version:** n/a

**Comment by UsrLightmann** [comment]
Try running `sudo apt-get update` and then run the install command again. 

Also, this isn't a Theos issue.

**Comment by Babyyoda777** [comment]
Thanks! This fixed the issue. I was about to downgrade to windows 10 lol.
