### ISSUE TITLE
[Bug]: Occasional failure to compile with Orion and Substrate mixed codebase

### ISSUE THREAD

**Issue by midnightchip** [theos/theos#627]
### What are the steps to reproduce this issue?

Make a project with Orion and Logos based files.
Run Make Do
Occasionally, the compiler will begin compiling Orion files before preprocessing the Logos file has completed, causing the entire compilation to fail.

### What happens?

The project fails to compile

### What were you expecting to happen?

The Project to compile

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

12.0.1

### What toolchain and version are you using?

Xcode 13.1

### Which SDK version are you using?

iOS 14

### What OS is your client device running?

iOS

### What OS version does it have installed?

14.9

### Which device model is it?

iPhone 7

### Which jailbreak is it using (if relevant)?

checkra1n

**Comment by kabiroberai** [comment]
Could you please run `make clean all messages=yes` and provide the output for 1) a failing build and 2) a successful build here?

**Comment by L1ghtmann** [comment]
Closing due to lack of response. If the issue persists, please feel free to reopen.
