### ISSUE TITLE
tpm - theos package manager

### ISSUE THREAD

**Issue by DHowett** [theos/theos#63]
`tpm install logos`

    theos/pkg/logos/bin/logos.pl
    theos/pkg/logos/lib/Logos/Util.pm
    ...
    theos/bin/logos.pl => ../pkg/logos/bin/logos.pl
    theos/bin/logify.pl => ../pkg/logos/bin/logify.pl

<br>

    theos/pkg/android/mod/android/common.mk
    ...
    theos/mod/android => ../pkg/android/mod/android

**Comment by alucard0134** [comment]
I really have no idea what to make out of this, how about you @kirb

**Comment by DHowett** [comment]
It's an issue from nearly three years ago documenting a speculative package manager. It's probably not necessary now.

However, commenting on issues you don't understand just to say you don't understand them is also probably not useful. :+1:

**Comment by kirb** [comment]
Yeah I reckon this would be better off just being a wiki page listing
well-known extensions. Just makes things a lot easier, not having to
explicitly deal with package manager-esque things when the user can just
`git clone` whatever inside $THEOS and anything they break is their problem.

On Sun, 14 Feb 2016 at 14:34, Dustin L. Howett <notifications@github.com>
wrote:

> It's an issue from nearly three years ago documenting a speculative
> package manager. It's probably not necessary now.
>
> However, commenting on issues you don't understand just to say you don't
> understand them is also probably not useful. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/63#issuecomment-183818119>.
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by DHowett** [comment]
Agreed
