### ISSUE TITLE
Any tweaks not working on iOS13.5.1 iPhone 11,8 arm64e Unc0ver jailbreak !

### ISSUE THREAD

**Issue by H0meDev** [theos/theos#633]
Any tweaks not working on iOS13.5.1 iPhone 11,8 arm64e Unc0ver jailbreak !
When i changed my theos environment to macOS High Sierra, every tweak works as expected !
I can't find the really problem, can you guys fix ? Thank you !

**Comment by kirb** [comment]
Did you update Xcode? If so, see https://theos.dev/docs/arm64e-deployment.

In future please fill out the [issue template](https://github.com/theos/theos/issues/new/choose), this exists so we can better understand what’s going on when you encounter a potential bug.

**Comment by H0meDev** [comment]
> Did you update Xcode past 11.7? If so, see https://theos.dev/docs/arm64e-deployment.
> 
> In future please fill out the [issue template](https://github.com/theos/theos/issues/new/choose), this exists so we can better understand what’s going on when you encounter a potential bug.

OK, I got it, thank you !
