### ISSUE TITLE
[Bug]: make: *** No rule to make target 'package'.

### ISSUE THREAD

**Issue by iRedddy** [theos/theos#639]
### What are the steps to reproduce this issue?

I tried making a tweak using ImGUI

### What happens?

make: *** No rule to make target 'package'.

### What were you expecting to happen?

make a full tweak because it did on my phone

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

Windows 10

### What toolchain and version are you using?

Dont know

### Which SDK version are you using?

iOS 11.2

### What OS is your client device running?

Linux/WSL

### What OS version does it have installed?

14.5

### Which device model is it?

iPhone SE 2020

### Which jailbreak is it using (if relevant)?

unc0ver

**Comment by iRedddy** [comment]
This is my makefile

```
export THEOS=/home/shrino/theos


ARCHS = arm64 

DEBUG = 0
FINALPACKAGE = 1
FOR_RELEASE = 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SHRINO




SHRINO_FRAMEWORKS =  UIKit Foundation Security QuartzCore CoreGraphics CoreText  AVFoundation Accelerate GLKit SystemConfiguration GameController

SHRINO_CCFLAGS = -std=c++11 -fno-rtti -fno-exceptions -DNDEBUG
SHRINO_CFLAGS = -fobjc-arc -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-value

SHRINO_FILES = ImGuiDrawView.mm delete.xm $(wildcard views/*.m) $(wildcard Esp/*.mm) $(wildcard Esp/*.m) $(wildcard KittyMemory/*.cpp) $(wildcard KittyMemory/*.mm) $(wildcard KittyMemory/*.m) $(wildcard las/*.m) 


include $(THEOS_MAKE_PATH)/tweak.mk

#SHRINO_LIBRARIES += substrate
# GO_EASY_ON_ME = 1

after-install::
   install.exec "killall -9 cod || :"
```

**Comment by L1ghtmann** [comment]
A couple things:

1) $THEOS should be set in your shell's profile (~/.profile if you're using bash or ~/.zshenv if you're using zsh -- test with ```echo $SHELL```), not in your project's makefile;

2) The ```no rule to make target 'arg'``` error typically occurs either when $THEOS isn't set properly or when you're in a directory without a Makefile. Were you cd'ed into the project directory when you ran ```make package```?

**Comment by kirb** [comment]
Closing due to lack of response. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
