### ISSUE TITLE
Bash 5 installation for macOS instruction

### ISSUE THREAD

**Issue by PoomSmart** [theos/theos#679]
This PR (https://github.com/theos/theos/pull/636) introduces `readarray` which is available in Bash 4 and newer. However, most macOS comes with Bash 3 and the user has to manually upgrade to Bash 5 (latest is better?) by running `brew install bash`.

`readarray`:
https://github.com/theos/theos/blob/master/bin/convert_xml_plist.sh#L31

This should be mentioned in the Wiki.

**Comment by kirb** [comment]
Fixed, script works on bash 3 now. I don't intend to increase the bash version we target, since there isn't too much that's missing that we can't easily work around using Perl and other utilities shipped with macOS.
