### ISSUE TITLE
Compress/Raw/Lzma.pm not in @INC | sudo cpan IO::Compress::Lzma not working

### ISSUE THREAD

**Issue by covalspace** [theos/theos#681]
### What are the steps to reproduce this issue?

install Compress::Raw::Lzma with macports 
use sudo cpan IO::Compress::Lzma

### What happens?

when I run `sudo cpan IO::Compress::Lzma` I get

```
Parse errors: No plan found in TAP output
Files=45, Tests=37,  1 wallclock secs ( 0.04 usr  0.03 sys +  0.73 cusr  0.20 csys =  1.00 CPU)
Result: FAIL
Failed 39/45 test programs. 9/37 subtests failed.
make: *** [test_dynamic] Error 255
  PMQS/IO-Compress-Lzma-2.201.tar.gz
one dependency not OK (Compress::Raw::Lzma); additionally test harness failed
  /usr/bin/make test -- NOT OK
```

I'm on MacOS M1 Chip. Installed with macports.

### What were you expecting to happen?

I was expecting sudo cpan IO::Compress::Lzma to make Compress::Raw::Lzma accessible in @INC

### Paste any relevant logs, error output, etc.

```shell
https://gist.github.com/covalspace/68a9738d0119ef6029f65540819279f3
```

### Additional context

I'm ultimately trying to use 7z2john

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

Big Sur 11.3.1

### What toolchain and version are you using?

Xcode 12.5

### Which SDK version are you using?

?

### What OS is your client device running?

macOS

### What OS version does it have installed?

Big Sur 11.3.1

### Which device model is it?

MacBook Pro

**Comment by covalspace** [comment]
UPDATE I FOUND A FIX:

The only fix for M1 that worked for me was to use a virtual machine and emulate Ubuntu linux AMD through UMT on my macbook. (Even though emulation on Ubuntu is painfully slow, the 64 bit AMD part is important because homebrew doesn't work on ARM architecture)

Because I was still running into an issue with zip2john I used

export PATH="$PATH:/home/linuxbrew/.linuxbrew/Cellar/john-jumbo/1.9.0_1/share/john”

Then used 7z2john.pl. You may get an error that says you need lmza. If this happens use

sudo apt-get install libcompress-raw-lzma-perl



Now if you use

7z2john examplefile.7z > examplehash.txt

You should get a .txt file WITH bytes and WITH a hash!

**Comment by covalspace** [comment]
> We haven't used IO::Compress::Lzma in a few years now. Are you using a very old release of dm.pl? Or are you possibly in the wrong place?

This wasn't for theos actually this is for john the ripper but same error code. I'm sorry for any inconvenience.

**Comment by kirb** [comment]
No worries :+1: Just wanted to make sure.
