### ISSUE TITLE
[Bug]: ldid: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by ChrisGleich1AufsMaul** [theos/theos#686]
### What are the steps to reproduce this issue?

1. Make new Project
2. Run `make package`

### What happens?
I followed this tutorial: https://theos.dev/docs/installation-linux and then I tried to compile for the first time a project, but an ldid error occured, although everythin is installed correctly... ldid seems to be the problem.

### What were you expecting to happen?
compiling

### Paste any relevant logs, error output, etc.
```shell
make package
> Making all for tweak djayPro…
==> Merging tweak djayPro…
==> Signing djayPro…
bash: line 1: /home/chris/theos/toolchain/linux/iphone/bin/ldid: cannot execute binary file: Exec format error
make[2]: *** [/home/chris/theos/makefiles/instance/library.mk:51: /home/chris/theosProjects/djaypro/.theos/obj/debug/djayPro.dylib] Error 126
rm /home/chris/theosProjects/djaypro/.theos/obj/debug/djayPro.dylib.4e292e05.unsigned
make[1]: *** [/home/chris/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/chris/theos/makefiles/master/rules.mk:119: djayPro.all.tweak.variables] Error 2
```

### What OS are you seeing the problem on?
Linux subsystem of Windows

### What OS version does it have installed?
Ubuntu 22.04.1 LTS (on Windows 10 64x)

### What toolchain and version are you using?
clang

### Which SDK version are you using?
iOS 14.5 (don't know, where to get a iOS 15 SDK ^^)

### What OS is your client device running?
iOS

### What OS version does it have installed?
iOS 15

### Which device model is it?
iPad Air 4th gen.

### Which jailbreak is it using (if relevant)?
XinaA15

**Comment by L1ghtmann** [comment]
Did you install the swift or non-swift toolchain? And can you run `file $THEOS/toolchain/linux/iphone/bin/ldid` and share the output here please? Thanks!

**Comment by ChrisGleich1AufsMaul** [comment]
Well… I set up the Environment again from scratch 😅
Now I have other problems: PATH-Variable and permissions are propably incorrect set 

> Did you install the swift or non-swift toolchain? 

which method would you recommend?

**Comment by L1ghtmann** [comment]
Are you encountering any problems (re $PATH and perms)? And the non-swift if you don't intend to code/build Swift projects. The toolchain can be changed later if desired.

**Comment by mkotu** [comment]
> Did you install the swift or non-swift toolchain? And can you run `file $THEOS/toolchain/linux/iphone/bin/ldid` and share the output here please? Thanks!

-bash: /home/user/theos/toolchain/linux/iphone/bin/ldid: cannot execute binary file: Exec format error

**Comment by L1ghtmann** [comment]
@mkotu @ChrisGleich1AufsMaul the issue appears to be specific to WSL v1. I've compiled an updated toolchain that should fix the issue. To try it, run:
```
rm -r $THEOS/toolchain/*
curl -LO https://github.com/L1ghtmann/llvm-project/releases/latest/download/iOSToolchain.tar.xz
tar -xvf iOSToolchain.tar.xz -C $THEOS/toolchain/
rm iOSToolchain.tar.xz
```
