### ISSUE TITLE
I cant make package

### ISSUE THREAD

**Issue by D7my2001** [theos/theos#691]
![image](https://user-images.githubusercontent.com/120202931/211208081-4f9e3108-bbd9-41e1-835f-cc36f24d516d.jpeg)

**Comment by L1ghtmann** [comment]
A few things:
1) Theos is not meant to be installed or run as root. I would recommend that you remove your current install and reinstall as mobile (i.e., the default user) or another non-root user. 

2) That error indicates that the SDK you're targeting in your Makefile doesn't exist. Would you mind sharing the project's Makefile? 

3) That error's messaging has been slightly improved in recent weeks. To get the update, run ```$THEOS/bin/update-theos```.

**Comment by D7my2001** [comment]
This is the project https://github.com/haoict/crackerxi-searchbar

**Comment by D7my2001** [comment]
And now i delete all the sdk files and theos i want to reinstall it from the beginning

**Comment by L1ghtmann** [comment]
You'll want to change ```TARGET = iphone:clang:12.2:10.0``` to ```TARGET = iphone:clang:latest:10.0``` or ```TARGET = iphone:clang:12.4:10.0``` as Theos no longer ships a 12.2 SDK.

**Comment by D7my2001** [comment]
> You'll want to change ```TARGET = iphone:clang:12.2:10.0``` to ```TARGET = iphone:clang:latest:10.0``` or ```TARGET = iphone:clang:12.4:10.0``` as Theos no longer ships a 12.2 SDK.

I really appreciate that
