### ISSUE TITLE
[Bug]: Installer script not detecting Xcode

### ISSUE THREAD

**Issue by AndnixSH** [theos/theos#698]
### What are the steps to reproduce this issue?

Follow steps on https://theos.dev/docs/installation-macos

### What happens?

The script says Xcode is required even though I already installed it. I tried installing Xcode from both App store and developer page. I'm using VM, idk if it makes a difference

```
vm@Mac-tilhrende-VM ~ %  bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
==> Theos Installer: Starting install...

==> Platform: Darwin
==> Xcode, not just the Command Line Tools, is required for Theos to function properly. Please install Xcode before continuing with the installation.

==> We recommend that you install Xcode from https://developer.apple.com/download/applications/ instead of from the Mac App Store as it's much faster.
```

### What were you expecting to happen?

Install without issue just like the previous installation method

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

Ventura 13.2

### What toolchain and version are you using?

Xcode 14.2

### Which SDK version are you using?

16.2

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 14.2

### Which device model is it?

iPad 7 gen.

### Which jailbreak is it using (if relevant)?

checkra1n

**Comment by EinTim23** [comment]
The default selected xcode directory points to the command line tools only. To fix this enter
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/` into your terminal and try to run the installation script again afterwards.

**Comment by AndnixSH** [comment]
Ok, I did it and the installation succeded and restarted the system, but i'm getting an error when running `make`

```
vm@Mac-tilhrende-VM aaa % make                                 
==> Error: A SYSROOT could not be found. For instructions on installing an SDK: https://theos.dev/docs/installation
make: *** [/Users/vm/theos/makefiles/master/rules.mk:46: before-all] Error 1
```

**Comment by L1ghtmann** [comment]
That can occur for a couple of reasons, but most often when the sdk you're targeting in the makefile doesn't exist. 

Would you mind sharing the project's makefile? Thanks

**Comment by AndnixSH** [comment]
> That can occur for a couple of reasons, but most often when the sdk you're targeting in the makefile doesn't exist.
> 
> Would you mind sharing the project's makefile? Thanks

Yeah, the target sdk I had set didn't exist anymore, so I changed it to latest version and problem solved 👍
