### ISSUE TITLE
[Need Help]: make install with error

### ISSUE THREAD

**Issue by Coder-ZJQ** [theos/theos#704]
### What are the steps to reproduce this issue?

1. run `nic.pl` to make a new tweak project
2. connect device with USB, bind ports with:
``` bash
$ iproxy 10012 22
Creating listening port 10012 for device port 22
waiting for connection
```
3. set device ip and port in shell profile:
``` txt
export THEOS_DEVICE_IP=127.0.0.1
export THEOS_DEVICE_PORT=10012
```
4. make package and install

### What happens?

make install with error:
``` bash
$ make install messages=yes 
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 6 "Installing"); set -o pipefail; (install.exec "cat > /tmp/_theos_install.deb;  dpkg -i /tmp/_theos_install.deb && rm /tmp/_theos_install.deb" < "./packages/com.yourcompany.test_0.0.1-9+debug_iphoneos-arm.deb")
==> Installing…
Shell "bash" is not executable: No such file or directory
make: *** [/Users/Joker/.theos/makefiles/install/deb_remote.mk:2: internal-install] Error 255
```

### What were you expecting to happen?

I expected the package to install.

### Additional context

ssh works properly:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/15013685/218677371-4fe67b1c-effb-4dcc-ab43-af403c9bf547.png">

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

macOS 13.2.1

### What toolchain and version are you using?

Xcode 14.2

### Which SDK version are you using?

iOS 14.0

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 14.0

### Which device model is it?

iPhone 8 Plus

### Which jailbreak is it using (if relevant)?

checkra1n

**Comment by Luki120** [comment]
This is unrelated but don't shove your IP stuff in the makefile, the same goes for everyone who might be reading this. It's bad practice besides the fact you make your tweak uncompilable for others, add them your shell profile instead.

**Comment by Coder-ZJQ** [comment]
> This is unrelated but don't shove your IP stuff in the makefile, the same goes for everyone who might be reading this. It's bad practice besides the fact you make your tweak uncompilable for others, add them your shell profile instead.

Thank you for your advice :) I have edit this issue.

**Comment by Coder-ZJQ** [comment]
Fixed by uninstall [fig](https://fig.io/) so close.

**Comment by Coder-ZJQ** [comment]
Caused by fig ssh integrations, fixed by uninstall ssh integrations with: `fig integrations uninstall ssh`
https://github.com/withfig/fig/issues/2374#issuecomment-1447813355
