### ISSUE TITLE
`make uninstall` command

### ISSUE THREAD

**Issue by vr1s** [theos/theos#708]
### What problem are you trying to solve?

A quick and easy command to uninstall the current package. Useful if you respring loop or need to uninstall for other reasons.

### Describe the solution you’d like

A simple `make uninstall` that does the opposite of `make install`

### Describe any alternatives you’ve considered

> Can you do this using other tools?
[personal build system] does this via reading the config file and just sending `dpkg -r <id>`

**Comment by L1ghtmann** [comment]
Closing as this was implemented in https://github.com/theos/theos/commit/ce7f559.
