### ISSUE TITLE
[Bug]: The Preference Bundle template adds a load command that exposes developer's username and working directory 

### ISSUE THREAD

**Issue by limneos** [theos/theos#720]
### What are the steps to reproduce this issue?

1) Make new project
2) Add a preference bundle subproject to the project using nic.pl - preference-bundle option
3) compile etc.

### What happens?

The resulting PreferenceBundle binary self load dylib  command  includes the working directory of the developer's computer, including the account username. 

### What were you expecting to happen?

The resulting binary  load dylib  command  should either use @rpath or since it's not important, use any other path other than the real working directory on the developer's computer. 

### Paste any relevant logs, error output, etc.

```shell
iphone: root# otool -L /Library/PreferenceBundles/SubstitutePrefs.bundle/SubstitutePrefs 

SubstitutePrefs.bundle/SubstitutePrefs (architecture arm64):
	/Users/gitlab/builds/JvkhZZgY/0/sbingner/substitute-package/.theos/obj/arm64/SubstitutePrefs.bundle/SubstitutePrefs (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1444.12.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1443.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3694.4.18)
	/System/Library/PrivateFrameworks/Preferences.framework/Preferences (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

13.1

### What toolchain and version are you using?

Xcode 12

### Which SDK version are you using?

iOS 14

### What OS is your client device running?

iOS

### What OS version does it have installed?

14

### Which device model is it?

iPhone 12

**Comment by blanxd** [comment]
I've been just running ````THEOS_PROJECT_DIR=. make ...```` when it comes time to share any binaries out, exactly so to prevent this one.
