### ISSUE TITLE
[Bug]:  The rootless scheme doesn't handle library linking replacement in bundle.mk projects

### ISSUE THREAD

**Issue by limneos** [theos/theos#722]
### What are the steps to reproduce this issue?

1. Add rootless scheme to a project's Makefile
2. In the preference bundle of the process, link with libsubstrate
3. Compile

### What happens?

The resulting binary doesn't link to @rpath/CydiaSubstrate.framework/CydiaSubstrate but to the rootful path /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate

### What were you expecting to happen?

The resulting binary should link to  @rpath/CydiaSubstrate.framework/CydiaSubstrate 

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

13.1

### What toolchain and version are you using?

Xcode 12

### Which SDK version are you using?

iOS 14

### What OS is your client device running?

iOS

### What OS version does it have installed?

14

### Which device model is it?

iPhone 12 Pro Max

**Comment by L1ghtmann** [comment]
Thanks for catching this! Does it happen to be resolved by #718?

**Comment by limneos** [comment]
It does happen to be resolved with #718, yes. Awesome :)

**Comment by Tweaker177** [comment]
what?? so this could be why my tweaks with prefs fail at the linkage stage when trying to build rootless debs?  And it's fixed now?  I need fetch me some theos and try again.  Good catch!  Thanks. 🤙

**Comment by MrGcGamer** [comment]
@Tweaker177 nope... #718 has not been merged yet
