### ISSUE TITLE
[suggestion] rootless libraries link against other rootless libraries

### ISSUE THREAD

**Issue by H5GG** [theos/theos#726]
### What problem are you trying to solve?

Avoid using the /var/jb fixed path to link unrooted libraries, otherwise we won't be able to modify the /var/jb path or randomize it without recompiling the tweak.

### Describe the solution you’d like

![](https://user-images.githubusercontent.com/74475614/233489485-ef3b52bb-de4b-4824-99d3-6261ea677d7f.png)

exampes:
the install name of the first rootless libraries is "@rpath/usr/lib/libA/libA.dylib"
the install name of the second rootless libraries is "@rpath/usr/lib/libB/libB.dylib"

1: libA.dylib link against libB.dylib with "@rpath/usr/lib/libB/libB.dylib"
2: add rpath "@loader_path/../../../" to libA.dylib

so the rpath does not need to contain any fixed path, and we can use the complete subpath of the library in the jb root directory for the install name. And this method is also officially supported by Apple.

**Comment by kirb** [comment]
Really appreciate the idea, but I’m going to close this based on it being explained as impractical by the Procursus team here: https://github.com/opa334/Dopamine/issues/30#issuecomment-1517005681
