### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joycelewis** [theos/theos#728]
### What are the steps to reproduce this issue?

make clean package
==> Cleaning…
> Making all for tweak FreeFire_ThanhDark1909…
==> Compiling DTTJailbreakDetection.m (arm64)…
==> Compiling Esp/PubgLoad.mm (arm64)…
==> Compiling Esp/ImGuiLoad.m (arm64)…
==> Compiling Esp/JHPP.m (arm64)…
==> Compiling Esp/JHUIViewControllerDecoupler.m (arm64)…
==> Compiling ImGuiDrawView.mm (arm64)…
==> Compiling Esp/UIView+Toast.m (arm64)…
==> Compiling KittyMemory/imgui_demo.cpp (arm64)…
==> Compiling KittyMemory/imgui.cpp (arm64)…
==> Compiling KittyMemory/imgui_draw.cpp (arm64)…
==> Compiling KittyMemory/imgui_tables.cpp (arm64)…
==> Compiling KittyMemory/KittyArm64.cpp (arm64)…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
==> Compiling KittyMemory/KittyScanner.cpp (arm64)…
==> Compiling KittyMemory/KittyUtils.cpp (arm64)…
==> Compiling KittyMemory/MemoryBackup.cpp (arm64)…
==> Compiling KittyMemory/MemoryPatch.cpp (arm64)…
==> Compiling KittyMemory/writeData.cpp (arm64)…
==> Compiling KittyMemory/imgui_impl_metal.mm (arm64)…
==> Compiling KittyMemory/imgui_widgets.cpp (arm64)…
==> Linking tweak FreeFire_ThanhDark1909 (arm64)…
ld: warning: directory not found for option '-F/home/kali/theos/vendor/lib/iphone/rootful'
duplicate symbol '_mainWindow' in:
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/PubgLoad.mm.9adce9e4.o
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/ImGuiLoad.m.9adce9e4.o
ld: 1 duplicate symbol for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 1
make[2]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 2
make[1]: *** [/home/kali/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/kali/theos/makefiles/master/rules.mk:119: FreeFire_ThanhDark1909.all.tweak.variables] Error 2

### What happens?

make clean package
==> Cleaning…
> Making all for tweak FreeFire_ThanhDark1909…
==> Compiling DTTJailbreakDetection.m (arm64)…
==> Compiling Esp/PubgLoad.mm (arm64)…
==> Compiling Esp/ImGuiLoad.m (arm64)…
==> Compiling Esp/JHPP.m (arm64)…
==> Compiling Esp/JHUIViewControllerDecoupler.m (arm64)…
==> Compiling ImGuiDrawView.mm (arm64)…
==> Compiling Esp/UIView+Toast.m (arm64)…
==> Compiling KittyMemory/imgui_demo.cpp (arm64)…
==> Compiling KittyMemory/imgui.cpp (arm64)…
==> Compiling KittyMemory/imgui_draw.cpp (arm64)…
==> Compiling KittyMemory/imgui_tables.cpp (arm64)…
==> Compiling KittyMemory/KittyArm64.cpp (arm64)…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
==> Compiling KittyMemory/KittyScanner.cpp (arm64)…
==> Compiling KittyMemory/KittyUtils.cpp (arm64)…
==> Compiling KittyMemory/MemoryBackup.cpp (arm64)…
==> Compiling KittyMemory/MemoryPatch.cpp (arm64)…
==> Compiling KittyMemory/writeData.cpp (arm64)…
==> Compiling KittyMemory/imgui_impl_metal.mm (arm64)…
==> Compiling KittyMemory/imgui_widgets.cpp (arm64)…
==> Linking tweak FreeFire_ThanhDark1909 (arm64)…
ld: warning: directory not found for option '-F/home/kali/theos/vendor/lib/iphone/rootful'
duplicate symbol '_mainWindow' in:
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/PubgLoad.mm.9adce9e4.o
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/ImGuiLoad.m.9adce9e4.o
ld: 1 duplicate symbol for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 1
make[2]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 2
make[1]: *** [/home/kali/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/kali/theos/makefiles/master/rules.mk:119: FreeFire_ThanhDark1909.all.tweak.variables] Error 2

### What were you expecting to happen?

make clean package
==> Cleaning…
> Making all for tweak FreeFire_ThanhDark1909…
==> Compiling DTTJailbreakDetection.m (arm64)…
==> Compiling Esp/PubgLoad.mm (arm64)…
==> Compiling Esp/ImGuiLoad.m (arm64)…
==> Compiling Esp/JHPP.m (arm64)…
==> Compiling Esp/JHUIViewControllerDecoupler.m (arm64)…
==> Compiling ImGuiDrawView.mm (arm64)…
==> Compiling Esp/UIView+Toast.m (arm64)…
==> Compiling KittyMemory/imgui_demo.cpp (arm64)…
==> Compiling KittyMemory/imgui.cpp (arm64)…
==> Compiling KittyMemory/imgui_draw.cpp (arm64)…
==> Compiling KittyMemory/imgui_tables.cpp (arm64)…
==> Compiling KittyMemory/KittyArm64.cpp (arm64)…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
==> Compiling KittyMemory/KittyScanner.cpp (arm64)…
==> Compiling KittyMemory/KittyUtils.cpp (arm64)…
==> Compiling KittyMemory/MemoryBackup.cpp (arm64)…
==> Compiling KittyMemory/MemoryPatch.cpp (arm64)…
==> Compiling KittyMemory/writeData.cpp (arm64)…
==> Compiling KittyMemory/imgui_impl_metal.mm (arm64)…
==> Compiling KittyMemory/imgui_widgets.cpp (arm64)…
==> Linking tweak FreeFire_ThanhDark1909 (arm64)…
ld: warning: directory not found for option '-F/home/kali/theos/vendor/lib/iphone/rootful'
duplicate symbol '_mainWindow' in:
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/PubgLoad.mm.9adce9e4.o
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/ImGuiLoad.m.9adce9e4.o
ld: 1 duplicate symbol for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 1
make[2]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 2
make[1]: *** [/home/kali/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/kali/theos/makefiles/master/rules.mk:119: FreeFire_ThanhDark1909.all.tweak.variables] Error 2

### Paste any relevant logs, error output, etc.

```shell
make clean package
==> Cleaning…
> Making all for tweak FreeFire_ThanhDark1909…
==> Compiling DTTJailbreakDetection.m (arm64)…
==> Compiling Esp/PubgLoad.mm (arm64)…
==> Compiling Esp/ImGuiLoad.m (arm64)…
==> Compiling Esp/JHPP.m (arm64)…
==> Compiling Esp/JHUIViewControllerDecoupler.m (arm64)…
==> Compiling ImGuiDrawView.mm (arm64)…
==> Compiling Esp/UIView+Toast.m (arm64)…
==> Compiling KittyMemory/imgui_demo.cpp (arm64)…
==> Compiling KittyMemory/imgui.cpp (arm64)…
==> Compiling KittyMemory/imgui_draw.cpp (arm64)…
==> Compiling KittyMemory/imgui_tables.cpp (arm64)…
==> Compiling KittyMemory/KittyArm64.cpp (arm64)…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
==> Compiling KittyMemory/KittyScanner.cpp (arm64)…
==> Compiling KittyMemory/KittyUtils.cpp (arm64)…
==> Compiling KittyMemory/MemoryBackup.cpp (arm64)…
==> Compiling KittyMemory/MemoryPatch.cpp (arm64)…
==> Compiling KittyMemory/writeData.cpp (arm64)…
==> Compiling KittyMemory/imgui_impl_metal.mm (arm64)…
==> Compiling KittyMemory/imgui_widgets.cpp (arm64)…
==> Linking tweak FreeFire_ThanhDark1909 (arm64)…
ld: warning: directory not found for option '-F/home/kali/theos/vendor/lib/iphone/rootful'
duplicate symbol '_mainWindow' in:
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/PubgLoad.mm.9adce9e4.o
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/ImGuiLoad.m.9adce9e4.o
ld: 1 duplicate symbol for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 1
make[2]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 2
make[1]: *** [/home/kali/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/kali/theos/makefiles/master/rules.mk:119: FreeFire_ThanhDark1909.all.tweak.variables] Error 2
```

### Additional context

im make it in kali linux but it have this erro

make clean package
==> Cleaning…
> Making all for tweak FreeFire_ThanhDark1909…
==> Compiling DTTJailbreakDetection.m (arm64)…
==> Compiling Esp/PubgLoad.mm (arm64)…
==> Compiling Esp/ImGuiLoad.m (arm64)…
==> Compiling Esp/JHPP.m (arm64)…
==> Compiling Esp/JHUIViewControllerDecoupler.m (arm64)…
==> Compiling ImGuiDrawView.mm (arm64)…
==> Compiling Esp/UIView+Toast.m (arm64)…
==> Compiling KittyMemory/imgui_demo.cpp (arm64)…
==> Compiling KittyMemory/imgui.cpp (arm64)…
==> Compiling KittyMemory/imgui_draw.cpp (arm64)…
==> Compiling KittyMemory/imgui_tables.cpp (arm64)…
==> Compiling KittyMemory/KittyArm64.cpp (arm64)…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
==> Compiling KittyMemory/KittyScanner.cpp (arm64)…
==> Compiling KittyMemory/KittyUtils.cpp (arm64)…
==> Compiling KittyMemory/MemoryBackup.cpp (arm64)…
==> Compiling KittyMemory/MemoryPatch.cpp (arm64)…
==> Compiling KittyMemory/writeData.cpp (arm64)…
==> Compiling KittyMemory/imgui_impl_metal.mm (arm64)…
==> Compiling KittyMemory/imgui_widgets.cpp (arm64)…
==> Linking tweak FreeFire_ThanhDark1909 (arm64)…
ld: warning: directory not found for option '-F/home/kali/theos/vendor/lib/iphone/rootful'
duplicate symbol '_mainWindow' in:
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/PubgLoad.mm.9adce9e4.o
    /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/Esp/ImGuiLoad.m.9adce9e4.o
ld: 1 duplicate symbol for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 1
make[2]: *** [/home/kali/theos/makefiles/instance/library.mk:52: /home/kali/Desktop/ThanhDark1909_FreeFrire/.theos/obj/arm64/FreeFire_ThanhDark1909.dylib] Error 2
make[1]: *** [/home/kali/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/kali/theos/makefiles/master/rules.mk:119: FreeFire_ThanhDark1909.all.tweak.variables] Error 2

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

.

### What toolchain and version are you using?

.

### Which SDK version are you using?

14.5

### What OS is your client device running?

iOS

### What OS version does it have installed?

15.7.5

### Which device model is it?

iphone 6s

### Which jailbreak is it using (if relevant)?

palera1n

**Comment by MrGcGamer** [comment]
This should be resoled by #712

**Comment by L1ghtmann** [comment]
@joycelewis what issue are you reporting? The duplicate symbol or the missing directory? Also, pasting the same error log five times is a bit excessive...once is fine.

**Comment by joycelewis** [comment]
> @joycelewis what issue are you reporting? The duplicate symbol or the missing directory? Also, pasting the same error log five times is a bit excessive...once is fine.
i fixed it, i haven't been using github for a long time so i don't know how to report it i just pasted my error -.-
