### ISSUE TITLE
apt update on Ubuntu may make the theos installer script exit

### ISSUE THREAD

**Issue by HMaker** [theos/theos#736]
I tried following the [installation guide](https://theos.dev/docs/installation-linux) but the installer script always exit at `sudo apt update` command. I have some broken apt repositories unrelated to theos, I guess this makes apt update exit the bash script. Weird.

I removed the `sudo apt update` command from the linux installer and it worked.

I am using Ubuntu 20.04.

**Comment by L1ghtmann** [comment]
A potential solution: change the update command to always return true -- `sudo apt update || true`
