### ISSUE TITLE
[Bug]: Xcode Project's Make File is throwing 'xcodebuild: error: “InstallationBuildProductsLocation” couldn’t be moved'

### ISSUE THREAD

**Issue by prathumca** [theos/theos#751]
### What are the steps to reproduce this issue?

1. Create Xcode project
2. Add MakeFile with necessary details
3. Run make to archive the project
4. The error is popped at the end 'xcodebuild: error: “InstallationBuildProductsLocation” couldn’t be moved ........'.

Makefile looks like below

```
export THEOS_SCHEMA = Release
export THEOS_PACKAGE_SCHEME=$(THEOS_PACKAGE_SCHEME)

include $(THEOS)/makefiles/common.mk

XCODEPROJ_NAME = Sample
Sample_XCODE_SCHEME = Sample

Sample_XCODEFLAGS = INSTALL_PREFIX=$(INSTALL_PREFIX) CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES

Sample_CODESIGN_FLAGS = -SEntitlements.xml

include $(THEOS_MAKE_PATH)/xcodeproj.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
```

### What happens?

when I run the following command in terminal 

`make package FINALPACKAGE=1`

The project failed to compile with below error

```
xcodebuild[44201:1174549] Writing error result bundle to /var/folders/yy/bqs8h46s3kz6xpr8c6d82cwr0000gn/T/ResultBundle_2023-13-07_21-07-0017.xcresult
xcodebuild: error: “InstallationBuildProductsLocation” couldn’t be moved to “Sample.xcarchive” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.: The operation couldn’t be completed. No such file or directory.
```

### What were you expecting to happen?

It should be compile and with archive and the `Sample.app` is extracted and copied to `$(THEOS_STAGING_DIR)/Applications`

### Paste any relevant logs, error output, etc.

```shell
▸ Linking Sample
▸ Processing Info.plist
    'UILaunchImages' has been deprecated, use launch storyboards instead. (in target 'Sample' from project 'Sample')
▸ Generating 'Sample.app.dSYM'
2023-07-13 09:07:17.502 xcodebuild[44201:1174549] Writing error result bundle to /var/folders/yy/bqs8h46s3kz6xpr8c6d82cwr0000gn/T/ResultBundle_2023-13-07_09-07-0017.xcresult
xcodebuild: error: “InstallationBuildProductsLocation” couldn’t be moved to “Sample.xcarchive” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.: The operation couldn’t be completed. No such file or directory
make[3]: *** [/opt/theos/makefiles/instance/xcodeproj.mk:87: internal-xcodeproj-compile] Error 70
make[2]: *** [/opt/theos/makefiles/instance/xcodeproj.mk:20: internal-xcodeproj-all_] Error 2
make[1]: *** [/opt/theos/makefiles/master/rules.mk:119: Sample.all.xcodeproj.variables] Error 2
make: *** [/opt/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
```

### Additional context

Looks like DSTROOT is broken and should be replaced with `-archivePath `option.

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

13.4.1

### What toolchain and version are you using?

Xcode 14.3.1

### Which SDK version are you using?

iOS 14.5

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 15.1

### Which device model is it?

iPhone 11 Pro Max

### Which jailbreak is it using (if relevant)?

Dopamine

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this. Does changing DSTROOT to INSTALL_ROOT in $THEOS/makefiles/instance/xcodeproj.mk happen to fix the error?

**Comment by prathumca** [comment]
@L1ghtmann - sorry for the late reply, yes it is working perfectly.

**Comment by L1ghtmann** [comment]
No worries! And thanks so much for confirming. Will pr a fix later today
