### ISSUE TITLE
[Bug]: FILES += <Source Files> Not Compiling <Source Files>

### ISSUE THREAD

**Issue by xuan32546** [theos/theos#762]
### What are the steps to reproduce this issue?

1. Create a tweak project
2. Add the line **FILES = a.xm** in the Makefile
3. Build

### What happens?

The file `a.xm` will not be compiled. And currently, $(THEOS_CURRENT_INSTANCE) prefix is mandatory.

It is not convenient when we have shared source files for subprojects. For example, if `shared/a.xm` is used in 5 subprojects, I can only include the file `shared/a.xm` manually in every makefile of the subprojects for now. It will be more reasonable if we can create a file called `shared.mk` and put FILES += a.xm in `shared.mk` and include `shared.mk` in makefiles of the subprojects.

### What were you expecting to happen?

a.xm should be compiled

### Additional context

Line 5 of `rules.mk`: `__USER_FILES = $(call __schema_var_all,$(THEOS_CURRENT_INSTANCE)_,FILES) $($(THEOS_CURRENT_INSTANCE)_OBJCC_FILES) $($(THEOS_CURRENT_INSTANCE)_LOGOS_FILES) $($(THEOS_CURRENT_INSTANCE)_OBJC_FILES) $($(THEOS_CURRENT_INSTANCE)_CC_FILES) $($(THEOS_CURRENT_INSTANCE)_C_FILES) $($(THEOS_CURRENT_INSTANCE)_SWIFT_FILES)
`

This will be solved if we can make it: `__USER_FILES = $(call __schema_var_all,$(THEOS_CURRENT_INSTANCE)_,FILES) $($(THEOS_CURRENT_INSTANCE)_OBJCC_FILES) $($(THEOS_CURRENT_INSTANCE)_LOGOS_FILES) $($(THEOS_CURRENT_INSTANCE)_OBJC_FILES) $($(THEOS_CURRENT_INSTANCE)_CC_FILES) $($(THEOS_CURRENT_INSTANCE)_C_FILES) $($(THEOS_CURRENT_INSTANCE)_SWIFT_FILES) $(FILES)
`

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

12.5

### What toolchain and version are you using?

clang 11

### Which SDK version are you using?

iOS 14.5

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 15.0

### Which device model is it?

iPad Pro 2018

**Comment by kirb** [comment]
I’m not sure it makes sense to have a global FILES var built into Theos, given this is something you can implement in your own makefiles pretty easily:

```make
export FILES := $(PWD)/GlobalStuff.m

# …

MyThing_FILES = MyThing.m $(FILES)
```

Being exported, you can also access it from your subproject makefiles.
