### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by snowcapcyber** [theos/theos#766]
### What are the steps to reproduce this issue?

(base) Andrews-MacBook-Pro:iSpy ajcblyth$ make package
/Users/ajcblyth/Desktop/Tools/iSpy/theos/makefiles/targets/Darwin-arm/iphone.mk:21: *** first argument to `word' function must be greater than 0.  Stop.
(base) Andrews-MacBook-Pro:iSpy ajcblyth$

### What happens?

I am runing this on a new Mac Book with the latest version of the OS and Xcode

### What were you expecting to happen?

It to compile 

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

Mac Latest

### What toolchain and version are you using?

Latest 

### Which SDK version are you using?

The lates

### What OS is your client device running?

macOS

### What OS version does it have installed?

The Latest

### Which device model is it?

Macbook

### Which jailbreak is it using (if relevant)?

None

**Comment by L1ghtmann** [comment]
Hey, thanks for reaching out! It looks like you have a very old Theos install which lacks support for your newer OS. 

I would highly recommend updating your Theos install, which you can learn about on the [Upgrading from legacy Theos](https://theos.dev/docs/upgrading-from-legacy-theos) page in the docs

**Comment by snowcapcyber** [comment]
Thanks for the help


Andrew



Dr Andrew Blyth, PhD.
+44 (0) 7811 856 741
***@***.******@***.***>
www.snowcapcyber.com<http://www.snowcapcyber.com>


From: Lightmann ***@***.***>
Reply to: theos/theos ***@***.***>
Date: Thursday, 31 August 2023 at 20:05
To: theos/theos ***@***.***>
Cc: Andrew Blyth ***@***.***>, Author ***@***.***>
Subject: Re: [theos/theos] [Bug]: (Issue #766)


Hey, thanks for reaching out! It looks like you have a very old Theos install which lacks support for your newer OS.

I would highly recommend updating your Theos install, which you can learn about on the Upgrading from legacy Theos<https://theos.dev/docs/upgrading-from-legacy-theos> page in the docs

**Comment by L1ghtmann** [comment]
@snowcapcyber is your issue resolved?

**Comment by L1ghtmann** [comment]
Going to close this. If your issue persists, feel free to reopen.
