### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Team-jbnews4u** [theos/theos#771]
### What are the steps to reproduce this issue?

broke on the latest mac os

### What happens?

broke on the latest mac os

### What were you expecting to happen?

broke on the latest mac os

### Paste any relevant logs, error output, etc.

```shell
broke on the latest mac os
```

### Additional context

broke on the latest mac os

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

latest

### What toolchain and version are you using?

latest

### Which SDK version are you using?

latest

### What OS is your client device running?

macOS

### What OS version does it have installed?

latest

### Which device model is it?

latest

### Which jailbreak is it using (if relevant)?

latest

**Comment by L1ghtmann** [comment]
What does broken mean? You've provided no information here nor filled out the fields as described.

**Comment by L1ghtmann** [comment]
#772
