### ISSUE TITLE
[Bug]: fix is the new update 

### ISSUE THREAD

**Issue by Team-jbnews4u** [theos/theos#772]
### What are the steps to reproduce this issue?

==> Compiling SCLAlertView/SCLAlertView.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewResponder.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewStyleKit.m (armv7)…
==> Compiling SCLAlertView/SCLButton.m (armv7)…
==> Compiling SCLAlertView/SCLSwitchView.m (armv7)…
==> Compiling SCLAlertView/SCLTextView.m (armv7)…
==> Compiling SCLAlertView/SCLTimerDisplay.m (armv7)…
==> Compiling SCLAlertView/UIImage+ImageEffects.m (armv7)…
==> Linking tweak nabzclanpopup (armv7)…
ld: warning: -multiply_defined is obsolete
ld: malformed file
/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~
 file '/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### What happens?

==> Compiling SCLAlertView/SCLAlertView.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewResponder.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewStyleKit.m (armv7)…
==> Compiling SCLAlertView/SCLButton.m (armv7)…
==> Compiling SCLAlertView/SCLSwitchView.m (armv7)…
==> Compiling SCLAlertView/SCLTextView.m (armv7)…
==> Compiling SCLAlertView/SCLTimerDisplay.m (armv7)…
==> Compiling SCLAlertView/UIImage+ImageEffects.m (armv7)…
==> Linking tweak nabzclanpopup (armv7)…
ld: warning: -multiply_defined is obsolete
ld: malformed file
/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~
 file '/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### What were you expecting to happen?

==> Compiling SCLAlertView/SCLAlertView.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewResponder.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewStyleKit.m (armv7)…
==> Compiling SCLAlertView/SCLButton.m (armv7)…
==> Compiling SCLAlertView/SCLSwitchView.m (armv7)…
==> Compiling SCLAlertView/SCLTextView.m (armv7)…
==> Compiling SCLAlertView/SCLTimerDisplay.m (armv7)…
==> Compiling SCLAlertView/UIImage+ImageEffects.m (armv7)…
==> Linking tweak nabzclanpopup (armv7)…
ld: warning: -multiply_defined is obsolete
ld: malformed file
/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~
 file '/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Paste any relevant logs, error output, etc.

```shell
==> Compiling SCLAlertView/SCLAlertView.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewResponder.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewStyleKit.m (armv7)…
==> Compiling SCLAlertView/SCLButton.m (armv7)…
==> Compiling SCLAlertView/SCLSwitchView.m (armv7)…
==> Compiling SCLAlertView/SCLTextView.m (armv7)…
==> Compiling SCLAlertView/SCLTimerDisplay.m (armv7)…
==> Compiling SCLAlertView/UIImage+ImageEffects.m (armv7)…
==> Linking tweak nabzclanpopup (armv7)…
ld: warning: -multiply_defined is obsolete
ld: malformed file
/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~
 file '/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Additional context

==> Compiling SCLAlertView/SCLAlertView.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewResponder.m (armv7)…
==> Compiling SCLAlertView/SCLAlertViewStyleKit.m (armv7)…
==> Compiling SCLAlertView/SCLButton.m (armv7)…
==> Compiling SCLAlertView/SCLSwitchView.m (armv7)…
==> Compiling SCLAlertView/SCLTextView.m (armv7)…
==> Compiling SCLAlertView/SCLTimerDisplay.m (armv7)…
==> Compiling SCLAlertView/UIImage+ImageEffects.m (armv7)…
==> Linking tweak nabzclanpopup (armv7)…
ld: warning: -multiply_defined is obsolete
ld: malformed file
/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~
 file '/Users/me/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### What OS are you seeing the problem on?

iOS

### What OS version does it have installed?

latest

### What toolchain and version are you using?

latest

### Which SDK version are you using?

mac

### What OS is your client device running?

iOS

### What OS version does it have installed?

latest

### Which device model is it?

latest

### Which jailbreak is it using (if relevant)?

Mac

**Comment by leptos-null** [comment]
This should be fixed with https://github.com/theos/lib/pull/19

Please run `$THEOS/bin/update-theos` to update to the latest version of theos.
Please let us know if this issue continues after updating. We will plan to close this thread after 1 week of inactivity.

**Comment by L1ghtmann** [comment]
Closing following comment above.
