### ISSUE TITLE
[Bug]: Stage contains empty directories when building for rootless

### ISSUE THREAD

**Issue by xybp888** [theos/theos#774]
### What are the steps to reproduce this issue?

`deb.mk`

### What happens?

```make
ifeq ($(THEOS_PACKAGE_SCHEME),rootless)
 	$(ECHO_NOTHING)mkdir -p "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)"$(ECHO_END)
 	$(ECHO_NOTHING)rsync -a "$(THEOS_STAGING_DIR)/" "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)" --exclude "DEBIAN" --exclude "$(THEOS_PACKAGE_INSTALL_PREFIX)" $(_THEOS_RSYNC_EXCLUDE_COMMANDLINE) --remove-source-files$(ECHO_END)
 # Delete everything except DEBIAN/ and THEOS_PACKAGE_INSTALL_PREFIX
 	$(ECHO_NOTHING)find "$(THEOS_STAGING_DIR)" -mindepth 1 ! -path "*/DEBIAN*" ! -path "*$(THEOS_PACKAGE_INSTALL_PREFIX)*" \( -type d -empty -o -type f \) -delete$(ECHO_END)
 endif
```

### What were you expecting to happen?

In rootless mode, this part will cause additional var empty directories to appear in the generated package. The path is: `/var/jb/var`

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

macOS 14

### What toolchain and version are you using?

Xcode 15.0

### Which SDK version are you using?

iOS 15.0

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 15.1.1

### Which device model is it?

iPhone13 Pro Max

### Which jailbreak is it using (if relevant)?

Dopamine

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this. Do you happen to have a project structure handy that could be used to replicate this?

**Comment by xybp888** [comment]
> Hey, thanks for reporting this. Do you happen to have a project structure handy that could be used to replicate this?

You can create a new tweak, then make package. Finally, when you unzip the package, you will find that there will be an empty var directory under the /var/jb/ directory.

**Comment by xybp888** [comment]
> Hey, thanks for reporting this. Do you happen to have a project structure handy that could be used to replicate this?

`I want $(ECHO_NOTHING)find "$(THEOS_STAGING_DIR)" -mindepth 1 ! -path "*/DEBIAN*" ! -path "*$(THEOS_PACKAGE_INSTALL_PREFIX)*" \( -type d -empty -o -type f \) -delete$(ECHO_END) `This code does not delete the empty folders in the $(THEOS_PACKAGE_INSTALL_PREFIX) directory

**Comment by xybp888** [comment]
> Hey, thanks for reporting this. Do you happen to have a project structure handy that could be used to replicate this?

`$(ECHO_NOTHING)rmdir "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)/var" >/dev/null || true$(ECHO_END)`

I am usethis code comes to temporarily solve this problem

**Comment by xybp888** [comment]
> Hey, thanks for reporting this. Do you happen to have a project structure handy that could be used to replicate this?
![50022e10de36fc7b547872c1d288c4c9](https://github.com/theos/theos/assets/24733048/9e5428d7-966b-4bb8-beb0-51e1df42212e)

**Comment by xybp888** [comment]
[test.zip](https://github.com/theos/theos/files/12831472/test.zip)

**Comment by xybp888** [comment]
I have written THEOS_PACKAGE_SCHEME=rootless in the Makefile
But my project will still be generated

**Comment by xybp888** [comment]
<img width="1655" alt="image" src="https://github.com/theos/theos/assets/24733048/b4c660dd-c82a-475b-aa7a-ef48f38cad08">
I am using the latest version of theos

**Comment by Patickhuang** [comment]
![C0CA25AF76C41A89B5C8BA2E4D09B161](https://github.com/theos/theos/assets/80010629/1a878a22-45dd-4fe4-937c-635af4255fe5)

The same thing happened to me too

**Comment by Patickhuang** [comment]
yes, macos14

**Comment by w2599** [comment]
> I am still unable to reproduce with the provided test project. This may very well be a case of BSD and GNU `find` being different. @xybp888 @Patickhuang @w2599, are you all using OSX?

macOS 12.5

**Comment by xybp888** [comment]
> I am still unable to reproduce with the provided test project. This may very well be a case of BSD and GNU `find` being different. @xybp888 @Patickhuang @w2599, are you all using OSX?

macOS 14

**Comment by xybp888** [comment]
> I am still unable to reproduce with the provided test project. This may very well be a case of BSD and GNU `find` being different. @xybp888 @Patickhuang @w2599, are you all using OSX?

`$(ECHO_NOTHING)[ -d "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)/var" ] && rmdir "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)/var" || true$(ECHO_END)`

This can solve the problem

**Comment by Patickhuang** [comment]
> > I am still unable to reproduce with the provided test project. This may very well be a case of BSD and GNU `find` being different. @xybp888 @Patickhuang @w2599, are you all using OSX?
> 
> `$(ECHO_NOTHING)[ -d "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)/var" ] && rmdir "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)/var" || true$(ECHO_END)`
> 
> This can solve the problem

yes,thank you

**Comment by L1ghtmann** [comment]
The issue appears to spawn from the `rsync` usage mentioned above, so implementing a fix to broken impl seems a bit silly. I believe we've come up with a worthwhile fix in #775. If you guys wouldn't mind trying it out, that would be great.

**Comment by xybp888** [comment]
> The issue appears to spawn from the `rsync` usage mentioned above, so implementing a fix for a broken impl seems a bit silly. I believe we've come up with a worthwhile replacement impl in #775. If you guys wouldn't mind trying it out, that would be great.

After I tried it, it was indeed solved!

**Comment by xybp888** [comment]
> The issue appears to spawn from the `rsync` usage mentioned above, so implementing a fix for a broken impl seems a bit silly. I believe we've come up with a worthwhile replacement impl in #775. If you guys wouldn't mind trying it out, that would be great.

Using the make clean command will not clean this tmp folder
I modified the code on line 107 can be cleaned up

`/opt/theos/makefiles/master/rules.mk`

`$(ECHO_NOTHING)rm -rf "$(THEOS_STAGING_DIR)" "$(_THEOS_STAGING_TMP)" "$(_THEOS_SWIFT_AUXILIARY_DIR)" "$(_THEOS_TMP_COMPILE_COMMANDS_FILE)"$(ECHO_END)`

**Comment by L1ghtmann** [comment]
> Using the make clean command will not clean this tmp folder

Ha, totally forgot to check this. Thank you! Fixed.
