### ISSUE TITLE
[Bug]: Theos isn't finding libz3

### ISSUE THREAD

**Issue by danipoak** [theos/theos#784]
### What are the steps to reproduce this issue?

1. '$ make package`

### What happens?

```
> Making all for tweak PNRSender…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
/home/user/theos/toolchain/linux/iphone/bin/clang++: error while loading shared libraries: libz3.so.4: cannot open shared object file: No such file or directory
```

### What were you expecting to happen?

Teak.x should compile. Theos complains about missing libz3 however the library does exist. 
```
$ ldconfig -p | grep libz3
        libz3.so.4.12 (libc6,x86-64) => /usr/lib64/libz3.so.4.12
        libz3.so (libc6,x86-64) => /usr/lib64/libz3.so
```

### Paste any relevant logs, error output, etc.

```shell
$ make package
> Making all for tweak PNRSender…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
/home/user/theos/toolchain/linux/iphone/bin/clang++: error while loading shared libraries: libz3.so.4: cannot open shared object file: No such file or directory
make[3]: *** [/home/user/theos/makefiles/instance/rules.mk:379: /home/user/Repositories/SIMLessPNRGateway/pnrsender/.theos/obj/debug/arm64/Tweak.x.aa49848d.o] Error 127
rm /home/user/Repositories/SIMLessPNRGateway/pnrsender/.theos/obj/debug/arm64/Tweak.x.m
make[2]: *** [/home/user/theos/makefiles/instance/library.mk:58: /home/user/Repositories/SIMLessPNRGateway/pnrsender/.theos/obj/debug/arm64/PNRSender.dylib] Error 2
make[1]: *** [/home/user/theos/makefiles/instance/library.mk:43: internal-library-all_] Error 2
make: *** [/home/user/theos/makefiles/master/rules.mk:146: PNRSender.all.tweak.variables] Error 2
```

### Additional context

I don't see any options to point Theos to a different library folder that contains libz3. 

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

Gentoo

### What toolchain and version are you using?

clang 17.0.6

### Which SDK version are you using?

iPhoneOS12.4

### What OS is your client device running?

iOS

### What OS version does it have installed?

12.5.7

### Which device model is it?

iPhone 5s

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this! The issue isn't with Theos itself but with the toolchain. The Linux toolchains Theos provides are built on Ubuntu and thus expect certain versions of the required dependencies. In this case, you can cater to your libz3 by creating a symlink to the expected shared object file:
```
sudo ln -s /usr/lib64/libz3.so.4.12 /usr/lib64/libz3.so.4
```
This has to occur for other non-Debian distros as well, but the installer ($THEOS/bin/install-theos) is currently only configured for three: SUSE-based, Red Hat-based, and Arch-based distros.

**Comment by danipoak** [comment]
Ah okay that makes sense. I'll give this a go. I imagine I may come up with more missing libs in which case just firing up an Ubuntu VM may be the quickest/easiest solution. Thanks!
