### ISSUE TITLE
[Bug]: Unable to locate package error on Garuda Linux

### ISSUE THREAD

**Issue by ChumbleDev** [theos/theos#785]
### What are the steps to reproduce this issue?

1. Install theos using the command
2. Error shows up

### What happens?

When I try to install theos on garuda linux this error happens:
 ==> Theos Installer: Starting install...

==> Platform: Linux

==> Preparing to install dependencies. Please enter your password if prompted:
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package build-essential
E: Unable to locate package fakeroot
E: Unable to locate package rsync
E: Unable to locate package curl
E: Unable to locate package perl
E: Unable to locate package zip
E: Unable to locate package git
E: Unable to locate package libxml2
==> Dependency install command seems to have encountered an error. Please see the log above.

### What were you expecting to happen?

For it to install

### Paste any relevant logs, error output, etc.

```shell
==> Theos Installer: Starting install...

==> Platform: Linux

==> Preparing to install dependencies. Please enter your password if prompted:
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package build-essential
E: Unable to locate package fakeroot
E: Unable to locate package rsync
E: Unable to locate package curl
E: Unable to locate package perl
E: Unable to locate package zip
E: Unable to locate package git
E: Unable to locate package libxml2
==> Dependency install command seems to have encountered an error. Please see the log above.
```

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

Garuda Linux

### What toolchain and version are you using?

idk

### Which SDK version are you using?

idk

### What OS is your client device running?

Linux/WSL

### What OS version does it have installed?

no device

### Which device model is it?

no device

### Which jailbreak is it using (if relevant)?

no device

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this. I hadn't heard of Garuda Linux before, but after looking it up it appears to be Arch-based. The dependencies that failed to install imply that your system is being treated as a Debian-based system by the installer. Do you happen to have `apt` installed somehow?

**Comment by ChumbleDev** [comment]
> Hey, thanks for reporting this. I hadn't heard of Garuda Linux before, but after looking it up it appears to be Arch-based. The dependencies that failed to install imply that your system is being treated as a Debian-based system by the installer. Do you happen to have `apt` installed somehow?

oh yeah now that i think about it i did install apt i’m gonna remove that

**Comment by L1ghtmann** [comment]
Is your issue resolved @ChumbleDev ?

**Comment by L1ghtmann** [comment]
Closing as the issue spawned from an incompatible package manager being installed on an Arch-based system.
