### ISSUE TITLE
报错443

### ISSUE THREAD

**Issue by Mieing** [theos/theos#793]
bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 1 ms: Connection refused

**Comment by EinTim23** [comment]
Thats an issue with your connection and not with theos. Make sure that the internet on your machine works fine and github isnt getting blocked by something.

**Comment by Mieing** [comment]
I know this has nothing to do with Theos. My computer has VPN enabled, but it has no effect on Ubuntu. I don't know how to solve it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: EinTim ***@***.***>
发送时间: Wednesday, February 21, 2024 7:26:42 PM
收件人: theos/theos ***@***.***>
抄送: Mieing ***@***.***>; Author ***@***.***>
主题: Re: [theos/theos] 报错443 (Issue #793)


Thats an issue with your connection and not with theos. Make sure that the internet on your machine works fine and github isnt getting blocked by something.

―
