### ISSUE TITLE
[Bug]: Install on Fresh iOS 8.4.1 EtasonJB

### ISSUE THREAD

**Issue by BJamin99** [theos/theos#797]
### What are the steps to reproduce this issue?

On a fresh iOS 8.4.1 install with EtasonJB (don't install any additional packages) attempt the install instructions for Prior to iOS 12.0.

### What happens?

apt-get, head, cut aren't available so this cannot complete.

### What were you expecting to happen?

apt-get, head, and cut available to complete the install.

### What OS are you seeing the problem on?

iOS

### What OS version does it have installed?

iOS 8.4.1

### What toolchain and version are you using?

N/A

### Which SDK version are you using?

N/A

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 8.4.1

### Which device model is it?

iPad 4

### Which jailbreak is it using (if relevant)?

EtasonJB

**Comment by L1ghtmann** [comment]
Hey @BJamin99, thanks a ton for this info! I had hoped to get my old 4s up and running again one of these days to confirm our installer's support but haven't gotten around to it. So `apt` *and* `apt-get` are not installed by default? 

Just to confirm I've understood the rest correctly, the changes required are 
https://github.com/theos/theos/blob/5bfdc3cb7133ec1cab43182115d902e2b57c9eac/bin/install-theos#L233-L234
1) ensure `coreutils` is installed

https://github.com/theos/theos/blob/5bfdc3cb7133ec1cab43182115d902e2b57c9eac/bin/install-theos#L246-L258
1) Remove cooltstar.org ref
2) `apt-get` -> `apt` (?)
3) install `xz`

**Comment by L1ghtmann** [comment]
Hey @BJamin99, saw that there is a pr associated with this issue, but it looks to be open on your fork (i.e., fork/branch1 -> fork/master). Was that intentional?

**Comment by L1ghtmann** [comment]
Sweet, thanks again! Had a couple comments but otherwise looks great.
