### ISSUE TITLE
"import is a language extension" when compiling a C file with the -pedantic flag

### ISSUE THREAD

**Issue by pixelomer** [theos/theos#819]
### What are the steps to reproduce this issue?

Compiling [libunarr-ios](https://github.com/pixelomer/libunarr-ios) with the latest version of Theos reproduces the issue.

### What happens?

A Prefix.pch file is imported during compilation that imports the `<AvailabilityVersions.h>` header. Because `#import` is used, this causes a compilation error when the `-pedantic` flag is used.

### What were you expecting to happen?

I expected the project to compile successfully. Removing the problematic part in Prefix.pch fixes the issue.

### Paste any relevant logs, error output, etc.

```shell
$THEOS/Prefix.pch:18:3: error: #import is a language extension [-Werror,-Wimport-preprocessor-directive-pedantic]
        #import <AvailabilityVersions.h>
        ^
1 error generated.
gmake[3]: ***[$THEOS/makefiles/instance/rules.mk:321: /.../libunarr-ios/.theos/obj/debug/arm64/unarr/common/stream.c.o] Error 1
gmake[3]: *** Waiting for unfinished jobs...
```

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

macOS 14.5

### What toolchain and version are you using?

Xcode 15.4

### Which SDK version are you using?

iOS 16.5

### What OS is your client device running?

iOS

### What OS version does it have installed?

irrelevant

### Which device model is it?

irrelevant

### Which jailbreak is it using (if relevant)?

irrelevant

**Comment by L1ghtmann** [comment]
Should be resolved by https://github.com/theos/theos/commit/8a93fabf189ab82f2add7a57ec893dabcf7053c2.
