### ISSUE TITLE
[Bug]: There was an error running

### ISSUE THREAD

**Issue by Mieing** [theos/theos#823]
### What are the steps to reproduce this issue?

make

### What happens?

/home/mie/theos/toolchain/linux/iphone/bin/lipo: error: not ranlib, ar, lib or dlltool
make[2]: *** [/home/mie/theos/makefiles/instance/library.mk:51: /home/mie/x/.theos/obj/debug/x.dylib.6ccec61e.unsigned] Error 1
make[1]: *** [/home/mie/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/mie/theos/makefiles/master/rules.mk:146: x.all.tweak.variables] Error 2

### What were you expecting to happen?

Run-time compilation

### Paste any relevant logs, error output, etc.

```shell
mie@ovo:~/x$ make
> Making all for tweak x…
==> Preprocessing Tweak.x…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Compiling Tweak.x (arm64e)…
==> Linking tweak x (arm64)…
==> Linking tweak x (arm64e)…
==> Merging tweak x…
/home/mie/theos/toolchain/linux/iphone/bin/lipo: error: not ranlib, ar, lib or dlltool
make[2]: *** [/home/mie/theos/makefiles/instance/library.mk:51: /home/mie/x/.theos/obj/debug/x.dylib.6ccec61e.unsigned] Error 1
make[1]: *** [/home/mie/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/mie/theos/makefiles/master/rules.mk:146: x.all.tweak.variables] Error 2
```

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

ubuntu 2204.3.49.0

### What toolchain and version are you using?

clang

### Which SDK version are you using?

iOS 15

### What OS is your client device running?

Linux/WSL

### What OS version does it have installed?

ubuntu 2204.3.49.0

### Which device model is it?

xr

### Which jailbreak is it using (if relevant)?

xinaa15

**Comment by L1ghtmann** [comment]
Would you mind sharing the output of:

1) `make clean package messages=yes`

2) `ls -A $THEOS/toolchain/linux/iphone/bin/`

Thanks!
