### ISSUE TITLE
[Bug]: error: import of C++ module 'MachO.nlist' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c]

### ISSUE THREAD

**Issue by nabz-polo** [theos/theos#827]
### What are the steps to reproduce this issue?

/Users/pc/Desktop/project/substrate.h:45:1: error: import of C++ module 'MachO.nlist' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c]
   45 | #include <mach-o/nlist.h>
      | ^
/Users/pc/Desktop/project/substrate.h:43:1: note: extern "C" language linkage specification begins here
   43 | extern "C" {
      | ^
5 errors generated.

### What happens?

when I try to run this 

### What were you expecting to happen?

compile the code 

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

15.1

### What toolchain and version are you using?

Xcode 16.0

### Which SDK version are you using?

14

### What OS is your client device running?

macOS

### What OS version does it have installed?

14

### Which device model is it?

macOS

**Comment by leptos-null** [comment]
This appears to be the same issue as #791.
Do you still have this issue with the latest version of Theos?
You can update Theos by running `$THEOS/bin/update-theos`
