### ISSUE TITLE
[Need Help plz] make package with error 2

### ISSUE THREAD

**Issue by Shadow403** [theos/theos#828]
![IMG_0375](https://github.com/user-attachments/assets/be9a2c2d-d322-466e-931d-aa7d0fa09ca2)

What versions of software are you using?
----------------------------------------
**Operating System:**
IOS 15.8.3(19H386)

I used Trollstore Installed Dopamine and JB

**Comment by L1ghtmann** [comment]
Install `gzip` in your package manager. Procursus has yet to update the dependencies package [https://github.com/ProcursusTeam/Procursus/pull/1414/files]. In hindsight, they should not be hosting this

**Comment by Shadow403** [comment]
so is dependencies `gzip` didn't install

**Comment by L1ghtmann** [comment]
Correct, you need to install it

**Comment by Shadow403** [comment]
thx bro
