### ISSUE TITLE
theos setup

### ISSUE THREAD

**Issue by albfan** [theos/theos#99]
After clone project and download sdk, no luck with a hello world project. 

I have follow this guides
1. http://iphonedevwiki.net/index.php/Theos/Getting_Started#On_Mac_OS_X_or_Linux
2. http://ioscheaters.com/topic/767-tut-set-up-theos-with-sdk-61-on-linuxupdated/

Hope solving this issue helps others to setup theos on linux. Maybe a wiki could be helpful for setup

```
$ $THEOS/bin/nic.pl
```

choose iphone/application named autocameraroll

Debug make shows this:
```
$ make -n
[ -d "/home/alberto/bin/theos/sdks/iPhoneOS7.1.sdk" ] || { echo "Your current SYSROOT, \"/home/alberto/bin/theos/sdks/iPhoneOS7.1.sdk\", appears to be missing."; exit 1; }
\
abs_build_dir=.; \
if [ "" != "" ]; then \
  echo Making all in subprojects of application autocameraroll...; \
  for d in ; do \
    d="${d%:*}"; \
    if [ "${abs_build_dir}" = "." ]; then \
      lbuilddir="."; \
    else \
      lbuilddir="${abs_build_dir}/$d"; \
    fi; \
    if make -C $d -f Makefile --no-print-directory --no-keep-going all \
        THEOS_BUILD_DIR="$lbuilddir" \
       ; then\
       :; \
    else exit $?; \
    fi; \
  done; \
 fi; \
echo Making all for application autocameraroll...; \
make -f Makefile --no-print-directory --no-keep-going \
	internal-application-all \
	_THEOS_CURRENT_TYPE="application" \
	THEOS_CURRENT_INSTANCE="autocameraroll" \
	_THEOS_CURRENT_OPERATION="all" \
	THEOS_BUILD_DIR="."
Making all for application autocameraroll...
:
(mkdir -p "obj/autocameraroll.app/")
(mkdir -p "obj/autocameraroll.app/")
(mkdir -p "obj/autocameraroll.app/")
(echo " Copying resource directories into the application wrapper...";for d in Resources; do \
		if [ -d "$d" ]; then \
			rsync -a "$d/" "./obj/autocameraroll.app/" --exclude "_MTN" --exclude ".git" --exclude ".svn" --exclude ".DS_Store" --exclude "._*"; \
		else \
			echo "Warning: ignoring missing bundle resource directory $d."; \
		fi; \
	done)
```

this leads to (sorry my lang is ES)

```
$ make
Making all for application autocameraroll...
 Copying resource directories into the application wrapper...
make[2]: *** No hay ninguna regla para construir el objetivo «obj/main.m.390d8355.o», necesario para «obj/autocameraroll.app/autocameraroll.27541137.unsigned».  Alto.
make[1]: *** [internal-application-all_] Error 2
make: *** [autocameraroll.all.application.variables] Error 2
```

any clues?

**Comment by uroboro** [comment]
@albfan Is this still happening? Have you been able to fix it?

**Comment by albfan** [comment]
No luck. I'm still working from ssh

**Comment by uroboro** [comment]
Can you post the output of `make clean package debug=yes messages=yes`?

**Comment by albfan** [comment]
I have done a fresh install. Not sure for sdk version downloaded

<pre>
$ git clone --recursive https://github.com/kirb/theos.git
$ export THEOS=/home/alberto/theos/
$ wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6011_iphoneos-arm.deb
$ mkdir substrate
$ dpkg-deb -x mobilesubstrate_*_iphoneos-arm.deb substrate
$ mv substrate/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate $THEOS/lib/libsubstrate.dylib
$ mv substrate/Library/Frameworks/CydiaSubstrate.framework/Headers/CydiaSubstrate.h $THEOS/include/substrate.h

download xcode (I choose xcode 5.1.1 for an ipad with software 7.1.2)

$ 7z x xcode_5.1.1.dmg 
$ mv Xcode/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/* ~/theos/sdks/
$ $THEOS/bin/nic.pl 
NIC 2.0 - New Instance Creator
------------------------------
  [1.] iphone/activator_event
  [2.] iphone/application_modern
  [3.] iphone/cydget
  [4.] iphone/flipswitch_switch
  [5.] iphone/framework
  [6.] iphone/ios7_notification_center_widget
  [7.] iphone/library
  [8.] iphone/notification_center_widget
  [9.] iphone/preference_bundle_modern
  [10.] iphone/tool
  [11.] iphone/tweak
  [12.] iphone/xpc_service
Choose a Template (required): 2
Project Name (required): autocameraroll
Package Name [com.yourcompany.autocameraroll]: 
Author/Maintainer Name [alberto]: 
[iphone/application_modern] Class name prefix (two or more characters) [XX]: 
Instantiating iphone/application_modern in autocameraroll/...
Done.
$ cd autocameraroll/
$ make clean package debug=yes messages=yes
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 6 "Cleaning"); set -o pipefail; (rm -rf "/home/alberto/autocameraroll/.theos/obj/debug")
==> Cleaning…
set -o pipefail; (rm "/home/alberto/autocameraroll/.theos/build_session")
set -o pipefail; (rm -rf "/home/alberto/autocameraroll/.theos/_")
> Making all for application autocameraroll…
set -o pipefail; (mkdir -p "/home/alberto/autocameraroll/.theos/obj/debug/autocameraroll.app/")
set -o pipefail; (mkdir -p "/home/alberto/autocameraroll/.theos/obj/debug/autocameraroll.app/")
set -o pipefail; (mkdir -p "/home/alberto/autocameraroll/.theos/obj/debug/autocameraroll.app/")
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 5 "Copying resource directories into the application wrapper"); set -o pipefail; (for d in Resources; do \
	if [ -d "$d" ]; then \
		rsync -a "$d/" "/home/alberto/autocameraroll/.theos/obj/debug/autocameraroll.app/" --exclude "_MTN" --exclude ".git" --exclude ".svn" --exclude ".DS_Store" --exclude "._*"; \
	else \
		printf "\e[0;33m==> \e[1;33mWarning:\e[m %s\n" "Warning: ignoring missing bundle resource directory $d." >&2; \
	fi; \
done)
==> Copying resource directories into the application wrapper…
set -o pipefail; (make -f Makefile --no-print-directory --no-keep-going \
	internal-application-compile \
	_THEOS_CURRENT_TYPE=application THEOS_CURRENT_INSTANCE=autocameraroll _THEOS_CURRENT_OPERATION=compile \
	THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes)
set -o pipefail; (mkdir -p /home/alberto/autocameraroll/.theos/obj/debug/armv7/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 2 "Compiling main.m (armv7)"); set -o pipefail; (/home/alberto/theos/toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++ -x objective-c -c -I/home/alberto/theos/include -include /home/alberto/theos/Prefix.pch -DTARGET_IPHONE=1 -Os -Wall -Werror -isysroot "/home/alberto/theos/sdks/iPhoneOS7.1.sdk" -D__IPHONE_OS_VERSION_MIN_REQUIRED=__IPHONE_5_0 -miphoneos-version-min=5.0     -I/home/alberto/theos/vendor/include -I/home/alberto/theos/include/_fallback -DDEBUG -ggdb -O0  -DTHEOS_INSTANCE_NAME="\"autocameraroll\""  -arch armv7      -std=c99 main.m -o /home/alberto/autocameraroll/.theos/obj/debug/armv7/main.m.00014e02.o)
==> Compiling main.m (armv7)…
/bin/bash: /home/alberto/theos/toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++: No existe el fichero o el directorio
/home/alberto/theos/makefiles/instance/rules.mk:170: fallo en las instrucciones para el objetivo '/home/alberto/autocameraroll/.theos/obj/debug/armv7/main.m.00014e02.o'
make[3]: *** [/home/alberto/autocameraroll/.theos/obj/debug/armv7/main.m.00014e02.o] Error 127
/home/alberto/theos/makefiles/instance/application.mk:47: fallo en las instrucciones para el objetivo '/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll'
make[2]: *** [/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll] Error 2
/home/alberto/theos/makefiles/instance/application.mk:39: fallo en las instrucciones para el objetivo 'internal-application-all_'
make[1]: *** [internal-application-all_] Error 2
/home/alberto/theos/makefiles/master/rules.mk:78: fallo en las instrucciones para el objetivo 'autocameraroll.all.application.variables'
make: *** [autocameraroll.all.application.variables] Error 2
</pre>

**Comment by kirb** [comment]
You missed out a toolchain. The toolchain is a set of compilers, linkers, and other tools that are an absolute requirement to build programs.

I’d advise you also change from kirb/theos to theos/theos – the former is being transitioned to the latter and may end up being removed.

@coolstar, could you explain how to set up your Linux toolchain? (Forgot to ask you about that.)

**Comment by albfan** [comment]
I see this line

> ==> Compiling main.m (armv7)…
> /bin/bash: /home/alberto/theos/toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++: No existe el fichero o el directorio

and find this port

https://github.com/tpoechtrager/cctools-port

also installed llvm and clang

How does toolchain/linux/iphone/bin/armv7-apple-darwin11-clang++ arrives to that place?

**Comment by alucard0134** [comment]
@albfan 1.download https://developer.angelxwind.net/Linux/ios-toolchain_clang%2bllvm%2bld64_latest_linux_x86_64.zip 
2. unzip it to $THEOS/toolchain
3. Grab an SDK from xcode or find somewhere

Then your done

**Comment by albfan** [comment]
All this crazy stuff comming from somewhere nobody knows really amaze me. I wonder if there's sources for that, but anyway, that solves toolchain missing step.

On archlinux https://aur.archlinux.org/packages/libtinfo/ is needed (I have installed it with yaourt)

I understand theos is not really stable, but another set of bizarre errors was solve by

    make update-theos

Know I'm stuck with:

<pre>
> Making all for application autocameraroll…
==> Copying resource directories into the application wrapper…
==> Linking application autocameraroll (armv7)…
ld: file too small (length=15) file '/home/alberto/theos/sdks/iPhoneOS7.1.sdk/usr/lib/libobjc.dylib' for architecture armv7
armv7-apple-darwin11-clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
/home/alberto/theos/makefiles/instance/application.mk:47: fallo en las instrucciones para el objetivo '/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll'
make[3]: *** [/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll] Error 1
/home/alberto/theos/makefiles/instance/application.mk:47: fallo en las instrucciones para el objetivo '/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll'
make[2]: *** [/home/alberto/autocameraroll/.theos/obj/debug/armv7/autocameraroll.app/autocameraroll] Error 2
/home/alberto/theos/makefiles/instance/application.mk:39: fallo en las instrucciones para el objetivo 'internal-application-all_'
make[1]: *** [internal-application-all_] Error 2
/home/alberto/theos/makefiles/master/rules.mk:78: fallo en las instrucciones para el objetivo 'autocameraroll.all.application.variables'
make: *** [autocameraroll.all.application.variables] Error 2
</pre>

that everybody seems to solve with a 

    make clean && make package

But for me it's not working.

Is option 2 on $THEOS/bin/nic.pl the right choose for a hello world application?

**Comment by uroboro** [comment]
The provided toolchain is built from the opensource releases of the tools that compose it, with patches to work correctly for the iOS platform.

Regarding your last error output, it's never solved with `make clean && make package` (which can simply be `make clean package`) since it's an problem with the SDK. See [this section on the troubleshooting page](http://iphonedevwiki.net/index.php/Theos/Troubleshooting#Small_SDK). Always add `messages=yes` to the `make` calls that you want to share since the real problem is sometimes hidden. (`make clean package messages=yes` for example)

On templates, the option number depends on how many templates you have, so you'll have to choose the one that says 'application'.

**Comment by albfan** [comment]
Problems with sdk sounds understandable

> Instead, copy the SDK in the compressed form and extract it on the device

But I do compile apps on device, that's working. What I want is to develop apps on my laptop. After decompress, can I move decompressed files to my laptop? Can I pick them directly from device?

I use 

    $ 7z x xcode_5.1.1.dmg

Which seems to corrupt decompress. I will try

http://askubuntu.com/a/38122/89479

, and compare with actual decompression, trying to detect underneat problem

**Comment by albfan** [comment]
Using https://sourceforge.net/projects/catacombae/files/HFSExplorer/0.23.1/

and choosing not to follow simbolic links (maybe it will work following too) I can extract directly 

Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk

to $THEOS/sdks

Now compilation is working smoothly

I don't want to close this until somebody told me if steps here can be updated on theos wiki for linux users. Let me know if I can help in anyway

**Comment by alucard0134** [comment]
Considering https://jbdevs.org/sdks is now up no further help will be needed. Closing this now, and if you have any other issues feel free to comment back
